// Generated by crates/nalgebra/src/linalg/generate.py: do not edit by hand.
//! `Qr5x2` / `Matrix5x2QrTrait` through the public API (WP 8.5-P14b): oracle vectors
//! (`tools/oracle` suite `spectral`), the factor identities, gas benchmarks.

use core::cmp::max;
use nalgebra::linalg::{Matrix5x2QrTrait, Qr5x2Trait};
use nalgebra::{Matrix5x2, MatrixMul, Vector5};
use nalgebra_testing::black_box;
use nalgebra_tests_utils::{abs_raw, excess, fx, oracle_tol, ulp_diff};
use crate::builders::{amax_5x2, mat2x2, mat5x2, max_ulp_5x1, max_ulp_5x2, orth_5x2, vec5};
use crate::oracle_qr as oracle;

const ONE: i64 = 0x100000000;

/// `qr5x2_q_r` (oracle): `q` and `r` entry by entry within the oracle tolerance (upstream's
/// unpacked factors: `diag(r) >= 0`), `q r = A` and the orthonormality of `q` within the
/// measured bounds.
#[test]
fn test_oracle_qr5x2_q_r() {
    let mut cases = oracle::qr5x2_q_r_cases();
    let (mut ex, mut rec, mut orth) = (0, 0, 0);
    while let Some(case) = cases.pop_front() {
        let (a, eq, er, tol) = *case;
        let a = black_box(mat5x2(a));
        let f = a.qr();
        let (q, r) = f.unpack();
        let (q2, r2) = f.qr_internal();
        assert!(q2 == q && r2 == r && f.q() == q && f.r() == r && f.unpack_r() == r);
        let (eq, er) = (mat5x2(eq), mat2x2(er));
        ex = max(ex, excess(ulp_diff(q.m11, eq.m11), oracle_tol(abs_raw(eq.m11), tol)));
        ex = max(ex, excess(ulp_diff(q.m12, eq.m12), oracle_tol(abs_raw(eq.m12), tol)));
        ex = max(ex, excess(ulp_diff(q.m21, eq.m21), oracle_tol(abs_raw(eq.m21), tol)));
        ex = max(ex, excess(ulp_diff(q.m22, eq.m22), oracle_tol(abs_raw(eq.m22), tol)));
        ex = max(ex, excess(ulp_diff(q.m31, eq.m31), oracle_tol(abs_raw(eq.m31), tol)));
        ex = max(ex, excess(ulp_diff(q.m32, eq.m32), oracle_tol(abs_raw(eq.m32), tol)));
        ex = max(ex, excess(ulp_diff(q.m41, eq.m41), oracle_tol(abs_raw(eq.m41), tol)));
        ex = max(ex, excess(ulp_diff(q.m42, eq.m42), oracle_tol(abs_raw(eq.m42), tol)));
        ex = max(ex, excess(ulp_diff(q.m51, eq.m51), oracle_tol(abs_raw(eq.m51), tol)));
        ex = max(ex, excess(ulp_diff(q.m52, eq.m52), oracle_tol(abs_raw(eq.m52), tol)));
        ex = max(ex, excess(ulp_diff(r.m11, er.m11), oracle_tol(abs_raw(er.m11), tol)));
        ex = max(ex, excess(ulp_diff(r.m12, er.m12), oracle_tol(abs_raw(er.m12), tol)));
        ex = max(ex, excess(ulp_diff(r.m21, er.m21), oracle_tol(abs_raw(er.m21), tol)));
        ex = max(ex, excess(ulp_diff(r.m22, er.m22), oracle_tol(abs_raw(er.m22), tol)));
        rec = max(rec, max_ulp_5x2(q.mul_mat(r), a) / amax_5x2(a));
        orth = max(orth, orth_5x2(q));
    }
    assert!(ex == 0, "oracle tolerance exceeded by {}", ex);
    assert!(rec <= 2 && orth <= 32, "measured {} {}", rec, orth);
}

#[test]
#[inline(never)]
fn bench_qr5x2_new__baseline() {
    let (a, _, _, _) = *oracle::qr5x2_q_r_cases().at(3);
    let _a = black_box(mat5x2(a));
    let e = black_box(true);
    assert!(e == e);
}

/// Modified Gram-Schmidt, unrolled.
#[test]
#[inline(never)]
fn bench_qr5x2_new__mgs() {
    let (a, _, _, _) = *oracle::qr5x2_q_r_cases().at(3);
    let a = black_box(mat5x2(a));
    let e = black_box(true);
    let f = Qr5x2Trait::new(a);
    assert!((f.r.m11 >= fx(0)) == e);
}
