// Generated by crates/nalgebra/src/linalg/generate.py: do not edit by hand.
//! `Qr1`: the QR factorisation of a `Matrix1` (upstream `nalgebra::linalg::QR<T, U1, U1>`) by
//! modified Gram-Schmidt, the algorithm of `Qr3` / `Qr4` (see `linalg::qr` for the study of the
//! alternatives), generated for the shapes P14a did not cover (WP 8.5-P14b).

use simba::scalar::Real;
use crate::base::matrix1::Matrix1;
use crate::base::solve::SolveKernel;

/// The QR factorisation `A = q * r` of a `Matrix1<T>`: `q` is 1x1, `r` is 1x1
/// upper triangular (trapezoidal) with a non-negative diagonal and an exactly zero strict lower
/// part — upstream's unpacked `q()` / `r()`. A column that collapses to exactly zero gives a
/// zero column of `q` and a zero diagonal entry of `r` (`q * r = A` still holds; see
/// `linalg::qr`). Upstream: `nalgebra::linalg::QR`.
#[derive(Copy, Drop, Serde, Debug)]
pub struct Qr1<T> {
    /// The orthonormal factor (1x1).
    pub q: Matrix1<T>,
    /// The upper triangular factor (1x1), `r_ii >= 0`.
    pub r: Matrix1<T>,
}

/// Test-only field-wise equality (upstream `QR` has no `PartialEq`).
#[cfg(test)]
impl Qr1PartialEq<T, +PartialEq<T>> of PartialEq<Qr1<T>> {
    fn eq(lhs: @Qr1<T>, rhs: @Qr1<T>) -> bool {
        lhs.q == rhs.q && lhs.r == rhs.r
    }
}

/// Methods of `Qr1<T>` for any `Real` scalar.
#[generate_trait]
pub impl Qr1Impl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Qr1Trait<T> {
    /// The QR factorisation of `matrix` by modified Gram-Schmidt, fully unrolled: for each of
    /// the 1 leading columns, `r_ii = |a_i|` (floored norm of the exact sum of squares), `q_i =
    /// a_i / r_ii` (one prepared divisor), then `r_ij = <q_i, a_j>` (fused) and `a_j -= r_ij q_i`
    /// (one `mul_add` per component) for the later columns. Panics on overflow of a norm.
    /// Upstream: `matrix.qr()` / `QR::new(matrix)` (Householder, same unpacked factors).
    fn new(matrix: Matrix1<T>) -> Qr1<T> {
        let a0 = Matrix1 { x: matrix.x };
        let r0_0 = a0.x.abs();
        let q0 = if r0_0 == R::zero() {
            Matrix1 { x: R::zero() }
        } else {
            Matrix1 { x: R::div(a0.x, r0_0) }
        };
        Qr1 { q: Matrix1 { x: q0.x }, r: Matrix1 { x: r0_0 } }
    }

    /// The orthonormal factor. Exact: a move. Upstream: `QR::q`.
    #[inline(always)]
    fn q(self: Qr1<T>) -> Matrix1<T> {
        self.q
    }

    /// The upper triangular factor. Exact: a move. Upstream: `QR::r`.
    #[inline(always)]
    fn r(self: Qr1<T>) -> Matrix1<T> {
        self.r
    }

    /// `(q, r)`. Exact: moves. Upstream: `QR::unpack`.
    #[inline(always)]
    fn unpack(self: Qr1<T>) -> (Matrix1<T>, Matrix1<T>) {
        (self.q, self.r)
    }

    /// The upper triangular factor, consuming the factorisation. Exact. Upstream: `QR::unpack_r`.
    #[inline(always)]
    fn unpack_r(self: Qr1<T>) -> Matrix1<T> {
        self.r
    }

    /// The factors as stored, `(q, r)` (modified Gram-Schmidt keeps both; upstream packs the
    /// reflectors). Exact. Upstream: `QR::qr_internal` (`#[doc(hidden)]`).
    #[inline(always)]
    fn qr_internal(self: Qr1<T>) -> (Matrix1<T>, Matrix1<T>) {
        (self.q, self.r)
    }

    /// `rhs = Qᵀ * rhs` in place, for any `rhs` with 1 rows (a vector or a matrix): ONE fused
    /// sum of products per entry, floored once. Upstream: `QR::q_tr_mul` (the Householder
    /// reflections one after the other, a rounding each).
    fn q_tr_mul<B, impl K: SolveKernel<Matrix1<T>, B>, +Drop<B>>(self: Qr1<T>, ref rhs: B) {
        rhs = K::tr_mul_rhs(self.q, rhs);
    }

    /// Overwrites `b` (any shape with 1 rows) with the solution of `A * x = b` and returns
    /// `true`, or returns `false` and leaves `b` unchanged when a diagonal entry of `R` is exactly
    /// zero (upstream returns `false` after overwriting `b` with `Qᵀ b`). `x = R⁻¹ (Qᵀ b)`:
    /// one fused `tr_mul`, then back substitution. Panics on overflow. Upstream: `QR::solve_mut`.
    fn solve_mut<B, impl K: SolveKernel<Matrix1<T>, B>, +Drop<B>>(self: Qr1<T>, ref b: B) -> bool {
        if !Self::is_invertible(self) {
            return false;
        }
        b = K::upper(self.r, K::tr_mul_rhs(self.q, b));
        true
    }

    /// Whether every diagonal entry of `R` is EXACTLY nonzero (no epsilon), like upstream's
    /// `QR::is_invertible`. Equivalently, `Q` is orthonormal.
    #[inline(always)]
    fn is_invertible(self: Qr1<T>) -> bool {
        self.r.x != R::zero()
    }

    /// The solution of `A * x = b`, or `None` when `R` has an exactly zero diagonal entry.
    /// `Qᵀ b` (one fused sum per component), then back substitution (one fused numerator and one
    /// correctly rounded division per component). Panics on overflow. Upstream: `QR::solve`.
    fn solve(self: Qr1<T>, b: Matrix1<T>) -> Option<Matrix1<T>> {
        if !Self::is_invertible(self) {
            return None;
        }
        let y0 = self.q.x * b.x;
        Some(Qr1InternalTrait::back_substitute(self, Matrix1 { x: y0 }))
    }

    /// The inverse `R⁻¹ Qᵀ`, or `None` when `R` has an exactly zero diagonal entry: the back
    /// substitution of each row of `Q`. Two roundings per entry. Panics on overflow. Upstream:
    /// `QR::try_inverse`.
    fn try_inverse(self: Qr1<T>) -> Option<Matrix1<T>> {
        if !Self::is_invertible(self) {
            return None;
        }
        let c0 = Qr1InternalTrait::back_substitute(self, Matrix1 { x: self.q.x });
        Some(Matrix1 { x: c0.x })
    }
}

/// Crate-internal kernel of `Qr1<T>`: the back substitution shared by `solve` and `try_inverse`.
#[generate_trait]
pub(crate) impl Qr1InternalImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Qr1InternalTrait<T> {
    /// `R⁻¹ y` (the caller guarantees a nonzero diagonal).
    #[inline(always)]
    fn back_substitute(self: Qr1<T>, y: Matrix1<T>) -> Matrix1<T> {
        let x0 = R::div(R::wide_rescale(R::wide_add(R::wide_zero(), y.x)), self.r.x);
        Matrix1 { x: x0 }
    }
}

/// `Matrix1` methods that go through the QR factorisation. Import `Matrix1QrTrait` to use them.
#[generate_trait]
pub impl Matrix1QrImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix1QrTrait<T> {
    /// The QR factorisation. Upstream: `Matrix::qr`.
    #[inline(always)]
    fn qr(self: Matrix1<T>) -> Qr1<T> {
        Qr1Trait::new(self)
    }
}
