[package]
name = "nalgebra_geometry3"
description = "The 3D geometry: quaternions, unit quaternions, Rotation3 methods, isometries, similarities, dual quaternions, AbstractRotation, point / translation / scale 3 methods, Matrix4 homogeneous (cg)."
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["linear-algebra", "fixed-point", "geometry", "cg"]
readme = "README.md"

[dependencies]
nalgebra_core = { path = "../core", version = "0.1.1" }
nalgebra_types2 = { path = "../types2", version = "0.1.1" }
nalgebra_types3 = { path = "../types3", version = "0.1.1" }
nalgebra_types4 = { path = "../types4", version = "0.1.1" }
nalgebra_static3 = { path = "../static3", version = "0.1.1", default-features = false }
nalgebra_geometry2 = { path = "../geometry2", version = "0.1.1" }
simba.workspace = true

[dev-dependencies]
fixed.workspace = true
snforge_std.workspace = true
assert_macros.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true
