[package]
name = "nalgebra_geometry2"
description = "The 1D / 2D geometry: UnitComplex, Rotation2 methods, isometries, similarities, points / translations / scales 1-2 methods, swizzles, Matrix2 / Matrix3 homogeneous (cg)."
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["linear-algebra", "fixed-point", "geometry", "cg"]
readme = "README.md"

[dependencies]
nalgebra_core = { path = "../core", version = "0.1.1" }
nalgebra_types2 = { path = "../types2", version = "0.1.1" }
nalgebra_types3 = { path = "../types3", version = "0.1.1" }
simba.workspace = true

[dev-dependencies]
fixed.workspace = true
snforge_std.workspace = true
assert_macros.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true
