// Generated by tools/linalggen/generate.py: do not edit by hand.
//! `Matrix5::pow / pow_mut` through the public API (WP 8.5-P17): oracle vectors (`tools/oracle`
//! suite `matrix_functions`), exact cases, gas benchmarks.

use core::cmp::max;
use nalgebra::linalg::Matrix5PowTrait;
use nalgebra_testing::black_box;
use nalgebra_tests_utils::{abs_raw, excess, oracle_tol, ulp_diff};
use crate::builders::mat5x5;
use crate::oracle_matrix_functions as oracle;

/// `pow5` (oracle): every entry within the oracle tolerance; `pow_mut` agrees bit for bit.
#[test]
fn test_oracle_pow5() {
    let mut cases = oracle::pow5_cases();
    let mut ex = 0;
    while let Some(case) = cases.pop_front() {
        let (a, k, e, tol) = *case;
        let a = black_box(mat5x5(a));
        let k: u32 = (k / 0x100000000).try_into().unwrap();
        let got = a.pow(k);
        let e = mat5x5(e);
        ex = max(ex, excess(ulp_diff(got.m11, e.m11), oracle_tol(abs_raw(e.m11), tol)));
        ex = max(ex, excess(ulp_diff(got.m12, e.m12), oracle_tol(abs_raw(e.m12), tol)));
        ex = max(ex, excess(ulp_diff(got.m13, e.m13), oracle_tol(abs_raw(e.m13), tol)));
        ex = max(ex, excess(ulp_diff(got.m14, e.m14), oracle_tol(abs_raw(e.m14), tol)));
        ex = max(ex, excess(ulp_diff(got.m15, e.m15), oracle_tol(abs_raw(e.m15), tol)));
        ex = max(ex, excess(ulp_diff(got.m21, e.m21), oracle_tol(abs_raw(e.m21), tol)));
        ex = max(ex, excess(ulp_diff(got.m22, e.m22), oracle_tol(abs_raw(e.m22), tol)));
        ex = max(ex, excess(ulp_diff(got.m23, e.m23), oracle_tol(abs_raw(e.m23), tol)));
        ex = max(ex, excess(ulp_diff(got.m24, e.m24), oracle_tol(abs_raw(e.m24), tol)));
        ex = max(ex, excess(ulp_diff(got.m25, e.m25), oracle_tol(abs_raw(e.m25), tol)));
        ex = max(ex, excess(ulp_diff(got.m31, e.m31), oracle_tol(abs_raw(e.m31), tol)));
        ex = max(ex, excess(ulp_diff(got.m32, e.m32), oracle_tol(abs_raw(e.m32), tol)));
        ex = max(ex, excess(ulp_diff(got.m33, e.m33), oracle_tol(abs_raw(e.m33), tol)));
        ex = max(ex, excess(ulp_diff(got.m34, e.m34), oracle_tol(abs_raw(e.m34), tol)));
        ex = max(ex, excess(ulp_diff(got.m35, e.m35), oracle_tol(abs_raw(e.m35), tol)));
        ex = max(ex, excess(ulp_diff(got.m41, e.m41), oracle_tol(abs_raw(e.m41), tol)));
        ex = max(ex, excess(ulp_diff(got.m42, e.m42), oracle_tol(abs_raw(e.m42), tol)));
        ex = max(ex, excess(ulp_diff(got.m43, e.m43), oracle_tol(abs_raw(e.m43), tol)));
        ex = max(ex, excess(ulp_diff(got.m44, e.m44), oracle_tol(abs_raw(e.m44), tol)));
        ex = max(ex, excess(ulp_diff(got.m45, e.m45), oracle_tol(abs_raw(e.m45), tol)));
        ex = max(ex, excess(ulp_diff(got.m51, e.m51), oracle_tol(abs_raw(e.m51), tol)));
        ex = max(ex, excess(ulp_diff(got.m52, e.m52), oracle_tol(abs_raw(e.m52), tol)));
        ex = max(ex, excess(ulp_diff(got.m53, e.m53), oracle_tol(abs_raw(e.m53), tol)));
        ex = max(ex, excess(ulp_diff(got.m54, e.m54), oracle_tol(abs_raw(e.m54), tol)));
        ex = max(ex, excess(ulp_diff(got.m55, e.m55), oracle_tol(abs_raw(e.m55), tol)));
        let mut b = a;
        b.pow_mut(k);
        assert!(b == got);
    }
    assert!(ex == 0, "oracle tolerance exceeded by {}", ex);
}

/// Exact cases: `a⁰ = I`, `a¹ = a`, `(2 I)⁷ = 128 I`.
#[test]
fn test_pow5_exact_cases() {
    let (a, _, _, _) = *oracle::pow5_cases().at(0);
    let a = black_box(mat5x5(a));
    assert!(
        a
            .pow(
                0,
            ) == mat5x5(
                [
                    [4294967296, 0, 0, 0, 0], [0, 4294967296, 0, 0, 0], [0, 0, 4294967296, 0, 0],
                    [0, 0, 0, 4294967296, 0], [0, 0, 0, 0, 4294967296],
                ],
            ),
    );
    assert!(a.pow(1) == a);
    let t = black_box(
        mat5x5(
            [
                [8589934592, 0, 0, 0, 0], [0, 8589934592, 0, 0, 0], [0, 0, 8589934592, 0, 0],
                [0, 0, 0, 8589934592, 0], [0, 0, 0, 0, 8589934592],
            ],
        ),
    );
    assert!(
        t
            .pow(
                7,
            ) == mat5x5(
                [
                    [549755813888, 0, 0, 0, 0], [0, 549755813888, 0, 0, 0],
                    [0, 0, 549755813888, 0, 0], [0, 0, 0, 549755813888, 0],
                    [0, 0, 0, 0, 549755813888],
                ],
            ),
    );
}

#[test]
#[inline(never)]
fn bench_pow5__baseline() {
    let (a, _, _, _) = *oracle::pow5_cases().at(0);
    let _a = black_box(mat5x5(a));
    let _k = black_box(5_u32);
    let e = black_box(true);
    assert!(e == e);
}

/// `a⁵`: three products (bits 101: `x`, `x²`, `x⁴`, `self = x · x⁴`).
#[test]
#[inline(never)]
fn bench_pow5__by_squaring() {
    let (a, _, _, _) = *oracle::pow5_cases().at(0);
    let a = black_box(mat5x5(a));
    let k = black_box(5_u32);
    let e = black_box(true);
    let p = a.pow(k);
    assert!((p.m11 == p.m11) == e);
}
