// Generated by crates/nalgebra/src/linalg/generate.py: do not edit by hand.
//! `FullPivLu6x4`: the LU factorisation with full pivoting of a `Matrix6x4` (upstream
//! `nalgebra::linalg::FullPivLU<T, U6, U4>`), fully unrolled (WP 8.5-P15).

use core::internal::revoke_ap_tracking;
use simba::scalar::Real;
use crate::base::matrix4::Matrix4;
use crate::base::matrix6x4::Matrix6x4;
use crate::linalg::lu::{Perm4, Perm6};

/// The LU factorisation with full (row and column) pivoting of a `Matrix6x4<T>`: `P A Q = L U`.
///
/// `lu` packs both factors like upstream (strict lower triangle = `L` without its unit diagonal,
/// upper triangle = `U`); `p` holds the row transpositions and `q` the column transpositions, as
/// the compact sequences `Perm6` / `Perm4` — the permutations of the rows / columns of the
/// matrix, where upstream's `PermutationSequence<DimMinimum<R, C>>` holds the same `min(R, C)`
/// transpositions (a step that swaps nothing records the identity, as upstream's `append` of
/// `(i, i)`).
///
/// Non-square: `m = min(6, 4) = 4` elimination steps; `L` is 6x4, `U` 4x4. Built by
/// `FullPivLu6x4Trait::new` or `Matrix6x4FullPivLuTrait::full_piv_lu`.
/// Upstream: `nalgebra::linalg::FullPivLU`.
#[derive(Copy, Drop, Serde, Debug)]
pub struct FullPivLu6x4<T> {
    /// `L` (strict lower triangle) and `U` (upper triangle) packed in one matrix.
    pub lu: Matrix6x4<T>,
    /// The row transpositions (`P`).
    pub p: Perm6,
    /// The column transpositions (`Q`).
    pub q: Perm4,
}

/// Methods of `FullPivLu6x4<T>` for any `Real` scalar.
#[generate_trait]
pub impl FullPivLu6x4Impl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of FullPivLu6x4Trait<T> {
    /// The LU factorisation of `matrix` with full pivoting, fully unrolled. Upstream:
    /// `matrix.full_piv_lu()` / `FullPivLU::new(matrix)`.
    ///
    /// Always succeeds, like upstream. At step `k` the pivot is the FIRST entry of largest `|a_ij|`
    /// of the trailing block in column-major order (upstream's `icamax_full`: strict `>`, so ties
    /// go to the lowest column, then the lowest row); its column is swapped with column `k` and its
    /// row with row `k` (whole rows and columns: upstream's `swap_columns` + `gauss_step_swap`).
    /// A trailing block that is exactly zero ends the elimination (upstream's `break`): nothing is
    /// swapped nor recorded from there on. The multipliers `l_ik = a_ik / a_kk` are correctly
    /// rounded quotients by one prepared divisor (upstream multiplies by a rounded `1 / a_kk`, as
    /// in `gauss_step`), and every update is ONE `Real::mul_add` (one floor per entry per step).
    /// Panics on overflow of an update.
    fn new(matrix: Matrix6x4<T>) -> FullPivLu6x4<T> {
        revoke_ap_tracking();
        let mut a00 = matrix.m11;
        let mut a10 = matrix.m21;
        let mut a20 = matrix.m31;
        let mut a30 = matrix.m41;
        let mut a40 = matrix.m51;
        let mut a50 = matrix.m61;
        let mut a01 = matrix.m12;
        let mut a11 = matrix.m22;
        let mut a21 = matrix.m32;
        let mut a31 = matrix.m42;
        let mut a41 = matrix.m52;
        let mut a51 = matrix.m62;
        let mut a02 = matrix.m13;
        let mut a12 = matrix.m23;
        let mut a22 = matrix.m33;
        let mut a32 = matrix.m43;
        let mut a42 = matrix.m53;
        let mut a52 = matrix.m63;
        let mut a03 = matrix.m14;
        let mut a13 = matrix.m24;
        let mut a23 = matrix.m34;
        let mut a33 = matrix.m44;
        let mut a43 = matrix.m54;
        let mut a53 = matrix.m64;
        // step 1: the first largest |a_ij| of rows 1..6, columns 1..4 (column-major scan)
        let mut piv = R::abs(a00);
        let mut rp0 = 1_u8;
        let mut cp0 = 1_u8;
        let x = R::abs(a10);
        if x > piv {
            piv = x;
            rp0 = 2;
            cp0 = 1;
        }
        let x = R::abs(a20);
        if x > piv {
            piv = x;
            rp0 = 3;
            cp0 = 1;
        }
        let x = R::abs(a30);
        if x > piv {
            piv = x;
            rp0 = 4;
            cp0 = 1;
        }
        let x = R::abs(a40);
        if x > piv {
            piv = x;
            rp0 = 5;
            cp0 = 1;
        }
        let x = R::abs(a50);
        if x > piv {
            piv = x;
            rp0 = 6;
            cp0 = 1;
        }
        let x = R::abs(a01);
        if x > piv {
            piv = x;
            rp0 = 1;
            cp0 = 2;
        }
        let x = R::abs(a11);
        if x > piv {
            piv = x;
            rp0 = 2;
            cp0 = 2;
        }
        let x = R::abs(a21);
        if x > piv {
            piv = x;
            rp0 = 3;
            cp0 = 2;
        }
        let x = R::abs(a31);
        if x > piv {
            piv = x;
            rp0 = 4;
            cp0 = 2;
        }
        let x = R::abs(a41);
        if x > piv {
            piv = x;
            rp0 = 5;
            cp0 = 2;
        }
        let x = R::abs(a51);
        if x > piv {
            piv = x;
            rp0 = 6;
            cp0 = 2;
        }
        let x = R::abs(a02);
        if x > piv {
            piv = x;
            rp0 = 1;
            cp0 = 3;
        }
        let x = R::abs(a12);
        if x > piv {
            piv = x;
            rp0 = 2;
            cp0 = 3;
        }
        let x = R::abs(a22);
        if x > piv {
            piv = x;
            rp0 = 3;
            cp0 = 3;
        }
        let x = R::abs(a32);
        if x > piv {
            piv = x;
            rp0 = 4;
            cp0 = 3;
        }
        let x = R::abs(a42);
        if x > piv {
            piv = x;
            rp0 = 5;
            cp0 = 3;
        }
        let x = R::abs(a52);
        if x > piv {
            piv = x;
            rp0 = 6;
            cp0 = 3;
        }
        let x = R::abs(a03);
        if x > piv {
            piv = x;
            rp0 = 1;
            cp0 = 4;
        }
        let x = R::abs(a13);
        if x > piv {
            piv = x;
            rp0 = 2;
            cp0 = 4;
        }
        let x = R::abs(a23);
        if x > piv {
            piv = x;
            rp0 = 3;
            cp0 = 4;
        }
        let x = R::abs(a33);
        if x > piv {
            piv = x;
            rp0 = 4;
            cp0 = 4;
        }
        let x = R::abs(a43);
        if x > piv {
            piv = x;
            rp0 = 5;
            cp0 = 4;
        }
        let x = R::abs(a53);
        if x > piv {
            piv = x;
            rp0 = 6;
            cp0 = 4;
        }
        if piv != R::zero() {
            if cp0 == 2 {
                let t = a00;
                a00 = a01;
                a01 = t;
                let t = a10;
                a10 = a11;
                a11 = t;
                let t = a20;
                a20 = a21;
                a21 = t;
                let t = a30;
                a30 = a31;
                a31 = t;
                let t = a40;
                a40 = a41;
                a41 = t;
                let t = a50;
                a50 = a51;
                a51 = t;
            } else if cp0 == 3 {
                let t = a00;
                a00 = a02;
                a02 = t;
                let t = a10;
                a10 = a12;
                a12 = t;
                let t = a20;
                a20 = a22;
                a22 = t;
                let t = a30;
                a30 = a32;
                a32 = t;
                let t = a40;
                a40 = a42;
                a42 = t;
                let t = a50;
                a50 = a52;
                a52 = t;
            } else if cp0 == 4 {
                let t = a00;
                a00 = a03;
                a03 = t;
                let t = a10;
                a10 = a13;
                a13 = t;
                let t = a20;
                a20 = a23;
                a23 = t;
                let t = a30;
                a30 = a33;
                a33 = t;
                let t = a40;
                a40 = a43;
                a43 = t;
                let t = a50;
                a50 = a53;
                a53 = t;
            }
            if rp0 == 2 {
                let t = a00;
                a00 = a10;
                a10 = t;
                let t = a01;
                a01 = a11;
                a11 = t;
                let t = a02;
                a02 = a12;
                a12 = t;
                let t = a03;
                a03 = a13;
                a13 = t;
            } else if rp0 == 3 {
                let t = a00;
                a00 = a20;
                a20 = t;
                let t = a01;
                a01 = a21;
                a21 = t;
                let t = a02;
                a02 = a22;
                a22 = t;
                let t = a03;
                a03 = a23;
                a23 = t;
            } else if rp0 == 4 {
                let t = a00;
                a00 = a30;
                a30 = t;
                let t = a01;
                a01 = a31;
                a31 = t;
                let t = a02;
                a02 = a32;
                a32 = t;
                let t = a03;
                a03 = a33;
                a33 = t;
            } else if rp0 == 5 {
                let t = a00;
                a00 = a40;
                a40 = t;
                let t = a01;
                a01 = a41;
                a41 = t;
                let t = a02;
                a02 = a42;
                a42 = t;
                let t = a03;
                a03 = a43;
                a43 = t;
            } else if rp0 == 6 {
                let t = a00;
                a00 = a50;
                a50 = t;
                let t = a01;
                a01 = a51;
                a51 = t;
                let t = a02;
                a02 = a52;
                a52 = t;
                let t = a03;
                a03 = a53;
                a53 = t;
            }
            let (l1, l2, l3, l4, l5) = R::div5(a10, a20, a30, a40, a50, a00);
            let nl = -l1;
            a11 = R::mul_add(nl, a01, a11);
            a12 = R::mul_add(nl, a02, a12);
            a13 = R::mul_add(nl, a03, a13);
            a10 = l1;
            let nl = -l2;
            a21 = R::mul_add(nl, a01, a21);
            a22 = R::mul_add(nl, a02, a22);
            a23 = R::mul_add(nl, a03, a23);
            a20 = l2;
            let nl = -l3;
            a31 = R::mul_add(nl, a01, a31);
            a32 = R::mul_add(nl, a02, a32);
            a33 = R::mul_add(nl, a03, a33);
            a30 = l3;
            let nl = -l4;
            a41 = R::mul_add(nl, a01, a41);
            a42 = R::mul_add(nl, a02, a42);
            a43 = R::mul_add(nl, a03, a43);
            a40 = l4;
            let nl = -l5;
            a51 = R::mul_add(nl, a01, a51);
            a52 = R::mul_add(nl, a02, a52);
            a53 = R::mul_add(nl, a03, a53);
            a50 = l5;
        }
        // step 2: the first largest |a_ij| of rows 2..6, columns 2..4 (column-major scan)
        let mut piv = R::abs(a11);
        let mut rp1 = 2_u8;
        let mut cp1 = 2_u8;
        let x = R::abs(a21);
        if x > piv {
            piv = x;
            rp1 = 3;
            cp1 = 2;
        }
        let x = R::abs(a31);
        if x > piv {
            piv = x;
            rp1 = 4;
            cp1 = 2;
        }
        let x = R::abs(a41);
        if x > piv {
            piv = x;
            rp1 = 5;
            cp1 = 2;
        }
        let x = R::abs(a51);
        if x > piv {
            piv = x;
            rp1 = 6;
            cp1 = 2;
        }
        let x = R::abs(a12);
        if x > piv {
            piv = x;
            rp1 = 2;
            cp1 = 3;
        }
        let x = R::abs(a22);
        if x > piv {
            piv = x;
            rp1 = 3;
            cp1 = 3;
        }
        let x = R::abs(a32);
        if x > piv {
            piv = x;
            rp1 = 4;
            cp1 = 3;
        }
        let x = R::abs(a42);
        if x > piv {
            piv = x;
            rp1 = 5;
            cp1 = 3;
        }
        let x = R::abs(a52);
        if x > piv {
            piv = x;
            rp1 = 6;
            cp1 = 3;
        }
        let x = R::abs(a13);
        if x > piv {
            piv = x;
            rp1 = 2;
            cp1 = 4;
        }
        let x = R::abs(a23);
        if x > piv {
            piv = x;
            rp1 = 3;
            cp1 = 4;
        }
        let x = R::abs(a33);
        if x > piv {
            piv = x;
            rp1 = 4;
            cp1 = 4;
        }
        let x = R::abs(a43);
        if x > piv {
            piv = x;
            rp1 = 5;
            cp1 = 4;
        }
        let x = R::abs(a53);
        if x > piv {
            piv = x;
            rp1 = 6;
            cp1 = 4;
        }
        if piv != R::zero() {
            if cp1 == 3 {
                let t = a01;
                a01 = a02;
                a02 = t;
                let t = a11;
                a11 = a12;
                a12 = t;
                let t = a21;
                a21 = a22;
                a22 = t;
                let t = a31;
                a31 = a32;
                a32 = t;
                let t = a41;
                a41 = a42;
                a42 = t;
                let t = a51;
                a51 = a52;
                a52 = t;
            } else if cp1 == 4 {
                let t = a01;
                a01 = a03;
                a03 = t;
                let t = a11;
                a11 = a13;
                a13 = t;
                let t = a21;
                a21 = a23;
                a23 = t;
                let t = a31;
                a31 = a33;
                a33 = t;
                let t = a41;
                a41 = a43;
                a43 = t;
                let t = a51;
                a51 = a53;
                a53 = t;
            }
            if rp1 == 3 {
                let t = a10;
                a10 = a20;
                a20 = t;
                let t = a11;
                a11 = a21;
                a21 = t;
                let t = a12;
                a12 = a22;
                a22 = t;
                let t = a13;
                a13 = a23;
                a23 = t;
            } else if rp1 == 4 {
                let t = a10;
                a10 = a30;
                a30 = t;
                let t = a11;
                a11 = a31;
                a31 = t;
                let t = a12;
                a12 = a32;
                a32 = t;
                let t = a13;
                a13 = a33;
                a33 = t;
            } else if rp1 == 5 {
                let t = a10;
                a10 = a40;
                a40 = t;
                let t = a11;
                a11 = a41;
                a41 = t;
                let t = a12;
                a12 = a42;
                a42 = t;
                let t = a13;
                a13 = a43;
                a43 = t;
            } else if rp1 == 6 {
                let t = a10;
                a10 = a50;
                a50 = t;
                let t = a11;
                a11 = a51;
                a51 = t;
                let t = a12;
                a12 = a52;
                a52 = t;
                let t = a13;
                a13 = a53;
                a53 = t;
            }
            let (l2, l3, l4, l5) = R::div4(a21, a31, a41, a51, a11);
            let nl = -l2;
            a22 = R::mul_add(nl, a12, a22);
            a23 = R::mul_add(nl, a13, a23);
            a21 = l2;
            let nl = -l3;
            a32 = R::mul_add(nl, a12, a32);
            a33 = R::mul_add(nl, a13, a33);
            a31 = l3;
            let nl = -l4;
            a42 = R::mul_add(nl, a12, a42);
            a43 = R::mul_add(nl, a13, a43);
            a41 = l4;
            let nl = -l5;
            a52 = R::mul_add(nl, a12, a52);
            a53 = R::mul_add(nl, a13, a53);
            a51 = l5;
        }
        // step 3: the first largest |a_ij| of rows 3..6, columns 3..4 (column-major scan)
        let mut piv = R::abs(a22);
        let mut rp2 = 3_u8;
        let mut cp2 = 3_u8;
        let x = R::abs(a32);
        if x > piv {
            piv = x;
            rp2 = 4;
            cp2 = 3;
        }
        let x = R::abs(a42);
        if x > piv {
            piv = x;
            rp2 = 5;
            cp2 = 3;
        }
        let x = R::abs(a52);
        if x > piv {
            piv = x;
            rp2 = 6;
            cp2 = 3;
        }
        let x = R::abs(a23);
        if x > piv {
            piv = x;
            rp2 = 3;
            cp2 = 4;
        }
        let x = R::abs(a33);
        if x > piv {
            piv = x;
            rp2 = 4;
            cp2 = 4;
        }
        let x = R::abs(a43);
        if x > piv {
            piv = x;
            rp2 = 5;
            cp2 = 4;
        }
        let x = R::abs(a53);
        if x > piv {
            piv = x;
            rp2 = 6;
            cp2 = 4;
        }
        if piv != R::zero() {
            if cp2 == 4 {
                let t = a02;
                a02 = a03;
                a03 = t;
                let t = a12;
                a12 = a13;
                a13 = t;
                let t = a22;
                a22 = a23;
                a23 = t;
                let t = a32;
                a32 = a33;
                a33 = t;
                let t = a42;
                a42 = a43;
                a43 = t;
                let t = a52;
                a52 = a53;
                a53 = t;
            }
            if rp2 == 4 {
                let t = a20;
                a20 = a30;
                a30 = t;
                let t = a21;
                a21 = a31;
                a31 = t;
                let t = a22;
                a22 = a32;
                a32 = t;
                let t = a23;
                a23 = a33;
                a33 = t;
            } else if rp2 == 5 {
                let t = a20;
                a20 = a40;
                a40 = t;
                let t = a21;
                a21 = a41;
                a41 = t;
                let t = a22;
                a22 = a42;
                a42 = t;
                let t = a23;
                a23 = a43;
                a43 = t;
            } else if rp2 == 6 {
                let t = a20;
                a20 = a50;
                a50 = t;
                let t = a21;
                a21 = a51;
                a51 = t;
                let t = a22;
                a22 = a52;
                a52 = t;
                let t = a23;
                a23 = a53;
                a53 = t;
            }
            let (l3, l4, l5) = R::div3(a32, a42, a52, a22);
            let nl = -l3;
            a33 = R::mul_add(nl, a23, a33);
            a32 = l3;
            let nl = -l4;
            a43 = R::mul_add(nl, a23, a43);
            a42 = l4;
            let nl = -l5;
            a53 = R::mul_add(nl, a23, a53);
            a52 = l5;
        }
        // step 4: the first largest |a_ij| of rows 4..6, columns 4..4 (column-major scan)
        let mut piv = R::abs(a33);
        let mut rp3 = 4_u8;
        let x = R::abs(a43);
        if x > piv {
            piv = x;
            rp3 = 5;
        }
        let x = R::abs(a53);
        if x > piv {
            piv = x;
            rp3 = 6;
        }
        if piv != R::zero() {
            if rp3 == 5 {
                let t = a30;
                a30 = a40;
                a40 = t;
                let t = a31;
                a31 = a41;
                a41 = t;
                let t = a32;
                a32 = a42;
                a42 = t;
                let t = a33;
                a33 = a43;
                a43 = t;
            } else if rp3 == 6 {
                let t = a30;
                a30 = a50;
                a50 = t;
                let t = a31;
                a31 = a51;
                a51 = t;
                let t = a32;
                a32 = a52;
                a52 = t;
                let t = a33;
                a33 = a53;
                a53 = t;
            }
            let (l4, l5) = (R::div(a43, a33), R::div(a53, a33));
            a43 = l4;
            a53 = l5;
        }
        FullPivLu6x4 {
            lu: Matrix6x4 {
                m11: a00,
                m21: a10,
                m31: a20,
                m41: a30,
                m51: a40,
                m61: a50,
                m12: a01,
                m22: a11,
                m32: a21,
                m42: a31,
                m52: a41,
                m62: a51,
                m13: a02,
                m23: a12,
                m33: a22,
                m43: a32,
                m53: a42,
                m63: a52,
                m14: a03,
                m24: a13,
                m34: a23,
                m44: a33,
                m54: a43,
                m64: a53,
            },
            p: Perm6 { p1: rp0, p2: rp1, p3: rp2, p4: rp3, p5: 5 },
            q: Perm4 { p1: cp0, p2: cp1, p3: cp2 },
        }
    }

    /// The packed factors as stored (strict lower triangle = `L`, upper triangle = `U`). Exact.
    /// Upstream: `FullPivLU::lu_internal` (`#[doc(hidden)]`).
    #[inline(always)]
    fn lu_internal(self: FullPivLu6x4<T>) -> Matrix6x4<T> {
        self.lu
    }

    /// The unit lower triangular factor `L` (6x4). Exact: moves. Upstream: `FullPivLU::l`.
    #[inline(always)]
    fn l(self: FullPivLu6x4<T>) -> Matrix6x4<T> {
        Matrix6x4 {
            m11: R::one(),
            m21: self.lu.m21,
            m31: self.lu.m31,
            m41: self.lu.m41,
            m51: self.lu.m51,
            m61: self.lu.m61,
            m12: R::zero(),
            m22: R::one(),
            m32: self.lu.m32,
            m42: self.lu.m42,
            m52: self.lu.m52,
            m62: self.lu.m62,
            m13: R::zero(),
            m23: R::zero(),
            m33: R::one(),
            m43: self.lu.m43,
            m53: self.lu.m53,
            m63: self.lu.m63,
            m14: R::zero(),
            m24: R::zero(),
            m34: R::zero(),
            m44: R::one(),
            m54: self.lu.m54,
            m64: self.lu.m64,
        }
    }

    /// The upper triangular factor `U` (4x4). Exact: moves. Upstream: `FullPivLU::u`.
    #[inline(always)]
    fn u(self: FullPivLu6x4<T>) -> Matrix4<T> {
        Matrix4 {
            m11: self.lu.m11,
            m21: R::zero(),
            m31: R::zero(),
            m41: R::zero(),
            m12: self.lu.m12,
            m22: self.lu.m22,
            m32: R::zero(),
            m42: R::zero(),
            m13: self.lu.m13,
            m23: self.lu.m23,
            m33: self.lu.m33,
            m43: R::zero(),
            m14: self.lu.m14,
            m24: self.lu.m24,
            m34: self.lu.m34,
            m44: self.lu.m44,
        }
    }

    /// The row permutation `P`. Upstream: `FullPivLU::p`.
    #[inline(always)]
    fn p(self: FullPivLu6x4<T>) -> Perm6 {
        self.p
    }

    /// The column permutation `Q`. Upstream: `FullPivLU::q`.
    #[inline(always)]
    fn q(self: FullPivLu6x4<T>) -> Perm4 {
        self.q
    }

    /// `(P, L, U, Q)`: `(p(), l(), u(), q())`, exact. Upstream: `FullPivLU::unpack`.
    #[inline(always)]
    fn unpack(self: FullPivLu6x4<T>) -> (Perm6, Matrix6x4<T>, Matrix4<T>, Perm4) {
        (self.p, Self::l(self), Self::u(self), self.q)
    }
}

/// `Matrix6x4` methods that go through the full-pivot LU factorisation. Import
/// `Matrix6x4FullPivLuTrait`.
#[generate_trait]
pub impl Matrix6x4FullPivLuImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix6x4FullPivLuTrait<T> {
    /// The LU factorisation with full pivoting. Upstream: `Matrix::full_piv_lu`.
    #[inline(always)]
    fn full_piv_lu(self: Matrix6x4<T>) -> FullPivLu6x4<T> {
        FullPivLu6x4Trait::new(self)
    }
}
