// Generated by crates/nalgebra/src/linalg/generate.py: do not edit by hand.
//! `FullPivLu2`: the LU factorisation with full pivoting of a `Matrix2` (upstream
//! `nalgebra::linalg::FullPivLU<T, U2, U2>`), fully unrolled (WP 8.5-P15).

use core::internal::revoke_ap_tracking;
use simba::scalar::Real;
use crate::base::matrix2::Matrix2;
use crate::base::solve::SolveKernel;
use crate::linalg::lu::Perm2;
use crate::linalg::permutation_sequence::{PermuteColumns, PermuteRows};

/// The LU factorisation with full (row and column) pivoting of a `Matrix2<T>`: `P A Q = L U`.
///
/// `lu` packs both factors like upstream (strict lower triangle = `L` without its unit diagonal,
/// upper triangle = `U`); `p` holds the row transpositions and `q` the column transpositions, as
/// the compact sequences `Perm2` / `Perm2` — the permutations of the rows / columns of the
/// matrix, where upstream's `PermutationSequence<DimMinimum<R, C>>` holds the same `min(R, C)`
/// transpositions (a step that swaps nothing records the identity, as upstream's `append` of
/// `(i, i)`). Built by `FullPivLu2Trait::new` or `Matrix2FullPivLuTrait::full_piv_lu`.
/// Upstream: `nalgebra::linalg::FullPivLU`.
#[derive(Copy, Drop, Serde, Debug)]
pub struct FullPivLu2<T> {
    /// `L` (strict lower triangle) and `U` (upper triangle) packed in one matrix.
    pub lu: Matrix2<T>,
    /// The row transpositions (`P`).
    pub p: Perm2,
    /// The column transpositions (`Q`).
    pub q: Perm2,
}

/// Methods of `FullPivLu2<T>` for any `Real` scalar.
#[generate_trait]
pub impl FullPivLu2Impl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of FullPivLu2Trait<T> {
    /// The LU factorisation of `matrix` with full pivoting, fully unrolled. Upstream:
    /// `matrix.full_piv_lu()` / `FullPivLU::new(matrix)`.
    ///
    /// Always succeeds, like upstream. At step `k` the pivot is the FIRST entry of largest `|a_ij|`
    /// of the trailing block in column-major order (upstream's `icamax_full`: strict `>`, so ties
    /// go to the lowest column, then the lowest row); its column is swapped with column `k` and its
    /// row with row `k` (whole rows and columns: upstream's `swap_columns` + `gauss_step_swap`).
    /// A trailing block that is exactly zero ends the elimination (upstream's `break`): nothing is
    /// swapped nor recorded from there on. The multipliers `l_ik = a_ik / a_kk` are correctly
    /// rounded quotients by one prepared divisor (upstream multiplies by a rounded `1 / a_kk`, as
    /// in `gauss_step`), and every update is ONE `Real::mul_add` (one floor per entry per step).
    /// Panics on overflow of an update.
    fn new(matrix: Matrix2<T>) -> FullPivLu2<T> {
        revoke_ap_tracking();
        let mut a00 = matrix.m11;
        let mut a10 = matrix.m21;
        let mut a01 = matrix.m12;
        let mut a11 = matrix.m22;
        // step 1: the first largest |a_ij| of rows 1..2, columns 1..2 (column-major scan)
        let mut piv = R::abs(a00);
        let mut rp0 = 1_u8;
        let mut cp0 = 1_u8;
        let x = R::abs(a10);
        if x > piv {
            piv = x;
            rp0 = 2;
            cp0 = 1;
        }
        let x = R::abs(a01);
        if x > piv {
            piv = x;
            rp0 = 1;
            cp0 = 2;
        }
        let x = R::abs(a11);
        if x > piv {
            piv = x;
            rp0 = 2;
            cp0 = 2;
        }
        if piv != R::zero() {
            if cp0 == 2 {
                let t = a00;
                a00 = a01;
                a01 = t;
                let t = a10;
                a10 = a11;
                a11 = t;
            }
            if rp0 == 2 {
                let t = a00;
                a00 = a10;
                a10 = t;
                let t = a01;
                a01 = a11;
                a11 = t;
            }
            let l1 = R::div(a10, a00);
            let nl = -l1;
            a11 = R::mul_add(nl, a01, a11);
            a10 = l1;
        }
        FullPivLu2 {
            lu: Matrix2 { m11: a00, m21: a10, m12: a01, m22: a11 },
            p: Perm2 { p1: rp0 },
            q: Perm2 { p1: cp0 },
        }
    }

    /// The packed factors as stored (strict lower triangle = `L`, upper triangle = `U`). Exact.
    /// Upstream: `FullPivLU::lu_internal` (`#[doc(hidden)]`).
    #[inline(always)]
    fn lu_internal(self: FullPivLu2<T>) -> Matrix2<T> {
        self.lu
    }

    /// The unit lower triangular factor `L` (2x2). Exact: moves. Upstream: `FullPivLU::l`.
    #[inline(always)]
    fn l(self: FullPivLu2<T>) -> Matrix2<T> {
        Matrix2 { m11: R::one(), m21: self.lu.m21, m12: R::zero(), m22: R::one() }
    }

    /// The upper triangular factor `U` (2x2). Exact: moves. Upstream: `FullPivLU::u`.
    #[inline(always)]
    fn u(self: FullPivLu2<T>) -> Matrix2<T> {
        Matrix2 { m11: self.lu.m11, m21: R::zero(), m12: self.lu.m12, m22: self.lu.m22 }
    }

    /// The row permutation `P`. Upstream: `FullPivLU::p`.
    #[inline(always)]
    fn p(self: FullPivLu2<T>) -> Perm2 {
        self.p
    }

    /// The column permutation `Q`. Upstream: `FullPivLU::q`.
    #[inline(always)]
    fn q(self: FullPivLu2<T>) -> Perm2 {
        self.q
    }

    /// `(P, L, U, Q)`: `(p(), l(), u(), q())`, exact. Upstream: `FullPivLU::unpack`.
    #[inline(always)]
    fn unpack(self: FullPivLu2<T>) -> (Perm2, Matrix2<T>, Matrix2<T>, Perm2) {
        (self.p, Self::l(self), Self::u(self), self.q)
    }

    /// Whether the factored matrix is invertible: the LAST pivot is exactly nonzero, like
    /// upstream's `FullPivLU::is_invertible` (full pivoting makes the pivots non-increasing in
    /// magnitude: an exactly zero trailing block leaves zeros from its first pivot to the last).
    #[inline(always)]
    fn is_invertible(self: FullPivLu2<T>) -> bool {
        self.lu.m22 != R::zero()
    }

    /// The determinant: `sign(P) sign(Q)` times the product of the 2 pivots, or exactly zero when
    /// the last pivot is (upstream's early return). The sign goes on the last pivot (an exact
    /// negation), then the chain is upstream's order — the last pivot times the others from the
    /// first — one floor per product (`Real` has no exact product of three scalars). Panics on
    /// overflow of a partial product. Upstream: `FullPivLU::determinant`.
    fn determinant(self: FullPivLu2<T>) -> T {
        if self.lu.m22 == R::zero() {
            return R::zero();
        }
        let mut neg = false;
        if self.p.p1 != 1 {
            neg = !neg;
        }
        if self.q.p1 != 1 {
            neg = !neg;
        }
        let d = if neg {
            -self.lu.m22
        } else {
            self.lu.m22
        };
        let d = d * self.lu.m11;
        d
    }

    /// Overwrites `b` (any shape with 2 rows: a vector or a matrix) with the solution `x` of
    /// `A x = b` and returns `true`, or returns `false` and leaves `b` unchanged when the matrix
    /// is not invertible (`is_invertible`; upstream may leave `b` overwritten). Upstream's steps
    /// on every column at once: `P b` (moves), `L y = P b` (unit diagonal: one floor per
    /// component), `U z = y` (one fused numerator and one correctly rounded division per
    /// component), `x = Qᵀ z` (moves). Panics on overflow. Upstream: `FullPivLU::solve_mut`.
    fn solve_mut<B, impl P: PermuteRows<Perm2, B>, impl K: SolveKernel<Matrix2<T>, B>, +Drop<B>>(
        self: FullPivLu2<T>, ref b: B,
    ) -> bool {
        if !Self::is_invertible(self) {
            return false;
        }
        P::permute_rows(self.p, ref b);
        b = K::upper(self.lu, K::lower_unit(self.lu, b));
        P::inv_permute_rows(self.q, ref b);
        true
    }

    /// The solution of `A x = b` for any `b` with 2 rows, or `None` when the matrix is not
    /// invertible: `solve_mut` on a copy. Upstream: `FullPivLU::solve`.
    fn solve<B, impl P: PermuteRows<Perm2, B>, impl K: SolveKernel<Matrix2<T>, B>, +Drop<B>>(
        self: FullPivLu2<T>, b: B,
    ) -> Option<B> {
        let mut x = b;
        if Self::solve_mut(self, ref x) {
            Some(x)
        } else {
            None
        }
    }

    /// The inverse, or `None` when the matrix is not invertible. Upstream solves against the
    /// identity (`FullPivLU::try_inverse`); here `(L U)⁻¹` is computed on the STATIC unit
    /// columns (their zeros vanish at generation time: bit-identical to the general solve, fewer
    /// products), one prepared divisor per row of the back substitution, then the columns are
    /// permuted by `P`
    /// and the rows by `Qᵀ` (moves). Two roundings per entry of the back substitution. Panics on
    /// overflow. Upstream: `FullPivLU::try_inverse`.
    fn try_inverse(self: FullPivLu2<T>) -> Option<Matrix2<T>> {
        revoke_ap_tracking();
        if !Self::is_invertible(self) {
            return None;
        }
        let y10 = -self.lu.m21;
        let (x10, x11) = (R::div(y10, self.lu.m22), R::div(R::one(), self.lu.m22));
        let (x00, x01) = (
            R::div(R::mul_add(-self.lu.m12, x10, R::one()), self.lu.m11),
            R::div((-self.lu.m12) * x11, self.lu.m11),
        );
        let mut x = Matrix2 { m11: x00, m21: x10, m12: x01, m22: x11 };
        PermuteColumns::inv_permute_columns(self.p, ref x);
        PermuteRows::inv_permute_rows(self.q, ref x);
        Some(x)
    }
}

/// `Matrix2` methods that go through the full-pivot LU factorisation. Import
/// `Matrix2FullPivLuTrait`.
#[generate_trait]
pub impl Matrix2FullPivLuImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix2FullPivLuTrait<T> {
    /// The LU factorisation with full pivoting. Upstream: `Matrix::full_piv_lu`.
    #[inline(always)]
    fn full_piv_lu(self: Matrix2<T>) -> FullPivLu2<T> {
        FullPivLu2Trait::new(self)
    }
}
