// Generated by crates/nalgebra/src/linalg/generate.py: do not edit by hand.
//! `ColPivQr5`: the QR factorisation with column pivoting of a `Matrix5` (upstream
//! `nalgebra::linalg::ColPivQR<T, U5, U5>`) by Householder reflections, fully unrolled
//! (WP 8.5-P15).

use core::internal::revoke_ap_tracking;
use simba::scalar::Real;
use crate::base::matrix5::Matrix5;
use crate::base::solve::SolveKernel;
use crate::base::vector5::Vector5;
use crate::linalg::lu::Perm5;
use crate::linalg::permutation_sequence::PermuteRows;

/// The QR factorisation with column pivoting of a `Matrix5<T>`: `A P = Q R` (`P` = `p`, applied to
/// the columns).
///
/// Upstream's storage: `col_piv_qr` holds the Householder axes on and below the diagonal (unit
/// vectors, one per column) and the strict upper triangle of `R` above it, `diag` the SIGNED
/// Householder norms (`r_ii = |diag_i|`), `p` the column transpositions as the compact `Perm5`
/// (upstream: a `PermutationSequence<DimMinimum<R, C>>` of the same 5 transpositions). Built by
/// `ColPivQr5Trait::new` or `Matrix5ColPivQrTrait::col_piv_qr`. Upstream:
/// `nalgebra::linalg::ColPivQR`.
#[derive(Copy, Drop, Serde, Debug)]
pub struct ColPivQr5<T> {
    /// Householder axes (lower part) and strict upper triangle of `R`, packed.
    pub col_piv_qr: Matrix5<T>,
    /// The column transpositions.
    pub p: Perm5,
    /// The signed Householder norms (`|diag_i|` is the diagonal of `R`).
    pub diag: Vector5<T>,
}

/// Methods of `ColPivQr5<T>` for any `Real` scalar.
#[generate_trait]
pub impl ColPivQr5Impl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of ColPivQr5Trait<T> {
    /// The QR factorisation with column pivoting of `matrix` by Householder reflections, fully
    /// unrolled. Upstream: `matrix.col_piv_qr()` / `ColPivQR::new(matrix)`.
    ///
    /// At step `k` the column holding the FIRST largest `|a_ij|` of the trailing block
    /// (column-major scan, upstream's `icamax_full`: ties to the lowest column) is swapped with
    /// column `k`; then upstream's `clear_column_unchecked`: the axis `u` of the reflection mapping
    /// the trailing part of column `k` onto `-sign(a_kk) |a| e_k` (`reflection_axis_mut`, zero
    /// column: no reflection and a zero norm), and the later columns become `s (a - 2 (u·a) u)`
    /// with `s = signum(diag_k)`.
    ///
    /// Rounding: `|a|` and the axis norm are floored square roots of exact sums of squares; the
    /// axis is normalised ONCE by one prepared divisor (upstream divides, then normalises again:
    /// the second pass only repeats the first, see `reflection_axis_mut`); `u·a` is one fused sum,
    /// doubled exactly, and each reflected entry one `Real::mul_add`. A one-component axis is
    /// `sign(a_kk)` exactly (no square root). Panics on overflow.
    fn new(matrix: Matrix5<T>) -> ColPivQr5<T> {
        revoke_ap_tracking();
        let mut a00 = matrix.m11;
        let mut a10 = matrix.m21;
        let mut a20 = matrix.m31;
        let mut a30 = matrix.m41;
        let mut a40 = matrix.m51;
        let mut a01 = matrix.m12;
        let mut a11 = matrix.m22;
        let mut a21 = matrix.m32;
        let mut a31 = matrix.m42;
        let mut a41 = matrix.m52;
        let mut a02 = matrix.m13;
        let mut a12 = matrix.m23;
        let mut a22 = matrix.m33;
        let mut a32 = matrix.m43;
        let mut a42 = matrix.m53;
        let mut a03 = matrix.m14;
        let mut a13 = matrix.m24;
        let mut a23 = matrix.m34;
        let mut a33 = matrix.m44;
        let mut a43 = matrix.m54;
        let mut a04 = matrix.m15;
        let mut a14 = matrix.m25;
        let mut a24 = matrix.m35;
        let mut a34 = matrix.m45;
        let mut a44 = matrix.m55;
        // step 1
        let mut piv = R::abs(a00);
        let mut cp0 = 1_u8;
        let x = R::abs(a10);
        if x > piv {
            piv = x;
        }
        let x = R::abs(a20);
        if x > piv {
            piv = x;
        }
        let x = R::abs(a30);
        if x > piv {
            piv = x;
        }
        let x = R::abs(a40);
        if x > piv {
            piv = x;
        }
        let x = R::abs(a01);
        if x > piv {
            piv = x;
            cp0 = 2;
        }
        let x = R::abs(a11);
        if x > piv {
            piv = x;
            cp0 = 2;
        }
        let x = R::abs(a21);
        if x > piv {
            piv = x;
            cp0 = 2;
        }
        let x = R::abs(a31);
        if x > piv {
            piv = x;
            cp0 = 2;
        }
        let x = R::abs(a41);
        if x > piv {
            piv = x;
            cp0 = 2;
        }
        let x = R::abs(a02);
        if x > piv {
            piv = x;
            cp0 = 3;
        }
        let x = R::abs(a12);
        if x > piv {
            piv = x;
            cp0 = 3;
        }
        let x = R::abs(a22);
        if x > piv {
            piv = x;
            cp0 = 3;
        }
        let x = R::abs(a32);
        if x > piv {
            piv = x;
            cp0 = 3;
        }
        let x = R::abs(a42);
        if x > piv {
            piv = x;
            cp0 = 3;
        }
        let x = R::abs(a03);
        if x > piv {
            piv = x;
            cp0 = 4;
        }
        let x = R::abs(a13);
        if x > piv {
            piv = x;
            cp0 = 4;
        }
        let x = R::abs(a23);
        if x > piv {
            piv = x;
            cp0 = 4;
        }
        let x = R::abs(a33);
        if x > piv {
            piv = x;
            cp0 = 4;
        }
        let x = R::abs(a43);
        if x > piv {
            piv = x;
            cp0 = 4;
        }
        let x = R::abs(a04);
        if x > piv {
            piv = x;
            cp0 = 5;
        }
        let x = R::abs(a14);
        if x > piv {
            piv = x;
            cp0 = 5;
        }
        let x = R::abs(a24);
        if x > piv {
            piv = x;
            cp0 = 5;
        }
        let x = R::abs(a34);
        if x > piv {
            piv = x;
            cp0 = 5;
        }
        let x = R::abs(a44);
        if x > piv {
            piv = x;
            cp0 = 5;
        }
        if cp0 == 2 {
            let t = a00;
            a00 = a01;
            a01 = t;
            let t = a10;
            a10 = a11;
            a11 = t;
            let t = a20;
            a20 = a21;
            a21 = t;
            let t = a30;
            a30 = a31;
            a31 = t;
            let t = a40;
            a40 = a41;
            a41 = t;
        } else if cp0 == 3 {
            let t = a00;
            a00 = a02;
            a02 = t;
            let t = a10;
            a10 = a12;
            a12 = t;
            let t = a20;
            a20 = a22;
            a22 = t;
            let t = a30;
            a30 = a32;
            a32 = t;
            let t = a40;
            a40 = a42;
            a42 = t;
        } else if cp0 == 4 {
            let t = a00;
            a00 = a03;
            a03 = t;
            let t = a10;
            a10 = a13;
            a13 = t;
            let t = a20;
            a20 = a23;
            a23 = t;
            let t = a30;
            a30 = a33;
            a33 = t;
            let t = a40;
            a40 = a43;
            a43 = t;
        } else if cp0 == 5 {
            let t = a00;
            a00 = a04;
            a04 = t;
            let t = a10;
            a10 = a14;
            a14 = t;
            let t = a20;
            a20 = a24;
            a24 = t;
            let t = a30;
            a30 = a34;
            a34 = t;
            let t = a40;
            a40 = a44;
            a44 = t;
        }
        let nrm = R::wide_sqrt(
            R::wide_add_prod(
                R::wide_add_prod(
                    R::wide_add_prod(
                        R::wide_add_prod(R::wide_add_prod(R::wide_zero(), a00, a00), a10, a10),
                        a20,
                        a20,
                    ),
                    a30,
                    a30,
                ),
                a40,
                a40,
            ),
        );
        let mut d0 = R::zero();
        if nrm != R::zero() {
            let neg = a00 < R::zero();
            let signed = if neg {
                -nrm
            } else {
                nrm
            };
            let y0 = a00 + signed;
            let dd = R::wide_sqrt(
                R::wide_add_prod(
                    R::wide_add_prod(
                        R::wide_add_prod(
                            R::wide_add_prod(R::wide_add_prod(R::wide_zero(), y0, y0), a10, a10),
                            a20,
                            a20,
                        ),
                        a30,
                        a30,
                    ),
                    a40,
                    a40,
                ),
            );
            let (u0, u1, u2, u3, u4) = R::div5(y0, a10, a20, a30, a40, dd);
            a00 = u0;
            a10 = u1;
            a20 = u2;
            a30 = u3;
            a40 = u4;
            d0 = -signed;
            let h = R::wide_rescale(
                R::wide_add_prod(
                    R::wide_add_prod(
                        R::wide_add_prod(
                            R::wide_add_prod(R::wide_add_prod(R::wide_zero(), a00, a01), a10, a11),
                            a20,
                            a21,
                        ),
                        a30,
                        a31,
                    ),
                    a40,
                    a41,
                ),
            );
            let w = h + h;
            let nw = -w;
            a01 = if neg {
                R::mul_add(nw, a00, a01)
            } else {
                R::mul_add(w, a00, -a01)
            };
            a11 = if neg {
                R::mul_add(nw, a10, a11)
            } else {
                R::mul_add(w, a10, -a11)
            };
            a21 = if neg {
                R::mul_add(nw, a20, a21)
            } else {
                R::mul_add(w, a20, -a21)
            };
            a31 = if neg {
                R::mul_add(nw, a30, a31)
            } else {
                R::mul_add(w, a30, -a31)
            };
            a41 = if neg {
                R::mul_add(nw, a40, a41)
            } else {
                R::mul_add(w, a40, -a41)
            };
            let h = R::wide_rescale(
                R::wide_add_prod(
                    R::wide_add_prod(
                        R::wide_add_prod(
                            R::wide_add_prod(R::wide_add_prod(R::wide_zero(), a00, a02), a10, a12),
                            a20,
                            a22,
                        ),
                        a30,
                        a32,
                    ),
                    a40,
                    a42,
                ),
            );
            let w = h + h;
            let nw = -w;
            a02 = if neg {
                R::mul_add(nw, a00, a02)
            } else {
                R::mul_add(w, a00, -a02)
            };
            a12 = if neg {
                R::mul_add(nw, a10, a12)
            } else {
                R::mul_add(w, a10, -a12)
            };
            a22 = if neg {
                R::mul_add(nw, a20, a22)
            } else {
                R::mul_add(w, a20, -a22)
            };
            a32 = if neg {
                R::mul_add(nw, a30, a32)
            } else {
                R::mul_add(w, a30, -a32)
            };
            a42 = if neg {
                R::mul_add(nw, a40, a42)
            } else {
                R::mul_add(w, a40, -a42)
            };
            let h = R::wide_rescale(
                R::wide_add_prod(
                    R::wide_add_prod(
                        R::wide_add_prod(
                            R::wide_add_prod(R::wide_add_prod(R::wide_zero(), a00, a03), a10, a13),
                            a20,
                            a23,
                        ),
                        a30,
                        a33,
                    ),
                    a40,
                    a43,
                ),
            );
            let w = h + h;
            let nw = -w;
            a03 = if neg {
                R::mul_add(nw, a00, a03)
            } else {
                R::mul_add(w, a00, -a03)
            };
            a13 = if neg {
                R::mul_add(nw, a10, a13)
            } else {
                R::mul_add(w, a10, -a13)
            };
            a23 = if neg {
                R::mul_add(nw, a20, a23)
            } else {
                R::mul_add(w, a20, -a23)
            };
            a33 = if neg {
                R::mul_add(nw, a30, a33)
            } else {
                R::mul_add(w, a30, -a33)
            };
            a43 = if neg {
                R::mul_add(nw, a40, a43)
            } else {
                R::mul_add(w, a40, -a43)
            };
            let h = R::wide_rescale(
                R::wide_add_prod(
                    R::wide_add_prod(
                        R::wide_add_prod(
                            R::wide_add_prod(R::wide_add_prod(R::wide_zero(), a00, a04), a10, a14),
                            a20,
                            a24,
                        ),
                        a30,
                        a34,
                    ),
                    a40,
                    a44,
                ),
            );
            let w = h + h;
            let nw = -w;
            a04 = if neg {
                R::mul_add(nw, a00, a04)
            } else {
                R::mul_add(w, a00, -a04)
            };
            a14 = if neg {
                R::mul_add(nw, a10, a14)
            } else {
                R::mul_add(w, a10, -a14)
            };
            a24 = if neg {
                R::mul_add(nw, a20, a24)
            } else {
                R::mul_add(w, a20, -a24)
            };
            a34 = if neg {
                R::mul_add(nw, a30, a34)
            } else {
                R::mul_add(w, a30, -a34)
            };
            a44 = if neg {
                R::mul_add(nw, a40, a44)
            } else {
                R::mul_add(w, a40, -a44)
            };
        }
        // step 2
        let mut piv = R::abs(a11);
        let mut cp1 = 2_u8;
        let x = R::abs(a21);
        if x > piv {
            piv = x;
        }
        let x = R::abs(a31);
        if x > piv {
            piv = x;
        }
        let x = R::abs(a41);
        if x > piv {
            piv = x;
        }
        let x = R::abs(a12);
        if x > piv {
            piv = x;
            cp1 = 3;
        }
        let x = R::abs(a22);
        if x > piv {
            piv = x;
            cp1 = 3;
        }
        let x = R::abs(a32);
        if x > piv {
            piv = x;
            cp1 = 3;
        }
        let x = R::abs(a42);
        if x > piv {
            piv = x;
            cp1 = 3;
        }
        let x = R::abs(a13);
        if x > piv {
            piv = x;
            cp1 = 4;
        }
        let x = R::abs(a23);
        if x > piv {
            piv = x;
            cp1 = 4;
        }
        let x = R::abs(a33);
        if x > piv {
            piv = x;
            cp1 = 4;
        }
        let x = R::abs(a43);
        if x > piv {
            piv = x;
            cp1 = 4;
        }
        let x = R::abs(a14);
        if x > piv {
            piv = x;
            cp1 = 5;
        }
        let x = R::abs(a24);
        if x > piv {
            piv = x;
            cp1 = 5;
        }
        let x = R::abs(a34);
        if x > piv {
            piv = x;
            cp1 = 5;
        }
        let x = R::abs(a44);
        if x > piv {
            piv = x;
            cp1 = 5;
        }
        if cp1 == 3 {
            let t = a01;
            a01 = a02;
            a02 = t;
            let t = a11;
            a11 = a12;
            a12 = t;
            let t = a21;
            a21 = a22;
            a22 = t;
            let t = a31;
            a31 = a32;
            a32 = t;
            let t = a41;
            a41 = a42;
            a42 = t;
        } else if cp1 == 4 {
            let t = a01;
            a01 = a03;
            a03 = t;
            let t = a11;
            a11 = a13;
            a13 = t;
            let t = a21;
            a21 = a23;
            a23 = t;
            let t = a31;
            a31 = a33;
            a33 = t;
            let t = a41;
            a41 = a43;
            a43 = t;
        } else if cp1 == 5 {
            let t = a01;
            a01 = a04;
            a04 = t;
            let t = a11;
            a11 = a14;
            a14 = t;
            let t = a21;
            a21 = a24;
            a24 = t;
            let t = a31;
            a31 = a34;
            a34 = t;
            let t = a41;
            a41 = a44;
            a44 = t;
        }
        let nrm = R::norm4(a11, a21, a31, a41);
        let mut d1 = R::zero();
        if nrm != R::zero() {
            let neg = a11 < R::zero();
            let signed = if neg {
                -nrm
            } else {
                nrm
            };
            let y0 = a11 + signed;
            let dd = R::norm4(y0, a21, a31, a41);
            let (u1, u2, u3, u4) = R::div4(y0, a21, a31, a41, dd);
            a11 = u1;
            a21 = u2;
            a31 = u3;
            a41 = u4;
            d1 = -signed;
            let h = R::sum_prod4(a11, a12, a21, a22, a31, a32, a41, a42);
            let w = h + h;
            let nw = -w;
            a12 = if neg {
                R::mul_add(nw, a11, a12)
            } else {
                R::mul_add(w, a11, -a12)
            };
            a22 = if neg {
                R::mul_add(nw, a21, a22)
            } else {
                R::mul_add(w, a21, -a22)
            };
            a32 = if neg {
                R::mul_add(nw, a31, a32)
            } else {
                R::mul_add(w, a31, -a32)
            };
            a42 = if neg {
                R::mul_add(nw, a41, a42)
            } else {
                R::mul_add(w, a41, -a42)
            };
            let h = R::sum_prod4(a11, a13, a21, a23, a31, a33, a41, a43);
            let w = h + h;
            let nw = -w;
            a13 = if neg {
                R::mul_add(nw, a11, a13)
            } else {
                R::mul_add(w, a11, -a13)
            };
            a23 = if neg {
                R::mul_add(nw, a21, a23)
            } else {
                R::mul_add(w, a21, -a23)
            };
            a33 = if neg {
                R::mul_add(nw, a31, a33)
            } else {
                R::mul_add(w, a31, -a33)
            };
            a43 = if neg {
                R::mul_add(nw, a41, a43)
            } else {
                R::mul_add(w, a41, -a43)
            };
            let h = R::sum_prod4(a11, a14, a21, a24, a31, a34, a41, a44);
            let w = h + h;
            let nw = -w;
            a14 = if neg {
                R::mul_add(nw, a11, a14)
            } else {
                R::mul_add(w, a11, -a14)
            };
            a24 = if neg {
                R::mul_add(nw, a21, a24)
            } else {
                R::mul_add(w, a21, -a24)
            };
            a34 = if neg {
                R::mul_add(nw, a31, a34)
            } else {
                R::mul_add(w, a31, -a34)
            };
            a44 = if neg {
                R::mul_add(nw, a41, a44)
            } else {
                R::mul_add(w, a41, -a44)
            };
        }
        // step 3
        let mut piv = R::abs(a22);
        let mut cp2 = 3_u8;
        let x = R::abs(a32);
        if x > piv {
            piv = x;
        }
        let x = R::abs(a42);
        if x > piv {
            piv = x;
        }
        let x = R::abs(a23);
        if x > piv {
            piv = x;
            cp2 = 4;
        }
        let x = R::abs(a33);
        if x > piv {
            piv = x;
            cp2 = 4;
        }
        let x = R::abs(a43);
        if x > piv {
            piv = x;
            cp2 = 4;
        }
        let x = R::abs(a24);
        if x > piv {
            piv = x;
            cp2 = 5;
        }
        let x = R::abs(a34);
        if x > piv {
            piv = x;
            cp2 = 5;
        }
        let x = R::abs(a44);
        if x > piv {
            piv = x;
            cp2 = 5;
        }
        if cp2 == 4 {
            let t = a02;
            a02 = a03;
            a03 = t;
            let t = a12;
            a12 = a13;
            a13 = t;
            let t = a22;
            a22 = a23;
            a23 = t;
            let t = a32;
            a32 = a33;
            a33 = t;
            let t = a42;
            a42 = a43;
            a43 = t;
        } else if cp2 == 5 {
            let t = a02;
            a02 = a04;
            a04 = t;
            let t = a12;
            a12 = a14;
            a14 = t;
            let t = a22;
            a22 = a24;
            a24 = t;
            let t = a32;
            a32 = a34;
            a34 = t;
            let t = a42;
            a42 = a44;
            a44 = t;
        }
        let nrm = R::norm3(a22, a32, a42);
        let mut d2 = R::zero();
        if nrm != R::zero() {
            let neg = a22 < R::zero();
            let signed = if neg {
                -nrm
            } else {
                nrm
            };
            let y0 = a22 + signed;
            let dd = R::norm3(y0, a32, a42);
            let (u2, u3, u4) = R::div3(y0, a32, a42, dd);
            a22 = u2;
            a32 = u3;
            a42 = u4;
            d2 = -signed;
            let h = R::sum_prod3(a22, a23, a32, a33, a42, a43);
            let w = h + h;
            let nw = -w;
            a23 = if neg {
                R::mul_add(nw, a22, a23)
            } else {
                R::mul_add(w, a22, -a23)
            };
            a33 = if neg {
                R::mul_add(nw, a32, a33)
            } else {
                R::mul_add(w, a32, -a33)
            };
            a43 = if neg {
                R::mul_add(nw, a42, a43)
            } else {
                R::mul_add(w, a42, -a43)
            };
            let h = R::sum_prod3(a22, a24, a32, a34, a42, a44);
            let w = h + h;
            let nw = -w;
            a24 = if neg {
                R::mul_add(nw, a22, a24)
            } else {
                R::mul_add(w, a22, -a24)
            };
            a34 = if neg {
                R::mul_add(nw, a32, a34)
            } else {
                R::mul_add(w, a32, -a34)
            };
            a44 = if neg {
                R::mul_add(nw, a42, a44)
            } else {
                R::mul_add(w, a42, -a44)
            };
        }
        // step 4
        let mut piv = R::abs(a33);
        let mut cp3 = 4_u8;
        let x = R::abs(a43);
        if x > piv {
            piv = x;
        }
        let x = R::abs(a34);
        if x > piv {
            piv = x;
            cp3 = 5;
        }
        let x = R::abs(a44);
        if x > piv {
            piv = x;
            cp3 = 5;
        }
        if cp3 == 5 {
            let t = a03;
            a03 = a04;
            a04 = t;
            let t = a13;
            a13 = a14;
            a14 = t;
            let t = a23;
            a23 = a24;
            a24 = t;
            let t = a33;
            a33 = a34;
            a34 = t;
            let t = a43;
            a43 = a44;
            a44 = t;
        }
        let nrm = R::norm2(a33, a43);
        let mut d3 = R::zero();
        if nrm != R::zero() {
            let neg = a33 < R::zero();
            let signed = if neg {
                -nrm
            } else {
                nrm
            };
            let y0 = a33 + signed;
            let dd = R::norm2(y0, a43);
            let (u3, u4) = (R::div(y0, dd), R::div(a43, dd));
            a33 = u3;
            a43 = u4;
            d3 = -signed;
            let h = R::sum_prod2(a33, a34, a43, a44);
            let w = h + h;
            let nw = -w;
            a34 = if neg {
                R::mul_add(nw, a33, a34)
            } else {
                R::mul_add(w, a33, -a34)
            };
            a44 = if neg {
                R::mul_add(nw, a43, a44)
            } else {
                R::mul_add(w, a43, -a44)
            };
        }
        // step 5
        let d4 = -a44;
        if a44 < R::zero() {
            a44 = -R::one();
        } else if a44 > R::zero() {
            a44 = R::one();
        }
        ColPivQr5 {
            col_piv_qr: Matrix5 {
                m11: a00,
                m21: a10,
                m31: a20,
                m41: a30,
                m51: a40,
                m12: a01,
                m22: a11,
                m32: a21,
                m42: a31,
                m52: a41,
                m13: a02,
                m23: a12,
                m33: a22,
                m43: a32,
                m53: a42,
                m14: a03,
                m24: a13,
                m34: a23,
                m44: a33,
                m54: a43,
                m15: a04,
                m25: a14,
                m35: a24,
                m45: a34,
                m55: a44,
            },
            p: Perm5 { p1: cp0, p2: cp1, p3: cp2, p4: cp3 },
            diag: Vector5 { x: d0, y: d1, z: d2, w: d3, a: d4 },
        }
    }

    /// The upper trapezoidal factor `R` (5x5): the strict upper triangle as stored and
    /// `|diag|` on the diagonal. Exact: moves and absolute values. Upstream: `ColPivQR::r`.
    #[inline(always)]
    fn r(self: ColPivQr5<T>) -> Matrix5<T> {
        Matrix5 {
            m11: R::abs(self.diag.x),
            m21: R::zero(),
            m31: R::zero(),
            m41: R::zero(),
            m51: R::zero(),
            m12: self.col_piv_qr.m12,
            m22: R::abs(self.diag.y),
            m32: R::zero(),
            m42: R::zero(),
            m52: R::zero(),
            m13: self.col_piv_qr.m13,
            m23: self.col_piv_qr.m23,
            m33: R::abs(self.diag.z),
            m43: R::zero(),
            m53: R::zero(),
            m14: self.col_piv_qr.m14,
            m24: self.col_piv_qr.m24,
            m34: self.col_piv_qr.m34,
            m44: R::abs(self.diag.w),
            m54: R::zero(),
            m15: self.col_piv_qr.m15,
            m25: self.col_piv_qr.m25,
            m35: self.col_piv_qr.m35,
            m45: self.col_piv_qr.m45,
            m55: R::abs(self.diag.a),
        }
    }

    /// `R`, consuming the factorisation: `r()`. Upstream: `ColPivQR::unpack_r`.
    #[inline(always)]
    fn unpack_r(self: ColPivQr5<T>) -> Matrix5<T> {
        Self::r(self)
    }

    /// The orthonormal factor `Q` (5x5): upstream's loop, the 5 signed reflections applied in
    /// reverse order to the identity, on symbolic entries (the static zeros and ones of the
    /// identity cost nothing): one fused dot product (doubled exactly) per column and reflection,
    /// one `Real::mul_add` per entry. Upstream: `ColPivQR::q`.
    fn q(self: ColPivQr5<T>) -> Matrix5<T> {
        revoke_ap_tracking();
        let s4 = self.diag.a < R::zero();
        let h = self.col_piv_qr.m55;
        let w = h + h;
        let nw = -w;
        let q44_4 = if s4 {
            R::mul_add(w, self.col_piv_qr.m55, -R::one())
        } else {
            R::mul_add(nw, self.col_piv_qr.m55, R::one())
        };
        let s3 = self.diag.w < R::zero();
        let h = self.col_piv_qr.m44;
        let w = h + h;
        let nw = -w;
        let q33_3 = if s3 {
            R::mul_add(w, self.col_piv_qr.m44, -R::one())
        } else {
            R::mul_add(nw, self.col_piv_qr.m44, R::one())
        };
        let q43_3 = if s3 {
            w * self.col_piv_qr.m54
        } else {
            nw * self.col_piv_qr.m54
        };
        let h = self.col_piv_qr.m54 * q44_4;
        let w = h + h;
        let nw = -w;
        let q34_3 = if s3 {
            w * self.col_piv_qr.m44
        } else {
            nw * self.col_piv_qr.m44
        };
        let q44_3 = if s3 {
            R::mul_add(w, self.col_piv_qr.m54, -q44_4)
        } else {
            R::mul_add(nw, self.col_piv_qr.m54, q44_4)
        };
        let s2 = self.diag.z < R::zero();
        let h = self.col_piv_qr.m33;
        let w = h + h;
        let nw = -w;
        let q22_2 = if s2 {
            R::mul_add(w, self.col_piv_qr.m33, -R::one())
        } else {
            R::mul_add(nw, self.col_piv_qr.m33, R::one())
        };
        let q32_2 = if s2 {
            w * self.col_piv_qr.m43
        } else {
            nw * self.col_piv_qr.m43
        };
        let q42_2 = if s2 {
            w * self.col_piv_qr.m53
        } else {
            nw * self.col_piv_qr.m53
        };
        let h = R::sum_prod2(self.col_piv_qr.m43, q33_3, self.col_piv_qr.m53, q43_3);
        let w = h + h;
        let nw = -w;
        let q23_2 = if s2 {
            w * self.col_piv_qr.m33
        } else {
            nw * self.col_piv_qr.m33
        };
        let q33_2 = if s2 {
            R::mul_add(w, self.col_piv_qr.m43, -q33_3)
        } else {
            R::mul_add(nw, self.col_piv_qr.m43, q33_3)
        };
        let q43_2 = if s2 {
            R::mul_add(w, self.col_piv_qr.m53, -q43_3)
        } else {
            R::mul_add(nw, self.col_piv_qr.m53, q43_3)
        };
        let h = R::sum_prod2(self.col_piv_qr.m43, q34_3, self.col_piv_qr.m53, q44_3);
        let w = h + h;
        let nw = -w;
        let q24_2 = if s2 {
            w * self.col_piv_qr.m33
        } else {
            nw * self.col_piv_qr.m33
        };
        let q34_2 = if s2 {
            R::mul_add(w, self.col_piv_qr.m43, -q34_3)
        } else {
            R::mul_add(nw, self.col_piv_qr.m43, q34_3)
        };
        let q44_2 = if s2 {
            R::mul_add(w, self.col_piv_qr.m53, -q44_3)
        } else {
            R::mul_add(nw, self.col_piv_qr.m53, q44_3)
        };
        let s1 = self.diag.y < R::zero();
        let h = self.col_piv_qr.m22;
        let w = h + h;
        let nw = -w;
        let q11_1 = if s1 {
            R::mul_add(w, self.col_piv_qr.m22, -R::one())
        } else {
            R::mul_add(nw, self.col_piv_qr.m22, R::one())
        };
        let q21_1 = if s1 {
            w * self.col_piv_qr.m32
        } else {
            nw * self.col_piv_qr.m32
        };
        let q31_1 = if s1 {
            w * self.col_piv_qr.m42
        } else {
            nw * self.col_piv_qr.m42
        };
        let q41_1 = if s1 {
            w * self.col_piv_qr.m52
        } else {
            nw * self.col_piv_qr.m52
        };
        let h = R::sum_prod3(
            self.col_piv_qr.m32, q22_2, self.col_piv_qr.m42, q32_2, self.col_piv_qr.m52, q42_2,
        );
        let w = h + h;
        let nw = -w;
        let q12_1 = if s1 {
            w * self.col_piv_qr.m22
        } else {
            nw * self.col_piv_qr.m22
        };
        let q22_1 = if s1 {
            R::mul_add(w, self.col_piv_qr.m32, -q22_2)
        } else {
            R::mul_add(nw, self.col_piv_qr.m32, q22_2)
        };
        let q32_1 = if s1 {
            R::mul_add(w, self.col_piv_qr.m42, -q32_2)
        } else {
            R::mul_add(nw, self.col_piv_qr.m42, q32_2)
        };
        let q42_1 = if s1 {
            R::mul_add(w, self.col_piv_qr.m52, -q42_2)
        } else {
            R::mul_add(nw, self.col_piv_qr.m52, q42_2)
        };
        let h = R::sum_prod3(
            self.col_piv_qr.m32, q23_2, self.col_piv_qr.m42, q33_2, self.col_piv_qr.m52, q43_2,
        );
        let w = h + h;
        let nw = -w;
        let q13_1 = if s1 {
            w * self.col_piv_qr.m22
        } else {
            nw * self.col_piv_qr.m22
        };
        let q23_1 = if s1 {
            R::mul_add(w, self.col_piv_qr.m32, -q23_2)
        } else {
            R::mul_add(nw, self.col_piv_qr.m32, q23_2)
        };
        let q33_1 = if s1 {
            R::mul_add(w, self.col_piv_qr.m42, -q33_2)
        } else {
            R::mul_add(nw, self.col_piv_qr.m42, q33_2)
        };
        let q43_1 = if s1 {
            R::mul_add(w, self.col_piv_qr.m52, -q43_2)
        } else {
            R::mul_add(nw, self.col_piv_qr.m52, q43_2)
        };
        let h = R::sum_prod3(
            self.col_piv_qr.m32, q24_2, self.col_piv_qr.m42, q34_2, self.col_piv_qr.m52, q44_2,
        );
        let w = h + h;
        let nw = -w;
        let q14_1 = if s1 {
            w * self.col_piv_qr.m22
        } else {
            nw * self.col_piv_qr.m22
        };
        let q24_1 = if s1 {
            R::mul_add(w, self.col_piv_qr.m32, -q24_2)
        } else {
            R::mul_add(nw, self.col_piv_qr.m32, q24_2)
        };
        let q34_1 = if s1 {
            R::mul_add(w, self.col_piv_qr.m42, -q34_2)
        } else {
            R::mul_add(nw, self.col_piv_qr.m42, q34_2)
        };
        let q44_1 = if s1 {
            R::mul_add(w, self.col_piv_qr.m52, -q44_2)
        } else {
            R::mul_add(nw, self.col_piv_qr.m52, q44_2)
        };
        let s0 = self.diag.x < R::zero();
        let h = self.col_piv_qr.m11;
        let w = h + h;
        let nw = -w;
        let q00_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m11, -R::one())
        } else {
            R::mul_add(nw, self.col_piv_qr.m11, R::one())
        };
        let q10_0 = if s0 {
            w * self.col_piv_qr.m21
        } else {
            nw * self.col_piv_qr.m21
        };
        let q20_0 = if s0 {
            w * self.col_piv_qr.m31
        } else {
            nw * self.col_piv_qr.m31
        };
        let q30_0 = if s0 {
            w * self.col_piv_qr.m41
        } else {
            nw * self.col_piv_qr.m41
        };
        let q40_0 = if s0 {
            w * self.col_piv_qr.m51
        } else {
            nw * self.col_piv_qr.m51
        };
        let h = R::sum_prod4(
            self.col_piv_qr.m21,
            q11_1,
            self.col_piv_qr.m31,
            q21_1,
            self.col_piv_qr.m41,
            q31_1,
            self.col_piv_qr.m51,
            q41_1,
        );
        let w = h + h;
        let nw = -w;
        let q01_0 = if s0 {
            w * self.col_piv_qr.m11
        } else {
            nw * self.col_piv_qr.m11
        };
        let q11_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m21, -q11_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m21, q11_1)
        };
        let q21_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m31, -q21_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m31, q21_1)
        };
        let q31_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m41, -q31_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m41, q31_1)
        };
        let q41_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m51, -q41_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m51, q41_1)
        };
        let h = R::sum_prod4(
            self.col_piv_qr.m21,
            q12_1,
            self.col_piv_qr.m31,
            q22_1,
            self.col_piv_qr.m41,
            q32_1,
            self.col_piv_qr.m51,
            q42_1,
        );
        let w = h + h;
        let nw = -w;
        let q02_0 = if s0 {
            w * self.col_piv_qr.m11
        } else {
            nw * self.col_piv_qr.m11
        };
        let q12_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m21, -q12_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m21, q12_1)
        };
        let q22_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m31, -q22_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m31, q22_1)
        };
        let q32_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m41, -q32_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m41, q32_1)
        };
        let q42_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m51, -q42_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m51, q42_1)
        };
        let h = R::sum_prod4(
            self.col_piv_qr.m21,
            q13_1,
            self.col_piv_qr.m31,
            q23_1,
            self.col_piv_qr.m41,
            q33_1,
            self.col_piv_qr.m51,
            q43_1,
        );
        let w = h + h;
        let nw = -w;
        let q03_0 = if s0 {
            w * self.col_piv_qr.m11
        } else {
            nw * self.col_piv_qr.m11
        };
        let q13_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m21, -q13_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m21, q13_1)
        };
        let q23_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m31, -q23_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m31, q23_1)
        };
        let q33_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m41, -q33_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m41, q33_1)
        };
        let q43_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m51, -q43_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m51, q43_1)
        };
        let h = R::sum_prod4(
            self.col_piv_qr.m21,
            q14_1,
            self.col_piv_qr.m31,
            q24_1,
            self.col_piv_qr.m41,
            q34_1,
            self.col_piv_qr.m51,
            q44_1,
        );
        let w = h + h;
        let nw = -w;
        let q04_0 = if s0 {
            w * self.col_piv_qr.m11
        } else {
            nw * self.col_piv_qr.m11
        };
        let q14_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m21, -q14_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m21, q14_1)
        };
        let q24_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m31, -q24_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m31, q24_1)
        };
        let q34_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m41, -q34_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m41, q34_1)
        };
        let q44_0 = if s0 {
            R::mul_add(w, self.col_piv_qr.m51, -q44_1)
        } else {
            R::mul_add(nw, self.col_piv_qr.m51, q44_1)
        };
        Matrix5 {
            m11: q00_0,
            m21: q10_0,
            m31: q20_0,
            m41: q30_0,
            m51: q40_0,
            m12: q01_0,
            m22: q11_0,
            m32: q21_0,
            m42: q31_0,
            m52: q41_0,
            m13: q02_0,
            m23: q12_0,
            m33: q22_0,
            m43: q32_0,
            m53: q42_0,
            m14: q03_0,
            m24: q13_0,
            m34: q23_0,
            m44: q33_0,
            m54: q43_0,
            m15: q04_0,
            m25: q14_0,
            m35: q24_0,
            m45: q34_0,
            m55: q44_0,
        }
    }

    /// The column permutation. Upstream: `ColPivQR::p`.
    #[inline(always)]
    fn p(self: ColPivQr5<T>) -> Perm5 {
        self.p
    }

    /// `(Q, R, P)`: `(q(), r(), p())`. Upstream: `ColPivQR::unpack`.
    #[inline(always)]
    fn unpack(self: ColPivQr5<T>) -> (Matrix5<T>, Matrix5<T>, Perm5) {
        (Self::q(self), Self::r(self), self.p)
    }

    /// The packed storage (axes and strict upper triangle of `R`). Exact. Upstream:
    /// `ColPivQR::col_piv_qr_internal` (`#[doc(hidden)]`).
    #[inline(always)]
    fn col_piv_qr_internal(self: ColPivQr5<T>) -> Matrix5<T> {
        self.col_piv_qr
    }

    /// `rhs = Qᵀ rhs` in place, `Q` the FULL 5x5 product of the reflections (upstream applies
    /// them one after the other to `rhs`), for any `rhs` with 5 rows: the product is formed
    /// once, then ONE fused sum per entry. Upstream: `ColPivQR::q_tr_mul`.
    fn q_tr_mul<B, impl K: SolveKernel<Matrix5<T>, B>, +Drop<B>>(self: ColPivQr5<T>, ref rhs: B) {
        rhs = K::tr_mul_rhs(Self::q(self), rhs);
    }

    /// Whether every Householder norm (`diag`, the signed diagonal of `R`) is EXACTLY nonzero,
    /// like upstream's `ColPivQR::is_invertible`.
    #[inline(always)]
    fn is_invertible(self: ColPivQr5<T>) -> bool {
        self.diag.x != R::zero()
            && self.diag.y != R::zero()
            && self.diag.z != R::zero()
            && self.diag.w != R::zero()
            && self.diag.a != R::zero()
    }

    /// The determinant: `sign(P)` times the product of the SIGNED Householder norms (upstream's
    /// `diag`, not `|r_ii|`), the sign on the first factor (exact), then one floor per product.
    /// Panics on overflow of a partial product. Upstream: `ColPivQR::determinant`.
    fn determinant(self: ColPivQr5<T>) -> T {
        let mut neg = false;
        if self.p.p1 != 1 {
            neg = !neg;
        }
        if self.p.p2 != 2 {
            neg = !neg;
        }
        if self.p.p3 != 3 {
            neg = !neg;
        }
        if self.p.p4 != 4 {
            neg = !neg;
        }
        let d = if neg {
            -self.diag.x
        } else {
            self.diag.x
        };
        let d = d * self.diag.y;
        let d = d * self.diag.z;
        let d = d * self.diag.w;
        let d = d * self.diag.a;
        d
    }

    /// Overwrites `b` (any shape with 5 rows) with the solution of `A x = b` and returns
    /// `true`, or returns `false` and leaves `b` unchanged when `R` has an exactly zero diagonal
    /// entry (upstream leaves `Qᵀ b` behind). `x = P (R⁻¹ (Qᵀ b))`: `Qᵀ b` as one fused
    /// sum per entry (upstream: the reflections one after the other), back substitution on `R`
    /// (upstream's `|diag|` on the diagonal: one fused numerator and one correctly rounded division
    /// per component), then the inverse column permutation (moves). Panics on overflow. Upstream:
    /// `ColPivQR::solve_mut`.
    fn solve_mut<B, impl P: PermuteRows<Perm5, B>, impl K: SolveKernel<Matrix5<T>, B>, +Drop<B>>(
        self: ColPivQr5<T>, ref b: B,
    ) -> bool {
        if !Self::is_invertible(self) {
            return false;
        }
        b = K::upper(Self::r(self), K::tr_mul_rhs(Self::q(self), b));
        P::inv_permute_rows(self.p, ref b);
        true
    }

    /// The solution of `A x = b` for any `b` with 5 rows, or `None` when `R` has an exactly
    /// zero diagonal entry: `solve_mut` on a copy. Upstream: `ColPivQR::solve`.
    fn solve<B, impl P: PermuteRows<Perm5, B>, impl K: SolveKernel<Matrix5<T>, B>, +Drop<B>>(
        self: ColPivQr5<T>, b: B,
    ) -> Option<B> {
        let mut x = b;
        if Self::solve_mut(self, ref x) {
            Some(x)
        } else {
            None
        }
    }

    /// The inverse `P R⁻¹ Qᵀ`, or `None` when `R` has an exactly zero diagonal entry: the back
    /// substitution of `Qᵀ` (moves: upstream multiplies the identity by `Qᵀ`), then the inverse
    /// row permutation. Panics on overflow. Upstream: `ColPivQR::try_inverse`.
    fn try_inverse(self: ColPivQr5<T>) -> Option<Matrix5<T>> {
        if !Self::is_invertible(self) {
            return None;
        }
        let q = Self::q(self);
        let mut x = SolveKernel::<
            Matrix5<T>, Matrix5<T>,
        >::upper(
            Self::r(self),
            Matrix5 {
                m11: q.m11,
                m21: q.m12,
                m31: q.m13,
                m41: q.m14,
                m51: q.m15,
                m12: q.m21,
                m22: q.m22,
                m32: q.m23,
                m42: q.m24,
                m52: q.m25,
                m13: q.m31,
                m23: q.m32,
                m33: q.m33,
                m43: q.m34,
                m53: q.m35,
                m14: q.m41,
                m24: q.m42,
                m34: q.m43,
                m44: q.m44,
                m54: q.m45,
                m15: q.m51,
                m25: q.m52,
                m35: q.m53,
                m45: q.m54,
                m55: q.m55,
            },
        );
        PermuteRows::inv_permute_rows(self.p, ref x);
        Some(x)
    }
}

/// `Matrix5` methods that go through the column-pivot QR factorisation. Import
/// `Matrix5ColPivQrTrait`.
#[generate_trait]
pub impl Matrix5ColPivQrImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix5ColPivQrTrait<T> {
    /// The QR factorisation with column pivoting. Upstream: `Matrix::col_piv_qr`.
    #[inline(always)]
    fn col_piv_qr(self: Matrix5<T>) -> ColPivQr5<T> {
        ColPivQr5Trait::new(self)
    }
}
