[package]
name = "pf"
version.workspace = true
edition.workspace = true
experimental-features = ["user_defined_inline_macros", "associated_item_constraints"]
[dependencies]
pa = { path = "../pa", default-features = false }
pb = { path = "../pb" }
pc = { path = "../pc" }
[dev-dependencies]
assert_macros.workspace = true
[features]
default = ["extra"]
extra = ["pa/extra"]
