// Generated by tools/shapegen/shapegen.py: do not edit by hand. Template:
// tools/shapegen/shapes.py.
//! `Matrix2x6`: a statically sized 2x6 matrix (upstream `nalgebra::Matrix2x6`).
//!
//! Every sum of products goes through a fused `Real` kernel: one rounding (floor) and one overflow
//! check per output scalar. Operators (`+`, `-`, unary `-` and their assigning forms) are
//! implemented in this module, so they need no import; the other operations are methods of
//! `Matrix2x6Trait`, the products with every conformable shape `MatrixMul::mul_mat` (`self * rhs`)
//! and `MatrixTrMul::tr_mul` (`selfᵀ * rhs`).

use nalgebra_core::base::errors;
use nalgebra_core::base::matrix_index::MatrixIndex;
use nalgebra_core::base::matrix_tr_mul::MatrixTrMul;
use nalgebra_core::base::norm::Norm;
use nalgebra_core::base::vector2::Vector2;
use nalgebra_core::internal::base::kernels::Powi;
use nalgebra_core::internal::geometry::quaternion::ApproxEqTrait;
use nalgebra_shapes5::base::matrix2x5::Matrix2x5;
use nalgebra_shapes6::base::matrix2x6::Matrix2x6;
use nalgebra_shapes6::base::matrix3x6::Matrix3x6;
use nalgebra_shapes6::base::matrix6x2::Matrix6x2;
use nalgebra_shapes6::base::row_vector6::RowVector6;
use nalgebra_shapes6::base::vector6::Vector6;
use nalgebra_static6_tall::internal::base::matrix2x6::Matrix2x6EditTrait;
use simba::scalar::{Real, Transcendental};
use crate::base::matrix6::Matrix6Trait;

/// Methods of `Matrix2x6<T>` for any `Real` scalar.
#[generate_trait]
pub impl Matrix2x6Impl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix2x6Trait<T> {
    /// The 2x6 matrix with the given components, in ROW-major order. Upstream: `Matrix2x6::new`.
    #[inline(always)]
    fn new(
        m11: T,
        m12: T,
        m13: T,
        m14: T,
        m15: T,
        m16: T,
        m21: T,
        m22: T,
        m23: T,
        m24: T,
        m25: T,
        m26: T,
    ) -> Matrix2x6<T> {
        Matrix2x6 { m11, m21, m12, m22, m13, m23, m14, m24, m15, m25, m16, m26 }
    }

    /// The zero 2x6 matrix. Upstream: `Matrix2x6::zeros`.
    #[inline(always)]
    fn zeros() -> Matrix2x6<T> {
        Matrix2x6 {
            m11: R::zero(),
            m21: R::zero(),
            m12: R::zero(),
            m22: R::zero(),
            m13: R::zero(),
            m23: R::zero(),
            m14: R::zero(),
            m24: R::zero(),
            m15: R::zero(),
            m25: R::zero(),
            m16: R::zero(),
            m26: R::zero(),
        }
    }

    /// The transpose, a `Matrix6x2`. Exact. Upstream: `transpose`.
    #[inline(always)]
    fn transpose(self: Matrix2x6<T>) -> Matrix6x2<T> {
        Matrix6x2 {
            m11: self.m11,
            m21: self.m12,
            m31: self.m13,
            m41: self.m14,
            m51: self.m15,
            m61: self.m16,
            m12: self.m21,
            m22: self.m22,
            m32: self.m23,
            m42: self.m24,
            m52: self.m25,
            m62: self.m26,
        }
    }

    /// Component-wise absolute value. Exact; panics on overflow (`|MIN|`). Upstream: `abs`.
    #[inline(always)]
    fn abs(self: Matrix2x6<T>) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: R::abs(self.m11),
            m21: R::abs(self.m21),
            m12: R::abs(self.m12),
            m22: R::abs(self.m22),
            m13: R::abs(self.m13),
            m23: R::abs(self.m23),
            m14: R::abs(self.m14),
            m24: R::abs(self.m24),
            m15: R::abs(self.m15),
            m25: R::abs(self.m25),
            m16: R::abs(self.m16),
            m26: R::abs(self.m26),
        }
    }

    /// `self * k`, each component floored once. Panics on overflow. Upstream: `scale` (`self * k`).
    #[inline(always)]
    fn scale(self: Matrix2x6<T>, k: T) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: self.m11 * k,
            m21: self.m21 * k,
            m12: self.m12 * k,
            m22: self.m22 * k,
            m13: self.m13 * k,
            m23: self.m23 * k,
            m14: self.m14 * k,
            m24: self.m24 * k,
            m15: self.m15 * k,
            m25: self.m25 * k,
            m16: self.m16 * k,
            m26: self.m26 * k,
        }
    }

    /// Whether every component of `self` is within `ulps` smallest units (raw units for fixed
    /// point) of `other`'s; cannot overflow. Upstream: `approx::AbsDiffEq::abs_diff_eq`, the
    /// tolerance being counted in ulp instead of a float epsilon (DESIGN D3).
    #[inline(always)]
    fn abs_diff_eq(self: Matrix2x6<T>, other: Matrix2x6<T>, ulps: u64) -> bool {
        R::abs_diff_eq(self.m11, other.m11, ulps)
            && R::abs_diff_eq(self.m21, other.m21, ulps)
            && R::abs_diff_eq(self.m12, other.m12, ulps)
            && R::abs_diff_eq(self.m22, other.m22, ulps)
            && R::abs_diff_eq(self.m13, other.m13, ulps)
            && R::abs_diff_eq(self.m23, other.m23, ulps)
            && R::abs_diff_eq(self.m14, other.m14, ulps)
            && R::abs_diff_eq(self.m24, other.m24, ulps)
            && R::abs_diff_eq(self.m15, other.m15, ulps)
            && R::abs_diff_eq(self.m25, other.m25, ulps)
            && R::abs_diff_eq(self.m16, other.m16, ulps)
            && R::abs_diff_eq(self.m26, other.m26, ulps)
    }

    /// The 2x6 matrix whose components all equal `elem`. Upstream: `Matrix2x6::repeat`.
    #[inline(always)]
    fn repeat(elem: T) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: elem,
            m21: elem,
            m12: elem,
            m22: elem,
            m13: elem,
            m23: elem,
            m14: elem,
            m24: elem,
            m15: elem,
            m25: elem,
            m16: elem,
            m26: elem,
        }
    }

    /// Alias of `repeat`. Upstream: `Matrix2x6::from_element`.
    #[inline(always)]
    fn from_element(elem: T) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: elem,
            m21: elem,
            m12: elem,
            m22: elem,
            m13: elem,
            m23: elem,
            m14: elem,
            m24: elem,
            m15: elem,
            m25: elem,
            m16: elem,
            m26: elem,
        }
    }

    /// The 2x6 matrix whose component `(i, j)` (row, column, 0-based) is `f(i, j)`, `f` being
    /// called in column-major order like upstream. `f` is any closure or `Fn` value of `(usize,
    /// usize)` whose output converts `Into<T>` (the identity included): Cairo cannot state `Output
    /// = T` on the closure without the `associated_item_constraints` experimental feature.
    /// Upstream: `Matrix2x6::from_fn`.
    fn from_fn<
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (usize, usize)>,
        +Into<Func::Output, T>,
        +Drop<Func::Output>,
    >(
        f: F,
    ) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: f(0, 0).into(),
            m21: f(1, 0).into(),
            m12: f(0, 1).into(),
            m22: f(1, 1).into(),
            m13: f(0, 2).into(),
            m23: f(1, 2).into(),
            m14: f(0, 3).into(),
            m24: f(1, 3).into(),
            m15: f(0, 4).into(),
            m25: f(1, 4).into(),
            m16: f(0, 5).into(),
            m26: f(1, 5).into(),
        }
    }

    /// The 2x6 matrix of the 12 values of `data`, in row-major order. Panics with `nalgebra: wrong
    /// slice length` unless `data.len() == 12`. Upstream: `Matrix2x6::from_row_slice` (`&[T]`).
    ///
    /// `data` is read as ONE fixed-size array (`Span -> @Box<[T; 12]>`, one length check): measured
    /// about 5 times cheaper than a bounds-checked `*data[k]` per component
    /// (`bench_matrix3_from_row_slice__alt_span_index`).
    #[inline(always)]
    fn from_row_slice(data: Span<T>) -> Matrix2x6<T> {
        let boxed: @Box<[T; 12]> = data.try_into().expect(errors::SLICE_LENGTH);
        let [v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11] = boxed.unbox();
        Matrix2x6 {
            m11: v0,
            m21: v6,
            m12: v1,
            m22: v7,
            m13: v2,
            m23: v8,
            m14: v3,
            m24: v9,
            m15: v4,
            m25: v10,
            m16: v5,
            m26: v11,
        }
    }

    /// The 2x6 matrix of the 12 values of `data`, in column-major order. Panics with `nalgebra:
    /// wrong slice length` unless `data.len() == 12`. Upstream: `Matrix2x6::from_column_slice`
    /// (`&[T]`).
    ///
    /// `data` is read as ONE fixed-size array (`Span -> @Box<[T; 12]>`, one length check): measured
    /// about 5 times cheaper than a bounds-checked `*data[k]` per component
    /// (`bench_matrix3_from_row_slice__alt_span_index`).
    #[inline(always)]
    fn from_column_slice(data: Span<T>) -> Matrix2x6<T> {
        let boxed: @Box<[T; 12]> = data.try_into().expect(errors::SLICE_LENGTH);
        let [v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11] = boxed.unbox();
        Matrix2x6 {
            m11: v0,
            m21: v1,
            m12: v2,
            m22: v3,
            m13: v4,
            m23: v5,
            m14: v6,
            m24: v7,
            m15: v8,
            m25: v9,
            m16: v10,
            m26: v11,
        }
    }

    /// The 2x6 matrix whose first `data.len()` diagonal components are `data`, every other
    /// component zero. Panics with `nalgebra: diagonal too long` when `data.len() > 2`. Upstream:
    /// `Matrix2x6::from_partial_diagonal` (`&[T]`).
    #[inline(always)]
    fn from_partial_diagonal(data: Span<T>) -> Matrix2x6<T> {
        let len = data.len();
        if len > 2 {
            core::panic_with_felt252(errors::TOO_MANY_DIAGONAL);
        }
        Matrix2x6 {
            m11: if len > 0 {
                *data[0]
            } else {
                R::zero()
            },
            m21: R::zero(),
            m12: R::zero(),
            m22: if len > 1 {
                *data[1]
            } else {
                R::zero()
            },
            m13: R::zero(),
            m23: R::zero(),
            m14: R::zero(),
            m24: R::zero(),
            m15: R::zero(),
            m25: R::zero(),
            m16: R::zero(),
            m26: R::zero(),
        }
    }

    /// `true` when every component is zero. Upstream: `Zero::is_zero`.
    #[inline(always)]
    fn is_zero(self: Matrix2x6<T>) -> bool {
        self.m11 == R::zero()
            && self.m21 == R::zero()
            && self.m12 == R::zero()
            && self.m22 == R::zero()
            && self.m13 == R::zero()
            && self.m23 == R::zero()
            && self.m14 == R::zero()
            && self.m24 == R::zero()
            && self.m15 == R::zero()
            && self.m25 == R::zero()
            && self.m16 == R::zero()
            && self.m26 == R::zero()
    }

    /// Component-wise (Hadamard) product, each component floored once. Panics on overflow.
    /// Upstream: `component_mul`.
    #[inline(always)]
    fn component_mul(self: Matrix2x6<T>, rhs: Matrix2x6<T>) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: self.m11 * rhs.m11,
            m21: self.m21 * rhs.m21,
            m12: self.m12 * rhs.m12,
            m22: self.m22 * rhs.m22,
            m13: self.m13 * rhs.m13,
            m23: self.m23 * rhs.m23,
            m14: self.m14 * rhs.m14,
            m24: self.m24 * rhs.m24,
            m15: self.m15 * rhs.m15,
            m25: self.m25 * rhs.m25,
            m16: self.m16 * rhs.m16,
            m26: self.m26 * rhs.m26,
        }
    }

    /// `self = self.component_mul(rhs)`. Upstream: `component_mul_assign`.
    #[inline(always)]
    fn component_mul_assign(ref self: Matrix2x6<T>, rhs: Matrix2x6<T>) {
        self =
            Matrix2x6 {
                m11: self.m11 * rhs.m11,
                m21: self.m21 * rhs.m21,
                m12: self.m12 * rhs.m12,
                m22: self.m22 * rhs.m22,
                m13: self.m13 * rhs.m13,
                m23: self.m23 * rhs.m23,
                m14: self.m14 * rhs.m14,
                m24: self.m24 * rhs.m24,
                m15: self.m15 * rhs.m15,
                m25: self.m25 * rhs.m25,
                m16: self.m16 * rhs.m16,
                m26: self.m26 * rhs.m26,
            };
    }

    /// Component-wise quotient, each component rounded to nearest (ties to even). Panics on a zero
    /// component of `rhs` and on overflow. Upstream: `component_div`.
    #[inline(always)]
    fn component_div(self: Matrix2x6<T>, rhs: Matrix2x6<T>) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: R::div(self.m11, rhs.m11),
            m21: R::div(self.m21, rhs.m21),
            m12: R::div(self.m12, rhs.m12),
            m22: R::div(self.m22, rhs.m22),
            m13: R::div(self.m13, rhs.m13),
            m23: R::div(self.m23, rhs.m23),
            m14: R::div(self.m14, rhs.m14),
            m24: R::div(self.m24, rhs.m24),
            m15: R::div(self.m15, rhs.m15),
            m25: R::div(self.m25, rhs.m25),
            m16: R::div(self.m16, rhs.m16),
            m26: R::div(self.m26, rhs.m26),
        }
    }

    /// `self = self.component_div(rhs)`. Upstream: `component_div_assign`.
    #[inline(always)]
    fn component_div_assign(ref self: Matrix2x6<T>, rhs: Matrix2x6<T>) {
        self =
            Matrix2x6 {
                m11: R::div(self.m11, rhs.m11),
                m21: R::div(self.m21, rhs.m21),
                m12: R::div(self.m12, rhs.m12),
                m22: R::div(self.m22, rhs.m22),
                m13: R::div(self.m13, rhs.m13),
                m23: R::div(self.m23, rhs.m23),
                m14: R::div(self.m14, rhs.m14),
                m24: R::div(self.m24, rhs.m24),
                m15: R::div(self.m15, rhs.m15),
                m25: R::div(self.m25, rhs.m25),
                m16: R::div(self.m16, rhs.m16),
                m26: R::div(self.m26, rhs.m26),
            };
    }

    /// Component-wise minimum (infimum). Exact. Upstream: `inf`.
    #[inline(always)]
    fn inf(self: Matrix2x6<T>, other: Matrix2x6<T>) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: R::min(self.m11, other.m11),
            m21: R::min(self.m21, other.m21),
            m12: R::min(self.m12, other.m12),
            m22: R::min(self.m22, other.m22),
            m13: R::min(self.m13, other.m13),
            m23: R::min(self.m23, other.m23),
            m14: R::min(self.m14, other.m14),
            m24: R::min(self.m24, other.m24),
            m15: R::min(self.m15, other.m15),
            m25: R::min(self.m25, other.m25),
            m16: R::min(self.m16, other.m16),
            m26: R::min(self.m26, other.m26),
        }
    }

    /// Component-wise maximum (supremum). Exact. Upstream: `sup`.
    #[inline(always)]
    fn sup(self: Matrix2x6<T>, other: Matrix2x6<T>) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: R::max(self.m11, other.m11),
            m21: R::max(self.m21, other.m21),
            m12: R::max(self.m12, other.m12),
            m22: R::max(self.m22, other.m22),
            m13: R::max(self.m13, other.m13),
            m23: R::max(self.m23, other.m23),
            m14: R::max(self.m14, other.m14),
            m24: R::max(self.m24, other.m24),
            m15: R::max(self.m15, other.m15),
            m25: R::max(self.m25, other.m25),
            m16: R::max(self.m16, other.m16),
            m26: R::max(self.m26, other.m26),
        }
    }

    /// `(self.inf(other), self.sup(other))`. Exact. Upstream: `inf_sup`.
    #[inline(always)]
    fn inf_sup(self: Matrix2x6<T>, other: Matrix2x6<T>) -> (Matrix2x6<T>, Matrix2x6<T>) {
        (Self::inf(self, other), Self::sup(self, other))
    }

    /// `self + k` added to every component. Exact; panics on overflow. Upstream: `add_scalar`.
    #[inline(always)]
    fn add_scalar(self: Matrix2x6<T>, k: T) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: self.m11 + k,
            m21: self.m21 + k,
            m12: self.m12 + k,
            m22: self.m22 + k,
            m13: self.m13 + k,
            m23: self.m23 + k,
            m14: self.m14 + k,
            m24: self.m24 + k,
            m15: self.m15 + k,
            m25: self.m25 + k,
            m16: self.m16 + k,
            m26: self.m26 + k,
        }
    }

    /// `self = alpha * a ∘ b + beta * self` (component-wise product): per component `alpha * a`
    /// is floored, then the two products are ONE fused `sum_prod2` (floored once). Panics on
    /// overflow.
    /// Upstream: `cmpy` (which skips reading `self` when `beta` is zero: a difference only for NaN,
    /// which fixed point has not).
    #[inline(always)]
    fn cmpy(ref self: Matrix2x6<T>, alpha: T, a: Matrix2x6<T>, b: Matrix2x6<T>, beta: T) {
        self =
            Matrix2x6 {
                m11: R::sum_prod2(alpha * a.m11, b.m11, beta, self.m11),
                m21: R::sum_prod2(alpha * a.m21, b.m21, beta, self.m21),
                m12: R::sum_prod2(alpha * a.m12, b.m12, beta, self.m12),
                m22: R::sum_prod2(alpha * a.m22, b.m22, beta, self.m22),
                m13: R::sum_prod2(alpha * a.m13, b.m13, beta, self.m13),
                m23: R::sum_prod2(alpha * a.m23, b.m23, beta, self.m23),
                m14: R::sum_prod2(alpha * a.m14, b.m14, beta, self.m14),
                m24: R::sum_prod2(alpha * a.m24, b.m24, beta, self.m24),
                m15: R::sum_prod2(alpha * a.m15, b.m15, beta, self.m15),
                m25: R::sum_prod2(alpha * a.m25, b.m25, beta, self.m25),
                m16: R::sum_prod2(alpha * a.m16, b.m16, beta, self.m16),
                m26: R::sum_prod2(alpha * a.m26, b.m26, beta, self.m26),
            };
    }

    /// `self = alpha * a / b + beta * self` (component-wise quotient): per component `alpha * a` is
    /// floored, divided by `b` (rounded to nearest), then `beta * self + quotient` is ONE `mul_add`
    /// (floored once). Panics on a zero component of `b` and on overflow. Upstream: `cdpy`.
    #[inline(always)]
    fn cdpy(ref self: Matrix2x6<T>, alpha: T, a: Matrix2x6<T>, b: Matrix2x6<T>, beta: T) {
        self =
            Matrix2x6 {
                m11: R::mul_add(beta, self.m11, R::div(alpha * a.m11, b.m11)),
                m21: R::mul_add(beta, self.m21, R::div(alpha * a.m21, b.m21)),
                m12: R::mul_add(beta, self.m12, R::div(alpha * a.m12, b.m12)),
                m22: R::mul_add(beta, self.m22, R::div(alpha * a.m22, b.m22)),
                m13: R::mul_add(beta, self.m13, R::div(alpha * a.m13, b.m13)),
                m23: R::mul_add(beta, self.m23, R::div(alpha * a.m23, b.m23)),
                m14: R::mul_add(beta, self.m14, R::div(alpha * a.m14, b.m14)),
                m24: R::mul_add(beta, self.m24, R::div(alpha * a.m24, b.m24)),
                m15: R::mul_add(beta, self.m15, R::div(alpha * a.m15, b.m15)),
                m25: R::mul_add(beta, self.m25, R::div(alpha * a.m25, b.m25)),
                m16: R::mul_add(beta, self.m16, R::div(alpha * a.m16, b.m16)),
                m26: R::mul_add(beta, self.m26, R::div(alpha * a.m26, b.m26)),
            };
    }

    /// The smallest component. Exact. Upstream: `min`.
    #[inline(always)]
    fn min(self: Matrix2x6<T>) -> T {
        R::min(
            R::min(
                R::min(
                    R::min(
                        R::min(
                            R::min(
                                R::min(
                                    R::min(
                                        R::min(
                                            R::min(R::min(self.m11, self.m21), self.m12), self.m22,
                                        ),
                                        self.m13,
                                    ),
                                    self.m23,
                                ),
                                self.m14,
                            ),
                            self.m24,
                        ),
                        self.m15,
                    ),
                    self.m25,
                ),
                self.m16,
            ),
            self.m26,
        )
    }

    /// The largest component. Exact. Upstream: `max`.
    #[inline(always)]
    fn max(self: Matrix2x6<T>) -> T {
        R::max(
            R::max(
                R::max(
                    R::max(
                        R::max(
                            R::max(
                                R::max(
                                    R::max(
                                        R::max(
                                            R::max(R::max(self.m11, self.m21), self.m12), self.m22,
                                        ),
                                        self.m13,
                                    ),
                                    self.m23,
                                ),
                                self.m14,
                            ),
                            self.m24,
                        ),
                        self.m15,
                    ),
                    self.m25,
                ),
                self.m16,
            ),
            self.m26,
        )
    }

    /// The smallest absolute value of a component. Panics on the scalar's `MIN`. Upstream: `amin`.
    #[inline(always)]
    fn amin(self: Matrix2x6<T>) -> T {
        R::min(
            R::min(
                R::min(
                    R::min(
                        R::min(
                            R::min(
                                R::min(
                                    R::min(
                                        R::min(
                                            R::min(
                                                R::min(R::abs(self.m11), R::abs(self.m21)),
                                                R::abs(self.m12),
                                            ),
                                            R::abs(self.m22),
                                        ),
                                        R::abs(self.m13),
                                    ),
                                    R::abs(self.m23),
                                ),
                                R::abs(self.m14),
                            ),
                            R::abs(self.m24),
                        ),
                        R::abs(self.m15),
                    ),
                    R::abs(self.m25),
                ),
                R::abs(self.m16),
            ),
            R::abs(self.m26),
        )
    }

    /// The largest absolute value of a component (the uniform norm). Panics on the scalar's `MIN`.
    /// Upstream: `amax`.
    #[inline(always)]
    fn amax(self: Matrix2x6<T>) -> T {
        R::max(
            R::max(
                R::max(
                    R::max(
                        R::max(
                            R::max(
                                R::max(
                                    R::max(
                                        R::max(
                                            R::max(
                                                R::max(R::abs(self.m11), R::abs(self.m21)),
                                                R::abs(self.m12),
                                            ),
                                            R::abs(self.m22),
                                        ),
                                        R::abs(self.m13),
                                    ),
                                    R::abs(self.m23),
                                ),
                                R::abs(self.m14),
                            ),
                            R::abs(self.m24),
                        ),
                        R::abs(self.m15),
                    ),
                    R::abs(self.m25),
                ),
                R::abs(self.m16),
            ),
            R::abs(self.m26),
        )
    }

    /// `amin`: the modulus of a real scalar is its absolute value. Upstream: `camin`.
    #[inline(always)]
    fn camin(self: Matrix2x6<T>) -> T {
        R::min(
            R::min(
                R::min(
                    R::min(
                        R::min(
                            R::min(
                                R::min(
                                    R::min(
                                        R::min(
                                            R::min(
                                                R::min(R::abs(self.m11), R::abs(self.m21)),
                                                R::abs(self.m12),
                                            ),
                                            R::abs(self.m22),
                                        ),
                                        R::abs(self.m13),
                                    ),
                                    R::abs(self.m23),
                                ),
                                R::abs(self.m14),
                            ),
                            R::abs(self.m24),
                        ),
                        R::abs(self.m15),
                    ),
                    R::abs(self.m25),
                ),
                R::abs(self.m16),
            ),
            R::abs(self.m26),
        )
    }

    /// `amax`: the modulus of a real scalar is its absolute value. Upstream: `camax`.
    #[inline(always)]
    fn camax(self: Matrix2x6<T>) -> T {
        R::max(
            R::max(
                R::max(
                    R::max(
                        R::max(
                            R::max(
                                R::max(
                                    R::max(
                                        R::max(
                                            R::max(
                                                R::max(R::abs(self.m11), R::abs(self.m21)),
                                                R::abs(self.m12),
                                            ),
                                            R::abs(self.m22),
                                        ),
                                        R::abs(self.m13),
                                    ),
                                    R::abs(self.m23),
                                ),
                                R::abs(self.m14),
                            ),
                            R::abs(self.m24),
                        ),
                        R::abs(self.m15),
                    ),
                    R::abs(self.m25),
                ),
                R::abs(self.m16),
            ),
            R::abs(self.m26),
        )
    }

    /// `(row, column)` of the component with the largest absolute value, the first one in
    /// column-major order on ties. Panics on the scalar's `MIN`. Upstream: `iamax_full`.
    fn iamax_full(self: Matrix2x6<T>) -> (usize, usize) {
        let mut best: (usize, usize) = (0, 0);
        let mut m = R::abs(self.m11);
        let v = R::abs(self.m21);
        if v > m {
            m = v;
            best = (1, 0);
        }
        let v = R::abs(self.m12);
        if v > m {
            m = v;
            best = (0, 1);
        }
        let v = R::abs(self.m22);
        if v > m {
            m = v;
            best = (1, 1);
        }
        let v = R::abs(self.m13);
        if v > m {
            m = v;
            best = (0, 2);
        }
        let v = R::abs(self.m23);
        if v > m {
            m = v;
            best = (1, 2);
        }
        let v = R::abs(self.m14);
        if v > m {
            m = v;
            best = (0, 3);
        }
        let v = R::abs(self.m24);
        if v > m {
            m = v;
            best = (1, 3);
        }
        let v = R::abs(self.m15);
        if v > m {
            m = v;
            best = (0, 4);
        }
        let v = R::abs(self.m25);
        if v > m {
            m = v;
            best = (1, 4);
        }
        let v = R::abs(self.m16);
        if v > m {
            m = v;
            best = (0, 5);
        }
        let v = R::abs(self.m26);
        if v > m {
            best = (1, 5);
        }
        best
    }

    /// `iamax_full`: the modulus of a real scalar is its absolute value. Upstream: `icamax_full`.
    #[inline(always)]
    fn icamax_full(self: Matrix2x6<T>) -> (usize, usize) {
        Self::iamax_full(self)
    }

    /// Dot product (the sum of the component-wise products, upstream's Frobenius inner product for
    /// matrices): the exact sum is floored ONCE, only the result must fit. Upstream: `dot`.
    fn dot(self: Matrix2x6<T>, rhs: Matrix2x6<T>) -> T {
        let w = R::wide_add_prod(R::wide_zero(), self.m11, rhs.m11);
        let w = R::wide_add_prod(w, self.m21, rhs.m21);
        let w = R::wide_add_prod(w, self.m12, rhs.m12);
        let w = R::wide_add_prod(w, self.m22, rhs.m22);
        let w = R::wide_add_prod(w, self.m13, rhs.m13);
        let w = R::wide_add_prod(w, self.m23, rhs.m23);
        let w = R::wide_add_prod(w, self.m14, rhs.m14);
        let w = R::wide_add_prod(w, self.m24, rhs.m24);
        let w = R::wide_add_prod(w, self.m15, rhs.m15);
        let w = R::wide_add_prod(w, self.m25, rhs.m25);
        let w = R::wide_add_prod(w, self.m16, rhs.m16);
        R::wide_rescale(R::wide_add_prod(w, self.m26, rhs.m26))
    }

    /// Squared Euclidean (Frobenius) norm: the exact sum of squares floored once. Panics on
    /// overflow (above a norm of about 46 340 in Q32.32 only `norm` works). Upstream:
    /// `norm_squared`.
    fn norm_squared(self: Matrix2x6<T>) -> T {
        let w = R::wide_add_prod(R::wide_zero(), self.m11, self.m11);
        let w = R::wide_add_prod(w, self.m21, self.m21);
        let w = R::wide_add_prod(w, self.m12, self.m12);
        let w = R::wide_add_prod(w, self.m22, self.m22);
        let w = R::wide_add_prod(w, self.m13, self.m13);
        let w = R::wide_add_prod(w, self.m23, self.m23);
        let w = R::wide_add_prod(w, self.m14, self.m14);
        let w = R::wide_add_prod(w, self.m24, self.m24);
        let w = R::wide_add_prod(w, self.m15, self.m15);
        let w = R::wide_add_prod(w, self.m25, self.m25);
        let w = R::wide_add_prod(w, self.m16, self.m16);
        R::wide_rescale(R::wide_add_prod(w, self.m26, self.m26))
    }

    /// Euclidean (Frobenius) norm: square root of the UNSCALED exact sum of squares, floored once.
    /// No intermediate overflow: only the result must fit. Upstream: `norm`.
    fn norm(self: Matrix2x6<T>) -> T {
        let w = R::wide_add_prod(R::wide_zero(), self.m11, self.m11);
        let w = R::wide_add_prod(w, self.m21, self.m21);
        let w = R::wide_add_prod(w, self.m12, self.m12);
        let w = R::wide_add_prod(w, self.m22, self.m22);
        let w = R::wide_add_prod(w, self.m13, self.m13);
        let w = R::wide_add_prod(w, self.m23, self.m23);
        let w = R::wide_add_prod(w, self.m14, self.m14);
        let w = R::wide_add_prod(w, self.m24, self.m24);
        let w = R::wide_add_prod(w, self.m15, self.m15);
        let w = R::wide_add_prod(w, self.m25, self.m25);
        let w = R::wide_add_prod(w, self.m16, self.m16);
        R::wide_sqrt(R::wide_add_prod(w, self.m26, self.m26))
    }

    /// Alias of `norm_squared`. Upstream: `magnitude_squared`.
    #[inline(always)]
    fn magnitude_squared(self: Matrix2x6<T>) -> T {
        Self::norm_squared(self)
    }

    /// Alias of `norm`. Upstream: `magnitude`.
    #[inline(always)]
    fn magnitude(self: Matrix2x6<T>) -> T {
        Self::norm(self)
    }

    /// `(self - rhs).norm()`: the differences are exact, then one fused norm. Panics when a
    /// difference or the result overflows. Upstream: `metric_distance`.
    fn metric_distance(self: Matrix2x6<T>, rhs: Matrix2x6<T>) -> T {
        let w = R::wide_add_prod(R::wide_zero(), self.m11 - rhs.m11, self.m11 - rhs.m11);
        let w = R::wide_add_prod(w, self.m21 - rhs.m21, self.m21 - rhs.m21);
        let w = R::wide_add_prod(w, self.m12 - rhs.m12, self.m12 - rhs.m12);
        let w = R::wide_add_prod(w, self.m22 - rhs.m22, self.m22 - rhs.m22);
        let w = R::wide_add_prod(w, self.m13 - rhs.m13, self.m13 - rhs.m13);
        let w = R::wide_add_prod(w, self.m23 - rhs.m23, self.m23 - rhs.m23);
        let w = R::wide_add_prod(w, self.m14 - rhs.m14, self.m14 - rhs.m14);
        let w = R::wide_add_prod(w, self.m24 - rhs.m24, self.m24 - rhs.m24);
        let w = R::wide_add_prod(w, self.m15 - rhs.m15, self.m15 - rhs.m15);
        let w = R::wide_add_prod(w, self.m25 - rhs.m25, self.m25 - rhs.m25);
        let w = R::wide_add_prod(w, self.m16 - rhs.m16, self.m16 - rhs.m16);
        R::wide_sqrt(R::wide_add_prod(w, self.m26 - rhs.m26, self.m26 - rhs.m26))
    }

    /// `self / k`, each component the correctly rounded quotient (nearest, ties to even), through 2
    /// prepared-divisor `Real::divN` call(s), bit-identical to one `Real::div` per component.
    /// Panics on a zero `k` and on overflow. Upstream: `unscale` (`self / k`).
    fn unscale(self: Matrix2x6<T>, k: T) -> Matrix2x6<T> {
        let (m11, m21, m12, m22, m13, m23, m14, m24, m15) = R::div9(
            self.m11,
            self.m21,
            self.m12,
            self.m22,
            self.m13,
            self.m23,
            self.m14,
            self.m24,
            self.m15,
            k,
        );
        let (m25, m16, m26) = R::div3(self.m25, self.m16, self.m26, k);
        Matrix2x6 { m11, m21, m12, m22, m13, m23, m14, m24, m15, m25, m16, m26 }
    }

    /// `self / self.norm()`: the floored norm, then `unscale`. Panics with a division by zero when
    /// the norm is zero, and on overflow when the norm does not fit. Upstream: `normalize`.
    fn normalize(self: Matrix2x6<T>) -> Matrix2x6<T> {
        Self::unscale(self, Self::norm(self))
    }

    /// `Some(self.normalize())`, or `None` when the norm is `<= min_norm` (never divides by zero
    /// for `min_norm >= 0`). Upstream: `try_normalize`.
    fn try_normalize(self: Matrix2x6<T>, min_norm: T) -> Option<Matrix2x6<T>> {
        let n = Self::norm(self);
        if n <= min_norm {
            None
        } else {
            Some(Self::unscale(self, n))
        }
    }

    /// `self` when its norm is `<= max`, otherwise `self.scale(max / norm)` (the ratio rounded to
    /// nearest, like upstream's `max / n`). Panics only when the norm does not fit. Upstream:
    /// `cap_magnitude`.
    fn cap_magnitude(self: Matrix2x6<T>, max: T) -> Matrix2x6<T> {
        let n = Self::norm(self);
        if n <= max {
            self
        } else {
            Self::scale(self, R::div(max, n))
        }
    }

    /// Scales `self` to the norm `magnitude` (`self.scale(magnitude / norm)`, the ratio rounded to
    /// nearest) when its norm is `> min_magnitude`, leaves it unchanged otherwise. Upstream:
    /// `try_set_magnitude` (`&mut self`).
    fn try_set_magnitude(ref self: Matrix2x6<T>, magnitude: T, min_magnitude: T) {
        let n = Self::norm(self);
        if n > min_magnitude {
            self = Self::scale(self, R::div(magnitude, n));
        }
    }

    /// The induced 1-norm: the largest absolute column sum (the L1 norm of a column vector, the
    /// largest absolute value of a row vector). Exact; panics on overflow. Upstream: `one_norm`.
    #[inline(always)]
    fn one_norm(self: Matrix2x6<T>) -> T {
        R::max(
            R::max(
                R::max(
                    R::max(
                        R::max(
                            R::abs(self.m11) + R::abs(self.m21),
                            R::abs(self.m12) + R::abs(self.m22),
                        ),
                        R::abs(self.m13) + R::abs(self.m23),
                    ),
                    R::abs(self.m14) + R::abs(self.m24),
                ),
                R::abs(self.m15) + R::abs(self.m25),
            ),
            R::abs(self.m16) + R::abs(self.m26),
        )
    }

    /// The conjugate transpose, a `Matrix6x2`: the transpose for a real scalar. Exact. Upstream:
    /// `adjoint`.
    #[inline(always)]
    fn adjoint(self: Matrix2x6<T>) -> Matrix6x2<T> {
        Self::transpose(self)
    }

    /// Alias of `adjoint` (deprecated upstream). Upstream: `conjugate_transpose`.
    #[inline(always)]
    fn conjugate_transpose(self: Matrix2x6<T>) -> Matrix6x2<T> {
        Self::transpose(self)
    }

    /// The component-wise conjugate: `self` for a real scalar. Upstream: `conjugate`.
    #[inline(always)]
    fn conjugate(self: Matrix2x6<T>) -> Matrix2x6<T> {
        self
    }

    /// The same shape with every component converted by `Into<T, U>`. With the single scalar of
    /// this library (`Fixed`) it is the identity; it exists for scalar-generic code. Upstream:
    /// `cast` (and `SubsetOf<Matrix<U>>`, the `nalgebra::convert` it goes through).
    fn cast<U, +Into<T, U>, +Drop<U>>(self: Matrix2x6<T>) -> Matrix2x6<U> {
        Matrix2x6 {
            m11: self.m11.into(),
            m21: self.m21.into(),
            m12: self.m12.into(),
            m22: self.m22.into(),
            m13: self.m13.into(),
            m23: self.m23.into(),
            m14: self.m14.into(),
            m24: self.m24.into(),
            m15: self.m15.into(),
            m25: self.m25.into(),
            m16: self.m16.into(),
            m26: self.m26.into(),
        }
    }

    /// `Some` of the shape with every component converted by `TryInto<T, U>`, `None` as soon as one
    /// conversion fails. Upstream: `try_cast`.
    fn try_cast<U, +TryInto<T, U>, +Drop<U>>(self: Matrix2x6<T>) -> Option<Matrix2x6<U>> {
        let m11: U = self.m11.try_into()?;
        let m21: U = self.m21.try_into()?;
        let m12: U = self.m12.try_into()?;
        let m22: U = self.m22.try_into()?;
        let m13: U = self.m13.try_into()?;
        let m23: U = self.m23.try_into()?;
        let m14: U = self.m14.try_into()?;
        let m24: U = self.m24.try_into()?;
        let m15: U = self.m15.try_into()?;
        let m25: U = self.m25.try_into()?;
        let m16: U = self.m16.try_into()?;
        let m26: U = self.m26.try_into()?;
        Option::Some(Matrix2x6 { m11, m21, m12, m22, m13, m23, m14, m24, m15, m25, m16, m26 })
    }

    /// `true` when every component is within `epsilon` ulp of `other`'s, or has the same sign and
    /// lies within `max_relative` times the larger magnitude of the two (`|a - b| <= max(|a|, |b|)
    /// · max_relative`). Panics on a component equal to the scalar's `MIN`, and on overflow of
    /// that product (only possible with `max_relative > 1`). Upstream:
    /// `approx::RelativeEq::relative_eq`, `epsilon` counted in ulp instead of a float epsilon
    /// (DESIGN D3).
    #[inline(always)]
    fn relative_eq(self: Matrix2x6<T>, other: Matrix2x6<T>, epsilon: u64, max_relative: T) -> bool {
        ApproxEqTrait::relative_eq(self.m11, other.m11, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m21, other.m21, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m12, other.m12, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m22, other.m22, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m13, other.m13, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m23, other.m23, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m14, other.m14, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m24, other.m24, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m15, other.m15, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m25, other.m25, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m16, other.m16, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m26, other.m26, epsilon, max_relative)
    }

    /// `true` when every component is within `epsilon` ulp of `other`'s, or has the same sign and
    /// lies within `max_ulps` ulp (in fixed point the distance in ulp IS the raw difference; the
    /// `max_ulps` budget does not cross zero, like upstream's float `ulps_eq`). Cannot overflow.
    /// Upstream: `approx::UlpsEq::ulps_eq`.
    #[inline(always)]
    fn ulps_eq(self: Matrix2x6<T>, other: Matrix2x6<T>, epsilon: u64, max_ulps: u32) -> bool {
        ApproxEqTrait::ulps_eq(self.m11, other.m11, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m21, other.m21, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m12, other.m12, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m22, other.m22, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m13, other.m13, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m23, other.m23, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m14, other.m14, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m24, other.m24, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m15, other.m15, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m25, other.m25, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m16, other.m16, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m26, other.m26, epsilon, max_ulps)
    }

    /// The 2x6 matrix of `f(x)` for every component `x` (called in column-major order). `f` is any
    /// closure or `Fn` value; Cairo closures take their arguments by value and cannot mutate their
    /// captures. Upstream: `map`.
    #[cfg(feature: 'closures')]
    #[inline]
    fn map<F, +Drop<F>, impl Func: core::ops::Fn<F, (T,)>, +Drop<Func::Output>>(
        self: Matrix2x6<T>, f: F,
    ) -> Matrix2x6<Func::Output> {
        Matrix2x6 {
            m11: f(self.m11),
            m21: f(self.m21),
            m12: f(self.m12),
            m22: f(self.m22),
            m13: f(self.m13),
            m23: f(self.m23),
            m14: f(self.m14),
            m24: f(self.m24),
            m15: f(self.m15),
            m25: f(self.m25),
            m16: f(self.m16),
            m26: f(self.m26),
        }
    }

    /// The 2x6 matrix of `f(i, j, x)` for every component `x` at row `i`, column `j` (0-based,
    /// column-major order). `f` is any closure or `Fn` value; Cairo closures take their arguments
    /// by value and cannot mutate their captures. Upstream: `map_with_location`.
    #[cfg(feature: 'closures')]
    #[inline]
    fn map_with_location<
        F, +Drop<F>, impl Func: core::ops::Fn<F, (usize, usize, T)>, +Drop<Func::Output>,
    >(
        self: Matrix2x6<T>, f: F,
    ) -> Matrix2x6<Func::Output> {
        Matrix2x6 {
            m11: f(0, 0, self.m11),
            m21: f(1, 0, self.m21),
            m12: f(0, 1, self.m12),
            m22: f(1, 1, self.m22),
            m13: f(0, 2, self.m13),
            m23: f(1, 2, self.m23),
            m14: f(0, 3, self.m14),
            m24: f(1, 3, self.m24),
            m15: f(0, 4, self.m15),
            m25: f(1, 4, self.m25),
            m16: f(0, 5, self.m16),
            m26: f(1, 5, self.m26),
        }
    }

    /// The 2x6 matrix of `f(a, b)` for the components `a` of `self` and `b` of `rhs` at the same
    /// position. `f` is any closure or `Fn` value; Cairo closures take their arguments by value and
    /// cannot mutate their captures. Upstream: `zip_map`.
    #[cfg(feature: 'closures')]
    #[inline]
    fn zip_map<
        T2,
        +Copy<T2>,
        +Drop<T2>,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (T, T2)>,
        +Drop<Func::Output>,
    >(
        self: Matrix2x6<T>, rhs: Matrix2x6<T2>, f: F,
    ) -> Matrix2x6<Func::Output> {
        Matrix2x6 {
            m11: f(self.m11, rhs.m11),
            m21: f(self.m21, rhs.m21),
            m12: f(self.m12, rhs.m12),
            m22: f(self.m22, rhs.m22),
            m13: f(self.m13, rhs.m13),
            m23: f(self.m23, rhs.m23),
            m14: f(self.m14, rhs.m14),
            m24: f(self.m24, rhs.m24),
            m15: f(self.m15, rhs.m15),
            m25: f(self.m25, rhs.m25),
            m16: f(self.m16, rhs.m16),
            m26: f(self.m26, rhs.m26),
        }
    }

    /// The 2x6 matrix of `f(a, b, c)` for the components of `self`, `b` and `c` at the same
    /// position. `f` is any closure or `Fn` value; Cairo closures take their arguments by value and
    /// cannot mutate their captures. Upstream: `zip_zip_map`.
    #[cfg(feature: 'closures')]
    #[inline]
    fn zip_zip_map<
        T2,
        T3,
        +Copy<T2>,
        +Drop<T2>,
        +Copy<T3>,
        +Drop<T3>,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (T, T2, T3)>,
        +Drop<Func::Output>,
    >(
        self: Matrix2x6<T>, b: Matrix2x6<T2>, c: Matrix2x6<T3>, f: F,
    ) -> Matrix2x6<Func::Output> {
        Matrix2x6 {
            m11: f(self.m11, b.m11, c.m11),
            m21: f(self.m21, b.m21, c.m21),
            m12: f(self.m12, b.m12, c.m12),
            m22: f(self.m22, b.m22, c.m22),
            m13: f(self.m13, b.m13, c.m13),
            m23: f(self.m23, b.m23, c.m23),
            m14: f(self.m14, b.m14, c.m14),
            m24: f(self.m24, b.m24, c.m24),
            m15: f(self.m15, b.m15, c.m15),
            m25: f(self.m25, b.m25, c.m25),
            m16: f(self.m16, b.m16, c.m16),
            m26: f(self.m26, b.m26, c.m26),
        }
    }

    /// `f(.. f(f(init, x0), x1) .., x11)` over the components in column-major order. The closure's
    /// output converts `Into<Acc>` (the identity included): Cairo cannot state `Output = Acc`
    /// without the `associated_item_constraints` experimental feature. `f` is any closure or `Fn`
    /// value; Cairo closures take their arguments by value and cannot mutate their captures.
    /// Upstream: `fold`.
    #[cfg(feature: 'closures')]
    #[inline]
    fn fold<Acc, F, +Drop<F>, impl Func: core::ops::Fn<F, (Acc, T)>, +Into<Func::Output, Acc>>(
        self: Matrix2x6<T>, init: Acc, f: F,
    ) -> Acc {
        let acc: Acc = f(init, self.m11).into();
        let acc: Acc = f(acc, self.m21).into();
        let acc: Acc = f(acc, self.m12).into();
        let acc: Acc = f(acc, self.m22).into();
        let acc: Acc = f(acc, self.m13).into();
        let acc: Acc = f(acc, self.m23).into();
        let acc: Acc = f(acc, self.m14).into();
        let acc: Acc = f(acc, self.m24).into();
        let acc: Acc = f(acc, self.m15).into();
        let acc: Acc = f(acc, self.m25).into();
        let acc: Acc = f(acc, self.m16).into();
        f(acc, self.m26).into()
    }

    /// `init_f(Some(x0))`, then `f(acc, x)` over the other components in column-major order:
    /// upstream's `fold_with` (`init_f` receives the first component, `None` only for an empty
    /// matrix, which a static shape never is). The accumulator has the type of `init_f`'s output;
    /// `f`'s output converts `Into` it. The closures receive values instead of upstream's `&T`.
    /// Upstream: `fold_with`.
    #[cfg(feature: 'closures')]
    #[inline]
    fn fold_with<
        G,
        +Drop<G>,
        impl Init: core::ops::Fn<G, (Option<T>,)>,
        +Drop<Init::Output>,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (Init::Output, T)>,
        +Into<Func::Output, Init::Output>,
    >(
        self: Matrix2x6<T>, init_f: G, f: F,
    ) -> Init::Output {
        let acc: Init::Output = init_f(Option::Some(self.m11));
        let acc: Init::Output = f(acc, self.m21).into();
        let acc: Init::Output = f(acc, self.m12).into();
        let acc: Init::Output = f(acc, self.m22).into();
        let acc: Init::Output = f(acc, self.m13).into();
        let acc: Init::Output = f(acc, self.m23).into();
        let acc: Init::Output = f(acc, self.m14).into();
        let acc: Init::Output = f(acc, self.m24).into();
        let acc: Init::Output = f(acc, self.m15).into();
        let acc: Init::Output = f(acc, self.m25).into();
        let acc: Init::Output = f(acc, self.m16).into();
        f(acc, self.m26).into()
    }

    /// `fold` over the pairs of components of `self` and `rhs` at the same position: `f(acc, a,
    /// b)`, column-major. `f` is any closure or `Fn` value; Cairo closures take their arguments by
    /// value and cannot mutate their captures. Upstream: `zip_fold`.
    #[cfg(feature: 'closures')]
    #[inline]
    fn zip_fold<
        T2,
        +Copy<T2>,
        +Drop<T2>,
        Acc,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (Acc, T, T2)>,
        +Into<Func::Output, Acc>,
    >(
        self: Matrix2x6<T>, rhs: Matrix2x6<T2>, init: Acc, f: F,
    ) -> Acc {
        let acc: Acc = f(init, self.m11, rhs.m11).into();
        let acc: Acc = f(acc, self.m21, rhs.m21).into();
        let acc: Acc = f(acc, self.m12, rhs.m12).into();
        let acc: Acc = f(acc, self.m22, rhs.m22).into();
        let acc: Acc = f(acc, self.m13, rhs.m13).into();
        let acc: Acc = f(acc, self.m23, rhs.m23).into();
        let acc: Acc = f(acc, self.m14, rhs.m14).into();
        let acc: Acc = f(acc, self.m24, rhs.m24).into();
        let acc: Acc = f(acc, self.m15, rhs.m15).into();
        let acc: Acc = f(acc, self.m25, rhs.m25).into();
        let acc: Acc = f(acc, self.m16, rhs.m16).into();
        f(acc, self.m26, rhs.m26).into()
    }

    /// Replaces every component `x` by `f(x)` (column-major order). Upstream's closure is
    /// `FnMut(&mut T)`, writing through the reference; a Cairo closure cannot, so it RETURNS the
    /// new component (its output converts `Into<T>`). Upstream: `apply`.
    #[cfg(feature: 'closures')]
    #[inline]
    fn apply<F, +Drop<F>, impl Func: core::ops::Fn<F, (T,)>, +Into<Func::Output, T>>(
        ref self: Matrix2x6<T>, f: F,
    ) {
        self =
            Matrix2x6 {
                m11: f(self.m11).into(),
                m21: f(self.m21).into(),
                m12: f(self.m12).into(),
                m22: f(self.m22).into(),
                m13: f(self.m13).into(),
                m23: f(self.m23).into(),
                m14: f(self.m14).into(),
                m24: f(self.m24).into(),
                m15: f(self.m15).into(),
                m25: f(self.m25).into(),
                m16: f(self.m16).into(),
                m26: f(self.m26).into(),
            };
    }

    /// `self` with every component `x` replaced by `f(x)`: `apply` by value. Upstream's closure is
    /// `FnMut(&mut T)`, writing through the reference; a Cairo closure cannot, so it RETURNS the
    /// new component (its output converts `Into<T>`). Upstream: `apply_into`.
    #[cfg(feature: 'closures')]
    #[inline]
    fn apply_into<F, +Drop<F>, impl Func: core::ops::Fn<F, (T,)>, +Into<Func::Output, T>>(
        self: Matrix2x6<T>, f: F,
    ) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: f(self.m11).into(),
            m21: f(self.m21).into(),
            m12: f(self.m12).into(),
            m22: f(self.m22).into(),
            m13: f(self.m13).into(),
            m23: f(self.m23).into(),
            m14: f(self.m14).into(),
            m24: f(self.m24).into(),
            m15: f(self.m15).into(),
            m25: f(self.m25).into(),
            m16: f(self.m16).into(),
            m26: f(self.m26).into(),
        }
    }

    /// Replaces every component `a` by `f(a, b)`, `b` the component of `rhs` at the same position.
    /// Upstream's closure is `FnMut(&mut T)`, writing through the reference; a Cairo closure
    /// cannot, so it RETURNS the new component (its output converts `Into<T>`). Upstream:
    /// `zip_apply`.
    #[cfg(feature: 'closures')]
    #[inline]
    fn zip_apply<
        T2,
        +Copy<T2>,
        +Drop<T2>,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (T, T2)>,
        +Into<Func::Output, T>,
    >(
        ref self: Matrix2x6<T>, rhs: Matrix2x6<T2>, f: F,
    ) {
        self =
            Matrix2x6 {
                m11: f(self.m11, rhs.m11).into(),
                m21: f(self.m21, rhs.m21).into(),
                m12: f(self.m12, rhs.m12).into(),
                m22: f(self.m22, rhs.m22).into(),
                m13: f(self.m13, rhs.m13).into(),
                m23: f(self.m23, rhs.m23).into(),
                m14: f(self.m14, rhs.m14).into(),
                m24: f(self.m24, rhs.m24).into(),
                m15: f(self.m15, rhs.m15).into(),
                m25: f(self.m25, rhs.m25).into(),
                m16: f(self.m16, rhs.m16).into(),
                m26: f(self.m26, rhs.m26).into(),
            };
    }

    /// Replaces every component `a` by `f(a, b, c)`, `b` and `c` the components of `b` and `c` at
    /// the same position. Upstream's closure is `FnMut(&mut T)`, writing through the reference; a
    /// Cairo closure cannot, so it RETURNS the new component (its output converts `Into<T>`).
    /// Upstream: `zip_zip_apply`.
    #[cfg(feature: 'closures')]
    #[inline]
    fn zip_zip_apply<
        T2,
        T3,
        +Copy<T2>,
        +Drop<T2>,
        +Copy<T3>,
        +Drop<T3>,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (T, T2, T3)>,
        +Into<Func::Output, T>,
    >(
        ref self: Matrix2x6<T>, b: Matrix2x6<T2>, c: Matrix2x6<T3>, f: F,
    ) {
        self =
            Matrix2x6 {
                m11: f(self.m11, b.m11, c.m11).into(),
                m21: f(self.m21, b.m21, c.m21).into(),
                m12: f(self.m12, b.m12, c.m12).into(),
                m22: f(self.m22, b.m22, c.m22).into(),
                m13: f(self.m13, b.m13, c.m13).into(),
                m23: f(self.m23, b.m23, c.m23).into(),
                m14: f(self.m14, b.m14, c.m14).into(),
                m24: f(self.m24, b.m24, c.m24).into(),
                m15: f(self.m15, b.m15, c.m15).into(),
                m25: f(self.m25, b.m25, c.m25).into(),
                m16: f(self.m16, b.m16, c.m16).into(),
                m26: f(self.m26, b.m26, c.m26).into(),
            };
    }

    /// Sets every component to `f()` (one call per component, column-major). The closure's output
    /// converts `Into<T>`. Upstream: `fill_with` (`impl Fn() -> T`).
    #[cfg(feature: 'closures')]
    #[inline]
    fn fill_with<F, +Drop<F>, impl Func: core::ops::Fn<F, ()>, +Into<Func::Output, T>>(
        ref self: Matrix2x6<T>, f: F,
    ) {
        self =
            Matrix2x6 {
                m11: f().into(),
                m21: f().into(),
                m12: f().into(),
                m22: f().into(),
                m13: f().into(),
                m23: f().into(),
                m14: f().into(),
                m24: f().into(),
                m15: f().into(),
                m25: f().into(),
                m16: f().into(),
                m26: f().into(),
            };
    }

    /// Sets every component to `val`. Upstream: `fill`.
    #[inline(always)]
    fn fill(ref self: Matrix2x6<T>, val: T) {
        self =
            Matrix2x6 {
                m11: val,
                m21: val,
                m12: val,
                m22: val,
                m13: val,
                m23: val,
                m14: val,
                m24: val,
                m15: val,
                m25: val,
                m16: val,
                m26: val,
            };
    }

    /// Sets the 2 diagonal components to `val`, the others unchanged. Upstream: `fill_diagonal`.
    #[inline(always)]
    fn fill_diagonal(ref self: Matrix2x6<T>, val: T) {
        self =
            Matrix2x6 {
                m11: val,
                m21: self.m21,
                m12: self.m12,
                m22: val,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            };
    }

    /// Sets `self` to the identity: ones on the diagonal, zeros elsewhere (`fill(0)` then
    /// `fill_diagonal(1)`). Upstream: `fill_with_identity`.
    #[inline(always)]
    fn fill_with_identity(ref self: Matrix2x6<T>) {
        self =
            Matrix2x6 {
                m11: R::one(),
                m21: R::zero(),
                m12: R::zero(),
                m22: R::one(),
                m13: R::zero(),
                m23: R::zero(),
                m14: R::zero(),
                m24: R::zero(),
                m15: R::zero(),
                m25: R::zero(),
                m16: R::zero(),
                m26: R::zero(),
            };
    }

    /// Sets the 6 components of row `i` to `val`. Panics with `nalgebra: index out of bounds` for
    /// `i >= 2`. Upstream: `fill_row`.
    ///
    /// ONE `match` on `i` selects the literal: measured 2.1 times cheaper than one comparison per
    /// component (`bench_matrix4_fill_row__alt_per_component`).
    #[inline(always)]
    fn fill_row(ref self: Matrix2x6<T>, i: usize, val: T) {
        self = match i {
            0 => Matrix2x6 {
                m11: val,
                m21: self.m21,
                m12: val,
                m22: self.m22,
                m13: val,
                m23: self.m23,
                m14: val,
                m24: self.m24,
                m15: val,
                m25: self.m25,
                m16: val,
                m26: self.m26,
            },
            1 => Matrix2x6 {
                m11: self.m11,
                m21: val,
                m12: self.m12,
                m22: val,
                m13: self.m13,
                m23: val,
                m14: self.m14,
                m24: val,
                m15: self.m15,
                m25: val,
                m16: self.m16,
                m26: val,
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        };
    }

    /// Sets the 2 components of column `j` to `val`. Panics with `nalgebra: index out of bounds`
    /// for `j >= 6`. Upstream: `fill_column`.
    #[inline(always)]
    fn fill_column(ref self: Matrix2x6<T>, j: usize, val: T) {
        self = match j {
            0 => Matrix2x6 {
                m11: val,
                m21: val,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            },
            1 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: val,
                m22: val,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            },
            2 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: val,
                m23: val,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            },
            3 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: val,
                m24: val,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            },
            4 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: val,
                m25: val,
                m16: self.m16,
                m26: self.m26,
            },
            5 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: val,
                m26: val,
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        };
    }

    /// Sets every component `(i, j)` with `i >= j + shift` to `val`: the lower triangle with the
    /// diagonal for `shift = 0`, without it for `shift = 1`, leaving `shift - 1` subdiagonals as
    /// well above; nothing changes for `shift >= 2`. ONE `match` on `shift` selects the literal:
    /// measured 2.7 times cheaper than one threshold test per component
    /// (`bench_matrix4_fill_lower_triangle__alt_per_component`). Upstream: `fill_lower_triangle`.
    #[inline(always)]
    fn fill_lower_triangle(ref self: Matrix2x6<T>, val: T, shift: usize) {
        self = match shift {
            0 => Matrix2x6 {
                m11: val,
                m21: val,
                m12: self.m12,
                m22: val,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            },
            1 => Matrix2x6 {
                m11: self.m11,
                m21: val,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            },
            _ => self,
        };
    }

    /// Sets every component `(i, j)` with `j >= i + shift` to `val`: the upper triangle with the
    /// diagonal for `shift = 0`, without it for `shift = 1`, leaving `shift - 1` superdiagonals as
    /// well below; nothing changes for `shift >= 6`. ONE `match` on `shift` selects the literal.
    /// Upstream: `fill_upper_triangle`.
    #[inline(always)]
    fn fill_upper_triangle(ref self: Matrix2x6<T>, val: T, shift: usize) {
        self = match shift {
            0 => Matrix2x6 {
                m11: val,
                m21: self.m21,
                m12: val,
                m22: val,
                m13: val,
                m23: val,
                m14: val,
                m24: val,
                m15: val,
                m25: val,
                m16: val,
                m26: val,
            },
            1 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: val,
                m22: self.m22,
                m13: val,
                m23: val,
                m14: val,
                m24: val,
                m15: val,
                m25: val,
                m16: val,
                m26: val,
            },
            2 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: val,
                m23: self.m23,
                m14: val,
                m24: val,
                m15: val,
                m25: val,
                m16: val,
                m26: val,
            },
            3 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: val,
                m24: self.m24,
                m15: val,
                m25: val,
                m16: val,
                m26: val,
            },
            4 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: val,
                m25: self.m25,
                m16: val,
                m26: val,
            },
            5 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: val,
                m26: self.m26,
            },
            _ => self,
        };
    }

    /// Replaces row `i` by `row`, a `RowVector6`. Panics with `nalgebra: index out of bounds` for
    /// `i >= 2`. Upstream: `set_row`.
    #[inline(always)]
    fn set_row(ref self: Matrix2x6<T>, i: usize, row: RowVector6<T>) {
        self = match i {
            0 => Matrix2x6 {
                m11: row.x,
                m21: self.m21,
                m12: row.y,
                m22: self.m22,
                m13: row.z,
                m23: self.m23,
                m14: row.w,
                m24: self.m24,
                m15: row.a,
                m25: self.m25,
                m16: row.b,
                m26: self.m26,
            },
            1 => Matrix2x6 {
                m11: self.m11,
                m21: row.x,
                m12: self.m12,
                m22: row.y,
                m13: self.m13,
                m23: row.z,
                m14: self.m14,
                m24: row.w,
                m15: self.m15,
                m25: row.a,
                m16: self.m16,
                m26: row.b,
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        };
    }

    /// Replaces column `j` by `column`, a `Vector2`. Panics with `nalgebra: index out of bounds`
    /// for `j >= 6`. Upstream: `set_column`.
    #[inline(always)]
    fn set_column(ref self: Matrix2x6<T>, j: usize, column: Vector2<T>) {
        self = match j {
            0 => Matrix2x6 {
                m11: column.x,
                m21: column.y,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            },
            1 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: column.x,
                m22: column.y,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            },
            2 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: column.x,
                m23: column.y,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            },
            3 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: column.x,
                m24: column.y,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            },
            4 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: column.x,
                m25: column.y,
                m16: self.m16,
                m26: self.m26,
            },
            5 => Matrix2x6 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: column.x,
                m26: column.y,
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        };
    }

    /// Replaces the diagonal by `diag`, a `Vector2` (upstream requires the length `min(R, C)` = 2).
    /// Upstream: `set_diagonal`.
    #[inline(always)]
    fn set_diagonal(ref self: Matrix2x6<T>, diag: Vector2<T>) {
        self =
            Matrix2x6 {
                m11: diag.x,
                m21: self.m21,
                m12: self.m12,
                m22: diag.y,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            };
    }

    /// Replaces the first `min(diag.len(), 2)` diagonal components by the values of `diag` (the
    /// extra values are ignored, like upstream's `take`), the others unchanged. Upstream:
    /// `set_partial_diagonal` (an iterator; a `Span` here).
    #[inline(always)]
    fn set_partial_diagonal(ref self: Matrix2x6<T>, diag: Span<T>) {
        let len = diag.len();
        self =
            Matrix2x6 {
                m11: if len > 0 {
                    *diag[0]
                } else {
                    self.m11
                },
                m21: self.m21,
                m12: self.m12,
                m22: if len > 1 {
                    *diag[1]
                } else {
                    self.m22
                },
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
                m16: self.m16,
                m26: self.m26,
            };
    }

    /// Sets `self` to `other` (a `Matrix2x6`: upstream requires the same shape). Upstream:
    /// `copy_from`.
    #[inline(always)]
    fn copy_from(ref self: Matrix2x6<T>, other: Matrix2x6<T>) {
        self = other;
    }

    /// Sets `self` to the 12 values of `slice` in column-major order (`from_column_slice`). Panics
    /// with `nalgebra: wrong slice length` unless `slice.len() == 12`. Upstream: `copy_from_slice`
    /// (`&[T]`).
    #[inline(always)]
    fn copy_from_slice(ref self: Matrix2x6<T>, slice: Span<T>) {
        self = Self::from_column_slice(slice);
    }

    /// Sets `self` to the transpose of `other`, a `Matrix6x2`. Exact. Upstream: `tr_copy_from`.
    #[inline(always)]
    fn tr_copy_from(ref self: Matrix2x6<T>, other: Matrix6x2<T>) {
        self =
            Matrix2x6 {
                m11: other.m11,
                m21: other.m12,
                m12: other.m21,
                m22: other.m22,
                m13: other.m31,
                m23: other.m32,
                m14: other.m41,
                m24: other.m42,
                m15: other.m51,
                m25: other.m52,
                m16: other.m61,
                m26: other.m62,
            };
    }

    /// Exchanges the components at `row_cols1` and `row_cols2` (`(row, column)`). Panics with
    /// `nalgebra: index out of bounds` when either is out of the shape. Upstream: `swap`.
    #[inline]
    fn swap(ref self: Matrix2x6<T>, row_cols1: (usize, usize), row_cols2: (usize, usize)) {
        let a = MatrixIndex::index(self, row_cols1);
        let b = MatrixIndex::index(self, row_cols2);
        self =
            Matrix2x6EditTrait::replace(
                Matrix2x6EditTrait::replace(self, row_cols1, b), row_cols2, a,
            );
    }

    /// Exchanges rows `irow1` and `irow2`. Panics with `nalgebra: index out of bounds` when either
    /// is `>= 2`. Upstream: `swap_rows`.
    ///
    /// Two reads and two writes of a row (one `match` each). ONE nested `match` on both rows is 940
    /// gas (15%) cheaper on `Matrix3` (`bench_matrix3_swap_rows__alt_pair_match`) but generates R²
    /// whole-shape literals (about 40 000 lines over the 36 shapes, per method): kept as a
    /// benchmark.
    #[inline]
    fn swap_rows(ref self: Matrix2x6<T>, irow1: usize, irow2: usize) {
        let a = Matrix2x6EditTrait::row_at(self, irow1);
        let b = Matrix2x6EditTrait::row_at(self, irow2);
        Self::set_row(ref self, irow1, b);
        Self::set_row(ref self, irow2, a);
    }

    /// Exchanges columns `icol1` and `icol2`. Panics with `nalgebra: index out of bounds` when
    /// either is `>= 6`. Upstream: `swap_columns`.
    #[inline]
    fn swap_columns(ref self: Matrix2x6<T>, icol1: usize, icol2: usize) {
        let a = Matrix2x6EditTrait::column_at(self, icol1);
        let b = Matrix2x6EditTrait::column_at(self, icol2);
        Self::set_column(ref self, icol1, b);
        Self::set_column(ref self, icol2, a);
    }

    /// `self = -self`. Exact; panics on overflow (`-MIN`). Upstream: `neg_mut`.
    #[inline(always)]
    fn neg_mut(ref self: Matrix2x6<T>) {
        self = -self;
    }

    /// `self = self.scale(k)`, each component floored once. Panics on overflow. Upstream:
    /// `scale_mut`.
    #[inline(always)]
    fn scale_mut(ref self: Matrix2x6<T>, k: T) {
        self = Self::scale(self, k);
    }

    /// `self = self.unscale(k)`, each component correctly rounded. Panics on a zero `k` and on
    /// overflow. Upstream: `unscale_mut`.
    #[inline(always)]
    fn unscale_mut(ref self: Matrix2x6<T>, k: T) {
        self = Self::unscale(self, k);
    }

    /// Normalizes `self` in place (`self = self.normalize()`, bit-identical) and returns the norm
    /// it had. Panics with a division by zero when the norm is zero. Upstream: `normalize_mut`.
    #[inline(always)]
    fn normalize_mut(ref self: Matrix2x6<T>) -> T {
        let n = Self::norm(self);
        self = Self::unscale(self, n);
        n
    }

    /// Normalizes `self` in place and returns `Some` of the norm it had, or leaves it unchanged and
    /// returns `None` when that norm is `<= min_norm`. Upstream: `try_normalize_mut`.
    #[inline(always)]
    fn try_normalize_mut(ref self: Matrix2x6<T>, min_norm: T) -> Option<T> {
        let n = Self::norm(self);
        if n <= min_norm {
            return None;
        }
        self = Self::unscale(self, n);
        Some(n)
    }

    /// Scales `self` to the norm `magnitude`: `self.scale(magnitude / norm)`, the ratio rounded to
    /// nearest (like `try_set_magnitude`). Panics with a division by zero when the norm is zero
    /// (upstream's floats give NaN). Upstream: `set_magnitude`.
    #[inline(always)]
    fn set_magnitude(ref self: Matrix2x6<T>, magnitude: T) {
        let n = Self::norm(self);
        self = Self::scale(self, R::div(magnitude, n));
    }

    /// `self = self.add_scalar(k)`. Exact; panics on overflow. Upstream: `add_scalar_mut`.
    #[inline(always)]
    fn add_scalar_mut(ref self: Matrix2x6<T>, k: T) {
        self = Self::add_scalar(self, k);
    }

    /// Alias of `component_mul_assign` (deprecated upstream). Upstream: `component_mul_mut`.
    #[inline(always)]
    fn component_mul_mut(ref self: Matrix2x6<T>, rhs: Matrix2x6<T>) {
        Self::component_mul_assign(ref self, rhs);
    }

    /// Alias of `component_div_assign` (deprecated upstream). Upstream: `component_div_mut`.
    #[inline(always)]
    fn component_div_mut(ref self: Matrix2x6<T>, rhs: Matrix2x6<T>) {
        Self::component_div_assign(ref self, rhs);
    }

    /// Conjugates every component in place: nothing changes for a real scalar. Upstream:
    /// `conjugate_mut`.
    #[inline(always)]
    fn conjugate_mut(ref self: Matrix2x6<T>) {
        self = Self::conjugate(self);
    }

    /// Writes the transpose of `self` into `out`, a `Matrix6x2`. Exact. Upstream: `transpose_to`.
    #[inline(always)]
    fn transpose_to(self: Matrix2x6<T>, ref out: Matrix6x2<T>) {
        out = Self::transpose(self);
    }

    /// Writes the adjoint of `self` (its transpose for a real scalar) into `out`, a `Matrix6x2`.
    /// Exact. Upstream: `adjoint_to`.
    #[inline(always)]
    fn adjoint_to(self: Matrix2x6<T>, ref out: Matrix6x2<T>) {
        out = Self::transpose(self);
    }

    /// Writes the adjoint of `self` (deprecated upstream alias of `adjoint_to`) into `out`, a
    /// `Matrix6x2`. Exact. Upstream: `conjugate_transpose_to`.
    #[inline(always)]
    fn conjugate_transpose_to(self: Matrix2x6<T>, ref out: Matrix6x2<T>) {
        out = Self::transpose(self);
    }

    /// Writes the sum `self + rhs` into `out`. Exact; panics on overflow. Upstream: `add_to`.
    #[inline(always)]
    fn add_to(self: Matrix2x6<T>, rhs: Matrix2x6<T>, ref out: Matrix2x6<T>) {
        out = self + rhs;
    }

    /// Writes the difference `self - rhs` into `out`. Exact; panics on overflow. Upstream:
    /// `sub_to`.
    #[inline(always)]
    fn sub_to(self: Matrix2x6<T>, rhs: Matrix2x6<T>, ref out: Matrix2x6<T>) {
        out = self - rhs;
    }

    /// The norm `norm` of `self`: `EuclideanNorm {}` (`norm`), `LpNorm { p }` (`lp_norm(p)`),
    /// `OneNorm {}` (`one_norm`) or `UniformNorm {}` (`amax`), through their `Norm` impls (static
    /// dispatch). Upstream: `apply_norm` (`&impl Norm<T>`; the markers are `Copy` values here).
    #[inline]
    fn apply_norm<N, +Drop<N>, impl Nm: Norm<N, Matrix2x6<T>, T>>(
        self: Matrix2x6<T>, norm: N,
    ) -> T {
        Nm::norm(@norm, self)
    }

    /// The distance between `self` and `rhs` in the norm `norm` (see `apply_norm`; the Euclidean
    /// one is the fused `metric_distance`, the others the norm of the exact difference). Upstream:
    /// `apply_metric_distance`.
    #[inline]
    fn apply_metric_distance<N, +Drop<N>, impl Nm: Norm<N, Matrix2x6<T>, T>>(
        self: Matrix2x6<T>, rhs: Matrix2x6<T>, norm: N,
    ) -> T {
        Nm::metric_distance(@norm, self, rhs)
    }

    /// The number of rows, 2. Upstream: `nrows`.
    #[inline(always)]
    fn nrows(self: Matrix2x6<T>) -> usize {
        2
    }

    /// The number of columns, 6. Upstream: `ncols`.
    #[inline(always)]
    fn ncols(self: Matrix2x6<T>) -> usize {
        6
    }

    /// `(nrows, ncols)`, `(2, 6)`. Upstream: `shape`.
    #[inline(always)]
    fn shape(self: Matrix2x6<T>) -> (usize, usize) {
        (2, 6)
    }

    /// Whether the shape is square: `false`. Upstream: `is_square`.
    #[inline(always)]
    fn is_square(self: Matrix2x6<T>) -> bool {
        false
    }

    /// The `(row, column)` of the `i`-th component in column-major order: `(i % 2, i / 2)`, one
    /// `DivRem` (no bounds check, like upstream). Upstream: `vector_to_matrix_index`.
    #[inline(always)]
    fn vector_to_matrix_index(self: Matrix2x6<T>, i: usize) -> (usize, usize) {
        let (j, i) = DivRem::div_rem(i, 2);
        (i, j)
    }

    /// Row `i`, a `RowVector6` (an owned copy: Cairo has no borrowed views). Panics with `nalgebra:
    /// index out of bounds` for `i >= 2`. ONE `match` on `i` selects the literal (the private
    /// `row_at` of `swap_rows`). Upstream: `row` (a view).
    #[inline(always)]
    fn row(self: Matrix2x6<T>, i: usize) -> RowVector6<T> {
        Matrix2x6EditTrait::row_at(self, i)
    }

    /// Column `j`, a `Vector2` (an owned copy: Cairo has no borrowed views). Panics with `nalgebra:
    /// index out of bounds` for `j >= 6`. ONE `match` on `j` selects the literal (the private
    /// `column_at` of `swap_columns`). Upstream: `column` (a view).
    #[inline(always)]
    fn column(self: Matrix2x6<T>, j: usize) -> Vector2<T> {
        Matrix2x6EditTrait::column_at(self, j)
    }

    /// The upper triangle of `self` (the diagonal included), the components below the diagonal set
    /// to zero. Exact. Upstream: `upper_triangle`.
    #[inline(always)]
    fn upper_triangle(self: Matrix2x6<T>) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: self.m11,
            m21: R::zero(),
            m12: self.m12,
            m22: self.m22,
            m13: self.m13,
            m23: self.m23,
            m14: self.m14,
            m24: self.m24,
            m15: self.m15,
            m25: self.m25,
            m16: self.m16,
            m26: self.m26,
        }
    }

    /// The lower triangle of `self` (the diagonal included), the components above the diagonal set
    /// to zero. Exact. Upstream: `lower_triangle`.
    #[inline(always)]
    fn lower_triangle(self: Matrix2x6<T>) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: self.m11,
            m21: self.m21,
            m12: R::zero(),
            m22: self.m22,
            m13: R::zero(),
            m23: R::zero(),
            m14: R::zero(),
            m24: R::zero(),
            m15: R::zero(),
            m25: R::zero(),
            m16: R::zero(),
            m26: R::zero(),
        }
    }

    /// The 2x6 matrix whose 2 rows are the given vectors, each a `Vector6` of the row's 6
    /// components (the argument form of the former `Matrix2/3/4::from_rows`, used by `linalg`).
    /// Exact. Upstream: `from_rows` (a slice of row vectors).
    #[inline(always)]
    fn from_rows(r1: Vector6<T>, r2: Vector6<T>) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: r1.x,
            m21: r2.x,
            m12: r1.y,
            m22: r2.y,
            m13: r1.z,
            m23: r2.z,
            m14: r1.w,
            m24: r2.w,
            m15: r1.a,
            m25: r2.a,
            m16: r1.b,
            m26: r2.b,
        }
    }

    /// The 2x6 matrix whose 6 columns are the given `Vector2`s. Exact. Upstream: `from_columns` (a
    /// slice of column vectors).
    #[inline(always)]
    fn from_columns(
        c1: Vector2<T>,
        c2: Vector2<T>,
        c3: Vector2<T>,
        c4: Vector2<T>,
        c5: Vector2<T>,
        c6: Vector2<T>,
    ) -> Matrix2x6<T> {
        Matrix2x6 {
            m11: c1.x,
            m21: c1.y,
            m12: c2.x,
            m22: c2.y,
            m13: c3.x,
            m23: c3.y,
            m14: c4.x,
            m24: c4.y,
            m15: c5.x,
            m25: c5.y,
            m16: c6.x,
            m26: c6.y,
        }
    }

    /// Whether the columns of `self` are orthonormal: `selfᵀ * self` (fused `tr_mul`, one
    /// rounding per component) is the 6x6 identity within `ulps`. Upstream: `is_orthogonal` (`eps`:
    /// here a tolerance in ulp, DESIGN D3).
    #[inline(always)]
    fn is_orthogonal(self: Matrix2x6<T>, ulps: u64) -> bool {
        Matrix6Trait::is_identity(MatrixTrMul::tr_mul(self, self), ulps)
    }

    /// `self` with a row of `val` inserted at index `i` (`i <= 2`), a `Matrix3x6`. Panics with
    /// `nalgebra: index out of bounds` for `i > 2`. Upstream: `insert_row`.
    fn insert_row(self: Matrix2x6<T>, i: usize, val: T) -> Matrix3x6<T> {
        match i {
            0 => Matrix3x6 {
                m11: val,
                m21: self.m11,
                m31: self.m21,
                m12: val,
                m22: self.m12,
                m32: self.m22,
                m13: val,
                m23: self.m13,
                m33: self.m23,
                m14: val,
                m24: self.m14,
                m34: self.m24,
                m15: val,
                m25: self.m15,
                m35: self.m25,
                m16: val,
                m26: self.m16,
                m36: self.m26,
            },
            1 => Matrix3x6 {
                m11: self.m11,
                m21: val,
                m31: self.m21,
                m12: self.m12,
                m22: val,
                m32: self.m22,
                m13: self.m13,
                m23: val,
                m33: self.m23,
                m14: self.m14,
                m24: val,
                m34: self.m24,
                m15: self.m15,
                m25: val,
                m35: self.m25,
                m16: self.m16,
                m26: val,
                m36: self.m26,
            },
            2 => Matrix3x6 {
                m11: self.m11,
                m21: self.m21,
                m31: val,
                m12: self.m12,
                m22: self.m22,
                m32: val,
                m13: self.m13,
                m23: self.m23,
                m33: val,
                m14: self.m14,
                m24: self.m24,
                m34: val,
                m15: self.m15,
                m25: self.m25,
                m35: val,
                m16: self.m16,
                m26: self.m26,
                m36: val,
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    /// `self` without its row `i`, a `RowVector6`. Panics with `nalgebra: index out of bounds` for
    /// `i >= 2`. Upstream: `remove_row`.
    #[inline(always)]
    fn remove_row(self: Matrix2x6<T>, i: usize) -> RowVector6<T> {
        match i {
            0 => RowVector6 {
                x: self.m21, y: self.m22, z: self.m23, w: self.m24, a: self.m25, b: self.m26,
            },
            1 => RowVector6 {
                x: self.m11, y: self.m12, z: self.m13, w: self.m14, a: self.m15, b: self.m16,
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    /// `self` without its column `i`, a `Matrix2x5`. Panics with `nalgebra: index out of bounds`
    /// for `i >= 6`. Upstream: `remove_column`.
    #[inline(always)]
    fn remove_column(self: Matrix2x6<T>, i: usize) -> Matrix2x5<T> {
        match i {
            0 => Matrix2x5 {
                m11: self.m12,
                m21: self.m22,
                m12: self.m13,
                m22: self.m23,
                m13: self.m14,
                m23: self.m24,
                m14: self.m15,
                m24: self.m25,
                m15: self.m16,
                m25: self.m26,
            },
            1 => Matrix2x5 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m13,
                m22: self.m23,
                m13: self.m14,
                m23: self.m24,
                m14: self.m15,
                m24: self.m25,
                m15: self.m16,
                m25: self.m26,
            },
            2 => Matrix2x5 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m14,
                m23: self.m24,
                m14: self.m15,
                m24: self.m25,
                m15: self.m16,
                m25: self.m26,
            },
            3 => Matrix2x5 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m15,
                m24: self.m25,
                m15: self.m16,
                m25: self.m26,
            },
            4 => Matrix2x5 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m16,
                m25: self.m26,
            },
            5 => Matrix2x5 {
                m11: self.m11,
                m21: self.m21,
                m12: self.m12,
                m22: self.m22,
                m13: self.m13,
                m23: self.m23,
                m14: self.m14,
                m24: self.m24,
                m15: self.m15,
                m25: self.m25,
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// The operations of `Matrix2x6<T>` that need `Transcendental` (inverse trigonometry, `exp`, `ln`):
/// a scalar may implement `Real` only.
#[generate_trait]
pub impl Matrix2x6AngleImpl<
    T,
    impl R: Real<T>,
    impl Tr: Transcendental<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix2x6AngleTrait<T> {
    /// The angle between `self` and `other` seen as vectors of the Frobenius inner product, in `[0,
    /// π]` (up to the rounding of `atan2`); `0` when one of them is zero. Computed as `2 *
    /// atan2(|u - v|, |u + v|)` on the normalized `u`, `v` (Kahan): unlike upstream's `acos(dot /
    /// (|a| *
    /// |b|))` it cannot overflow on long inputs and stays accurate for nearly parallel ones. Panics
    /// when a norm does not fit. Upstream: `angle`.
    fn angle(self: Matrix2x6<T>, other: Matrix2x6<T>) -> T {
        let n1 = Matrix2x6Trait::norm(self);
        let n2 = Matrix2x6Trait::norm(other);
        if n1 == R::zero() || n2 == R::zero() {
            return R::zero();
        }
        let u = Matrix2x6Trait::unscale(self, n1);
        let v = Matrix2x6Trait::unscale(other, n2);
        let half = Tr::atan2(Matrix2x6Trait::metric_distance(u, v), Matrix2x6Trait::norm(u + v));
        half + half
    }

    /// The entrywise Lp norm `(Σ |a|^p)^(1/p)`. `p = 1` is the exact sum of the absolute values
    /// and `p = 2` the fused `norm` (both exact up to their one rounding); above, the components
    /// are first divided by the largest absolute value `m` (so no power can overflow), `Σ (|a| /
    /// m)^p`
    /// is summed (`p` floored products each), and the root is `m * exp(ln(Σ) / p)`: a few ulp
    /// relative to the result, the rounding of `exp` / `ln`. Panics with `nalgebra: lp_norm needs p
    /// >= 1` for `p < 1` (upstream returns meaningless values: an infinite root for `p = 0`).
    /// Upstream: `lp_norm`.
    fn lp_norm(self: Matrix2x6<T>, p: i32) -> T {
        if p < 1 {
            core::panic_with_felt252(errors::LP_NORM_P);
        }
        if p == 1 {
            return R::abs(self.m11)
                + R::abs(self.m21)
                + R::abs(self.m12)
                + R::abs(self.m22)
                + R::abs(self.m13)
                + R::abs(self.m23)
                + R::abs(self.m14)
                + R::abs(self.m24)
                + R::abs(self.m15)
                + R::abs(self.m25)
                + R::abs(self.m16)
                + R::abs(self.m26);
        }
        if p == 2 {
            return Matrix2x6Trait::norm(self);
        }
        let m = Matrix2x6Trait::amax(self);
        if m == R::zero() {
            return R::zero();
        }
        let r = Matrix2x6Trait::unscale(Matrix2x6Trait::abs(self), m);
        let q: u32 = p.try_into().unwrap();
        let s = Powi::powi(r.m11, q)
            + Powi::powi(r.m21, q)
            + Powi::powi(r.m12, q)
            + Powi::powi(r.m22, q)
            + Powi::powi(r.m13, q)
            + Powi::powi(r.m23, q)
            + Powi::powi(r.m14, q)
            + Powi::powi(r.m24, q)
            + Powi::powi(r.m15, q)
            + Powi::powi(r.m25, q)
            + Powi::powi(r.m16, q)
            + Powi::powi(r.m26, q);
        m * Tr::exp(R::div(Tr::ln(s), R::from_int(p)))
    }
}
