// Generated by tools/shapegen/shapegen.py: do not edit by hand. Template:
// tools/shapegen/shapes.py.
//! `Matrix3x2`: a statically sized 3x2 matrix (upstream `nalgebra::Matrix3x2`).
//!
//! Every sum of products goes through a fused `Real` kernel: one rounding (floor) and one overflow
//! check per output scalar. Operators (`+`, `-`, unary `-` and their assigning forms) are
//! implemented in this module, so they need no import; the other operations are methods of
//! `Matrix3x2Trait`, the products with every conformable shape `MatrixMul::mul_mat` (`self * rhs`)
//! and `MatrixTrMul::tr_mul` (`selfᵀ * rhs`).

pub use nalgebra_blocks::base::matrix_kronecker::{
    Matrix3x2KroneckerMatrix1, Matrix3x2KroneckerMatrix2, Matrix3x2KroneckerMatrix2x3,
    Matrix3x2KroneckerRowVector2, Matrix3x2KroneckerRowVector3, Matrix3x2KroneckerVector2,
};
pub use nalgebra_blocks::base::matrix_view::{
    Matrix3x2FixedColumnsMatrix3x2, Matrix3x2FixedColumnsVector3, Matrix3x2FixedRowsMatrix2,
    Matrix3x2FixedRowsMatrix3x2, Matrix3x2FixedRowsRowVector2,
};
pub use nalgebra_norm::base::norm::{
    Matrix3x2EuclideanNorm, Matrix3x2LpNorm, Matrix3x2OneNorm, Matrix3x2UniformNorm,
};
pub use nalgebra_static3::base::matrix3x2::*;
pub use nalgebra_types3::base::matrix3x2::{
    Matrix3x2, Matrix3x2Add, Matrix3x2AddAssign, Matrix3x2Bounded, Matrix3x2DivAssignScalar,
    Matrix3x2FromColumnArrays, Matrix3x2IndexLinear, Matrix3x2IndexPair, Matrix3x2IntoColumnArrays,
    Matrix3x2MatrixIndexLinear, Matrix3x2MatrixIndexPair, Matrix3x2MulAssignScalar,
    Matrix3x2MulMatrix2, Matrix3x2MulMatrix2x3, Matrix3x2MulPoint, Matrix3x2MulRotation2,
    Matrix3x2MulVector2, Matrix3x2Neg, Matrix3x2PartialOrd, Matrix3x2Sub, Matrix3x2SubAssign,
    Matrix3x2Sum, Matrix3x2SumSnapshot, Matrix3x2TrMulMatrix3, Matrix3x2TrMulMatrix3x2,
    Matrix3x2TrMulVector3,
};
pub use nalgebra_types4::base::matrix2x4::Matrix3x2MulMatrix2x4;
pub use nalgebra_types4::base::matrix3x4::Matrix3x2TrMulMatrix3x4;
pub use nalgebra_types5::base::matrix2x5::Matrix3x2MulMatrix2x5;
pub use nalgebra_types5::base::matrix3x5::Matrix3x2TrMulMatrix3x5;
pub use nalgebra_types6::base::matrix2x6::Matrix3x2MulMatrix2x6;
pub use nalgebra_types6::base::matrix3x6::Matrix3x2TrMulMatrix3x6;
pub use nalgebra_views::base::matrix_view::{
    Matrix3x2FixedViewMatrix1, Matrix3x2FixedViewMatrix2, Matrix3x2FixedViewMatrix3x2,
    Matrix3x2FixedViewRowVector2, Matrix3x2FixedViewVector2, Matrix3x2FixedViewVector3,
};
pub use crate::root::matrix_inf_sup::Matrix3x2InfSup;
