// Generated by tools/shapegen/shapegen.py: do not edit by hand. Templates:
// tools/shapegen/library.py, shapes.py; kernels: tools/shapegen/specialisations/matrix3.cairo.
//! `Matrix3`: a statically sized 3x3 matrix (upstream `nalgebra::Matrix3`).
//!
//! Every sum of products goes through a fused `Real` kernel: one rounding (floor) and one overflow
//! check per output scalar. Operators (`+`, `-`, unary `-`, `*` between matrices and their
//! assigning forms) are implemented in this module, so they need no import; the other operations
//! are methods of `Matrix3Trait`, the products with every conformable shape `MatrixMul::mul_mat`
//! (`self * rhs`) and `MatrixTrMul::tr_mul` (`selfᵀ * rhs`).

use core::num::traits::{Bounded, One};
use core::ops::{AddAssign, IndexView, MulAssign, SubAssign};
use simba::scalar::{Real, Transcendental};
use crate::geometry::quaternion::ApproxEqTrait;
use super::errors;
use super::kernels::Powi;
use super::matrix3x2::Matrix3x2;
use super::matrix3x4::Matrix3x4;
use super::matrix3x5::Matrix3x5;
use super::matrix3x6::Matrix3x6;
use super::matrix4::Matrix4;
use super::matrix_index::MatrixIndex;
use super::matrix_mul::MatrixMul;
use super::matrix_tr_mul::MatrixTrMul;
use super::point3::Point3;
use super::sym_matrix3::SymMatrix3;
use super::vector3::Vector3;

#[cfg(test)]
mod tests;

/// A 3x3 matrix. `mRC` is the component at row `R`, column `C`.
///
/// Fields are declared in column-major order, so `Serde` matches upstream's storage order, while
/// `new` takes its arguments in row-major order like upstream.
#[derive(Copy, Drop, PartialEq, Serde, Default, Debug, Hash)]
pub struct Matrix3<T> {
    pub m11: T,
    pub m21: T,
    pub m31: T,
    pub m12: T,
    pub m22: T,
    pub m32: T,
    pub m13: T,
    pub m23: T,
    pub m33: T,
}

/// Methods of `Matrix3<T>` for any `Real` scalar.
#[generate_trait]
pub impl Matrix3Impl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix3Trait<T> {
    // --- constructors --------------------------------------------------------------------------

    /// The matrix with the given components, in ROW-major order. Upstream: `Matrix3::new`.
    #[inline(always)]
    fn new(m11: T, m12: T, m13: T, m21: T, m22: T, m23: T, m31: T, m32: T, m33: T) -> Matrix3<T> {
        Matrix3 { m11, m21, m31, m12, m22, m32, m13, m23, m33 }
    }

    /// The zero matrix. Upstream: `Matrix3::zeros`.
    #[inline(always)]
    fn zeros() -> Matrix3<T> {
        Matrix3 {
            m11: R::zero(),
            m21: R::zero(),
            m31: R::zero(),
            m12: R::zero(),
            m22: R::zero(),
            m32: R::zero(),
            m13: R::zero(),
            m23: R::zero(),
            m33: R::zero(),
        }
    }

    /// The identity matrix. Upstream: `Matrix3::identity`.
    #[inline(always)]
    fn identity() -> Matrix3<T> {
        Matrix3 {
            m11: R::one(),
            m21: R::zero(),
            m31: R::zero(),
            m12: R::zero(),
            m22: R::one(),
            m32: R::zero(),
            m13: R::zero(),
            m23: R::zero(),
            m33: R::one(),
        }
    }

    /// The diagonal matrix `diag(d)`. Upstream: `Matrix3::from_diagonal`.
    #[inline(always)]
    fn from_diagonal(d: Vector3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: d.x,
            m21: R::zero(),
            m31: R::zero(),
            m12: R::zero(),
            m22: d.y,
            m32: R::zero(),
            m13: R::zero(),
            m23: R::zero(),
            m33: d.z,
        }
    }

    /// The matrix `e * I`. Upstream: `Matrix3::from_diagonal_element`.
    #[inline(always)]
    fn from_diagonal_element(e: T) -> Matrix3<T> {
        Matrix3 {
            m11: e,
            m21: R::zero(),
            m31: R::zero(),
            m12: R::zero(),
            m22: e,
            m32: R::zero(),
            m13: R::zero(),
            m23: R::zero(),
            m33: e,
        }
    }

    /// The matrix whose columns are the given vectors. Upstream: `Matrix3::from_columns`.
    #[inline(always)]
    fn from_columns(c1: Vector3<T>, c2: Vector3<T>, c3: Vector3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: c1.x,
            m21: c1.y,
            m31: c1.z,
            m12: c2.x,
            m22: c2.y,
            m32: c2.z,
            m13: c3.x,
            m23: c3.y,
            m33: c3.z,
        }
    }

    /// The matrix whose rows are the given vectors. Upstream: `Matrix3::from_rows`.
    #[inline(always)]
    fn from_rows(r1: Vector3<T>, r2: Vector3<T>, r3: Vector3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: r1.x,
            m21: r2.x,
            m31: r3.x,
            m12: r1.y,
            m22: r2.y,
            m32: r3.y,
            m13: r1.z,
            m23: r2.z,
            m33: r3.z,
        }
    }

    /// The skew-symmetric matrix `[v]×` such that `[v]× * u = v × u`. Exact; panics on the
    /// scalar's `MIN`.
    /// Upstream: `Vector3::cross_matrix`.
    #[inline(always)]
    fn cross_matrix(v: Vector3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: R::zero(),
            m21: v.z,
            m31: -v.y,
            m12: -v.z,
            m22: R::zero(),
            m32: v.x,
            m13: v.y,
            m23: -v.x,
            m33: R::zero(),
        }
    }

    // --- accessors -----------------------------------------------------------------------------

    /// The diagonal. Upstream: `diagonal`.
    #[inline(always)]
    fn diagonal(self: Matrix3<T>) -> Vector3<T> {
        Vector3 { x: self.m11, y: self.m22, z: self.m33 }
    }

    // --- exact operations ----------------------------------------------------------------------

    /// The transpose. Exact. Upstream: `transpose`.
    #[inline(always)]
    fn transpose(self: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: self.m11,
            m21: self.m12,
            m31: self.m13,
            m12: self.m21,
            m22: self.m22,
            m32: self.m23,
            m13: self.m31,
            m23: self.m32,
            m33: self.m33,
        }
    }

    /// Sum of the diagonal. Exact; panics on overflow. Upstream: `trace`.
    #[inline(always)]
    fn trace(self: Matrix3<T>) -> T {
        self.m11 + self.m22 + self.m33
    }

    /// Component-wise absolute value. Panics on the scalar's `MIN`. Upstream: `abs`.
    #[inline(always)]
    fn abs(self: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: R::abs(self.m11),
            m21: R::abs(self.m21),
            m31: R::abs(self.m31),
            m12: R::abs(self.m12),
            m22: R::abs(self.m22),
            m32: R::abs(self.m32),
            m13: R::abs(self.m13),
            m23: R::abs(self.m23),
            m33: R::abs(self.m33),
        }
    }

    // --- products ------------------------------------------------------------------------------

    /// `self * k`: each component is one floored product. Panics on overflow.
    /// Upstream: `self * k`.
    #[inline(always)]
    fn scale(self: Matrix3<T>, k: T) -> Matrix3<T> {
        Matrix3 {
            m11: self.m11 * k,
            m21: self.m21 * k,
            m31: self.m31 * k,
            m12: self.m12 * k,
            m22: self.m22 * k,
            m32: self.m32 * k,
            m13: self.m13 * k,
            m23: self.m23 * k,
            m33: self.m33 * k,
        }
    }

    /// Component-wise (Hadamard) product: each component is one floored product. Panics on
    /// overflow. Upstream: `component_mul`.
    #[inline(always)]
    fn component_mul(self: Matrix3<T>, rhs: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: self.m11 * rhs.m11,
            m21: self.m21 * rhs.m21,
            m31: self.m31 * rhs.m31,
            m12: self.m12 * rhs.m12,
            m22: self.m22 * rhs.m22,
            m32: self.m32 * rhs.m32,
            m13: self.m13 * rhs.m13,
            m23: self.m23 * rhs.m23,
            m33: self.m33 * rhs.m33,
        }
    }

    // --- norms ---------------------------------------------------------------------------------

    /// Squared Frobenius norm: the 9 squares are accumulated exactly (wide accumulator) and
    /// rounded once. Panics on overflow. Upstream: `norm_squared`.
    #[inline(always)]
    fn norm_squared(self: Matrix3<T>) -> T {
        let w = R::wide_add_prod(R::wide_zero(), self.m11, self.m11);
        let w = R::wide_add_prod(w, self.m21, self.m21);
        let w = R::wide_add_prod(w, self.m31, self.m31);
        let w = R::wide_add_prod(w, self.m12, self.m12);
        let w = R::wide_add_prod(w, self.m22, self.m22);
        let w = R::wide_add_prod(w, self.m32, self.m32);
        let w = R::wide_add_prod(w, self.m13, self.m13);
        let w = R::wide_add_prod(w, self.m23, self.m23);
        R::wide_rescale(R::wide_add_prod(w, self.m33, self.m33))
    }

    /// Frobenius norm: square root of the exact, unscaled sum of squares (one rounding, no
    /// intermediate overflow: only the result must fit). Upstream: `norm`.
    #[inline(always)]
    fn norm(self: Matrix3<T>) -> T {
        let w = R::wide_add_prod(R::wide_zero(), self.m11, self.m11);
        let w = R::wide_add_prod(w, self.m21, self.m21);
        let w = R::wide_add_prod(w, self.m31, self.m31);
        let w = R::wide_add_prod(w, self.m12, self.m12);
        let w = R::wide_add_prod(w, self.m22, self.m22);
        let w = R::wide_add_prod(w, self.m32, self.m32);
        let w = R::wide_add_prod(w, self.m13, self.m13);
        let w = R::wide_add_prod(w, self.m23, self.m23);
        R::wide_sqrt(R::wide_add_prod(w, self.m33, self.m33))
    }

    // --- determinant and inverse ---------------------------------------------------------------

    /// The determinant, by cofactor expansion along the first row: 3 `diff_prod` (2x2 minors,
    /// one rounding each) then one `sum_prod3` (second rounding). The error against the exact
    /// floor is at most `|m11| + |m12| + |m13| + 1` ulp (values, not raw: 4 ulp for a rotation).
    /// Panics on overflow. Upstream: `determinant`.
    fn determinant(self: Matrix3<T>) -> T {
        R::sum_prod3(
            self.m11,
            R::diff_prod(self.m22, self.m33, self.m23, self.m32),
            self.m12,
            R::diff_prod(self.m23, self.m31, self.m21, self.m33),
            self.m13,
            R::diff_prod(self.m21, self.m32, self.m22, self.m31),
        )
    }

    /// The inverse, or `None` when the matrix is singular. Upstream: `try_inverse`.
    ///
    /// Singularity criterion, like upstream: the computed determinant is EXACTLY zero (no
    /// epsilon). The zero matrix is singular. A nearly singular matrix is inverted with the
    /// precision its conditioning allows, and panics with the scalar's overflow error when a
    /// component of the inverse does not fit.
    ///
    /// Algorithm: `adjugate / determinant`, one division per component (a single reciprocal
    /// followed by 9 multiplications is 15 % cheaper but loses the low bits of `1 / det` when
    /// `|det| >> 1`: up to 900 ulp on the oracle's `medium` matrices, against 1). Because a
    /// fixed-point determinant of a small matrix has few significant bits (a triple product of
    /// 0.05 is 2^-13), a matrix of Frobenius norm `f <= 1` is first multiplied by the INTEGER
    /// `k = floor(2 / f)` (exact products), which gives `inverse = adjugate(k * self) * (k /
    /// det(k * self))`: 27 ulp instead of 84 960 on the oracle's `small` matrices. Matrices
    /// with `|det| >= 1/2` skip the norm computation (`f <= 1` implies `|det| < 1/2`). Panics
    /// with the overflow error when `0 < f <= 2^-30`.
    ///
    /// Re-ranked on `fixed` 0.3.0 (WP 7.2): the unscaled branch divides through ONE prepared
    /// divisor (`Real::div9`, bit-identical to per-element division). `adjugate / det` without the
    /// pre-scaling — upstream's 3x3 formula — costs 66 860 gas through `Real::div9`
    /// (`bench_matrix3_try_inverse__alt_div_n`) against 88 360, and `adjugate * (1 / det)` is
    /// cheaper still, but they leave respectively 2 and 9 of the 30 oracle cases outside their
    /// tolerance (`test_try_inverse_candidates_error`), so the pre-scaled algorithm stays. The
    /// charged gas is that of the costliest branch (the pre-scaled one): the three
    /// `bench_matrix3_try_inverse__prescaled_*` benchmarks measure the same figure.
    fn try_inverse(self: Matrix3<T>) -> Option<Matrix3<T>> {
        let adj = Matrix3InternalTrait::adjugate(self);
        let det = R::sum_prod3(self.m11, adj.m11, self.m12, adj.m21, self.m13, adj.m31);
        if det < R::HALF && det > -R::HALF {
            let f = Self::norm(self);
            if f == R::zero() {
                return None;
            }
            let k = R::floor(R::div(R::TWO, f));
            if k >= R::TWO {
                let b = Self::scale(self, k);
                let adj_b = Matrix3InternalTrait::adjugate(b);
                let det_b = R::sum_prod3(b.m11, adj_b.m11, b.m12, adj_b.m21, b.m13, adj_b.m31);
                if det_b == R::zero() {
                    return None;
                }
                return Some(Self::scale(adj_b, R::div(k, det_b)));
            }
            if det == R::zero() {
                return None;
            }
        }
        let (m11, m21, m31, m12, m22, m32, m13, m23, m33) = R::div9(
            adj.m11, adj.m21, adj.m31, adj.m12, adj.m22, adj.m32, adj.m13, adj.m23, adj.m33, det,
        );
        Some(Matrix3 { m11, m21, m31, m12, m22, m32, m13, m23, m33 })
    }

    // --- approximate equality ------------------------------------------------------------------

    /// Whether every component is within `ulps` smallest units of the identity's.
    /// Upstream: `is_identity(eps)`, with the tolerance in raw units instead of a float epsilon.
    fn is_identity(self: Matrix3<T>, ulps: u64) -> bool {
        R::abs_diff_eq(self.m11, R::one(), ulps)
            && R::abs_diff_eq(self.m21, R::zero(), ulps)
            && R::abs_diff_eq(self.m31, R::zero(), ulps)
            && R::abs_diff_eq(self.m12, R::zero(), ulps)
            && R::abs_diff_eq(self.m22, R::one(), ulps)
            && R::abs_diff_eq(self.m32, R::zero(), ulps)
            && R::abs_diff_eq(self.m13, R::zero(), ulps)
            && R::abs_diff_eq(self.m23, R::zero(), ulps)
            && R::abs_diff_eq(self.m33, R::one(), ulps)
    }

    /// Whether every component of `self` is within `ulps` smallest units of `other`'s.
    /// Upstream: `abs_diff_eq`, with the tolerance in raw units instead of a float epsilon.
    fn abs_diff_eq(self: Matrix3<T>, other: Matrix3<T>, ulps: u64) -> bool {
        R::abs_diff_eq(self.m11, other.m11, ulps)
            && R::abs_diff_eq(self.m21, other.m21, ulps)
            && R::abs_diff_eq(self.m31, other.m31, ulps)
            && R::abs_diff_eq(self.m12, other.m12, ulps)
            && R::abs_diff_eq(self.m22, other.m22, ulps)
            && R::abs_diff_eq(self.m32, other.m32, ulps)
            && R::abs_diff_eq(self.m13, other.m13, ulps)
            && R::abs_diff_eq(self.m23, other.m23, ulps)
            && R::abs_diff_eq(self.m33, other.m33, ulps)
    }

    // --- base completion (WP 8.2a) -------------------------------------------------------------

    /// The 3x3 matrix whose components all equal `elem`. Upstream: `Matrix3::repeat`.
    #[inline(always)]
    fn repeat(elem: T) -> Matrix3<T> {
        Matrix3 {
            m11: elem,
            m21: elem,
            m31: elem,
            m12: elem,
            m22: elem,
            m32: elem,
            m13: elem,
            m23: elem,
            m33: elem,
        }
    }

    /// Alias of `repeat`. Upstream: `Matrix3::from_element`.
    #[inline(always)]
    fn from_element(elem: T) -> Matrix3<T> {
        Matrix3 {
            m11: elem,
            m21: elem,
            m31: elem,
            m12: elem,
            m22: elem,
            m32: elem,
            m13: elem,
            m23: elem,
            m33: elem,
        }
    }

    /// The 3x3 matrix whose component `(i, j)` (row, column, 0-based) is `f(i, j)`, `f` being
    /// called in column-major order like upstream. `f` is any closure or `Fn` value of `(usize,
    /// usize)` whose output converts `Into<T>` (the identity included): Cairo cannot state `Output
    /// = T` on the closure without the `associated_item_constraints` experimental feature.
    /// Upstream: `Matrix3::from_fn`.
    fn from_fn<
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (usize, usize)>,
        +Into<Func::Output, T>,
        +Drop<Func::Output>,
    >(
        f: F,
    ) -> Matrix3<T> {
        Matrix3 {
            m11: f(0, 0).into(),
            m21: f(1, 0).into(),
            m31: f(2, 0).into(),
            m12: f(0, 1).into(),
            m22: f(1, 1).into(),
            m32: f(2, 1).into(),
            m13: f(0, 2).into(),
            m23: f(1, 2).into(),
            m33: f(2, 2).into(),
        }
    }

    /// The 3x3 matrix of the 9 values of `data`, in row-major order. Panics with `nalgebra: wrong
    /// slice length` unless `data.len() == 9`. Upstream: `Matrix3::from_row_slice` (`&[T]`).
    #[inline(always)]
    fn from_row_slice(data: Span<T>) -> Matrix3<T> {
        if data.len() != 9 {
            core::panic_with_felt252(errors::SLICE_LENGTH);
        }
        Matrix3 {
            m11: *data[0],
            m21: *data[3],
            m31: *data[6],
            m12: *data[1],
            m22: *data[4],
            m32: *data[7],
            m13: *data[2],
            m23: *data[5],
            m33: *data[8],
        }
    }

    /// The 3x3 matrix of the 9 values of `data`, in column-major order. Panics with `nalgebra:
    /// wrong slice length` unless `data.len() == 9`. Upstream: `Matrix3::from_column_slice`
    /// (`&[T]`).
    #[inline(always)]
    fn from_column_slice(data: Span<T>) -> Matrix3<T> {
        if data.len() != 9 {
            core::panic_with_felt252(errors::SLICE_LENGTH);
        }
        Matrix3 {
            m11: *data[0],
            m21: *data[1],
            m31: *data[2],
            m12: *data[3],
            m22: *data[4],
            m32: *data[5],
            m13: *data[6],
            m23: *data[7],
            m33: *data[8],
        }
    }

    /// The 3x3 matrix whose first `data.len()` diagonal components are `data`, every other
    /// component zero. Panics with `nalgebra: diagonal too long` when `data.len() > 3`. Upstream:
    /// `Matrix3::from_partial_diagonal` (`&[T]`).
    #[inline(always)]
    fn from_partial_diagonal(data: Span<T>) -> Matrix3<T> {
        let len = data.len();
        if len > 3 {
            core::panic_with_felt252(errors::TOO_MANY_DIAGONAL);
        }
        Matrix3 {
            m11: if len > 0 {
                *data[0]
            } else {
                R::zero()
            },
            m21: R::zero(),
            m31: R::zero(),
            m12: R::zero(),
            m22: if len > 1 {
                *data[1]
            } else {
                R::zero()
            },
            m32: R::zero(),
            m13: R::zero(),
            m23: R::zero(),
            m33: if len > 2 {
                *data[2]
            } else {
                R::zero()
            },
        }
    }

    /// `true` when every component is zero. Upstream: `Zero::is_zero`.
    #[inline(always)]
    fn is_zero(self: Matrix3<T>) -> bool {
        self.m11 == R::zero()
            && self.m21 == R::zero()
            && self.m31 == R::zero()
            && self.m12 == R::zero()
            && self.m22 == R::zero()
            && self.m32 == R::zero()
            && self.m13 == R::zero()
            && self.m23 == R::zero()
            && self.m33 == R::zero()
    }

    /// `self = self.component_mul(rhs)`. Upstream: `component_mul_assign`.
    #[inline(always)]
    fn component_mul_assign(ref self: Matrix3<T>, rhs: Matrix3<T>) {
        self =
            Matrix3 {
                m11: self.m11 * rhs.m11,
                m21: self.m21 * rhs.m21,
                m31: self.m31 * rhs.m31,
                m12: self.m12 * rhs.m12,
                m22: self.m22 * rhs.m22,
                m32: self.m32 * rhs.m32,
                m13: self.m13 * rhs.m13,
                m23: self.m23 * rhs.m23,
                m33: self.m33 * rhs.m33,
            };
    }

    /// Component-wise quotient, each component rounded to nearest (ties to even). Panics on a zero
    /// component of `rhs` and on overflow. Upstream: `component_div`.
    #[inline(always)]
    fn component_div(self: Matrix3<T>, rhs: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: R::div(self.m11, rhs.m11),
            m21: R::div(self.m21, rhs.m21),
            m31: R::div(self.m31, rhs.m31),
            m12: R::div(self.m12, rhs.m12),
            m22: R::div(self.m22, rhs.m22),
            m32: R::div(self.m32, rhs.m32),
            m13: R::div(self.m13, rhs.m13),
            m23: R::div(self.m23, rhs.m23),
            m33: R::div(self.m33, rhs.m33),
        }
    }

    /// `self = self.component_div(rhs)`. Upstream: `component_div_assign`.
    #[inline(always)]
    fn component_div_assign(ref self: Matrix3<T>, rhs: Matrix3<T>) {
        self =
            Matrix3 {
                m11: R::div(self.m11, rhs.m11),
                m21: R::div(self.m21, rhs.m21),
                m31: R::div(self.m31, rhs.m31),
                m12: R::div(self.m12, rhs.m12),
                m22: R::div(self.m22, rhs.m22),
                m32: R::div(self.m32, rhs.m32),
                m13: R::div(self.m13, rhs.m13),
                m23: R::div(self.m23, rhs.m23),
                m33: R::div(self.m33, rhs.m33),
            };
    }

    /// Component-wise minimum (infimum). Exact. Upstream: `inf`.
    #[inline(always)]
    fn inf(self: Matrix3<T>, other: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: R::min(self.m11, other.m11),
            m21: R::min(self.m21, other.m21),
            m31: R::min(self.m31, other.m31),
            m12: R::min(self.m12, other.m12),
            m22: R::min(self.m22, other.m22),
            m32: R::min(self.m32, other.m32),
            m13: R::min(self.m13, other.m13),
            m23: R::min(self.m23, other.m23),
            m33: R::min(self.m33, other.m33),
        }
    }

    /// Component-wise maximum (supremum). Exact. Upstream: `sup`.
    #[inline(always)]
    fn sup(self: Matrix3<T>, other: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: R::max(self.m11, other.m11),
            m21: R::max(self.m21, other.m21),
            m31: R::max(self.m31, other.m31),
            m12: R::max(self.m12, other.m12),
            m22: R::max(self.m22, other.m22),
            m32: R::max(self.m32, other.m32),
            m13: R::max(self.m13, other.m13),
            m23: R::max(self.m23, other.m23),
            m33: R::max(self.m33, other.m33),
        }
    }

    /// `(self.inf(other), self.sup(other))`. Exact. Upstream: `inf_sup`.
    #[inline(always)]
    fn inf_sup(self: Matrix3<T>, other: Matrix3<T>) -> (Matrix3<T>, Matrix3<T>) {
        (Self::inf(self, other), Self::sup(self, other))
    }

    /// `self + k` added to every component. Exact; panics on overflow. Upstream: `add_scalar`.
    #[inline(always)]
    fn add_scalar(self: Matrix3<T>, k: T) -> Matrix3<T> {
        Matrix3 {
            m11: self.m11 + k,
            m21: self.m21 + k,
            m31: self.m31 + k,
            m12: self.m12 + k,
            m22: self.m22 + k,
            m32: self.m32 + k,
            m13: self.m13 + k,
            m23: self.m23 + k,
            m33: self.m33 + k,
        }
    }

    /// `self = alpha * a ∘ b + beta * self` (component-wise product): per component `alpha * a`
    /// is floored, then the two products are ONE fused `sum_prod2` (floored once). Panics on
    /// overflow.
    /// Upstream: `cmpy` (which skips reading `self` when `beta` is zero: a difference only for NaN,
    /// which fixed point has not).
    #[inline(always)]
    fn cmpy(ref self: Matrix3<T>, alpha: T, a: Matrix3<T>, b: Matrix3<T>, beta: T) {
        self =
            Matrix3 {
                m11: R::sum_prod2(alpha * a.m11, b.m11, beta, self.m11),
                m21: R::sum_prod2(alpha * a.m21, b.m21, beta, self.m21),
                m31: R::sum_prod2(alpha * a.m31, b.m31, beta, self.m31),
                m12: R::sum_prod2(alpha * a.m12, b.m12, beta, self.m12),
                m22: R::sum_prod2(alpha * a.m22, b.m22, beta, self.m22),
                m32: R::sum_prod2(alpha * a.m32, b.m32, beta, self.m32),
                m13: R::sum_prod2(alpha * a.m13, b.m13, beta, self.m13),
                m23: R::sum_prod2(alpha * a.m23, b.m23, beta, self.m23),
                m33: R::sum_prod2(alpha * a.m33, b.m33, beta, self.m33),
            };
    }

    /// `self = alpha * a / b + beta * self` (component-wise quotient): per component `alpha * a` is
    /// floored, divided by `b` (rounded to nearest), then `beta * self + quotient` is ONE `mul_add`
    /// (floored once). Panics on a zero component of `b` and on overflow. Upstream: `cdpy`.
    #[inline(always)]
    fn cdpy(ref self: Matrix3<T>, alpha: T, a: Matrix3<T>, b: Matrix3<T>, beta: T) {
        self =
            Matrix3 {
                m11: R::mul_add(beta, self.m11, R::div(alpha * a.m11, b.m11)),
                m21: R::mul_add(beta, self.m21, R::div(alpha * a.m21, b.m21)),
                m31: R::mul_add(beta, self.m31, R::div(alpha * a.m31, b.m31)),
                m12: R::mul_add(beta, self.m12, R::div(alpha * a.m12, b.m12)),
                m22: R::mul_add(beta, self.m22, R::div(alpha * a.m22, b.m22)),
                m32: R::mul_add(beta, self.m32, R::div(alpha * a.m32, b.m32)),
                m13: R::mul_add(beta, self.m13, R::div(alpha * a.m13, b.m13)),
                m23: R::mul_add(beta, self.m23, R::div(alpha * a.m23, b.m23)),
                m33: R::mul_add(beta, self.m33, R::div(alpha * a.m33, b.m33)),
            };
    }

    /// The smallest component. Exact. Upstream: `min`.
    #[inline(always)]
    fn min(self: Matrix3<T>) -> T {
        R::min(
            R::min(
                R::min(
                    R::min(
                        R::min(
                            R::min(R::min(R::min(self.m11, self.m21), self.m31), self.m12),
                            self.m22,
                        ),
                        self.m32,
                    ),
                    self.m13,
                ),
                self.m23,
            ),
            self.m33,
        )
    }

    /// The largest component. Exact. Upstream: `max`.
    #[inline(always)]
    fn max(self: Matrix3<T>) -> T {
        R::max(
            R::max(
                R::max(
                    R::max(
                        R::max(
                            R::max(R::max(R::max(self.m11, self.m21), self.m31), self.m12),
                            self.m22,
                        ),
                        self.m32,
                    ),
                    self.m13,
                ),
                self.m23,
            ),
            self.m33,
        )
    }

    /// The smallest absolute value of a component. Panics on the scalar's `MIN`. Upstream: `amin`.
    #[inline(always)]
    fn amin(self: Matrix3<T>) -> T {
        R::min(
            R::min(
                R::min(
                    R::min(
                        R::min(
                            R::min(
                                R::min(
                                    R::min(R::abs(self.m11), R::abs(self.m21)), R::abs(self.m31),
                                ),
                                R::abs(self.m12),
                            ),
                            R::abs(self.m22),
                        ),
                        R::abs(self.m32),
                    ),
                    R::abs(self.m13),
                ),
                R::abs(self.m23),
            ),
            R::abs(self.m33),
        )
    }

    /// The largest absolute value of a component (the uniform norm). Panics on the scalar's `MIN`.
    /// Upstream: `amax`.
    #[inline(always)]
    fn amax(self: Matrix3<T>) -> T {
        R::max(
            R::max(
                R::max(
                    R::max(
                        R::max(
                            R::max(
                                R::max(
                                    R::max(R::abs(self.m11), R::abs(self.m21)), R::abs(self.m31),
                                ),
                                R::abs(self.m12),
                            ),
                            R::abs(self.m22),
                        ),
                        R::abs(self.m32),
                    ),
                    R::abs(self.m13),
                ),
                R::abs(self.m23),
            ),
            R::abs(self.m33),
        )
    }

    /// `amin`: the modulus of a real scalar is its absolute value. Upstream: `camin`.
    #[inline(always)]
    fn camin(self: Matrix3<T>) -> T {
        R::min(
            R::min(
                R::min(
                    R::min(
                        R::min(
                            R::min(
                                R::min(
                                    R::min(R::abs(self.m11), R::abs(self.m21)), R::abs(self.m31),
                                ),
                                R::abs(self.m12),
                            ),
                            R::abs(self.m22),
                        ),
                        R::abs(self.m32),
                    ),
                    R::abs(self.m13),
                ),
                R::abs(self.m23),
            ),
            R::abs(self.m33),
        )
    }

    /// `amax`: the modulus of a real scalar is its absolute value. Upstream: `camax`.
    #[inline(always)]
    fn camax(self: Matrix3<T>) -> T {
        R::max(
            R::max(
                R::max(
                    R::max(
                        R::max(
                            R::max(
                                R::max(
                                    R::max(R::abs(self.m11), R::abs(self.m21)), R::abs(self.m31),
                                ),
                                R::abs(self.m12),
                            ),
                            R::abs(self.m22),
                        ),
                        R::abs(self.m32),
                    ),
                    R::abs(self.m13),
                ),
                R::abs(self.m23),
            ),
            R::abs(self.m33),
        )
    }

    /// `(row, column)` of the component with the largest absolute value, the first one in
    /// column-major order on ties. Panics on the scalar's `MIN`. Upstream: `iamax_full`.
    fn iamax_full(self: Matrix3<T>) -> (usize, usize) {
        let mut best: (usize, usize) = (0, 0);
        let mut m = R::abs(self.m11);
        let v = R::abs(self.m21);
        if v > m {
            m = v;
            best = (1, 0);
        }
        let v = R::abs(self.m31);
        if v > m {
            m = v;
            best = (2, 0);
        }
        let v = R::abs(self.m12);
        if v > m {
            m = v;
            best = (0, 1);
        }
        let v = R::abs(self.m22);
        if v > m {
            m = v;
            best = (1, 1);
        }
        let v = R::abs(self.m32);
        if v > m {
            m = v;
            best = (2, 1);
        }
        let v = R::abs(self.m13);
        if v > m {
            m = v;
            best = (0, 2);
        }
        let v = R::abs(self.m23);
        if v > m {
            m = v;
            best = (1, 2);
        }
        let v = R::abs(self.m33);
        if v > m {
            best = (2, 2);
        }
        best
    }

    /// `iamax_full`: the modulus of a real scalar is its absolute value. Upstream: `icamax_full`.
    #[inline(always)]
    fn icamax_full(self: Matrix3<T>) -> (usize, usize) {
        Self::iamax_full(self)
    }

    /// Dot product (the sum of the component-wise products, upstream's Frobenius inner product for
    /// matrices): the exact sum is floored ONCE, only the result must fit. Upstream: `dot`.
    fn dot(self: Matrix3<T>, rhs: Matrix3<T>) -> T {
        let w = R::wide_add_prod(R::wide_zero(), self.m11, rhs.m11);
        let w = R::wide_add_prod(w, self.m21, rhs.m21);
        let w = R::wide_add_prod(w, self.m31, rhs.m31);
        let w = R::wide_add_prod(w, self.m12, rhs.m12);
        let w = R::wide_add_prod(w, self.m22, rhs.m22);
        let w = R::wide_add_prod(w, self.m32, rhs.m32);
        let w = R::wide_add_prod(w, self.m13, rhs.m13);
        let w = R::wide_add_prod(w, self.m23, rhs.m23);
        R::wide_rescale(R::wide_add_prod(w, self.m33, rhs.m33))
    }

    /// Alias of `norm_squared`. Upstream: `magnitude_squared`.
    #[inline(always)]
    fn magnitude_squared(self: Matrix3<T>) -> T {
        Self::norm_squared(self)
    }

    /// Alias of `norm`. Upstream: `magnitude`.
    #[inline(always)]
    fn magnitude(self: Matrix3<T>) -> T {
        Self::norm(self)
    }

    /// `(self - rhs).norm()`: the differences are exact, then one fused norm. Panics when a
    /// difference or the result overflows. Upstream: `metric_distance`.
    fn metric_distance(self: Matrix3<T>, rhs: Matrix3<T>) -> T {
        let w = R::wide_add_prod(R::wide_zero(), self.m11 - rhs.m11, self.m11 - rhs.m11);
        let w = R::wide_add_prod(w, self.m21 - rhs.m21, self.m21 - rhs.m21);
        let w = R::wide_add_prod(w, self.m31 - rhs.m31, self.m31 - rhs.m31);
        let w = R::wide_add_prod(w, self.m12 - rhs.m12, self.m12 - rhs.m12);
        let w = R::wide_add_prod(w, self.m22 - rhs.m22, self.m22 - rhs.m22);
        let w = R::wide_add_prod(w, self.m32 - rhs.m32, self.m32 - rhs.m32);
        let w = R::wide_add_prod(w, self.m13 - rhs.m13, self.m13 - rhs.m13);
        let w = R::wide_add_prod(w, self.m23 - rhs.m23, self.m23 - rhs.m23);
        R::wide_sqrt(R::wide_add_prod(w, self.m33 - rhs.m33, self.m33 - rhs.m33))
    }

    /// `self / k`, each component the correctly rounded quotient (nearest, ties to even), through 1
    /// prepared-divisor `Real::divN` call(s), bit-identical to one `Real::div` per component.
    /// Panics on a zero `k` and on overflow. Upstream: `unscale` (`self / k`).
    fn unscale(self: Matrix3<T>, k: T) -> Matrix3<T> {
        let (m11, m21, m31, m12, m22, m32, m13, m23, m33) = R::div9(
            self.m11,
            self.m21,
            self.m31,
            self.m12,
            self.m22,
            self.m32,
            self.m13,
            self.m23,
            self.m33,
            k,
        );
        Matrix3 { m11, m21, m31, m12, m22, m32, m13, m23, m33 }
    }

    /// `self / self.norm()`: the floored norm, then `unscale`. Panics with a division by zero when
    /// the norm is zero, and on overflow when the norm does not fit. Upstream: `normalize`.
    fn normalize(self: Matrix3<T>) -> Matrix3<T> {
        Self::unscale(self, Self::norm(self))
    }

    /// `Some(self.normalize())`, or `None` when the norm is `<= min_norm` (never divides by zero
    /// for `min_norm >= 0`). Upstream: `try_normalize`.
    fn try_normalize(self: Matrix3<T>, min_norm: T) -> Option<Matrix3<T>> {
        let n = Self::norm(self);
        if n <= min_norm {
            None
        } else {
            Some(Self::unscale(self, n))
        }
    }

    /// `self` when its norm is `<= max`, otherwise `self.scale(max / norm)` (the ratio rounded to
    /// nearest, like upstream's `max / n`). Panics only when the norm does not fit. Upstream:
    /// `cap_magnitude`.
    fn cap_magnitude(self: Matrix3<T>, max: T) -> Matrix3<T> {
        let n = Self::norm(self);
        if n <= max {
            self
        } else {
            Self::scale(self, R::div(max, n))
        }
    }

    /// Scales `self` to the norm `magnitude` (`self.scale(magnitude / norm)`, the ratio rounded to
    /// nearest) when its norm is `> min_magnitude`, leaves it unchanged otherwise. Upstream:
    /// `try_set_magnitude` (`&mut self`).
    fn try_set_magnitude(ref self: Matrix3<T>, magnitude: T, min_magnitude: T) {
        let n = Self::norm(self);
        if n > min_magnitude {
            self = Self::scale(self, R::div(magnitude, n));
        }
    }

    /// The induced 1-norm: the largest absolute column sum (the L1 norm of a column vector, the
    /// largest absolute value of a row vector). Exact; panics on overflow. Upstream: `one_norm`.
    #[inline(always)]
    fn one_norm(self: Matrix3<T>) -> T {
        R::max(
            R::max(
                R::abs(self.m11) + R::abs(self.m21) + R::abs(self.m31),
                R::abs(self.m12) + R::abs(self.m22) + R::abs(self.m32),
            ),
            R::abs(self.m13) + R::abs(self.m23) + R::abs(self.m33),
        )
    }

    /// The conjugate transpose, a `Matrix3`: the transpose for a real scalar. Exact. Upstream:
    /// `adjoint`.
    #[inline(always)]
    fn adjoint(self: Matrix3<T>) -> Matrix3<T> {
        Self::transpose(self)
    }

    /// Alias of `adjoint` (deprecated upstream). Upstream: `conjugate_transpose`.
    #[inline(always)]
    fn conjugate_transpose(self: Matrix3<T>) -> Matrix3<T> {
        Self::transpose(self)
    }

    /// The component-wise conjugate: `self` for a real scalar. Upstream: `conjugate`.
    #[inline(always)]
    fn conjugate(self: Matrix3<T>) -> Matrix3<T> {
        self
    }

    /// `(self + selfᵀ) / 2`: each off-diagonal pair is ONE `sum_prod2` by `1/2` (floored once, no
    /// intermediate overflow), the diagonal is copied exactly. Upstream: `symmetric_part`.
    #[inline(always)]
    fn symmetric_part(self: Matrix3<T>) -> Matrix3<T> {
        let a21 = R::sum_prod2(self.m21, R::HALF, self.m12, R::HALF);
        let a31 = R::sum_prod2(self.m31, R::HALF, self.m13, R::HALF);
        let a32 = R::sum_prod2(self.m32, R::HALF, self.m23, R::HALF);
        Matrix3 {
            m11: self.m11,
            m21: a21,
            m31: a31,
            m12: a21,
            m22: self.m22,
            m32: a32,
            m13: a31,
            m23: a32,
            m33: self.m33,
        }
    }

    /// `symmetric_part`: the adjoint of a real matrix is its transpose. Upstream: `hermitian_part`.
    #[inline(always)]
    fn hermitian_part(self: Matrix3<T>) -> Matrix3<T> {
        Self::symmetric_part(self)
    }

    /// The `Matrix4` `[[self, 0], [0, 1]]`: `self` as the linear part of a homogeneous
    /// transformation. Exact. Upstream: `to_homogeneous`.
    #[inline(always)]
    fn to_homogeneous(self: Matrix3<T>) -> Matrix4<T> {
        Matrix4 {
            m11: self.m11,
            m21: self.m21,
            m31: self.m31,
            m41: R::zero(),
            m12: self.m12,
            m22: self.m22,
            m32: self.m32,
            m42: R::zero(),
            m13: self.m13,
            m23: self.m23,
            m33: self.m33,
            m43: R::zero(),
            m14: R::zero(),
            m24: R::zero(),
            m34: R::zero(),
            m44: R::one(),
        }
    }

    /// The same shape with every component converted by `Into<T, U>`. With the single scalar of
    /// this library (`Fixed`) it is the identity; it exists for scalar-generic code. Upstream:
    /// `cast` (and `SubsetOf<Matrix<U>>`, the `nalgebra::convert` it goes through).
    fn cast<U, +Into<T, U>, +Drop<U>>(self: Matrix3<T>) -> Matrix3<U> {
        Matrix3 {
            m11: self.m11.into(),
            m21: self.m21.into(),
            m31: self.m31.into(),
            m12: self.m12.into(),
            m22: self.m22.into(),
            m32: self.m32.into(),
            m13: self.m13.into(),
            m23: self.m23.into(),
            m33: self.m33.into(),
        }
    }

    /// `Some` of the shape with every component converted by `TryInto<T, U>`, `None` as soon as one
    /// conversion fails. Upstream: `try_cast`.
    fn try_cast<U, +TryInto<T, U>, +Drop<U>>(self: Matrix3<T>) -> Option<Matrix3<U>> {
        let m11: U = match self.m11.try_into() {
            Option::Some(v) => v,
            Option::None => { return Option::None; },
        };
        let m21: U = match self.m21.try_into() {
            Option::Some(v) => v,
            Option::None => { return Option::None; },
        };
        let m31: U = match self.m31.try_into() {
            Option::Some(v) => v,
            Option::None => { return Option::None; },
        };
        let m12: U = match self.m12.try_into() {
            Option::Some(v) => v,
            Option::None => { return Option::None; },
        };
        let m22: U = match self.m22.try_into() {
            Option::Some(v) => v,
            Option::None => { return Option::None; },
        };
        let m32: U = match self.m32.try_into() {
            Option::Some(v) => v,
            Option::None => { return Option::None; },
        };
        let m13: U = match self.m13.try_into() {
            Option::Some(v) => v,
            Option::None => { return Option::None; },
        };
        let m23: U = match self.m23.try_into() {
            Option::Some(v) => v,
            Option::None => { return Option::None; },
        };
        let m33: U = match self.m33.try_into() {
            Option::Some(v) => v,
            Option::None => { return Option::None; },
        };
        Option::Some(Matrix3 { m11, m21, m31, m12, m22, m32, m13, m23, m33 })
    }

    /// `true` when every component is within `epsilon` ulp of `other`'s, or has the same sign and
    /// lies within `max_relative` times the larger magnitude of the two (`|a - b| <= max(|a|, |b|)
    /// · max_relative`). Panics on a component equal to the scalar's `MIN`, and on overflow of
    /// that product (only possible with `max_relative > 1`). Upstream:
    /// `approx::RelativeEq::relative_eq`, `epsilon` counted in ulp instead of a float epsilon
    /// (DESIGN D3).
    #[inline(always)]
    fn relative_eq(self: Matrix3<T>, other: Matrix3<T>, epsilon: u64, max_relative: T) -> bool {
        ApproxEqTrait::relative_eq(self.m11, other.m11, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m21, other.m21, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m31, other.m31, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m12, other.m12, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m22, other.m22, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m32, other.m32, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m13, other.m13, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m23, other.m23, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.m33, other.m33, epsilon, max_relative)
    }

    /// `true` when every component is within `epsilon` ulp of `other`'s, or has the same sign and
    /// lies within `max_ulps` ulp (in fixed point the distance in ulp IS the raw difference; the
    /// `max_ulps` budget does not cross zero, like upstream's float `ulps_eq`). Cannot overflow.
    /// Upstream: `approx::UlpsEq::ulps_eq`.
    #[inline(always)]
    fn ulps_eq(self: Matrix3<T>, other: Matrix3<T>, epsilon: u64, max_ulps: u32) -> bool {
        ApproxEqTrait::ulps_eq(self.m11, other.m11, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m21, other.m21, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m31, other.m31, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m12, other.m12, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m22, other.m22, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m32, other.m32, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m13, other.m13, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m23, other.m23, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.m33, other.m33, epsilon, max_ulps)
    }
}

/// The operations of `Matrix3<T>` that need `Transcendental` (inverse trigonometry, `exp`, `ln`):
/// a scalar may implement `Real` only.
#[generate_trait]
pub impl Matrix3AngleImpl<
    T,
    impl R: Real<T>,
    impl Tr: Transcendental<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix3AngleTrait<T> {
    /// The angle between `self` and `other` seen as vectors of the Frobenius inner product, in `[0,
    /// π]` (up to the rounding of `atan2`); `0` when one of them is zero. Computed as `2 *
    /// atan2(|u - v|, |u + v|)` on the normalized `u`, `v` (Kahan): unlike upstream's `acos(dot /
    /// (|a| *
    /// |b|))` it cannot overflow on long inputs and stays accurate for nearly parallel ones. Panics
    /// when a norm does not fit. Upstream: `angle`.
    fn angle(self: Matrix3<T>, other: Matrix3<T>) -> T {
        let n1 = Matrix3Trait::norm(self);
        let n2 = Matrix3Trait::norm(other);
        if n1 == R::zero() || n2 == R::zero() {
            return R::zero();
        }
        let u = Matrix3Trait::unscale(self, n1);
        let v = Matrix3Trait::unscale(other, n2);
        let half = Tr::atan2(Matrix3Trait::metric_distance(u, v), Matrix3Trait::norm(u + v));
        half + half
    }

    /// The entrywise Lp norm `(Σ |a|^p)^(1/p)`. `p = 1` is the exact sum of the absolute values
    /// and `p = 2` the fused `norm` (both exact up to their one rounding); above, the components
    /// are first divided by the largest absolute value `m` (so no power can overflow), `Σ (|a| /
    /// m)^p`
    /// is summed (`p` floored products each), and the root is `m * exp(ln(Σ) / p)`: a few ulp
    /// relative to the result, the rounding of `exp` / `ln`. Panics with `nalgebra: lp_norm needs p
    /// >= 1` for `p < 1` (upstream returns meaningless values: an infinite root for `p = 0`).
    /// Upstream: `lp_norm`.
    fn lp_norm(self: Matrix3<T>, p: i32) -> T {
        if p < 1 {
            core::panic_with_felt252(errors::LP_NORM_P);
        }
        if p == 1 {
            return R::abs(self.m11)
                + R::abs(self.m21)
                + R::abs(self.m31)
                + R::abs(self.m12)
                + R::abs(self.m22)
                + R::abs(self.m32)
                + R::abs(self.m13)
                + R::abs(self.m23)
                + R::abs(self.m33);
        }
        if p == 2 {
            return Matrix3Trait::norm(self);
        }
        let m = Matrix3Trait::amax(self);
        if m == R::zero() {
            return R::zero();
        }
        let r = Matrix3Trait::unscale(Matrix3Trait::abs(self), m);
        let q: u32 = p.try_into().unwrap();
        let s = Powi::powi(r.m11, q)
            + Powi::powi(r.m21, q)
            + Powi::powi(r.m31, q)
            + Powi::powi(r.m12, q)
            + Powi::powi(r.m22, q)
            + Powi::powi(r.m32, q)
            + Powi::powi(r.m13, q)
            + Powi::powi(r.m23, q)
            + Powi::powi(r.m33, q);
        m * Tr::exp(R::div(Tr::ln(s), R::from_int(p)))
    }
}

/// Crate-internal kernels of `Matrix3<T>` with no upstream method of that name or shape (WP 8.0:
/// the public API is strictly upstream's). The structured kernels of DESIGN D4 (`from_outer`,
/// `cross_matrix_mul` = `v.cross_matrix() * m` without the skew matrix, `adjugate`, `mul_transpose`
/// into a `SymMatrix3`) and the unrolled row / column accessors that stand for upstream `row(i)` /
/// `column(i)` views, used by the decompositions.
#[generate_trait]
pub(crate) impl Matrix3InternalImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix3InternalTrait<T> {
    /// The outer product `a * bᵀ`: each component is one floored product. Panics with the
    /// scalar's overflow error. Upstream: `a * b.transpose()`.
    #[inline(always)]
    fn from_outer(a: Vector3<T>, b: Vector3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: a.x * b.x,
            m21: a.y * b.x,
            m31: a.z * b.x,
            m12: a.x * b.y,
            m22: a.y * b.y,
            m32: a.z * b.y,
            m13: a.x * b.z,
            m23: a.y * b.z,
            m33: a.z * b.z,
        }
    }

    /// `[v]× * m` without materialising `[v]×`: column `j` is `v × column_j(m)`, 9 `diff_prod`
    /// (one rounding per component), bit-identical to `cross_matrix(v) * m`. Panics on overflow.
    /// Upstream: `v.cross_matrix() * m`; rapier: `gcross_matrix`.
    fn cross_matrix_mul(v: Vector3<T>, m: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: R::diff_prod(v.y, m.m31, v.z, m.m21),
            m21: R::diff_prod(v.z, m.m11, v.x, m.m31),
            m31: R::diff_prod(v.x, m.m21, v.y, m.m11),
            m12: R::diff_prod(v.y, m.m32, v.z, m.m22),
            m22: R::diff_prod(v.z, m.m12, v.x, m.m32),
            m32: R::diff_prod(v.x, m.m22, v.y, m.m12),
            m13: R::diff_prod(v.y, m.m33, v.z, m.m23),
            m23: R::diff_prod(v.z, m.m13, v.x, m.m33),
            m33: R::diff_prod(v.x, m.m23, v.y, m.m13),
        }
    }

    /// Column 1. Upstream: `column(0)`.
    #[inline(always)]
    fn column1(self: Matrix3<T>) -> Vector3<T> {
        Vector3 { x: self.m11, y: self.m21, z: self.m31 }
    }

    /// Column 2. Upstream: `column(1)`.
    #[inline(always)]
    fn column2(self: Matrix3<T>) -> Vector3<T> {
        Vector3 { x: self.m12, y: self.m22, z: self.m32 }
    }

    /// Column 3. Upstream: `column(2)`.
    #[inline(always)]
    fn column3(self: Matrix3<T>) -> Vector3<T> {
        Vector3 { x: self.m13, y: self.m23, z: self.m33 }
    }

    /// Row 1, as a (column) vector. Upstream: `row(0).transpose()`.
    #[inline(always)]
    fn row1(self: Matrix3<T>) -> Vector3<T> {
        Vector3 { x: self.m11, y: self.m12, z: self.m13 }
    }

    /// Row 2, as a (column) vector. Upstream: `row(1).transpose()`.
    #[inline(always)]
    fn row2(self: Matrix3<T>) -> Vector3<T> {
        Vector3 { x: self.m21, y: self.m22, z: self.m23 }
    }

    /// Row 3, as a (column) vector. Upstream: `row(2).transpose()`.
    #[inline(always)]
    fn row3(self: Matrix3<T>) -> Vector3<T> {
        Vector3 { x: self.m31, y: self.m32, z: self.m33 }
    }

    /// `self * selfᵀ` as a symmetric matrix: 6 fused kernels instead of 9, bit-identical to the
    /// upper triangle of `self * self.transpose()`. Panics on overflow.
    /// Upstream: `self * self.transpose()`.
    fn mul_transpose(self: Matrix3<T>) -> SymMatrix3<T> {
        SymMatrix3 {
            m11: R::norm_squared3(self.m11, self.m12, self.m13),
            m12: R::sum_prod3(self.m11, self.m21, self.m12, self.m22, self.m13, self.m23),
            m13: R::sum_prod3(self.m11, self.m31, self.m12, self.m32, self.m13, self.m33),
            m22: R::norm_squared3(self.m21, self.m22, self.m23),
            m23: R::sum_prod3(self.m21, self.m31, self.m22, self.m32, self.m23, self.m33),
            m33: R::norm_squared3(self.m31, self.m32, self.m33),
        }
    }

    /// The adjugate (transposed cofactor matrix): `self * adjugate = determinant * I`. 9
    /// `diff_prod`, one rounding per component. Panics on overflow.
    /// No upstream equivalent (upstream `adjoint` is the conjugate transpose).
    #[inline(always)]
    fn adjugate(self: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: R::diff_prod(self.m22, self.m33, self.m23, self.m32),
            m21: R::diff_prod(self.m23, self.m31, self.m21, self.m33),
            m31: R::diff_prod(self.m21, self.m32, self.m22, self.m31),
            m12: R::diff_prod(self.m13, self.m32, self.m12, self.m33),
            m22: R::diff_prod(self.m11, self.m33, self.m13, self.m31),
            m32: R::diff_prod(self.m12, self.m31, self.m11, self.m32),
            m13: R::diff_prod(self.m12, self.m23, self.m13, self.m22),
            m23: R::diff_prod(self.m13, self.m21, self.m11, self.m23),
            m33: R::diff_prod(self.m11, self.m22, self.m12, self.m21),
        }
    }
}

// --- operators -----------------------------------------------------------------------------------

/// `a + b`, component-wise. Exact; panics on overflow.
pub impl Matrix3Add<T, +Add<T>, +Copy<T>, +Drop<T>> of Add<Matrix3<T>> {
    #[inline(always)]
    fn add(lhs: Matrix3<T>, rhs: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: lhs.m11 + rhs.m11,
            m21: lhs.m21 + rhs.m21,
            m31: lhs.m31 + rhs.m31,
            m12: lhs.m12 + rhs.m12,
            m22: lhs.m22 + rhs.m22,
            m32: lhs.m32 + rhs.m32,
            m13: lhs.m13 + rhs.m13,
            m23: lhs.m23 + rhs.m23,
            m33: lhs.m33 + rhs.m33,
        }
    }
}

/// `a - b`, component-wise. Exact; panics on overflow.
pub impl Matrix3Sub<T, +Sub<T>, +Copy<T>, +Drop<T>> of Sub<Matrix3<T>> {
    #[inline(always)]
    fn sub(lhs: Matrix3<T>, rhs: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: lhs.m11 - rhs.m11,
            m21: lhs.m21 - rhs.m21,
            m31: lhs.m31 - rhs.m31,
            m12: lhs.m12 - rhs.m12,
            m22: lhs.m22 - rhs.m22,
            m32: lhs.m32 - rhs.m32,
            m13: lhs.m13 - rhs.m13,
            m23: lhs.m23 - rhs.m23,
            m33: lhs.m33 - rhs.m33,
        }
    }
}

/// `-a`, component-wise. Exact; panics on the scalar's `MIN`.
pub impl Matrix3Neg<T, +Neg<T>, +Copy<T>, +Drop<T>> of Neg<Matrix3<T>> {
    #[inline(always)]
    fn neg(a: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: -a.m11,
            m21: -a.m21,
            m31: -a.m31,
            m12: -a.m12,
            m22: -a.m22,
            m32: -a.m32,
            m13: -a.m13,
            m23: -a.m23,
            m33: -a.m33,
        }
    }
}

/// `a * b` (matrix product): 9 `sum_prod3`, one rounding per component. Panics on overflow.
pub impl Matrix3Mul<T, impl R: Real<T>, +Copy<T>, +Drop<T>> of Mul<Matrix3<T>> {
    fn mul(lhs: Matrix3<T>, rhs: Matrix3<T>) -> Matrix3<T> {
        Matrix3 {
            m11: R::sum_prod3(lhs.m11, rhs.m11, lhs.m12, rhs.m21, lhs.m13, rhs.m31),
            m21: R::sum_prod3(lhs.m21, rhs.m11, lhs.m22, rhs.m21, lhs.m23, rhs.m31),
            m31: R::sum_prod3(lhs.m31, rhs.m11, lhs.m32, rhs.m21, lhs.m33, rhs.m31),
            m12: R::sum_prod3(lhs.m11, rhs.m12, lhs.m12, rhs.m22, lhs.m13, rhs.m32),
            m22: R::sum_prod3(lhs.m21, rhs.m12, lhs.m22, rhs.m22, lhs.m23, rhs.m32),
            m32: R::sum_prod3(lhs.m31, rhs.m12, lhs.m32, rhs.m22, lhs.m33, rhs.m32),
            m13: R::sum_prod3(lhs.m11, rhs.m13, lhs.m12, rhs.m23, lhs.m13, rhs.m33),
            m23: R::sum_prod3(lhs.m21, rhs.m13, lhs.m22, rhs.m23, lhs.m23, rhs.m33),
            m33: R::sum_prod3(lhs.m31, rhs.m13, lhs.m32, rhs.m23, lhs.m33, rhs.m33),
        }
    }
}

/// `a += b`.
pub impl Matrix3AddAssign<T, +Add<T>, +Copy<T>, +Drop<T>> of AddAssign<Matrix3<T>, Matrix3<T>> {
    #[inline(always)]
    fn add_assign(ref self: Matrix3<T>, rhs: Matrix3<T>) {
        self = self + rhs;
    }
}

/// `a -= b`.
pub impl Matrix3SubAssign<T, +Sub<T>, +Copy<T>, +Drop<T>> of SubAssign<Matrix3<T>, Matrix3<T>> {
    #[inline(always)]
    fn sub_assign(ref self: Matrix3<T>, rhs: Matrix3<T>) {
        self = self - rhs;
    }
}

/// `a *= b` (matrix product, `a = a * b`).
pub impl Matrix3MulAssign<
    T, impl R: Real<T>, +Copy<T>, +Drop<T>,
> of MulAssign<Matrix3<T>, Matrix3<T>> {
    #[inline(always)]
    fn mul_assign(ref self: Matrix3<T>, rhs: Matrix3<T>) {
        self = self * rhs;
    }
}

// --- products ------------------------------------------------------------------------------------

/// `self * rhs`, a `Vector3`: one `sum_prod3` per component (one rounding each). Panics on
/// overflow. Upstream: `Matrix3 * Vector3` (`Mul`).
pub impl Matrix3MulVector3<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<Matrix3<T>, Vector3<T>> {
    type Output = Vector3<T>;
    #[inline(always)]
    fn mul_mat(self: Matrix3<T>, rhs: Vector3<T>) -> Vector3<T> {
        Vector3 {
            x: R::sum_prod3(self.m11, rhs.x, self.m12, rhs.y, self.m13, rhs.z),
            y: R::sum_prod3(self.m21, rhs.x, self.m22, rhs.y, self.m23, rhs.z),
            z: R::sum_prod3(self.m31, rhs.x, self.m32, rhs.y, self.m33, rhs.z),
        }
    }
}

/// `self * rhs`, a `Matrix3x2`: one `sum_prod3` per component (one rounding each). Panics on
/// overflow. Upstream: `Matrix3 * Matrix3x2` (`Mul`).
pub impl Matrix3MulMatrix3x2<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<Matrix3<T>, Matrix3x2<T>> {
    type Output = Matrix3x2<T>;
    fn mul_mat(self: Matrix3<T>, rhs: Matrix3x2<T>) -> Matrix3x2<T> {
        Matrix3x2 {
            m11: R::sum_prod3(self.m11, rhs.m11, self.m12, rhs.m21, self.m13, rhs.m31),
            m21: R::sum_prod3(self.m21, rhs.m11, self.m22, rhs.m21, self.m23, rhs.m31),
            m31: R::sum_prod3(self.m31, rhs.m11, self.m32, rhs.m21, self.m33, rhs.m31),
            m12: R::sum_prod3(self.m11, rhs.m12, self.m12, rhs.m22, self.m13, rhs.m32),
            m22: R::sum_prod3(self.m21, rhs.m12, self.m22, rhs.m22, self.m23, rhs.m32),
            m32: R::sum_prod3(self.m31, rhs.m12, self.m32, rhs.m22, self.m33, rhs.m32),
        }
    }
}

/// `self * rhs` through `MatrixMul`: the `*` operator (same kernel, same gas), for code written
/// over every conformable shape. Upstream: `Mul`.
pub impl Matrix3MulMatrix3<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<Matrix3<T>, Matrix3<T>> {
    type Output = Matrix3<T>;
    #[inline(always)]
    fn mul_mat(self: Matrix3<T>, rhs: Matrix3<T>) -> Matrix3<T> {
        self * rhs
    }
}

/// `self * rhs`, a `Matrix3x4`: one `sum_prod3` per component (one rounding each). Panics on
/// overflow. Upstream: `Matrix3 * Matrix3x4` (`Mul`).
pub impl Matrix3MulMatrix3x4<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<Matrix3<T>, Matrix3x4<T>> {
    type Output = Matrix3x4<T>;
    fn mul_mat(self: Matrix3<T>, rhs: Matrix3x4<T>) -> Matrix3x4<T> {
        Matrix3x4 {
            m11: R::sum_prod3(self.m11, rhs.m11, self.m12, rhs.m21, self.m13, rhs.m31),
            m21: R::sum_prod3(self.m21, rhs.m11, self.m22, rhs.m21, self.m23, rhs.m31),
            m31: R::sum_prod3(self.m31, rhs.m11, self.m32, rhs.m21, self.m33, rhs.m31),
            m12: R::sum_prod3(self.m11, rhs.m12, self.m12, rhs.m22, self.m13, rhs.m32),
            m22: R::sum_prod3(self.m21, rhs.m12, self.m22, rhs.m22, self.m23, rhs.m32),
            m32: R::sum_prod3(self.m31, rhs.m12, self.m32, rhs.m22, self.m33, rhs.m32),
            m13: R::sum_prod3(self.m11, rhs.m13, self.m12, rhs.m23, self.m13, rhs.m33),
            m23: R::sum_prod3(self.m21, rhs.m13, self.m22, rhs.m23, self.m23, rhs.m33),
            m33: R::sum_prod3(self.m31, rhs.m13, self.m32, rhs.m23, self.m33, rhs.m33),
            m14: R::sum_prod3(self.m11, rhs.m14, self.m12, rhs.m24, self.m13, rhs.m34),
            m24: R::sum_prod3(self.m21, rhs.m14, self.m22, rhs.m24, self.m23, rhs.m34),
            m34: R::sum_prod3(self.m31, rhs.m14, self.m32, rhs.m24, self.m33, rhs.m34),
        }
    }
}

/// `self * rhs`, a `Matrix3x5`: one `sum_prod3` per component (one rounding each). Panics on
/// overflow. Upstream: `Matrix3 * Matrix3x5` (`Mul`).
pub impl Matrix3MulMatrix3x5<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<Matrix3<T>, Matrix3x5<T>> {
    type Output = Matrix3x5<T>;
    fn mul_mat(self: Matrix3<T>, rhs: Matrix3x5<T>) -> Matrix3x5<T> {
        Matrix3x5 {
            m11: R::sum_prod3(self.m11, rhs.m11, self.m12, rhs.m21, self.m13, rhs.m31),
            m21: R::sum_prod3(self.m21, rhs.m11, self.m22, rhs.m21, self.m23, rhs.m31),
            m31: R::sum_prod3(self.m31, rhs.m11, self.m32, rhs.m21, self.m33, rhs.m31),
            m12: R::sum_prod3(self.m11, rhs.m12, self.m12, rhs.m22, self.m13, rhs.m32),
            m22: R::sum_prod3(self.m21, rhs.m12, self.m22, rhs.m22, self.m23, rhs.m32),
            m32: R::sum_prod3(self.m31, rhs.m12, self.m32, rhs.m22, self.m33, rhs.m32),
            m13: R::sum_prod3(self.m11, rhs.m13, self.m12, rhs.m23, self.m13, rhs.m33),
            m23: R::sum_prod3(self.m21, rhs.m13, self.m22, rhs.m23, self.m23, rhs.m33),
            m33: R::sum_prod3(self.m31, rhs.m13, self.m32, rhs.m23, self.m33, rhs.m33),
            m14: R::sum_prod3(self.m11, rhs.m14, self.m12, rhs.m24, self.m13, rhs.m34),
            m24: R::sum_prod3(self.m21, rhs.m14, self.m22, rhs.m24, self.m23, rhs.m34),
            m34: R::sum_prod3(self.m31, rhs.m14, self.m32, rhs.m24, self.m33, rhs.m34),
            m15: R::sum_prod3(self.m11, rhs.m15, self.m12, rhs.m25, self.m13, rhs.m35),
            m25: R::sum_prod3(self.m21, rhs.m15, self.m22, rhs.m25, self.m23, rhs.m35),
            m35: R::sum_prod3(self.m31, rhs.m15, self.m32, rhs.m25, self.m33, rhs.m35),
        }
    }
}

/// `self * rhs`, a `Matrix3x6`: one `sum_prod3` per component (one rounding each). Panics on
/// overflow. Upstream: `Matrix3 * Matrix3x6` (`Mul`).
pub impl Matrix3MulMatrix3x6<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<Matrix3<T>, Matrix3x6<T>> {
    type Output = Matrix3x6<T>;
    fn mul_mat(self: Matrix3<T>, rhs: Matrix3x6<T>) -> Matrix3x6<T> {
        Matrix3x6 {
            m11: R::sum_prod3(self.m11, rhs.m11, self.m12, rhs.m21, self.m13, rhs.m31),
            m21: R::sum_prod3(self.m21, rhs.m11, self.m22, rhs.m21, self.m23, rhs.m31),
            m31: R::sum_prod3(self.m31, rhs.m11, self.m32, rhs.m21, self.m33, rhs.m31),
            m12: R::sum_prod3(self.m11, rhs.m12, self.m12, rhs.m22, self.m13, rhs.m32),
            m22: R::sum_prod3(self.m21, rhs.m12, self.m22, rhs.m22, self.m23, rhs.m32),
            m32: R::sum_prod3(self.m31, rhs.m12, self.m32, rhs.m22, self.m33, rhs.m32),
            m13: R::sum_prod3(self.m11, rhs.m13, self.m12, rhs.m23, self.m13, rhs.m33),
            m23: R::sum_prod3(self.m21, rhs.m13, self.m22, rhs.m23, self.m23, rhs.m33),
            m33: R::sum_prod3(self.m31, rhs.m13, self.m32, rhs.m23, self.m33, rhs.m33),
            m14: R::sum_prod3(self.m11, rhs.m14, self.m12, rhs.m24, self.m13, rhs.m34),
            m24: R::sum_prod3(self.m21, rhs.m14, self.m22, rhs.m24, self.m23, rhs.m34),
            m34: R::sum_prod3(self.m31, rhs.m14, self.m32, rhs.m24, self.m33, rhs.m34),
            m15: R::sum_prod3(self.m11, rhs.m15, self.m12, rhs.m25, self.m13, rhs.m35),
            m25: R::sum_prod3(self.m21, rhs.m15, self.m22, rhs.m25, self.m23, rhs.m35),
            m35: R::sum_prod3(self.m31, rhs.m15, self.m32, rhs.m25, self.m33, rhs.m35),
            m16: R::sum_prod3(self.m11, rhs.m16, self.m12, rhs.m26, self.m13, rhs.m36),
            m26: R::sum_prod3(self.m21, rhs.m16, self.m22, rhs.m26, self.m23, rhs.m36),
            m36: R::sum_prod3(self.m31, rhs.m16, self.m32, rhs.m26, self.m33, rhs.m36),
        }
    }
}

/// `selfᵀ * rhs`, a `Vector3`: `mul_mat` of the transposed components, so one `sum_prod3` per
/// component (one rounding each); bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas
/// (the transpose only relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl Matrix3TrMulVector3<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<Matrix3<T>, Vector3<T>> {
    type Output = Vector3<T>;
    #[inline(always)]
    fn tr_mul(self: Matrix3<T>, rhs: Vector3<T>) -> Vector3<T> {
        MatrixMul::mul_mat(
            Matrix3 {
                m11: self.m11,
                m21: self.m12,
                m31: self.m13,
                m12: self.m21,
                m22: self.m22,
                m32: self.m23,
                m13: self.m31,
                m23: self.m32,
                m33: self.m33,
            },
            rhs,
        )
    }
}

/// `selfᵀ * rhs`, a `Matrix3x2`: `mul_mat` of the transposed components, so one `sum_prod3` per
/// component (one rounding each); bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas
/// (the transpose only relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl Matrix3TrMulMatrix3x2<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<Matrix3<T>, Matrix3x2<T>> {
    type Output = Matrix3x2<T>;
    #[inline(always)]
    fn tr_mul(self: Matrix3<T>, rhs: Matrix3x2<T>) -> Matrix3x2<T> {
        MatrixMul::mul_mat(
            Matrix3 {
                m11: self.m11,
                m21: self.m12,
                m31: self.m13,
                m12: self.m21,
                m22: self.m22,
                m32: self.m23,
                m13: self.m31,
                m23: self.m32,
                m33: self.m33,
            },
            rhs,
        )
    }
}

/// `selfᵀ * rhs`, a `Matrix3`: `mul_mat` of the transposed components, so one `sum_prod3` per
/// component (one rounding each); bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas
/// (the transpose only relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl Matrix3TrMulMatrix3<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<Matrix3<T>, Matrix3<T>> {
    type Output = Matrix3<T>;
    #[inline(always)]
    fn tr_mul(self: Matrix3<T>, rhs: Matrix3<T>) -> Matrix3<T> {
        MatrixMul::mul_mat(
            Matrix3 {
                m11: self.m11,
                m21: self.m12,
                m31: self.m13,
                m12: self.m21,
                m22: self.m22,
                m32: self.m23,
                m13: self.m31,
                m23: self.m32,
                m33: self.m33,
            },
            rhs,
        )
    }
}

/// `selfᵀ * rhs`, a `Matrix3x4`: `mul_mat` of the transposed components, so one `sum_prod3` per
/// component (one rounding each); bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas
/// (the transpose only relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl Matrix3TrMulMatrix3x4<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<Matrix3<T>, Matrix3x4<T>> {
    type Output = Matrix3x4<T>;
    #[inline(always)]
    fn tr_mul(self: Matrix3<T>, rhs: Matrix3x4<T>) -> Matrix3x4<T> {
        MatrixMul::mul_mat(
            Matrix3 {
                m11: self.m11,
                m21: self.m12,
                m31: self.m13,
                m12: self.m21,
                m22: self.m22,
                m32: self.m23,
                m13: self.m31,
                m23: self.m32,
                m33: self.m33,
            },
            rhs,
        )
    }
}

/// `selfᵀ * rhs`, a `Matrix3x5`: `mul_mat` of the transposed components, so one `sum_prod3` per
/// component (one rounding each); bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas
/// (the transpose only relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl Matrix3TrMulMatrix3x5<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<Matrix3<T>, Matrix3x5<T>> {
    type Output = Matrix3x5<T>;
    #[inline(always)]
    fn tr_mul(self: Matrix3<T>, rhs: Matrix3x5<T>) -> Matrix3x5<T> {
        MatrixMul::mul_mat(
            Matrix3 {
                m11: self.m11,
                m21: self.m12,
                m31: self.m13,
                m12: self.m21,
                m22: self.m22,
                m32: self.m23,
                m13: self.m31,
                m23: self.m32,
                m33: self.m33,
            },
            rhs,
        )
    }
}

/// `selfᵀ * rhs`, a `Matrix3x6`: `mul_mat` of the transposed components, so one `sum_prod3` per
/// component (one rounding each); bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas
/// (the transpose only relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl Matrix3TrMulMatrix3x6<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<Matrix3<T>, Matrix3x6<T>> {
    type Output = Matrix3x6<T>;
    #[inline(always)]
    fn tr_mul(self: Matrix3<T>, rhs: Matrix3x6<T>) -> Matrix3x6<T> {
        MatrixMul::mul_mat(
            Matrix3 {
                m11: self.m11,
                m21: self.m12,
                m31: self.m13,
                m12: self.m21,
                m22: self.m22,
                m32: self.m23,
                m13: self.m31,
                m23: self.m32,
                m33: self.m33,
            },
            rhs,
        )
    }
}

// --- indexing, comparisons, conversions ----------------------------------------------------------

/// `m.get(i)` / `m.index(..)`: the component `index` in column-major (storage) order. `get` is
/// `None` out of bounds, `index` panics with `nalgebra: index out of bounds`. Upstream:
/// `Matrix::get` / `Matrix::index` (their `MatrixIndex` argument).
pub impl Matrix3MatrixIndexLinear<T, +Copy<T>, +Drop<T>> of MatrixIndex<Matrix3<T>, usize> {
    type Output = T;
    #[inline(always)]
    fn get(self: Matrix3<T>, index: usize) -> Option<T> {
        match index {
            0 => Option::Some(self.m11),
            1 => Option::Some(self.m21),
            2 => Option::Some(self.m31),
            3 => Option::Some(self.m12),
            4 => Option::Some(self.m22),
            5 => Option::Some(self.m32),
            6 => Option::Some(self.m13),
            7 => Option::Some(self.m23),
            8 => Option::Some(self.m33),
            _ => Option::None,
        }
    }
    #[inline(always)]
    fn index(self: Matrix3<T>, index: usize) -> T {
        match index {
            0 => self.m11,
            1 => self.m21,
            2 => self.m31,
            3 => self.m12,
            4 => self.m22,
            5 => self.m32,
            6 => self.m13,
            7 => self.m23,
            8 => self.m33,
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// `m[i]`: the component `index` in column-major (storage) order. Panics with `nalgebra: index out
/// of bounds`. Upstream: `Index<usize>`.
pub impl Matrix3IndexLinear<T, +Copy<T>, +Drop<T>> of IndexView<Matrix3<T>, usize> {
    type Target = T;
    #[inline(always)]
    fn index(self: @Matrix3<T>, index: usize) -> T {
        match index {
            0 => *self.m11,
            1 => *self.m21,
            2 => *self.m31,
            3 => *self.m12,
            4 => *self.m22,
            5 => *self.m32,
            6 => *self.m13,
            7 => *self.m23,
            8 => *self.m33,
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// `m.get((i, j))` / `m.index(..)`: the component at `(row, column)`. `get` is `None` out of
/// bounds, `index` panics with `nalgebra: index out of bounds`. Upstream: `Matrix::get` /
/// `Matrix::index` (their `MatrixIndex` argument).
pub impl Matrix3MatrixIndexPair<T, +Copy<T>, +Drop<T>> of MatrixIndex<Matrix3<T>, (usize, usize)> {
    type Output = T;
    #[inline(always)]
    fn get(self: Matrix3<T>, index: (usize, usize)) -> Option<T> {
        let (i, j) = index;
        match j {
            0 => match i {
                0 => Option::Some(self.m11),
                1 => Option::Some(self.m21),
                2 => Option::Some(self.m31),
                _ => Option::None,
            },
            1 => match i {
                0 => Option::Some(self.m12),
                1 => Option::Some(self.m22),
                2 => Option::Some(self.m32),
                _ => Option::None,
            },
            2 => match i {
                0 => Option::Some(self.m13),
                1 => Option::Some(self.m23),
                2 => Option::Some(self.m33),
                _ => Option::None,
            },
            _ => Option::None,
        }
    }
    #[inline(always)]
    fn index(self: Matrix3<T>, index: (usize, usize)) -> T {
        let (i, j) = index;
        match j {
            0 => match i {
                0 => self.m11,
                1 => self.m21,
                2 => self.m31,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            1 => match i {
                0 => self.m12,
                1 => self.m22,
                2 => self.m32,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            2 => match i {
                0 => self.m13,
                1 => self.m23,
                2 => self.m33,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// `m[(i, j)]`: the component at `(row, column)`. Panics with `nalgebra: index out of bounds`.
/// Upstream: `Index<(usize, usize)>`.
pub impl Matrix3IndexPair<T, +Copy<T>, +Drop<T>> of IndexView<Matrix3<T>, (usize, usize)> {
    type Target = T;
    #[inline(always)]
    fn index(self: @Matrix3<T>, index: (usize, usize)) -> T {
        let (i, j) = index;
        match j {
            0 => match i {
                0 => *self.m11,
                1 => *self.m21,
                2 => *self.m31,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            1 => match i {
                0 => *self.m12,
                1 => *self.m22,
                2 => *self.m32,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            2 => match i {
                0 => *self.m13,
                1 => *self.m23,
                2 => *self.m33,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// The component-wise partial order: `a < b` when EVERY component of `a` is smaller than `b`'s
/// (likewise `<=`, `>`, `>=`), so two matrices may be unordered (`!(a < b) && !(a >= b)`).
/// Upstream: `PartialOrd for Matrix`.
pub impl Matrix3PartialOrd<T, +PartialOrd<T>, +Copy<T>, +Drop<T>> of PartialOrd<Matrix3<T>> {
    #[inline(always)]
    fn lt(lhs: Matrix3<T>, rhs: Matrix3<T>) -> bool {
        lhs.m11 < rhs.m11
            && lhs.m21 < rhs.m21
            && lhs.m31 < rhs.m31
            && lhs.m12 < rhs.m12
            && lhs.m22 < rhs.m22
            && lhs.m32 < rhs.m32
            && lhs.m13 < rhs.m13
            && lhs.m23 < rhs.m23
            && lhs.m33 < rhs.m33
    }
    #[inline(always)]
    fn le(lhs: Matrix3<T>, rhs: Matrix3<T>) -> bool {
        lhs.m11 <= rhs.m11
            && lhs.m21 <= rhs.m21
            && lhs.m31 <= rhs.m31
            && lhs.m12 <= rhs.m12
            && lhs.m22 <= rhs.m22
            && lhs.m32 <= rhs.m32
            && lhs.m13 <= rhs.m13
            && lhs.m23 <= rhs.m23
            && lhs.m33 <= rhs.m33
    }
    #[inline(always)]
    fn gt(lhs: Matrix3<T>, rhs: Matrix3<T>) -> bool {
        lhs.m11 > rhs.m11
            && lhs.m21 > rhs.m21
            && lhs.m31 > rhs.m31
            && lhs.m12 > rhs.m12
            && lhs.m22 > rhs.m22
            && lhs.m32 > rhs.m32
            && lhs.m13 > rhs.m13
            && lhs.m23 > rhs.m23
            && lhs.m33 > rhs.m33
    }
    #[inline(always)]
    fn ge(lhs: Matrix3<T>, rhs: Matrix3<T>) -> bool {
        lhs.m11 >= rhs.m11
            && lhs.m21 >= rhs.m21
            && lhs.m31 >= rhs.m31
            && lhs.m12 >= rhs.m12
            && lhs.m22 >= rhs.m22
            && lhs.m32 >= rhs.m32
            && lhs.m13 >= rhs.m13
            && lhs.m23 >= rhs.m23
            && lhs.m33 >= rhs.m33
    }
}

/// The component-wise bounds: every component `Bounded::<T>::MIN` / `MAX`. Upstream: `num::Bounded
/// for Matrix`.
pub impl Matrix3Bounded<T, +Bounded<T>, +Drop<T>> of Bounded<Matrix3<T>> {
    const MIN: Matrix3<T> = Matrix3 {
        m11: Bounded::<T>::MIN,
        m21: Bounded::<T>::MIN,
        m31: Bounded::<T>::MIN,
        m12: Bounded::<T>::MIN,
        m22: Bounded::<T>::MIN,
        m32: Bounded::<T>::MIN,
        m13: Bounded::<T>::MIN,
        m23: Bounded::<T>::MIN,
        m33: Bounded::<T>::MIN,
    };
    const MAX: Matrix3<T> = Matrix3 {
        m11: Bounded::<T>::MAX,
        m21: Bounded::<T>::MAX,
        m31: Bounded::<T>::MAX,
        m12: Bounded::<T>::MAX,
        m22: Bounded::<T>::MAX,
        m32: Bounded::<T>::MAX,
        m13: Bounded::<T>::MAX,
        m23: Bounded::<T>::MAX,
        m33: Bounded::<T>::MAX,
    };
}

/// The multiplicative identity (`identity()`), exactly. Upstream: `num::One for SquareMatrix`.
pub impl Matrix3One<T, impl R: Real<T>, +PartialEq<T>, +Copy<T>, +Drop<T>> of One<Matrix3<T>> {
    #[inline(always)]
    fn one() -> Matrix3<T> {
        Matrix3 {
            m11: R::one(),
            m21: R::zero(),
            m31: R::zero(),
            m12: R::zero(),
            m22: R::one(),
            m32: R::zero(),
            m13: R::zero(),
            m23: R::zero(),
            m33: R::one(),
        }
    }
    #[inline(always)]
    fn is_one(self: @Matrix3<T>) -> bool {
        *self.m11 == R::one()
            && *self.m21 == R::zero()
            && *self.m31 == R::zero()
            && *self.m12 == R::zero()
            && *self.m22 == R::one()
            && *self.m32 == R::zero()
            && *self.m13 == R::zero()
            && *self.m23 == R::zero()
            && *self.m33 == R::one()
    }
    #[inline(always)]
    fn is_non_one(self: @Matrix3<T>) -> bool {
        !Self::is_one(self)
    }
}

/// The 3x3 matrix of the given COLUMNS (`[[m11, m21, ..], [m12, ..], ..]`). Upstream: `From<[[T;
/// R]; C]>`.
pub impl Matrix3FromColumnArrays<T, +Drop<T>> of Into<[[T; 3]; 3], Matrix3<T>> {
    #[inline(always)]
    fn into(self: [[T; 3]; 3]) -> Matrix3<T> {
        let [c0, c1, c2] = self;
        let [m11, m21, m31] = c0;
        let [m12, m22, m32] = c1;
        let [m13, m23, m33] = c2;
        Matrix3 { m11, m21, m31, m12, m22, m32, m13, m23, m33 }
    }
}

/// The columns of the 3x3 matrix as nested arrays (`[[m11, m21, ..], [m12, ..], ..]`). Upstream:
/// `Into<[[T; R]; C]>`.
pub impl Matrix3IntoColumnArrays<T, +Drop<T>> of Into<Matrix3<T>, [[T; 3]; 3]> {
    #[inline(always)]
    fn into(self: Matrix3<T>) -> [[T; 3]; 3] {
        let Matrix3 { m11, m21, m31, m12, m22, m32, m13, m23, m33 } = self;
        [[m11, m21, m31], [m12, m22, m32], [m13, m23, m33]]
    }
}

/// `self * p`, a `Point3`: the linear map applied to the coordinates of `p`, each coordinate one
/// fused `sum_prod3` (floored once). Panics on overflow. Upstream: `Mul<Point> for Matrix` (`m *
/// p`).
pub impl Matrix3MulPoint<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>,
> of MatrixMul<Matrix3<T>, Point3<T>> {
    type Output = Point3<T>;
    #[inline(always)]
    fn mul_mat(self: Matrix3<T>, rhs: Point3<T>) -> Point3<T> {
        Point3 {
            x: R::sum_prod3(self.m11, rhs.x, self.m12, rhs.y, self.m13, rhs.z),
            y: R::sum_prod3(self.m21, rhs.x, self.m22, rhs.y, self.m23, rhs.z),
            z: R::sum_prod3(self.m31, rhs.x, self.m32, rhs.y, self.m33, rhs.z),
        }
    }
}
