// Generated by tools/shapegen/shapegen.py: do not edit by hand. Template:
// tools/shapegen/shapes.py.
//! `RowVector4`: a statically sized 4-dimensional row vector (upstream `nalgebra::RowVector4`).
//!
//! Every sum of products goes through a fused `Real` kernel: one rounding (floor) and one overflow
//! check per output scalar. Operators (`+`, `-`, unary `-` and their assigning forms, conversions
//! from / to `[T; 4]`) are implemented in this module, so they need no import; the other operations
//! are methods of `RowVector4Trait`, the products with every conformable shape `MatrixMul::mul_mat`
//! (`self * rhs`) and `MatrixTrMul::tr_mul` (`selfᵀ * rhs`).

use core::num::traits::Bounded;
use core::ops::{AddAssign, DivAssign, IndexView, MulAssign, SubAssign};
use simba::scalar::{Real, Transcendental};
use crate::geometry::quaternion::ApproxEqTrait;
use super::errors;
use super::kernels::Powi;
use super::matrix1::Matrix1;
use super::matrix2x4::Matrix2x4;
use super::matrix3x4::Matrix3x4;
use super::matrix4::{Matrix4, Matrix4Trait};
use super::matrix4x2::Matrix4x2;
use super::matrix4x3::Matrix4x3;
use super::matrix4x5::Matrix4x5;
use super::matrix4x6::Matrix4x6;
use super::matrix5x4::Matrix5x4;
use super::matrix6::Matrix6;
use super::matrix6x4::Matrix6x4;
use super::matrix_index::MatrixIndex;
use super::matrix_kronecker::MatrixKronecker;
use super::matrix_mul::MatrixMul;
use super::matrix_tr_mul::MatrixTrMul;
use super::matrix_view::{CropFrom6, FixedColumns, FixedRows, FixedView, PadTo6, ShapeDims};
use super::norm::{EuclideanNorm, LpNorm, Norm, OneNorm, UniformNorm};
use super::row_vector2::RowVector2;
use super::row_vector3::RowVector3;
use super::row_vector5::RowVector5;
use super::row_vector6::RowVector6;
use super::vector2::Vector2;
use super::vector3::Vector3;
use super::vector4::Vector4;
use super::vector5::Vector5;
use super::vector6::Vector6;

/// A 4-dimensional row vector. Components are named like upstream's `Deref` targets (`x, y, z, w,
/// a, b`).
#[derive(Copy, Drop, PartialEq, Serde, Default, Debug, Hash)]
pub struct RowVector4<T> {
    pub x: T,
    pub y: T,
    pub z: T,
    pub w: T,
}

/// Upstream alias `Matrix1x4`: the same type as `RowVector4` (one Cairo struct per shape).
pub type Matrix1x4<T> = RowVector4<T>;

/// Methods of `RowVector4<T>` for any `Real` scalar.
#[generate_trait]
pub impl RowVector4Impl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of RowVector4Trait<T> {
    /// The 4-dimensional row vector with the given components. Upstream: `RowVector4::new`.
    #[inline(always)]
    fn new(x: T, y: T, z: T, w: T) -> RowVector4<T> {
        RowVector4 { x, y, z, w }
    }

    /// The zero 4-dimensional row vector. Upstream: `RowVector4::zeros`.
    #[inline(always)]
    fn zeros() -> RowVector4<T> {
        RowVector4 { x: R::zero(), y: R::zero(), z: R::zero(), w: R::zero() }
    }

    /// The transpose, a `Vector4`. Exact. Upstream: `transpose`.
    #[inline(always)]
    fn transpose(self: RowVector4<T>) -> Vector4<T> {
        Vector4 { x: self.x, y: self.y, z: self.z, w: self.w }
    }

    /// Component-wise absolute value. Exact; panics on overflow (`|MIN|`). Upstream: `abs`.
    #[inline(always)]
    fn abs(self: RowVector4<T>) -> RowVector4<T> {
        RowVector4 { x: R::abs(self.x), y: R::abs(self.y), z: R::abs(self.z), w: R::abs(self.w) }
    }

    /// `self * k`, each component floored once. Panics on overflow. Upstream: `scale` (`self * k`).
    #[inline(always)]
    fn scale(self: RowVector4<T>, k: T) -> RowVector4<T> {
        RowVector4 { x: self.x * k, y: self.y * k, z: self.z * k, w: self.w * k }
    }

    /// Whether every component of `self` is within `ulps` smallest units (raw units for fixed
    /// point) of `other`'s; cannot overflow. Upstream: `approx::AbsDiffEq::abs_diff_eq`, the
    /// tolerance being counted in ulp instead of a float epsilon (DESIGN D3).
    #[inline(always)]
    fn abs_diff_eq(self: RowVector4<T>, other: RowVector4<T>, ulps: u64) -> bool {
        R::abs_diff_eq(self.x, other.x, ulps)
            && R::abs_diff_eq(self.y, other.y, ulps)
            && R::abs_diff_eq(self.z, other.z, ulps)
            && R::abs_diff_eq(self.w, other.w, ulps)
    }

    /// The 4-dimensional row vector whose components all equal `elem`. Upstream:
    /// `RowVector4::repeat`.
    #[inline(always)]
    fn repeat(elem: T) -> RowVector4<T> {
        RowVector4 { x: elem, y: elem, z: elem, w: elem }
    }

    /// Alias of `repeat`. Upstream: `RowVector4::from_element`.
    #[inline(always)]
    fn from_element(elem: T) -> RowVector4<T> {
        RowVector4 { x: elem, y: elem, z: elem, w: elem }
    }

    /// The 4-dimensional row vector whose component `(i, j)` (row, column, 0-based) is `f(i, j)`,
    /// `f` being called in column-major order like upstream. `f` is any closure or `Fn` value of
    /// `(usize, usize)` whose output converts `Into<T>` (the identity included): Cairo cannot state
    /// `Output = T` on the closure without the `associated_item_constraints` experimental feature.
    /// Upstream: `RowVector4::from_fn`.
    fn from_fn<
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (usize, usize)>,
        +Into<Func::Output, T>,
        +Drop<Func::Output>,
    >(
        f: F,
    ) -> RowVector4<T> {
        RowVector4 { x: f(0, 0).into(), y: f(0, 1).into(), z: f(0, 2).into(), w: f(0, 3).into() }
    }

    /// The 4-dimensional row vector of the 4 values of `data`, in row-major order. Panics with
    /// `nalgebra: wrong slice length` unless `data.len() == 4`. Upstream:
    /// `RowVector4::from_row_slice` (`&[T]`).
    ///
    /// `data` is read as ONE fixed-size array (`Span -> @Box<[T; 4]>`, one length check): measured
    /// about 5 times cheaper than a bounds-checked `*data[k]` per component
    /// (`bench_matrix3_from_row_slice__alt_span_index`).
    #[inline(always)]
    fn from_row_slice(data: Span<T>) -> RowVector4<T> {
        let boxed: @Box<[T; 4]> = data.try_into().expect(errors::SLICE_LENGTH);
        let [v0, v1, v2, v3] = boxed.unbox();
        RowVector4 { x: v0, y: v1, z: v2, w: v3 }
    }

    /// The 4-dimensional row vector of the 4 values of `data`, in column-major order. Panics with
    /// `nalgebra: wrong slice length` unless `data.len() == 4`. Upstream:
    /// `RowVector4::from_column_slice` (`&[T]`).
    ///
    /// `data` is read as ONE fixed-size array (`Span -> @Box<[T; 4]>`, one length check): measured
    /// about 5 times cheaper than a bounds-checked `*data[k]` per component
    /// (`bench_matrix3_from_row_slice__alt_span_index`).
    #[inline(always)]
    fn from_column_slice(data: Span<T>) -> RowVector4<T> {
        let boxed: @Box<[T; 4]> = data.try_into().expect(errors::SLICE_LENGTH);
        let [v0, v1, v2, v3] = boxed.unbox();
        RowVector4 { x: v0, y: v1, z: v2, w: v3 }
    }

    /// The 4-dimensional row vector whose first `data.len()` diagonal components are `data`, every
    /// other component zero. Panics with `nalgebra: diagonal too long` when `data.len() > 1`.
    /// Upstream: `RowVector4::from_partial_diagonal` (`&[T]`).
    #[inline(always)]
    fn from_partial_diagonal(data: Span<T>) -> RowVector4<T> {
        let len = data.len();
        if len > 1 {
            core::panic_with_felt252(errors::TOO_MANY_DIAGONAL);
        }
        RowVector4 {
            x: if len > 0 {
                *data[0]
            } else {
                R::zero()
            }, y: R::zero(), z: R::zero(), w: R::zero(),
        }
    }

    /// `true` when every component is zero. Upstream: `Zero::is_zero`.
    #[inline(always)]
    fn is_zero(self: RowVector4<T>) -> bool {
        self.x == R::zero() && self.y == R::zero() && self.z == R::zero() && self.w == R::zero()
    }

    /// Component-wise (Hadamard) product, each component floored once. Panics on overflow.
    /// Upstream: `component_mul`.
    #[inline(always)]
    fn component_mul(self: RowVector4<T>, rhs: RowVector4<T>) -> RowVector4<T> {
        RowVector4 { x: self.x * rhs.x, y: self.y * rhs.y, z: self.z * rhs.z, w: self.w * rhs.w }
    }

    /// `self = self.component_mul(rhs)`. Upstream: `component_mul_assign`.
    #[inline(always)]
    fn component_mul_assign(ref self: RowVector4<T>, rhs: RowVector4<T>) {
        self =
            RowVector4 {
                x: self.x * rhs.x, y: self.y * rhs.y, z: self.z * rhs.z, w: self.w * rhs.w,
            };
    }

    /// Component-wise quotient, each component rounded to nearest (ties to even). Panics on a zero
    /// component of `rhs` and on overflow. Upstream: `component_div`.
    #[inline(always)]
    fn component_div(self: RowVector4<T>, rhs: RowVector4<T>) -> RowVector4<T> {
        RowVector4 {
            x: R::div(self.x, rhs.x),
            y: R::div(self.y, rhs.y),
            z: R::div(self.z, rhs.z),
            w: R::div(self.w, rhs.w),
        }
    }

    /// `self = self.component_div(rhs)`. Upstream: `component_div_assign`.
    #[inline(always)]
    fn component_div_assign(ref self: RowVector4<T>, rhs: RowVector4<T>) {
        self =
            RowVector4 {
                x: R::div(self.x, rhs.x),
                y: R::div(self.y, rhs.y),
                z: R::div(self.z, rhs.z),
                w: R::div(self.w, rhs.w),
            };
    }

    /// Component-wise minimum (infimum). Exact. Upstream: `inf`.
    #[inline(always)]
    fn inf(self: RowVector4<T>, other: RowVector4<T>) -> RowVector4<T> {
        RowVector4 {
            x: R::min(self.x, other.x),
            y: R::min(self.y, other.y),
            z: R::min(self.z, other.z),
            w: R::min(self.w, other.w),
        }
    }

    /// Component-wise maximum (supremum). Exact. Upstream: `sup`.
    #[inline(always)]
    fn sup(self: RowVector4<T>, other: RowVector4<T>) -> RowVector4<T> {
        RowVector4 {
            x: R::max(self.x, other.x),
            y: R::max(self.y, other.y),
            z: R::max(self.z, other.z),
            w: R::max(self.w, other.w),
        }
    }

    /// `(self.inf(other), self.sup(other))`. Exact. Upstream: `inf_sup`.
    #[inline(always)]
    fn inf_sup(self: RowVector4<T>, other: RowVector4<T>) -> (RowVector4<T>, RowVector4<T>) {
        (Self::inf(self, other), Self::sup(self, other))
    }

    /// `self + k` added to every component. Exact; panics on overflow. Upstream: `add_scalar`.
    #[inline(always)]
    fn add_scalar(self: RowVector4<T>, k: T) -> RowVector4<T> {
        RowVector4 { x: self.x + k, y: self.y + k, z: self.z + k, w: self.w + k }
    }

    /// `self = alpha * a ∘ b + beta * self` (component-wise product): per component `alpha * a`
    /// is floored, then the two products are ONE fused `sum_prod2` (floored once). Panics on
    /// overflow.
    /// Upstream: `cmpy` (which skips reading `self` when `beta` is zero: a difference only for NaN,
    /// which fixed point has not).
    #[inline(always)]
    fn cmpy(ref self: RowVector4<T>, alpha: T, a: RowVector4<T>, b: RowVector4<T>, beta: T) {
        self =
            RowVector4 {
                x: R::sum_prod2(alpha * a.x, b.x, beta, self.x),
                y: R::sum_prod2(alpha * a.y, b.y, beta, self.y),
                z: R::sum_prod2(alpha * a.z, b.z, beta, self.z),
                w: R::sum_prod2(alpha * a.w, b.w, beta, self.w),
            };
    }

    /// `self = alpha * a / b + beta * self` (component-wise quotient): per component `alpha * a` is
    /// floored, divided by `b` (rounded to nearest), then `beta * self + quotient` is ONE `mul_add`
    /// (floored once). Panics on a zero component of `b` and on overflow. Upstream: `cdpy`.
    #[inline(always)]
    fn cdpy(ref self: RowVector4<T>, alpha: T, a: RowVector4<T>, b: RowVector4<T>, beta: T) {
        self =
            RowVector4 {
                x: R::mul_add(beta, self.x, R::div(alpha * a.x, b.x)),
                y: R::mul_add(beta, self.y, R::div(alpha * a.y, b.y)),
                z: R::mul_add(beta, self.z, R::div(alpha * a.z, b.z)),
                w: R::mul_add(beta, self.w, R::div(alpha * a.w, b.w)),
            };
    }

    /// The smallest component. Exact. Upstream: `min`.
    #[inline(always)]
    fn min(self: RowVector4<T>) -> T {
        R::min(R::min(R::min(self.x, self.y), self.z), self.w)
    }

    /// The largest component. Exact. Upstream: `max`.
    #[inline(always)]
    fn max(self: RowVector4<T>) -> T {
        R::max(R::max(R::max(self.x, self.y), self.z), self.w)
    }

    /// The smallest absolute value of a component. Panics on the scalar's `MIN`. Upstream: `amin`.
    #[inline(always)]
    fn amin(self: RowVector4<T>) -> T {
        R::min(R::min(R::min(R::abs(self.x), R::abs(self.y)), R::abs(self.z)), R::abs(self.w))
    }

    /// The largest absolute value of a component (the uniform norm). Panics on the scalar's `MIN`.
    /// Upstream: `amax`.
    #[inline(always)]
    fn amax(self: RowVector4<T>) -> T {
        R::max(R::max(R::max(R::abs(self.x), R::abs(self.y)), R::abs(self.z)), R::abs(self.w))
    }

    /// `amin`: the modulus of a real scalar is its absolute value. Upstream: `camin`.
    #[inline(always)]
    fn camin(self: RowVector4<T>) -> T {
        R::min(R::min(R::min(R::abs(self.x), R::abs(self.y)), R::abs(self.z)), R::abs(self.w))
    }

    /// `amax`: the modulus of a real scalar is its absolute value. Upstream: `camax`.
    #[inline(always)]
    fn camax(self: RowVector4<T>) -> T {
        R::max(R::max(R::max(R::abs(self.x), R::abs(self.y)), R::abs(self.z)), R::abs(self.w))
    }

    /// `(row, column)` of the component with the largest absolute value, the first one in
    /// column-major order on ties. Panics on the scalar's `MIN`. Upstream: `iamax_full`.
    #[inline(always)]
    fn iamax_full(self: RowVector4<T>) -> (usize, usize) {
        let mut best: (usize, usize) = (0, 0);
        let mut m = R::abs(self.x);
        let v = R::abs(self.y);
        if v > m {
            m = v;
            best = (0, 1);
        }
        let v = R::abs(self.z);
        if v > m {
            m = v;
            best = (0, 2);
        }
        let v = R::abs(self.w);
        if v > m {
            best = (0, 3);
        }
        best
    }

    /// `iamax_full`: the modulus of a real scalar is its absolute value. Upstream: `icamax_full`.
    #[inline(always)]
    fn icamax_full(self: RowVector4<T>) -> (usize, usize) {
        Self::iamax_full(self)
    }

    /// Dot product (the sum of the component-wise products, upstream's Frobenius inner product for
    /// matrices): the exact sum is floored ONCE, only the result must fit. Upstream: `dot`.
    #[inline(always)]
    fn dot(self: RowVector4<T>, rhs: RowVector4<T>) -> T {
        R::sum_prod4(self.x, rhs.x, self.y, rhs.y, self.z, rhs.z, self.w, rhs.w)
    }

    /// Squared Euclidean (Frobenius) norm: the exact sum of squares floored once. Panics on
    /// overflow (above a norm of about 46 340 in Q32.32 only `norm` works). Upstream:
    /// `norm_squared`.
    #[inline(always)]
    fn norm_squared(self: RowVector4<T>) -> T {
        R::norm_squared4(self.x, self.y, self.z, self.w)
    }

    /// Euclidean (Frobenius) norm: square root of the UNSCALED exact sum of squares, floored once.
    /// No intermediate overflow: only the result must fit. Upstream: `norm`.
    #[inline(always)]
    fn norm(self: RowVector4<T>) -> T {
        R::norm4(self.x, self.y, self.z, self.w)
    }

    /// Alias of `norm_squared`. Upstream: `magnitude_squared`.
    #[inline(always)]
    fn magnitude_squared(self: RowVector4<T>) -> T {
        Self::norm_squared(self)
    }

    /// Alias of `norm`. Upstream: `magnitude`.
    #[inline(always)]
    fn magnitude(self: RowVector4<T>) -> T {
        Self::norm(self)
    }

    /// `(self - rhs).norm()`: the differences are exact, then one fused norm. Panics when a
    /// difference or the result overflows. Upstream: `metric_distance`.
    #[inline(always)]
    fn metric_distance(self: RowVector4<T>, rhs: RowVector4<T>) -> T {
        R::norm4(self.x - rhs.x, self.y - rhs.y, self.z - rhs.z, self.w - rhs.w)
    }

    /// `self / k`, each component the correctly rounded quotient (nearest, ties to even), through 1
    /// prepared-divisor `Real::divN` call(s), bit-identical to one `Real::div` per component.
    /// Panics on a zero `k` and on overflow. Upstream: `unscale` (`self / k`).
    #[inline(always)]
    fn unscale(self: RowVector4<T>, k: T) -> RowVector4<T> {
        let (x, y, z, w) = R::div4(self.x, self.y, self.z, self.w, k);
        RowVector4 { x, y, z, w }
    }

    /// `self / self.norm()`: the floored norm, then `unscale`. Panics with a division by zero when
    /// the norm is zero, and on overflow when the norm does not fit. Upstream: `normalize`.
    #[inline(always)]
    fn normalize(self: RowVector4<T>) -> RowVector4<T> {
        Self::unscale(self, R::norm4(self.x, self.y, self.z, self.w))
    }

    /// `Some(self.normalize())`, or `None` when the norm is `<= min_norm` (never divides by zero
    /// for `min_norm >= 0`). Upstream: `try_normalize`.
    #[inline(always)]
    fn try_normalize(self: RowVector4<T>, min_norm: T) -> Option<RowVector4<T>> {
        let n = R::norm4(self.x, self.y, self.z, self.w);
        if n <= min_norm {
            None
        } else {
            Some(Self::unscale(self, n))
        }
    }

    /// `self` when its norm is `<= max`, otherwise `self.scale(max / norm)` (the ratio rounded to
    /// nearest, like upstream's `max / n`). Panics only when the norm does not fit. Upstream:
    /// `cap_magnitude`.
    #[inline(always)]
    fn cap_magnitude(self: RowVector4<T>, max: T) -> RowVector4<T> {
        let n = R::norm4(self.x, self.y, self.z, self.w);
        if n <= max {
            self
        } else {
            Self::scale(self, R::div(max, n))
        }
    }

    /// Scales `self` to the norm `magnitude` (`self.scale(magnitude / norm)`, the ratio rounded to
    /// nearest) when its norm is `> min_magnitude`, leaves it unchanged otherwise. Upstream:
    /// `try_set_magnitude` (`&mut self`).
    #[inline(always)]
    fn try_set_magnitude(ref self: RowVector4<T>, magnitude: T, min_magnitude: T) {
        let n = Self::norm(self);
        if n > min_magnitude {
            self = Self::scale(self, R::div(magnitude, n));
        }
    }

    /// The induced 1-norm: the largest absolute column sum (the L1 norm of a column vector, the
    /// largest absolute value of a row vector). Exact; panics on overflow. Upstream: `one_norm`.
    #[inline(always)]
    fn one_norm(self: RowVector4<T>) -> T {
        R::max(R::max(R::max(R::abs(self.x), R::abs(self.y)), R::abs(self.z)), R::abs(self.w))
    }

    /// The conjugate transpose, a `Vector4`: the transpose for a real scalar. Exact. Upstream:
    /// `adjoint`.
    #[inline(always)]
    fn adjoint(self: RowVector4<T>) -> Vector4<T> {
        Self::transpose(self)
    }

    /// Alias of `adjoint` (deprecated upstream). Upstream: `conjugate_transpose`.
    #[inline(always)]
    fn conjugate_transpose(self: RowVector4<T>) -> Vector4<T> {
        Self::transpose(self)
    }

    /// The component-wise conjugate: `self` for a real scalar. Upstream: `conjugate`.
    #[inline(always)]
    fn conjugate(self: RowVector4<T>) -> RowVector4<T> {
        self
    }

    /// The same shape with every component converted by `Into<T, U>`. With the single scalar of
    /// this library (`Fixed`) it is the identity; it exists for scalar-generic code. Upstream:
    /// `cast` (and `SubsetOf<Matrix<U>>`, the `nalgebra::convert` it goes through).
    fn cast<U, +Into<T, U>, +Drop<U>>(self: RowVector4<T>) -> RowVector4<U> {
        RowVector4 { x: self.x.into(), y: self.y.into(), z: self.z.into(), w: self.w.into() }
    }

    /// `Some` of the shape with every component converted by `TryInto<T, U>`, `None` as soon as one
    /// conversion fails. Upstream: `try_cast`.
    fn try_cast<U, +TryInto<T, U>, +Drop<U>>(self: RowVector4<T>) -> Option<RowVector4<U>> {
        let x: U = self.x.try_into()?;
        let y: U = self.y.try_into()?;
        let z: U = self.z.try_into()?;
        let w: U = self.w.try_into()?;
        Option::Some(RowVector4 { x, y, z, w })
    }

    /// `true` when every component is within `epsilon` ulp of `other`'s, or has the same sign and
    /// lies within `max_relative` times the larger magnitude of the two (`|a - b| <= max(|a|, |b|)
    /// · max_relative`). Panics on a component equal to the scalar's `MIN`, and on overflow of
    /// that product (only possible with `max_relative > 1`). Upstream:
    /// `approx::RelativeEq::relative_eq`, `epsilon` counted in ulp instead of a float epsilon
    /// (DESIGN D3).
    #[inline(always)]
    fn relative_eq(
        self: RowVector4<T>, other: RowVector4<T>, epsilon: u64, max_relative: T,
    ) -> bool {
        ApproxEqTrait::relative_eq(self.x, other.x, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.y, other.y, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.z, other.z, epsilon, max_relative)
            && ApproxEqTrait::relative_eq(self.w, other.w, epsilon, max_relative)
    }

    /// `true` when every component is within `epsilon` ulp of `other`'s, or has the same sign and
    /// lies within `max_ulps` ulp (in fixed point the distance in ulp IS the raw difference; the
    /// `max_ulps` budget does not cross zero, like upstream's float `ulps_eq`). Cannot overflow.
    /// Upstream: `approx::UlpsEq::ulps_eq`.
    #[inline(always)]
    fn ulps_eq(self: RowVector4<T>, other: RowVector4<T>, epsilon: u64, max_ulps: u32) -> bool {
        ApproxEqTrait::ulps_eq(self.x, other.x, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.y, other.y, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.z, other.z, epsilon, max_ulps)
            && ApproxEqTrait::ulps_eq(self.w, other.w, epsilon, max_ulps)
    }

    /// The 4-dimensional row vector of `f(x)` for every component `x` (called in column-major
    /// order). `f` is any closure or `Fn` value; Cairo closures take their arguments by value and
    /// cannot mutate their captures. Upstream: `map`.
    #[inline]
    fn map<F, +Drop<F>, impl Func: core::ops::Fn<F, (T,)>, +Drop<Func::Output>>(
        self: RowVector4<T>, f: F,
    ) -> RowVector4<Func::Output> {
        RowVector4 { x: f(self.x), y: f(self.y), z: f(self.z), w: f(self.w) }
    }

    /// The 4-dimensional row vector of `f(i, j, x)` for every component `x` at row `i`, column `j`
    /// (0-based, column-major order). `f` is any closure or `Fn` value; Cairo closures take their
    /// arguments by value and cannot mutate their captures. Upstream: `map_with_location`.
    #[inline]
    fn map_with_location<
        F, +Drop<F>, impl Func: core::ops::Fn<F, (usize, usize, T)>, +Drop<Func::Output>,
    >(
        self: RowVector4<T>, f: F,
    ) -> RowVector4<Func::Output> {
        RowVector4 {
            x: f(0, 0, self.x), y: f(0, 1, self.y), z: f(0, 2, self.z), w: f(0, 3, self.w),
        }
    }

    /// The 4-dimensional row vector of `f(a, b)` for the components `a` of `self` and `b` of `rhs`
    /// at the same position. `f` is any closure or `Fn` value; Cairo closures take their arguments
    /// by value and cannot mutate their captures. Upstream: `zip_map`.
    #[inline]
    fn zip_map<
        T2,
        +Copy<T2>,
        +Drop<T2>,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (T, T2)>,
        +Drop<Func::Output>,
    >(
        self: RowVector4<T>, rhs: RowVector4<T2>, f: F,
    ) -> RowVector4<Func::Output> {
        RowVector4 {
            x: f(self.x, rhs.x), y: f(self.y, rhs.y), z: f(self.z, rhs.z), w: f(self.w, rhs.w),
        }
    }

    /// The 4-dimensional row vector of `f(a, b, c)` for the components of `self`, `b` and `c` at
    /// the same position. `f` is any closure or `Fn` value; Cairo closures take their arguments by
    /// value and cannot mutate their captures. Upstream: `zip_zip_map`.
    #[inline]
    fn zip_zip_map<
        T2,
        T3,
        +Copy<T2>,
        +Drop<T2>,
        +Copy<T3>,
        +Drop<T3>,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (T, T2, T3)>,
        +Drop<Func::Output>,
    >(
        self: RowVector4<T>, b: RowVector4<T2>, c: RowVector4<T3>, f: F,
    ) -> RowVector4<Func::Output> {
        RowVector4 {
            x: f(self.x, b.x, c.x),
            y: f(self.y, b.y, c.y),
            z: f(self.z, b.z, c.z),
            w: f(self.w, b.w, c.w),
        }
    }

    /// `f(.. f(f(init, x0), x1) .., x3)` over the components in column-major order. The closure's
    /// output converts `Into<Acc>` (the identity included): Cairo cannot state `Output = Acc`
    /// without the `associated_item_constraints` experimental feature. `f` is any closure or `Fn`
    /// value; Cairo closures take their arguments by value and cannot mutate their captures.
    /// Upstream: `fold`.
    #[inline]
    fn fold<Acc, F, +Drop<F>, impl Func: core::ops::Fn<F, (Acc, T)>, +Into<Func::Output, Acc>>(
        self: RowVector4<T>, init: Acc, f: F,
    ) -> Acc {
        let acc: Acc = f(init, self.x).into();
        let acc: Acc = f(acc, self.y).into();
        let acc: Acc = f(acc, self.z).into();
        f(acc, self.w).into()
    }

    /// `init_f(Some(x0))`, then `f(acc, x)` over the other components in column-major order:
    /// upstream's `fold_with` (`init_f` receives the first component, `None` only for an empty
    /// matrix, which a static shape never is). The accumulator has the type of `init_f`'s output;
    /// `f`'s output converts `Into` it. The closures receive values instead of upstream's `&T`.
    /// Upstream: `fold_with`.
    #[inline]
    fn fold_with<
        G,
        +Drop<G>,
        impl Init: core::ops::Fn<G, (Option<T>,)>,
        +Drop<Init::Output>,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (Init::Output, T)>,
        +Into<Func::Output, Init::Output>,
    >(
        self: RowVector4<T>, init_f: G, f: F,
    ) -> Init::Output {
        let acc: Init::Output = init_f(Option::Some(self.x));
        let acc: Init::Output = f(acc, self.y).into();
        let acc: Init::Output = f(acc, self.z).into();
        f(acc, self.w).into()
    }

    /// `fold` over the pairs of components of `self` and `rhs` at the same position: `f(acc, a,
    /// b)`, column-major. `f` is any closure or `Fn` value; Cairo closures take their arguments by
    /// value and cannot mutate their captures. Upstream: `zip_fold`.
    #[inline]
    fn zip_fold<
        T2,
        +Copy<T2>,
        +Drop<T2>,
        Acc,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (Acc, T, T2)>,
        +Into<Func::Output, Acc>,
    >(
        self: RowVector4<T>, rhs: RowVector4<T2>, init: Acc, f: F,
    ) -> Acc {
        let acc: Acc = f(init, self.x, rhs.x).into();
        let acc: Acc = f(acc, self.y, rhs.y).into();
        let acc: Acc = f(acc, self.z, rhs.z).into();
        f(acc, self.w, rhs.w).into()
    }

    /// Replaces every component `x` by `f(x)` (column-major order). Upstream's closure is
    /// `FnMut(&mut T)`, writing through the reference; a Cairo closure cannot, so it RETURNS the
    /// new component (its output converts `Into<T>`). Upstream: `apply`.
    #[inline]
    fn apply<F, +Drop<F>, impl Func: core::ops::Fn<F, (T,)>, +Into<Func::Output, T>>(
        ref self: RowVector4<T>, f: F,
    ) {
        self =
            RowVector4 {
                x: f(self.x).into(), y: f(self.y).into(), z: f(self.z).into(), w: f(self.w).into(),
            };
    }

    /// `self` with every component `x` replaced by `f(x)`: `apply` by value. Upstream's closure is
    /// `FnMut(&mut T)`, writing through the reference; a Cairo closure cannot, so it RETURNS the
    /// new component (its output converts `Into<T>`). Upstream: `apply_into`.
    #[inline]
    fn apply_into<F, +Drop<F>, impl Func: core::ops::Fn<F, (T,)>, +Into<Func::Output, T>>(
        self: RowVector4<T>, f: F,
    ) -> RowVector4<T> {
        RowVector4 {
            x: f(self.x).into(), y: f(self.y).into(), z: f(self.z).into(), w: f(self.w).into(),
        }
    }

    /// Replaces every component `a` by `f(a, b)`, `b` the component of `rhs` at the same position.
    /// Upstream's closure is `FnMut(&mut T)`, writing through the reference; a Cairo closure
    /// cannot, so it RETURNS the new component (its output converts `Into<T>`). Upstream:
    /// `zip_apply`.
    #[inline]
    fn zip_apply<
        T2,
        +Copy<T2>,
        +Drop<T2>,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (T, T2)>,
        +Into<Func::Output, T>,
    >(
        ref self: RowVector4<T>, rhs: RowVector4<T2>, f: F,
    ) {
        self =
            RowVector4 {
                x: f(self.x, rhs.x).into(),
                y: f(self.y, rhs.y).into(),
                z: f(self.z, rhs.z).into(),
                w: f(self.w, rhs.w).into(),
            };
    }

    /// Replaces every component `a` by `f(a, b, c)`, `b` and `c` the components of `b` and `c` at
    /// the same position. Upstream's closure is `FnMut(&mut T)`, writing through the reference; a
    /// Cairo closure cannot, so it RETURNS the new component (its output converts `Into<T>`).
    /// Upstream: `zip_zip_apply`.
    #[inline]
    fn zip_zip_apply<
        T2,
        T3,
        +Copy<T2>,
        +Drop<T2>,
        +Copy<T3>,
        +Drop<T3>,
        F,
        +Drop<F>,
        impl Func: core::ops::Fn<F, (T, T2, T3)>,
        +Into<Func::Output, T>,
    >(
        ref self: RowVector4<T>, b: RowVector4<T2>, c: RowVector4<T3>, f: F,
    ) {
        self =
            RowVector4 {
                x: f(self.x, b.x, c.x).into(),
                y: f(self.y, b.y, c.y).into(),
                z: f(self.z, b.z, c.z).into(),
                w: f(self.w, b.w, c.w).into(),
            };
    }

    /// Sets every component to `f()` (one call per component, column-major). The closure's output
    /// converts `Into<T>`. Upstream: `fill_with` (`impl Fn() -> T`).
    #[inline]
    fn fill_with<F, +Drop<F>, impl Func: core::ops::Fn<F, ()>, +Into<Func::Output, T>>(
        ref self: RowVector4<T>, f: F,
    ) {
        self = RowVector4 { x: f().into(), y: f().into(), z: f().into(), w: f().into() };
    }

    /// Sets every component to `val`. Upstream: `fill`.
    #[inline(always)]
    fn fill(ref self: RowVector4<T>, val: T) {
        self = RowVector4 { x: val, y: val, z: val, w: val };
    }

    /// Sets the 1 diagonal components to `val`, the others unchanged. Upstream: `fill_diagonal`.
    #[inline(always)]
    fn fill_diagonal(ref self: RowVector4<T>, val: T) {
        self = RowVector4 { x: val, y: self.y, z: self.z, w: self.w };
    }

    /// Sets `self` to the identity: ones on the diagonal, zeros elsewhere (`fill(0)` then
    /// `fill_diagonal(1)`). Upstream: `fill_with_identity`.
    #[inline(always)]
    fn fill_with_identity(ref self: RowVector4<T>) {
        self = RowVector4 { x: R::one(), y: R::zero(), z: R::zero(), w: R::zero() };
    }

    /// Sets the 4 components of row `i` to `val`. Panics with `nalgebra: index out of bounds` for
    /// `i >= 1`. Upstream: `fill_row`.
    ///
    /// ONE `match` on `i` selects the literal: measured 2.1 times cheaper than one comparison per
    /// component (`bench_matrix4_fill_row__alt_per_component`).
    #[inline(always)]
    fn fill_row(ref self: RowVector4<T>, i: usize, val: T) {
        self = match i {
            0 => RowVector4 { x: val, y: val, z: val, w: val },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        };
    }

    /// Sets the 1 components of column `j` to `val`. Panics with `nalgebra: index out of bounds`
    /// for `j >= 4`. Upstream: `fill_column`.
    #[inline(always)]
    fn fill_column(ref self: RowVector4<T>, j: usize, val: T) {
        self = match j {
            0 => RowVector4 { x: val, y: self.y, z: self.z, w: self.w },
            1 => RowVector4 { x: self.x, y: val, z: self.z, w: self.w },
            2 => RowVector4 { x: self.x, y: self.y, z: val, w: self.w },
            3 => RowVector4 { x: self.x, y: self.y, z: self.z, w: val },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        };
    }

    /// Sets every component `(i, j)` with `i >= j + shift` to `val`: the lower triangle with the
    /// diagonal for `shift = 0`, without it for `shift = 1`, leaving `shift - 1` subdiagonals as
    /// well above; nothing changes for `shift >= 1`. ONE `match` on `shift` selects the literal:
    /// measured 2.7 times cheaper than one threshold test per component
    /// (`bench_matrix4_fill_lower_triangle__alt_per_component`). Upstream: `fill_lower_triangle`.
    #[inline(always)]
    fn fill_lower_triangle(ref self: RowVector4<T>, val: T, shift: usize) {
        self = match shift {
            0 => RowVector4 { x: val, y: self.y, z: self.z, w: self.w },
            _ => self,
        };
    }

    /// Sets every component `(i, j)` with `j >= i + shift` to `val`: the upper triangle with the
    /// diagonal for `shift = 0`, without it for `shift = 1`, leaving `shift - 1` superdiagonals as
    /// well below; nothing changes for `shift >= 4`. ONE `match` on `shift` selects the literal.
    /// Upstream: `fill_upper_triangle`.
    #[inline(always)]
    fn fill_upper_triangle(ref self: RowVector4<T>, val: T, shift: usize) {
        self = match shift {
            0 => RowVector4 { x: val, y: val, z: val, w: val },
            1 => RowVector4 { x: self.x, y: val, z: val, w: val },
            2 => RowVector4 { x: self.x, y: self.y, z: val, w: val },
            3 => RowVector4 { x: self.x, y: self.y, z: self.z, w: val },
            _ => self,
        };
    }

    /// Replaces row `i` by `row`, a `RowVector4`. Panics with `nalgebra: index out of bounds` for
    /// `i >= 1`. Upstream: `set_row`.
    #[inline(always)]
    fn set_row(ref self: RowVector4<T>, i: usize, row: RowVector4<T>) {
        self = match i {
            0 => RowVector4 { x: row.x, y: row.y, z: row.z, w: row.w },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        };
    }

    /// Replaces column `j` by `column`, a `Matrix1`. Panics with `nalgebra: index out of bounds`
    /// for `j >= 4`. Upstream: `set_column`.
    #[inline(always)]
    fn set_column(ref self: RowVector4<T>, j: usize, column: Matrix1<T>) {
        self = match j {
            0 => RowVector4 { x: column.x, y: self.y, z: self.z, w: self.w },
            1 => RowVector4 { x: self.x, y: column.x, z: self.z, w: self.w },
            2 => RowVector4 { x: self.x, y: self.y, z: column.x, w: self.w },
            3 => RowVector4 { x: self.x, y: self.y, z: self.z, w: column.x },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        };
    }

    /// Replaces the diagonal by `diag`, a `Matrix1` (upstream requires the length `min(R, C)` = 1).
    /// Upstream: `set_diagonal`.
    #[inline(always)]
    fn set_diagonal(ref self: RowVector4<T>, diag: Matrix1<T>) {
        self = RowVector4 { x: diag.x, y: self.y, z: self.z, w: self.w };
    }

    /// Replaces the first `min(diag.len(), 1)` diagonal components by the values of `diag` (the
    /// extra values are ignored, like upstream's `take`), the others unchanged. Upstream:
    /// `set_partial_diagonal` (an iterator; a `Span` here).
    #[inline(always)]
    fn set_partial_diagonal(ref self: RowVector4<T>, diag: Span<T>) {
        let len = diag.len();
        self =
            RowVector4 {
                x: if len > 0 {
                    *diag[0]
                } else {
                    self.x
                }, y: self.y, z: self.z, w: self.w,
            };
    }

    /// Sets `self` to `other` (a `RowVector4`: upstream requires the same shape). Upstream:
    /// `copy_from`.
    #[inline(always)]
    fn copy_from(ref self: RowVector4<T>, other: RowVector4<T>) {
        self = other;
    }

    /// Sets `self` to the 4 values of `slice` in column-major order (`from_column_slice`). Panics
    /// with `nalgebra: wrong slice length` unless `slice.len() == 4`. Upstream: `copy_from_slice`
    /// (`&[T]`).
    #[inline(always)]
    fn copy_from_slice(ref self: RowVector4<T>, slice: Span<T>) {
        self = Self::from_column_slice(slice);
    }

    /// Sets `self` to the transpose of `other`, a `Vector4`. Exact. Upstream: `tr_copy_from`.
    #[inline(always)]
    fn tr_copy_from(ref self: RowVector4<T>, other: Vector4<T>) {
        self = RowVector4 { x: other.x, y: other.y, z: other.z, w: other.w };
    }

    /// Exchanges the components at `row_cols1` and `row_cols2` (`(row, column)`). Panics with
    /// `nalgebra: index out of bounds` when either is out of the shape. Upstream: `swap`.
    #[inline]
    fn swap(ref self: RowVector4<T>, row_cols1: (usize, usize), row_cols2: (usize, usize)) {
        let a = MatrixIndex::index(self, row_cols1);
        let b = MatrixIndex::index(self, row_cols2);
        self =
            RowVector4EditTrait::replace(
                RowVector4EditTrait::replace(self, row_cols1, b), row_cols2, a,
            );
    }

    /// Exchanges rows `irow1` and `irow2`. Panics with `nalgebra: index out of bounds` when either
    /// is `>= 1`. Upstream: `swap_rows`.
    ///
    /// Two reads and two writes of a row (one `match` each). ONE nested `match` on both rows is 940
    /// gas (15%) cheaper on `Matrix3` (`bench_matrix3_swap_rows__alt_pair_match`) but generates R²
    /// whole-shape literals (about 40 000 lines over the 36 shapes, per method): kept as a
    /// benchmark.
    #[inline]
    fn swap_rows(ref self: RowVector4<T>, irow1: usize, irow2: usize) {
        let a = RowVector4EditTrait::row_at(self, irow1);
        let b = RowVector4EditTrait::row_at(self, irow2);
        Self::set_row(ref self, irow1, b);
        Self::set_row(ref self, irow2, a);
    }

    /// Exchanges columns `icol1` and `icol2`. Panics with `nalgebra: index out of bounds` when
    /// either is `>= 4`. Upstream: `swap_columns`.
    #[inline]
    fn swap_columns(ref self: RowVector4<T>, icol1: usize, icol2: usize) {
        let a = RowVector4EditTrait::column_at(self, icol1);
        let b = RowVector4EditTrait::column_at(self, icol2);
        Self::set_column(ref self, icol1, b);
        Self::set_column(ref self, icol2, a);
    }

    /// `self = -self`. Exact; panics on overflow (`-MIN`). Upstream: `neg_mut`.
    #[inline(always)]
    fn neg_mut(ref self: RowVector4<T>) {
        self = -self;
    }

    /// `self = self.scale(k)`, each component floored once. Panics on overflow. Upstream:
    /// `scale_mut`.
    #[inline(always)]
    fn scale_mut(ref self: RowVector4<T>, k: T) {
        self = Self::scale(self, k);
    }

    /// `self = self.unscale(k)`, each component correctly rounded. Panics on a zero `k` and on
    /// overflow. Upstream: `unscale_mut`.
    #[inline(always)]
    fn unscale_mut(ref self: RowVector4<T>, k: T) {
        self = Self::unscale(self, k);
    }

    /// Normalizes `self` in place (`self = self.normalize()`, bit-identical) and returns the norm
    /// it had. Panics with a division by zero when the norm is zero. Upstream: `normalize_mut`.
    #[inline(always)]
    fn normalize_mut(ref self: RowVector4<T>) -> T {
        let n = Self::norm(self);
        self = Self::unscale(self, n);
        n
    }

    /// Normalizes `self` in place and returns `Some` of the norm it had, or leaves it unchanged and
    /// returns `None` when that norm is `<= min_norm`. Upstream: `try_normalize_mut`.
    #[inline(always)]
    fn try_normalize_mut(ref self: RowVector4<T>, min_norm: T) -> Option<T> {
        let n = Self::norm(self);
        if n <= min_norm {
            return None;
        }
        self = Self::unscale(self, n);
        Some(n)
    }

    /// Scales `self` to the norm `magnitude`: `self.scale(magnitude / norm)`, the ratio rounded to
    /// nearest (like `try_set_magnitude`). Panics with a division by zero when the norm is zero
    /// (upstream's floats give NaN). Upstream: `set_magnitude`.
    #[inline(always)]
    fn set_magnitude(ref self: RowVector4<T>, magnitude: T) {
        let n = Self::norm(self);
        self = Self::scale(self, R::div(magnitude, n));
    }

    /// `self = self.add_scalar(k)`. Exact; panics on overflow. Upstream: `add_scalar_mut`.
    #[inline(always)]
    fn add_scalar_mut(ref self: RowVector4<T>, k: T) {
        self = Self::add_scalar(self, k);
    }

    /// Alias of `component_mul_assign` (deprecated upstream). Upstream: `component_mul_mut`.
    #[inline(always)]
    fn component_mul_mut(ref self: RowVector4<T>, rhs: RowVector4<T>) {
        Self::component_mul_assign(ref self, rhs);
    }

    /// Alias of `component_div_assign` (deprecated upstream). Upstream: `component_div_mut`.
    #[inline(always)]
    fn component_div_mut(ref self: RowVector4<T>, rhs: RowVector4<T>) {
        Self::component_div_assign(ref self, rhs);
    }

    /// Conjugates every component in place: nothing changes for a real scalar. Upstream:
    /// `conjugate_mut`.
    #[inline(always)]
    fn conjugate_mut(ref self: RowVector4<T>) {
        self = Self::conjugate(self);
    }

    /// Writes the transpose of `self` into `out`, a `Vector4`. Exact. Upstream: `transpose_to`.
    #[inline(always)]
    fn transpose_to(self: RowVector4<T>, ref out: Vector4<T>) {
        out = Self::transpose(self);
    }

    /// Writes the adjoint of `self` (its transpose for a real scalar) into `out`, a `Vector4`.
    /// Exact. Upstream: `adjoint_to`.
    #[inline(always)]
    fn adjoint_to(self: RowVector4<T>, ref out: Vector4<T>) {
        out = Self::transpose(self);
    }

    /// Writes the adjoint of `self` (deprecated upstream alias of `adjoint_to`) into `out`, a
    /// `Vector4`. Exact. Upstream: `conjugate_transpose_to`.
    #[inline(always)]
    fn conjugate_transpose_to(self: RowVector4<T>, ref out: Vector4<T>) {
        out = Self::transpose(self);
    }

    /// Writes the sum `self + rhs` into `out`. Exact; panics on overflow. Upstream: `add_to`.
    #[inline(always)]
    fn add_to(self: RowVector4<T>, rhs: RowVector4<T>, ref out: RowVector4<T>) {
        out = self + rhs;
    }

    /// Writes the difference `self - rhs` into `out`. Exact; panics on overflow. Upstream:
    /// `sub_to`.
    #[inline(always)]
    fn sub_to(self: RowVector4<T>, rhs: RowVector4<T>, ref out: RowVector4<T>) {
        out = self - rhs;
    }

    /// The norm `norm` of `self`: `EuclideanNorm {}` (`norm`), `LpNorm { p }` (`lp_norm(p)`),
    /// `OneNorm {}` (`one_norm`) or `UniformNorm {}` (`amax`), through their `Norm` impls (static
    /// dispatch). Upstream: `apply_norm` (`&impl Norm<T>`; the markers are `Copy` values here).
    #[inline]
    fn apply_norm<N, +Drop<N>, impl Nm: Norm<N, RowVector4<T>, T>>(
        self: RowVector4<T>, norm: N,
    ) -> T {
        Nm::norm(@norm, self)
    }

    /// The distance between `self` and `rhs` in the norm `norm` (see `apply_norm`; the Euclidean
    /// one is the fused `metric_distance`, the others the norm of the exact difference). Upstream:
    /// `apply_metric_distance`.
    #[inline]
    fn apply_metric_distance<N, +Drop<N>, impl Nm: Norm<N, RowVector4<T>, T>>(
        self: RowVector4<T>, rhs: RowVector4<T>, norm: N,
    ) -> T {
        Nm::metric_distance(@norm, self, rhs)
    }

    /// The number of rows, 1. Upstream: `nrows`.
    #[inline(always)]
    fn nrows(self: RowVector4<T>) -> usize {
        1
    }

    /// The number of columns, 4. Upstream: `ncols`.
    #[inline(always)]
    fn ncols(self: RowVector4<T>) -> usize {
        4
    }

    /// `(nrows, ncols)`, `(1, 4)`. Upstream: `shape`.
    #[inline(always)]
    fn shape(self: RowVector4<T>) -> (usize, usize) {
        (1, 4)
    }

    /// Whether the shape is square: `false`. Upstream: `is_square`.
    #[inline(always)]
    fn is_square(self: RowVector4<T>) -> bool {
        false
    }

    /// The `(row, column)` of the `i`-th component in column-major order: `(i % 1, i / 1)`, one
    /// `DivRem` (no bounds check, like upstream). Upstream: `vector_to_matrix_index`.
    #[inline(always)]
    fn vector_to_matrix_index(self: RowVector4<T>, i: usize) -> (usize, usize) {
        (0, i)
    }

    /// Row `i`, a `RowVector4` (an owned copy: Cairo has no borrowed views). Panics with `nalgebra:
    /// index out of bounds` for `i >= 1`. ONE `match` on `i` selects the literal (the private
    /// `row_at` of `swap_rows`). Upstream: `row` (a view).
    #[inline(always)]
    fn row(self: RowVector4<T>, i: usize) -> RowVector4<T> {
        RowVector4EditTrait::row_at(self, i)
    }

    /// Column `j`, a `Matrix1` (an owned copy: Cairo has no borrowed views). Panics with `nalgebra:
    /// index out of bounds` for `j >= 4`. ONE `match` on `j` selects the literal (the private
    /// `column_at` of `swap_columns`). Upstream: `column` (a view).
    #[inline(always)]
    fn column(self: RowVector4<T>, j: usize) -> Matrix1<T> {
        RowVector4EditTrait::column_at(self, j)
    }

    /// The upper triangle of `self` (the diagonal included), the components below the diagonal set
    /// to zero. Exact. Upstream: `upper_triangle`.
    #[inline(always)]
    fn upper_triangle(self: RowVector4<T>) -> RowVector4<T> {
        RowVector4 { x: self.x, y: self.y, z: self.z, w: self.w }
    }

    /// The lower triangle of `self` (the diagonal included), the components above the diagonal set
    /// to zero. Exact. Upstream: `lower_triangle`.
    #[inline(always)]
    fn lower_triangle(self: RowVector4<T>) -> RowVector4<T> {
        RowVector4 { x: self.x, y: R::zero(), z: R::zero(), w: R::zero() }
    }

    /// The 4-dimensional row vector whose 1 rows are the given vectors, each a `Vector4` of the
    /// row's 4 components (the argument form of the former `Matrix2/3/4::from_rows`, used by
    /// `linalg`). Exact. Upstream: `from_rows` (a slice of row vectors).
    #[inline(always)]
    fn from_rows(r1: Vector4<T>) -> RowVector4<T> {
        RowVector4 { x: r1.x, y: r1.y, z: r1.z, w: r1.w }
    }

    /// The 4-dimensional row vector whose 4 columns are the given `Matrix1`s. Exact. Upstream:
    /// `from_columns` (a slice of column vectors).
    #[inline(always)]
    fn from_columns(
        c1: Matrix1<T>, c2: Matrix1<T>, c3: Matrix1<T>, c4: Matrix1<T>,
    ) -> RowVector4<T> {
        RowVector4 { x: c1.x, y: c2.x, z: c3.x, w: c4.x }
    }

    /// Whether the columns of `self` are orthonormal: `selfᵀ * self` (fused `tr_mul`, one
    /// rounding per component) is the 4x4 identity within `ulps`. Upstream: `is_orthogonal` (`eps`:
    /// here a tolerance in ulp, DESIGN D3).
    #[inline(always)]
    fn is_orthogonal(self: RowVector4<T>, ulps: u64) -> bool {
        Matrix4Trait::is_identity(MatrixTrMul::tr_mul(self, self), ulps)
    }

    /// `self` with a row of `val` inserted at index `i` (`i <= 1`), a `Matrix2x4`. Panics with
    /// `nalgebra: index out of bounds` for `i > 1`. Upstream: `insert_row`.
    #[inline(always)]
    fn insert_row(self: RowVector4<T>, i: usize, val: T) -> Matrix2x4<T> {
        match i {
            0 => Matrix2x4 {
                m11: val,
                m21: self.x,
                m12: val,
                m22: self.y,
                m13: val,
                m23: self.z,
                m14: val,
                m24: self.w,
            },
            1 => Matrix2x4 {
                m11: self.x,
                m21: val,
                m12: self.y,
                m22: val,
                m13: self.z,
                m23: val,
                m14: self.w,
                m24: val,
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    /// `self` with a column of `val` inserted at index `i` (`i <= 4`), a `RowVector5`. Panics with
    /// `nalgebra: index out of bounds` for `i > 4`. Upstream: `insert_column`.
    #[inline(always)]
    fn insert_column(self: RowVector4<T>, i: usize, val: T) -> RowVector5<T> {
        match i {
            0 => RowVector5 { x: val, y: self.x, z: self.y, w: self.z, a: self.w },
            1 => RowVector5 { x: self.x, y: val, z: self.y, w: self.z, a: self.w },
            2 => RowVector5 { x: self.x, y: self.y, z: val, w: self.z, a: self.w },
            3 => RowVector5 { x: self.x, y: self.y, z: self.z, w: val, a: self.w },
            4 => RowVector5 { x: self.x, y: self.y, z: self.z, w: self.w, a: val },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    /// `self` without its column `i`, a `RowVector3`. Panics with `nalgebra: index out of bounds`
    /// for `i >= 4`. Upstream: `remove_column`.
    #[inline(always)]
    fn remove_column(self: RowVector4<T>, i: usize) -> RowVector3<T> {
        match i {
            0 => RowVector3 { x: self.y, y: self.z, z: self.w },
            1 => RowVector3 { x: self.x, y: self.z, z: self.w },
            2 => RowVector3 { x: self.x, y: self.y, z: self.w },
            3 => RowVector3 { x: self.x, y: self.y, z: self.z },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// The operations of `RowVector4<T>` that need `Transcendental` (inverse trigonometry, `exp`,
/// `ln`):
/// a scalar may implement `Real` only.
#[generate_trait]
pub impl RowVector4AngleImpl<
    T,
    impl R: Real<T>,
    impl Tr: Transcendental<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of RowVector4AngleTrait<T> {
    /// The angle between `self` and `other` seen as vectors of the Frobenius inner product, in `[0,
    /// π]` (up to the rounding of `atan2`); `0` when one of them is zero. Computed as `2 *
    /// atan2(|u - v|, |u + v|)` on the normalized `u`, `v` (Kahan): unlike upstream's `acos(dot /
    /// (|a| *
    /// |b|))` it cannot overflow on long inputs and stays accurate for nearly parallel ones. Panics
    /// when a norm does not fit. Upstream: `angle`.
    fn angle(self: RowVector4<T>, other: RowVector4<T>) -> T {
        let n1 = RowVector4Trait::norm(self);
        let n2 = RowVector4Trait::norm(other);
        if n1 == R::zero() || n2 == R::zero() {
            return R::zero();
        }
        let u = RowVector4Trait::unscale(self, n1);
        let v = RowVector4Trait::unscale(other, n2);
        let half = Tr::atan2(RowVector4Trait::metric_distance(u, v), RowVector4Trait::norm(u + v));
        half + half
    }

    /// The entrywise Lp norm `(Σ |a|^p)^(1/p)`. `p = 1` is the exact sum of the absolute values
    /// and `p = 2` the fused `norm` (both exact up to their one rounding); above, the components
    /// are first divided by the largest absolute value `m` (so no power can overflow), `Σ (|a| /
    /// m)^p`
    /// is summed (`p` floored products each), and the root is `m * exp(ln(Σ) / p)`: a few ulp
    /// relative to the result, the rounding of `exp` / `ln`. Panics with `nalgebra: lp_norm needs p
    /// >= 1` for `p < 1` (upstream returns meaningless values: an infinite root for `p = 0`).
    /// Upstream: `lp_norm`.
    fn lp_norm(self: RowVector4<T>, p: i32) -> T {
        if p < 1 {
            core::panic_with_felt252(errors::LP_NORM_P);
        }
        if p == 1 {
            return R::abs(self.x) + R::abs(self.y) + R::abs(self.z) + R::abs(self.w);
        }
        if p == 2 {
            return RowVector4Trait::norm(self);
        }
        let m = RowVector4Trait::amax(self);
        if m == R::zero() {
            return R::zero();
        }
        let r = RowVector4Trait::unscale(RowVector4Trait::abs(self), m);
        let q: u32 = p.try_into().unwrap();
        let s = Powi::powi(r.x, q) + Powi::powi(r.y, q) + Powi::powi(r.z, q) + Powi::powi(r.w, q);
        m * Tr::exp(R::div(Tr::ln(s), R::from_int(p)))
    }
}

// --- operators -----------------------------------------------------------------------------------

/// `lhs + rhs`, component-wise. Exact; panics on overflow. Upstream: `Add`.
pub impl RowVector4Add<T, +Add<T>, +Copy<T>, +Drop<T>> of Add<RowVector4<T>> {
    #[inline(always)]
    fn add(lhs: RowVector4<T>, rhs: RowVector4<T>) -> RowVector4<T> {
        RowVector4 { x: lhs.x + rhs.x, y: lhs.y + rhs.y, z: lhs.z + rhs.z, w: lhs.w + rhs.w }
    }
}

/// `lhs - rhs`, component-wise. Exact; panics on overflow. Upstream: `Sub`.
pub impl RowVector4Sub<T, +Sub<T>, +Copy<T>, +Drop<T>> of Sub<RowVector4<T>> {
    #[inline(always)]
    fn sub(lhs: RowVector4<T>, rhs: RowVector4<T>) -> RowVector4<T> {
        RowVector4 { x: lhs.x - rhs.x, y: lhs.y - rhs.y, z: lhs.z - rhs.z, w: lhs.w - rhs.w }
    }
}

/// `-a`, component-wise. Exact; panics on overflow (`-MIN`). Upstream: `Neg`.
pub impl RowVector4Neg<T, +Neg<T>, +Copy<T>, +Drop<T>> of Neg<RowVector4<T>> {
    #[inline(always)]
    fn neg(a: RowVector4<T>) -> RowVector4<T> {
        RowVector4 { x: -a.x, y: -a.y, z: -a.z, w: -a.w }
    }
}

/// `self += rhs`. Exact; panics on overflow. Upstream: `AddAssign`.
pub impl RowVector4AddAssign<
    T, +Add<T>, +Copy<T>, +Drop<T>,
> of AddAssign<RowVector4<T>, RowVector4<T>> {
    #[inline(always)]
    fn add_assign(ref self: RowVector4<T>, rhs: RowVector4<T>) {
        self = self + rhs;
    }
}

/// `self -= rhs`. Exact; panics on overflow. Upstream: `SubAssign`.
pub impl RowVector4SubAssign<
    T, +Sub<T>, +Copy<T>, +Drop<T>,
> of SubAssign<RowVector4<T>, RowVector4<T>> {
    #[inline(always)]
    fn sub_assign(ref self: RowVector4<T>, rhs: RowVector4<T>) {
        self = self - rhs;
    }
}

/// `[x, y, z, w].into()`. Upstream: `From<[T; 4]>`.
pub impl RowVector4FromArray<T> of Into<[T; 4], RowVector4<T>> {
    #[inline(always)]
    fn into(self: [T; 4]) -> RowVector4<T> {
        let [x, y, z, w] = self;
        RowVector4 { x, y, z, w }
    }
}

/// The components as a fixed-size array `[x, y, z, w]`. Upstream: `Into<[T; 4]>`.
pub impl RowVector4IntoArray<T> of Into<RowVector4<T>, [T; 4]> {
    #[inline(always)]
    fn into(self: RowVector4<T>) -> [T; 4] {
        let RowVector4 { x, y, z, w } = self;
        [x, y, z, w]
    }
}

// --- products ------------------------------------------------------------------------------------

/// `self * rhs`, a `Matrix1`: one `sum_prod4` per component (one rounding each). Panics on
/// overflow. Upstream: `RowVector4 * Vector4` (`Mul`).
pub impl RowVector4MulVector4<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<RowVector4<T>, Vector4<T>> {
    type Output = Matrix1<T>;
    #[inline(always)]
    fn mul_mat(self: RowVector4<T>, rhs: Vector4<T>) -> Matrix1<T> {
        Matrix1 { x: R::sum_prod4(self.x, rhs.x, self.y, rhs.y, self.z, rhs.z, self.w, rhs.w) }
    }
}

/// `self * rhs`, a `RowVector2`: one `sum_prod4` per component (one rounding each). Panics on
/// overflow. Upstream: `RowVector4 * Matrix4x2` (`Mul`).
pub impl RowVector4MulMatrix4x2<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<RowVector4<T>, Matrix4x2<T>> {
    type Output = RowVector2<T>;
    #[inline(always)]
    fn mul_mat(self: RowVector4<T>, rhs: Matrix4x2<T>) -> RowVector2<T> {
        RowVector2 {
            x: R::sum_prod4(self.x, rhs.m11, self.y, rhs.m21, self.z, rhs.m31, self.w, rhs.m41),
            y: R::sum_prod4(self.x, rhs.m12, self.y, rhs.m22, self.z, rhs.m32, self.w, rhs.m42),
        }
    }
}

/// `self * rhs`, a `RowVector3`: one `sum_prod4` per component (one rounding each). Panics on
/// overflow. Upstream: `RowVector4 * Matrix4x3` (`Mul`).
pub impl RowVector4MulMatrix4x3<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<RowVector4<T>, Matrix4x3<T>> {
    type Output = RowVector3<T>;
    #[inline(always)]
    fn mul_mat(self: RowVector4<T>, rhs: Matrix4x3<T>) -> RowVector3<T> {
        RowVector3 {
            x: R::sum_prod4(self.x, rhs.m11, self.y, rhs.m21, self.z, rhs.m31, self.w, rhs.m41),
            y: R::sum_prod4(self.x, rhs.m12, self.y, rhs.m22, self.z, rhs.m32, self.w, rhs.m42),
            z: R::sum_prod4(self.x, rhs.m13, self.y, rhs.m23, self.z, rhs.m33, self.w, rhs.m43),
        }
    }
}

/// `self * rhs`, a `RowVector4`: one `sum_prod4` per component (one rounding each). Panics on
/// overflow. Upstream: `RowVector4 * Matrix4` (`Mul`).
pub impl RowVector4MulMatrix4<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<RowVector4<T>, Matrix4<T>> {
    type Output = RowVector4<T>;
    #[inline(always)]
    fn mul_mat(self: RowVector4<T>, rhs: Matrix4<T>) -> RowVector4<T> {
        RowVector4 {
            x: R::sum_prod4(self.x, rhs.m11, self.y, rhs.m21, self.z, rhs.m31, self.w, rhs.m41),
            y: R::sum_prod4(self.x, rhs.m12, self.y, rhs.m22, self.z, rhs.m32, self.w, rhs.m42),
            z: R::sum_prod4(self.x, rhs.m13, self.y, rhs.m23, self.z, rhs.m33, self.w, rhs.m43),
            w: R::sum_prod4(self.x, rhs.m14, self.y, rhs.m24, self.z, rhs.m34, self.w, rhs.m44),
        }
    }
}

/// `self * rhs`, a `RowVector5`: one `sum_prod4` per component (one rounding each). Panics on
/// overflow. Upstream: `RowVector4 * Matrix4x5` (`Mul`).
pub impl RowVector4MulMatrix4x5<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<RowVector4<T>, Matrix4x5<T>> {
    type Output = RowVector5<T>;
    fn mul_mat(self: RowVector4<T>, rhs: Matrix4x5<T>) -> RowVector5<T> {
        RowVector5 {
            x: R::sum_prod4(self.x, rhs.m11, self.y, rhs.m21, self.z, rhs.m31, self.w, rhs.m41),
            y: R::sum_prod4(self.x, rhs.m12, self.y, rhs.m22, self.z, rhs.m32, self.w, rhs.m42),
            z: R::sum_prod4(self.x, rhs.m13, self.y, rhs.m23, self.z, rhs.m33, self.w, rhs.m43),
            w: R::sum_prod4(self.x, rhs.m14, self.y, rhs.m24, self.z, rhs.m34, self.w, rhs.m44),
            a: R::sum_prod4(self.x, rhs.m15, self.y, rhs.m25, self.z, rhs.m35, self.w, rhs.m45),
        }
    }
}

/// `self * rhs`, a `RowVector6`: one `sum_prod4` per component (one rounding each). Panics on
/// overflow. Upstream: `RowVector4 * Matrix4x6` (`Mul`).
pub impl RowVector4MulMatrix4x6<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixMul<RowVector4<T>, Matrix4x6<T>> {
    type Output = RowVector6<T>;
    fn mul_mat(self: RowVector4<T>, rhs: Matrix4x6<T>) -> RowVector6<T> {
        RowVector6 {
            x: R::sum_prod4(self.x, rhs.m11, self.y, rhs.m21, self.z, rhs.m31, self.w, rhs.m41),
            y: R::sum_prod4(self.x, rhs.m12, self.y, rhs.m22, self.z, rhs.m32, self.w, rhs.m42),
            z: R::sum_prod4(self.x, rhs.m13, self.y, rhs.m23, self.z, rhs.m33, self.w, rhs.m43),
            w: R::sum_prod4(self.x, rhs.m14, self.y, rhs.m24, self.z, rhs.m34, self.w, rhs.m44),
            a: R::sum_prod4(self.x, rhs.m15, self.y, rhs.m25, self.z, rhs.m35, self.w, rhs.m45),
            b: R::sum_prod4(self.x, rhs.m16, self.y, rhs.m26, self.z, rhs.m36, self.w, rhs.m46),
        }
    }
}

/// `selfᵀ * rhs`, a `Vector4`: `mul_mat` of the transposed components, so one floored product per
/// component; bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas (the transpose only
/// relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl RowVector4TrMulMatrix1<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<RowVector4<T>, Matrix1<T>> {
    type Output = Vector4<T>;
    #[inline(always)]
    fn tr_mul(self: RowVector4<T>, rhs: Matrix1<T>) -> Vector4<T> {
        MatrixMul::mul_mat(Vector4 { x: self.x, y: self.y, z: self.z, w: self.w }, rhs)
    }
}

/// `selfᵀ * rhs`, a `Matrix4x2`: `mul_mat` of the transposed components, so one floored product
/// per component; bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas (the transpose
/// only relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl RowVector4TrMulRowVector2<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<RowVector4<T>, RowVector2<T>> {
    type Output = Matrix4x2<T>;
    #[inline(always)]
    fn tr_mul(self: RowVector4<T>, rhs: RowVector2<T>) -> Matrix4x2<T> {
        MatrixMul::mul_mat(Vector4 { x: self.x, y: self.y, z: self.z, w: self.w }, rhs)
    }
}

/// `selfᵀ * rhs`, a `Matrix4x3`: `mul_mat` of the transposed components, so one floored product
/// per component; bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas (the transpose
/// only relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl RowVector4TrMulRowVector3<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<RowVector4<T>, RowVector3<T>> {
    type Output = Matrix4x3<T>;
    #[inline(always)]
    fn tr_mul(self: RowVector4<T>, rhs: RowVector3<T>) -> Matrix4x3<T> {
        MatrixMul::mul_mat(Vector4 { x: self.x, y: self.y, z: self.z, w: self.w }, rhs)
    }
}

/// `selfᵀ * rhs`, a `Matrix4`: `mul_mat` of the transposed components, so one floored product per
/// component; bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas (the transpose only
/// relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl RowVector4TrMulRowVector4<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<RowVector4<T>, RowVector4<T>> {
    type Output = Matrix4<T>;
    #[inline(always)]
    fn tr_mul(self: RowVector4<T>, rhs: RowVector4<T>) -> Matrix4<T> {
        MatrixMul::mul_mat(Vector4 { x: self.x, y: self.y, z: self.z, w: self.w }, rhs)
    }
}

/// `selfᵀ * rhs`, a `Matrix4x5`: `mul_mat` of the transposed components, so one floored product
/// per component; bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas (the transpose
/// only relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl RowVector4TrMulRowVector5<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<RowVector4<T>, RowVector5<T>> {
    type Output = Matrix4x5<T>;
    #[inline(always)]
    fn tr_mul(self: RowVector4<T>, rhs: RowVector5<T>) -> Matrix4x5<T> {
        MatrixMul::mul_mat(Vector4 { x: self.x, y: self.y, z: self.z, w: self.w }, rhs)
    }
}

/// `selfᵀ * rhs`, a `Matrix4x6`: `mul_mat` of the transposed components, so one floored product
/// per component; bit-identical to `self.transpose().mul_mat(rhs)`, at the same gas (the transpose
/// only relabels values). Panics on overflow. Upstream: `tr_mul`.
pub impl RowVector4TrMulRowVector6<
    T, impl R: Real<T>, +Mul<T>, +Copy<T>, +Drop<T>, +Drop<R::Wide>,
> of MatrixTrMul<RowVector4<T>, RowVector6<T>> {
    type Output = Matrix4x6<T>;
    #[inline(always)]
    fn tr_mul(self: RowVector4<T>, rhs: RowVector6<T>) -> Matrix4x6<T> {
        MatrixMul::mul_mat(Vector4 { x: self.x, y: self.y, z: self.z, w: self.w }, rhs)
    }
}

// --- indexing, comparisons, conversions ----------------------------------------------------------

/// `m.get(i)` / `m.index(..)`: the component `index` in column-major (storage) order. `get` is
/// `None` out of bounds, `index` panics with `nalgebra: index out of bounds`. Upstream:
/// `Matrix::get` / `Matrix::index` (their `MatrixIndex` argument).
pub impl RowVector4MatrixIndexLinear<T, +Copy<T>, +Drop<T>> of MatrixIndex<RowVector4<T>, usize> {
    type Output = T;
    #[inline(always)]
    fn get(self: RowVector4<T>, index: usize) -> Option<T> {
        match index {
            0 => Option::Some(self.x),
            1 => Option::Some(self.y),
            2 => Option::Some(self.z),
            3 => Option::Some(self.w),
            _ => Option::None,
        }
    }
    #[inline(always)]
    fn index(self: RowVector4<T>, index: usize) -> T {
        match index {
            0 => self.x,
            1 => self.y,
            2 => self.z,
            3 => self.w,
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// `m[i]`: the component `index` in column-major (storage) order. Panics with `nalgebra: index out
/// of bounds`. Upstream: `Index<usize>`.
pub impl RowVector4IndexLinear<T, +Copy<T>, +Drop<T>> of IndexView<RowVector4<T>, usize> {
    type Target = T;
    #[inline(always)]
    fn index(self: @RowVector4<T>, index: usize) -> T {
        match index {
            0 => *self.x,
            1 => *self.y,
            2 => *self.z,
            3 => *self.w,
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// `m.get((i, j))` / `m.index(..)`: the component at `(row, column)`. `get` is `None` out of
/// bounds, `index` panics with `nalgebra: index out of bounds`. Upstream: `Matrix::get` /
/// `Matrix::index` (their `MatrixIndex` argument).
pub impl RowVector4MatrixIndexPair<
    T, +Copy<T>, +Drop<T>,
> of MatrixIndex<RowVector4<T>, (usize, usize)> {
    type Output = T;
    #[inline(always)]
    fn get(self: RowVector4<T>, index: (usize, usize)) -> Option<T> {
        let (i, j) = index;
        match j {
            0 => match i {
                0 => Option::Some(self.x),
                _ => Option::None,
            },
            1 => match i {
                0 => Option::Some(self.y),
                _ => Option::None,
            },
            2 => match i {
                0 => Option::Some(self.z),
                _ => Option::None,
            },
            3 => match i {
                0 => Option::Some(self.w),
                _ => Option::None,
            },
            _ => Option::None,
        }
    }
    #[inline(always)]
    fn index(self: RowVector4<T>, index: (usize, usize)) -> T {
        let (i, j) = index;
        match j {
            0 => match i {
                0 => self.x,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            1 => match i {
                0 => self.y,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            2 => match i {
                0 => self.z,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            3 => match i {
                0 => self.w,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// `m[(i, j)]`: the component at `(row, column)`. Panics with `nalgebra: index out of bounds`.
/// Upstream: `Index<(usize, usize)>`.
pub impl RowVector4IndexPair<T, +Copy<T>, +Drop<T>> of IndexView<RowVector4<T>, (usize, usize)> {
    type Target = T;
    #[inline(always)]
    fn index(self: @RowVector4<T>, index: (usize, usize)) -> T {
        let (i, j) = index;
        match j {
            0 => match i {
                0 => *self.x,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            1 => match i {
                0 => *self.y,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            2 => match i {
                0 => *self.z,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            3 => match i {
                0 => *self.w,
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// The component-wise partial order: `a < b` when EVERY component of `a` is smaller than `b`'s
/// (likewise `<=`, `>`, `>=`), so two matrices may be unordered (`!(a < b) && !(a >= b)`).
/// Upstream: `PartialOrd for Matrix`.
pub impl RowVector4PartialOrd<T, +PartialOrd<T>, +Copy<T>, +Drop<T>> of PartialOrd<RowVector4<T>> {
    #[inline(always)]
    fn lt(lhs: RowVector4<T>, rhs: RowVector4<T>) -> bool {
        lhs.x < rhs.x && lhs.y < rhs.y && lhs.z < rhs.z && lhs.w < rhs.w
    }
    #[inline(always)]
    fn le(lhs: RowVector4<T>, rhs: RowVector4<T>) -> bool {
        lhs.x <= rhs.x && lhs.y <= rhs.y && lhs.z <= rhs.z && lhs.w <= rhs.w
    }
    #[inline(always)]
    fn gt(lhs: RowVector4<T>, rhs: RowVector4<T>) -> bool {
        lhs.x > rhs.x && lhs.y > rhs.y && lhs.z > rhs.z && lhs.w > rhs.w
    }
    #[inline(always)]
    fn ge(lhs: RowVector4<T>, rhs: RowVector4<T>) -> bool {
        lhs.x >= rhs.x && lhs.y >= rhs.y && lhs.z >= rhs.z && lhs.w >= rhs.w
    }
}

/// The component-wise bounds: every component `Bounded::<T>::MIN` / `MAX`. Upstream: `num::Bounded
/// for Matrix`.
pub impl RowVector4Bounded<T, +Bounded<T>, +Drop<T>> of Bounded<RowVector4<T>> {
    const MIN: RowVector4<T> = RowVector4 {
        x: Bounded::<T>::MIN, y: Bounded::<T>::MIN, z: Bounded::<T>::MIN, w: Bounded::<T>::MIN,
    };
    const MAX: RowVector4<T> = RowVector4 {
        x: Bounded::<T>::MAX, y: Bounded::<T>::MAX, z: Bounded::<T>::MAX, w: Bounded::<T>::MAX,
    };
}

/// The 4-dimensional row vector of the given COLUMNS (`[[m11, m21, ..], [m12, ..], ..]`). Upstream:
/// `From<[[T; R]; C]>`.
pub impl RowVector4FromColumnArrays<T, +Drop<T>> of Into<[[T; 1]; 4], RowVector4<T>> {
    #[inline(always)]
    fn into(self: [[T; 1]; 4]) -> RowVector4<T> {
        let [c0, c1, c2, c3] = self;
        let [x] = c0;
        let [y] = c1;
        let [z] = c2;
        let [w] = c3;
        RowVector4 { x, y, z, w }
    }
}

/// The columns of the 4-dimensional row vector as nested arrays (`[[m11, m21, ..], [m12, ..],
/// ..]`). Upstream: `Into<[[T; R]; C]>`.
pub impl RowVector4IntoColumnArrays<T, +Drop<T>> of Into<RowVector4<T>, [[T; 1]; 4]> {
    #[inline(always)]
    fn into(self: RowVector4<T>) -> [[T; 1]; 4] {
        let RowVector4 { x, y, z, w } = self;
        [[x], [y], [z], [w]]
    }
}

/// `self *= k` for a scalar `k`: `scale` in place, each component floored once. Panics on overflow.
/// Upstream: `MulAssign<T>`.
pub impl RowVector4MulAssignScalar<T, +Mul<T>, +Copy<T>, +Drop<T>> of MulAssign<RowVector4<T>, T> {
    #[inline(always)]
    fn mul_assign(ref self: RowVector4<T>, rhs: T) {
        self = RowVector4 { x: self.x * rhs, y: self.y * rhs, z: self.z * rhs, w: self.w * rhs };
    }
}

/// `self /= k` for a scalar `k`: `unscale` in place, each component correctly rounded. Panics on a
/// zero `k` and on overflow. Upstream: `DivAssign<T>`.
pub impl RowVector4DivAssignScalar<
    T, impl R: Real<T>, +Copy<T>, +Drop<T>,
> of DivAssign<RowVector4<T>, T> {
    #[inline(always)]
    fn div_assign(ref self: RowVector4<T>, rhs: T) {
        let (x, y, z, w) = R::div4(self.x, self.y, self.z, self.w, rhs);
        self = RowVector4 { x, y, z, w };
    }
}

// --- functional and in-place variants ------------------------------------------------------------

/// Private helpers of the `swap*` methods (runtime positions: one `match` each).
#[generate_trait]
impl RowVector4EditImpl<T, +Copy<T>, +Drop<T>> of RowVector4EditTrait<T> {
    /// `self` with the component at `index` (`(row, column)`) replaced by `v`; panics out of
    /// bounds.
    #[inline(always)]
    fn replace(self: RowVector4<T>, index: (usize, usize), v: T) -> RowVector4<T> {
        let (i, j) = index;
        match j {
            0 => match i {
                0 => RowVector4 { x: v, y: self.y, z: self.z, w: self.w },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            1 => match i {
                0 => RowVector4 { x: self.x, y: v, z: self.z, w: self.w },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            2 => match i {
                0 => RowVector4 { x: self.x, y: self.y, z: v, w: self.w },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            3 => match i {
                0 => RowVector4 { x: self.x, y: self.y, z: self.z, w: v },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    /// Row `i`, a `RowVector4`; panics out of bounds.
    #[inline(always)]
    fn row_at(self: RowVector4<T>, i: usize) -> RowVector4<T> {
        match i {
            0 => RowVector4 { x: self.x, y: self.y, z: self.z, w: self.w },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    /// Column `j`, a `Matrix1`; panics out of bounds.
    #[inline(always)]
    fn column_at(self: RowVector4<T>, j: usize) -> Matrix1<T> {
        match j {
            0 => Matrix1 { x: self.x },
            1 => Matrix1 { x: self.y },
            2 => Matrix1 { x: self.z },
            3 => Matrix1 { x: self.w },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// `EuclideanNorm` on `RowVector4`: `m.norm()` and the fused `metric_distance`. Upstream: `Norm<T>
/// for EuclideanNorm`.
pub impl RowVector4EuclideanNorm<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Norm<EuclideanNorm, RowVector4<T>, T> {
    #[inline(always)]
    fn norm(self: @EuclideanNorm, m: RowVector4<T>) -> T {
        RowVector4Trait::norm(m)
    }
    #[inline(always)]
    fn metric_distance(self: @EuclideanNorm, m1: RowVector4<T>, m2: RowVector4<T>) -> T {
        RowVector4Trait::metric_distance(m1, m2)
    }
}

/// `LpNorm` on `RowVector4`: `m.lp_norm(p)`, of `m1 - m2` for the distance. Upstream: `Norm<T> for
/// LpNorm`.
pub impl RowVector4LpNorm<
    T,
    impl R: Real<T>,
    impl Tr: Transcendental<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Norm<LpNorm, RowVector4<T>, T> {
    #[inline(always)]
    fn norm(self: @LpNorm, m: RowVector4<T>) -> T {
        RowVector4AngleTrait::lp_norm(m, *self.p)
    }
    #[inline(always)]
    fn metric_distance(self: @LpNorm, m1: RowVector4<T>, m2: RowVector4<T>) -> T {
        RowVector4AngleTrait::lp_norm(m1 - m2, *self.p)
    }
}

/// `OneNorm` on `RowVector4`: `m.one_norm()`, of `m1 - m2` for the distance. Upstream: `Norm<T> for
/// OneNorm`.
pub impl RowVector4OneNorm<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Norm<OneNorm, RowVector4<T>, T> {
    #[inline(always)]
    fn norm(self: @OneNorm, m: RowVector4<T>) -> T {
        RowVector4Trait::one_norm(m)
    }
    #[inline(always)]
    fn metric_distance(self: @OneNorm, m1: RowVector4<T>, m2: RowVector4<T>) -> T {
        RowVector4Trait::one_norm(m1 - m2)
    }
}

/// `UniformNorm` on `RowVector4`: `m.amax()`, of `m1 - m2` for the distance. Upstream: `Norm<T> for
/// UniformNorm`.
pub impl RowVector4UniformNorm<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Norm<UniformNorm, RowVector4<T>, T> {
    #[inline(always)]
    fn norm(self: @UniformNorm, m: RowVector4<T>) -> T {
        RowVector4Trait::amax(m)
    }
    #[inline(always)]
    fn metric_distance(self: @UniformNorm, m1: RowVector4<T>, m2: RowVector4<T>) -> T {
        RowVector4Trait::amax(m1 - m2)
    }
}

// --- rows, columns, blocks and edition (WP 8.2c) -------------------------------------------------

/// The 1 consecutive rows of a `RowVector4` as a `RowVector4` (`rows` / `rows_range`: default
/// methods). Upstream: `fixed_rows::<1>`, `select_rows`.
pub impl RowVector4FixedRowsRowVector4<
    T, +Copy<T>, +Drop<T>,
> of FixedRows<RowVector4<T>, RowVector4<T>> {
    #[inline(always)]
    fn fixed_rows(self: RowVector4<T>, i: usize) -> RowVector4<T> {
        match i {
            0 => RowVector4 { x: self.x, y: self.y, z: self.z, w: self.w },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    #[inline(always)]
    fn select_rows(self: RowVector4<T>, irows: Span<usize>) -> RowVector4<T> {
        if irows.len() != 1 {
            core::panic_with_felt252(errors::DIMENSION_MISMATCH)
        }
        let r0 = RowVector4EditTrait::row_at(self, *irows[0]);
        RowVector4 { x: r0.x, y: r0.y, z: r0.z, w: r0.w }
    }
}

/// The 1 consecutive columns of a `RowVector4` as a `Matrix1` (`columns` / `columns_range`: default
/// methods). Upstream: `fixed_columns::<1>`, `select_columns`.
pub impl RowVector4FixedColumnsMatrix1<
    T, +Copy<T>, +Drop<T>,
> of FixedColumns<RowVector4<T>, Matrix1<T>> {
    #[inline(always)]
    fn fixed_columns(self: RowVector4<T>, i: usize) -> Matrix1<T> {
        match i {
            0 => Matrix1 { x: self.x },
            1 => Matrix1 { x: self.y },
            2 => Matrix1 { x: self.z },
            3 => Matrix1 { x: self.w },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    #[inline(always)]
    fn select_columns(self: RowVector4<T>, icols: Span<usize>) -> Matrix1<T> {
        if icols.len() != 1 {
            core::panic_with_felt252(errors::DIMENSION_MISMATCH)
        }
        let c0 = RowVector4EditTrait::column_at(self, *icols[0]);
        Matrix1 { x: c0.x }
    }
}

/// The 2 consecutive columns of a `RowVector4` as a `RowVector2` (`columns` / `columns_range`:
/// default methods). Upstream: `fixed_columns::<2>`, `select_columns`.
pub impl RowVector4FixedColumnsRowVector2<
    T, +Copy<T>, +Drop<T>,
> of FixedColumns<RowVector4<T>, RowVector2<T>> {
    #[inline(always)]
    fn fixed_columns(self: RowVector4<T>, i: usize) -> RowVector2<T> {
        match i {
            0 => RowVector2 { x: self.x, y: self.y },
            1 => RowVector2 { x: self.y, y: self.z },
            2 => RowVector2 { x: self.z, y: self.w },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    #[inline(always)]
    fn select_columns(self: RowVector4<T>, icols: Span<usize>) -> RowVector2<T> {
        if icols.len() != 2 {
            core::panic_with_felt252(errors::DIMENSION_MISMATCH)
        }
        let c0 = RowVector4EditTrait::column_at(self, *icols[0]);
        let c1 = RowVector4EditTrait::column_at(self, *icols[1]);
        RowVector2 { x: c0.x, y: c1.x }
    }
}

/// The 3 consecutive columns of a `RowVector4` as a `RowVector3` (`columns` / `columns_range`:
/// default methods). Upstream: `fixed_columns::<3>`, `select_columns`.
pub impl RowVector4FixedColumnsRowVector3<
    T, +Copy<T>, +Drop<T>,
> of FixedColumns<RowVector4<T>, RowVector3<T>> {
    #[inline(always)]
    fn fixed_columns(self: RowVector4<T>, i: usize) -> RowVector3<T> {
        match i {
            0 => RowVector3 { x: self.x, y: self.y, z: self.z },
            1 => RowVector3 { x: self.y, y: self.z, z: self.w },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    #[inline(always)]
    fn select_columns(self: RowVector4<T>, icols: Span<usize>) -> RowVector3<T> {
        if icols.len() != 3 {
            core::panic_with_felt252(errors::DIMENSION_MISMATCH)
        }
        let c0 = RowVector4EditTrait::column_at(self, *icols[0]);
        let c1 = RowVector4EditTrait::column_at(self, *icols[1]);
        let c2 = RowVector4EditTrait::column_at(self, *icols[2]);
        RowVector3 { x: c0.x, y: c1.x, z: c2.x }
    }
}

/// The 4 consecutive columns of a `RowVector4` as a `RowVector4` (`columns` / `columns_range`:
/// default methods). Upstream: `fixed_columns::<4>`, `select_columns`.
pub impl RowVector4FixedColumnsRowVector4<
    T, +Copy<T>, +Drop<T>,
> of FixedColumns<RowVector4<T>, RowVector4<T>> {
    #[inline(always)]
    fn fixed_columns(self: RowVector4<T>, i: usize) -> RowVector4<T> {
        match i {
            0 => RowVector4 { x: self.x, y: self.y, z: self.z, w: self.w },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    #[inline(always)]
    fn select_columns(self: RowVector4<T>, icols: Span<usize>) -> RowVector4<T> {
        if icols.len() != 4 {
            core::panic_with_felt252(errors::DIMENSION_MISMATCH)
        }
        let c0 = RowVector4EditTrait::column_at(self, *icols[0]);
        let c1 = RowVector4EditTrait::column_at(self, *icols[1]);
        let c2 = RowVector4EditTrait::column_at(self, *icols[2]);
        let c3 = RowVector4EditTrait::column_at(self, *icols[3]);
        RowVector4 { x: c0.x, y: c1.x, z: c2.x, w: c3.x }
    }
}

/// The 1x1 blocks of a `RowVector4` as a `Matrix1` (`view`, `fixed_slice`, `slice`: default
/// methods). Upstream: `fixed_view::<1, 1>`.
pub impl RowVector4FixedViewMatrix1<T, +Copy<T>, +Drop<T>> of FixedView<RowVector4<T>, Matrix1<T>> {
    #[inline(always)]
    fn fixed_view(self: RowVector4<T>, irow: usize, icol: usize) -> Matrix1<T> {
        match icol {
            0 => match irow {
                0 => Matrix1 { x: self.x },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            1 => match irow {
                0 => Matrix1 { x: self.y },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            2 => match irow {
                0 => Matrix1 { x: self.z },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            3 => match irow {
                0 => Matrix1 { x: self.w },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// The 1x2 blocks of a `RowVector4` as a `RowVector2` (`view`, `fixed_slice`, `slice`: default
/// methods). Upstream: `fixed_view::<1, 2>`.
pub impl RowVector4FixedViewRowVector2<
    T, +Copy<T>, +Drop<T>,
> of FixedView<RowVector4<T>, RowVector2<T>> {
    #[inline(always)]
    fn fixed_view(self: RowVector4<T>, irow: usize, icol: usize) -> RowVector2<T> {
        match icol {
            0 => match irow {
                0 => RowVector2 { x: self.x, y: self.y },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            1 => match irow {
                0 => RowVector2 { x: self.y, y: self.z },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            2 => match irow {
                0 => RowVector2 { x: self.z, y: self.w },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// The 1x3 blocks of a `RowVector4` as a `RowVector3` (`view`, `fixed_slice`, `slice`: default
/// methods). Upstream: `fixed_view::<1, 3>`.
pub impl RowVector4FixedViewRowVector3<
    T, +Copy<T>, +Drop<T>,
> of FixedView<RowVector4<T>, RowVector3<T>> {
    #[inline(always)]
    fn fixed_view(self: RowVector4<T>, irow: usize, icol: usize) -> RowVector3<T> {
        match icol {
            0 => match irow {
                0 => RowVector3 { x: self.x, y: self.y, z: self.z },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            1 => match irow {
                0 => RowVector3 { x: self.y, y: self.z, z: self.w },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// The 1x4 blocks of a `RowVector4` as a `RowVector4` (`view`, `fixed_slice`, `slice`: default
/// methods). Upstream: `fixed_view::<1, 4>`.
pub impl RowVector4FixedViewRowVector4<
    T, +Copy<T>, +Drop<T>,
> of FixedView<RowVector4<T>, RowVector4<T>> {
    #[inline(always)]
    fn fixed_view(self: RowVector4<T>, irow: usize, icol: usize) -> RowVector4<T> {
        match icol {
            0 => match irow {
                0 => RowVector4 { x: self.x, y: self.y, z: self.z, w: self.w },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}

/// The Kronecker product of a `RowVector4` and a `Matrix1`, a `RowVector4`: one floored product per
/// component. Panics on overflow. Upstream: `kronecker`.
pub impl RowVector4KroneckerMatrix1<
    T, +Mul<T>, +Copy<T>, +Drop<T>,
> of MatrixKronecker<RowVector4<T>, Matrix1<T>> {
    type Output = RowVector4<T>;
    #[inline(always)]
    fn kronecker(self: RowVector4<T>, rhs: Matrix1<T>) -> RowVector4<T> {
        RowVector4 { x: self.x * rhs.x, y: self.y * rhs.x, z: self.z * rhs.x, w: self.w * rhs.x }
    }
}

/// The Kronecker product of a `RowVector4` and a `Vector2`, a `Matrix2x4`: one floored product per
/// component. Panics on overflow. Upstream: `kronecker`.
pub impl RowVector4KroneckerVector2<
    T, +Mul<T>, +Copy<T>, +Drop<T>,
> of MatrixKronecker<RowVector4<T>, Vector2<T>> {
    type Output = Matrix2x4<T>;
    #[inline(always)]
    fn kronecker(self: RowVector4<T>, rhs: Vector2<T>) -> Matrix2x4<T> {
        Matrix2x4 {
            m11: self.x * rhs.x,
            m21: self.x * rhs.y,
            m12: self.y * rhs.x,
            m22: self.y * rhs.y,
            m13: self.z * rhs.x,
            m23: self.z * rhs.y,
            m14: self.w * rhs.x,
            m24: self.w * rhs.y,
        }
    }
}

/// The Kronecker product of a `RowVector4` and a `Vector3`, a `Matrix3x4`: one floored product per
/// component. Panics on overflow. Upstream: `kronecker`.
pub impl RowVector4KroneckerVector3<
    T, +Mul<T>, +Copy<T>, +Drop<T>,
> of MatrixKronecker<RowVector4<T>, Vector3<T>> {
    type Output = Matrix3x4<T>;
    #[inline(always)]
    fn kronecker(self: RowVector4<T>, rhs: Vector3<T>) -> Matrix3x4<T> {
        Matrix3x4 {
            m11: self.x * rhs.x,
            m21: self.x * rhs.y,
            m31: self.x * rhs.z,
            m12: self.y * rhs.x,
            m22: self.y * rhs.y,
            m32: self.y * rhs.z,
            m13: self.z * rhs.x,
            m23: self.z * rhs.y,
            m33: self.z * rhs.z,
            m14: self.w * rhs.x,
            m24: self.w * rhs.y,
            m34: self.w * rhs.z,
        }
    }
}

/// The Kronecker product of a `RowVector4` and a `Vector4`, a `Matrix4`: one floored product per
/// component. Panics on overflow. Upstream: `kronecker`.
pub impl RowVector4KroneckerVector4<
    T, +Mul<T>, +Copy<T>, +Drop<T>,
> of MatrixKronecker<RowVector4<T>, Vector4<T>> {
    type Output = Matrix4<T>;
    #[inline(always)]
    fn kronecker(self: RowVector4<T>, rhs: Vector4<T>) -> Matrix4<T> {
        Matrix4 {
            m11: self.x * rhs.x,
            m21: self.x * rhs.y,
            m31: self.x * rhs.z,
            m41: self.x * rhs.w,
            m12: self.y * rhs.x,
            m22: self.y * rhs.y,
            m32: self.y * rhs.z,
            m42: self.y * rhs.w,
            m13: self.z * rhs.x,
            m23: self.z * rhs.y,
            m33: self.z * rhs.z,
            m43: self.z * rhs.w,
            m14: self.w * rhs.x,
            m24: self.w * rhs.y,
            m34: self.w * rhs.z,
            m44: self.w * rhs.w,
        }
    }
}

/// The Kronecker product of a `RowVector4` and a `Vector5`, a `Matrix5x4`: one floored product per
/// component. Panics on overflow. Upstream: `kronecker`.
pub impl RowVector4KroneckerVector5<
    T, +Mul<T>, +Copy<T>, +Drop<T>,
> of MatrixKronecker<RowVector4<T>, Vector5<T>> {
    type Output = Matrix5x4<T>;
    fn kronecker(self: RowVector4<T>, rhs: Vector5<T>) -> Matrix5x4<T> {
        Matrix5x4 {
            m11: self.x * rhs.x,
            m21: self.x * rhs.y,
            m31: self.x * rhs.z,
            m41: self.x * rhs.w,
            m51: self.x * rhs.a,
            m12: self.y * rhs.x,
            m22: self.y * rhs.y,
            m32: self.y * rhs.z,
            m42: self.y * rhs.w,
            m52: self.y * rhs.a,
            m13: self.z * rhs.x,
            m23: self.z * rhs.y,
            m33: self.z * rhs.z,
            m43: self.z * rhs.w,
            m53: self.z * rhs.a,
            m14: self.w * rhs.x,
            m24: self.w * rhs.y,
            m34: self.w * rhs.z,
            m44: self.w * rhs.w,
            m54: self.w * rhs.a,
        }
    }
}

/// The Kronecker product of a `RowVector4` and a `Vector6`, a `Matrix6x4`: one floored product per
/// component. Panics on overflow. Upstream: `kronecker`.
pub impl RowVector4KroneckerVector6<
    T, +Mul<T>, +Copy<T>, +Drop<T>,
> of MatrixKronecker<RowVector4<T>, Vector6<T>> {
    type Output = Matrix6x4<T>;
    fn kronecker(self: RowVector4<T>, rhs: Vector6<T>) -> Matrix6x4<T> {
        Matrix6x4 {
            m11: self.x * rhs.x,
            m21: self.x * rhs.y,
            m31: self.x * rhs.z,
            m41: self.x * rhs.w,
            m51: self.x * rhs.a,
            m61: self.x * rhs.b,
            m12: self.y * rhs.x,
            m22: self.y * rhs.y,
            m32: self.y * rhs.z,
            m42: self.y * rhs.w,
            m52: self.y * rhs.a,
            m62: self.y * rhs.b,
            m13: self.z * rhs.x,
            m23: self.z * rhs.y,
            m33: self.z * rhs.z,
            m43: self.z * rhs.w,
            m53: self.z * rhs.a,
            m63: self.z * rhs.b,
            m14: self.w * rhs.x,
            m24: self.w * rhs.y,
            m34: self.w * rhs.z,
            m44: self.w * rhs.w,
            m54: self.w * rhs.a,
            m64: self.w * rhs.b,
        }
    }
}

/// `self` in the top-left corner of a `Matrix6` filled with `val` (`FixedResize`).
pub(crate) impl RowVector4PadTo6<T, +Copy<T>, +Drop<T>> of PadTo6<RowVector4<T>, T> {
    #[inline(always)]
    fn pad(self: RowVector4<T>, val: T) -> Matrix6<T> {
        Matrix6 {
            m11: self.x,
            m21: val,
            m31: val,
            m41: val,
            m51: val,
            m61: val,
            m12: self.y,
            m22: val,
            m32: val,
            m42: val,
            m52: val,
            m62: val,
            m13: self.z,
            m23: val,
            m33: val,
            m43: val,
            m53: val,
            m63: val,
            m14: self.w,
            m24: val,
            m34: val,
            m44: val,
            m54: val,
            m64: val,
            m15: val,
            m25: val,
            m35: val,
            m45: val,
            m55: val,
            m65: val,
            m16: val,
            m26: val,
            m36: val,
            m46: val,
            m56: val,
            m66: val,
        }
    }
}

/// The top-left `RowVector4` of a `Matrix6` (`FixedResize`).
pub(crate) impl RowVector4CropFrom6<T, +Copy<T>, +Drop<T>> of CropFrom6<RowVector4<T>, T> {
    #[inline(always)]
    fn crop(m: Matrix6<T>) -> RowVector4<T> {
        RowVector4 { x: m.m11, y: m.m12, z: m.m13, w: m.m14 }
    }
}

/// `(1, 4)`: the size checks of the runtime-sized views.
pub(crate) impl RowVector4ShapeDims<T> of ShapeDims<RowVector4<T>> {
    #[inline(always)]
    fn dims() -> (usize, usize) {
        (1, 4)
    }
}
