[package]
name = "simba"
description = "Scalar traits for provable linear algebra, implemented for glam.cairo's Q32.32 `fixed::Fixed`."
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
fixed = "0.2.0"

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true
nalgebra_testing = { path = "../testing" }

[tool]
fmt.workspace = true
scarb.workspace = true
