[package]
name = "layout"
version.workspace = true
edition.workspace = true

[dependencies]
harness = { path = "../harness" }

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true

[tool]
scarb.workspace = true
