// Generated by tools/linalggen/generate.py: do not edit by hand.
//! `Eigen1`: the eigen decomposition of a `Matrix1` with real eigenvalues (upstream
//! `nalgebra::linalg::Eigen<T, U1>`), WP 8.5-P16.

pub use nalgebra_linalg_spectral4::linalg::eigen::eigen1::*;
