// Generated by tools/linalggen/generate.py: do not edit by hand.
//! The matrix exponential of the static squares (upstream `nalgebra::linalg::exp`,
//! `OMatrix::exp`, WP 8.5-P17): `Matrix1ExpTrait` .. `Matrix6ExpTrait`. `Matrix1` is the scalar
//! exponential (upstream's `nrows() == 1` case); the others are the Padé approximant with scaling
//! and squaring documented on `Matrix2ExpTrait::exp`. Upstream's generic impl covers `DMatrix`
//! too: not ported (the D5 dynamic types have no LU; `SquareMatrix` only requires the static
//! squares, `docs/API_PARITY.md`).

use nalgebra_core::base::matrix1::Matrix1;
use nalgebra_core::base::matrix2::Matrix2;
use nalgebra_core::base::matrix3::Matrix3;
use nalgebra_core::base::matrix4::Matrix4;
use nalgebra_core::base::matrix_mul::MatrixMul;
use nalgebra_linalg4::linalg::lu::lu2::Lu2Trait;
use nalgebra_linalg4::linalg::lu::lu3::Lu3Trait;
use nalgebra_linalg4::linalg::lu::lu4::Lu4Trait;
use nalgebra_static3::base::matrix2::Matrix2Trait;
use nalgebra_static3::base::matrix3::Matrix3Trait;
use nalgebra_static4::base::matrix4::Matrix4Trait;
use simba::scalar::{Real, Transcendental};
use crate::internal::linalg::exp::SINGULAR_PADE;

/// `Matrix1::exp`: the scalar exponential. Import `Matrix1ExpTrait` to use it.
#[generate_trait]
pub impl Matrix1ExpImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix1ExpTrait<T> {
    /// `exp(x)` of the single entry, upstream's `nrows() == 1` case (`self.map(|v| v.exp())`):
    /// `Transcendental::exp`, whose error and domain are the scalar's (fixed-cairo `ExpTrait`).
    /// Upstream: `OMatrix::exp`.
    fn exp<+Transcendental<T>>(self: Matrix1<T>) -> Matrix1<T> {
        Matrix1 { x: Transcendental::exp(self.x) }
    }
}

/// `Matrix2::exp`. Import `Matrix2ExpTrait` to use it.
#[generate_trait]
pub impl Matrix2ExpImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix2ExpTrait<T> {
    /// The matrix exponential `exp(a) = Σ a^k / k!`. Upstream: `OMatrix::exp`.
    ///
    /// Padé approximant with scaling and squaring, upstream's family (Higham 2005 / Al-Mohy and
    /// Higham 2009, scipy's `expm`), with the degree chosen by the 1-norm thresholds:
    ///
    /// ```text
    /// |a|₁ <= θ₃ = 0.16917        Padé [3/3]    2 rounded products + LU solve
    /// |a|₁ <= θ₅ = 1.0858         Padé [5/5]    3 rounded products + LU solve
    /// otherwise, s = the smallest integer with |a|₁ / 2^s <= θ₇ = 2.6681:
    ///                             Padé [7/7] of a / 2^s, then s squarings
    ///                             4 + s rounded products + LU solve
    /// ```
    ///
    /// The thresholds `θ_m` are Higham's backward-error bounds (`exp(a + Δa)` with `|Δa| <= u
    /// |a|`)
    /// recomputed for the Q32.32 unit roundoff `u = 2^-32` (upstream's, for `f64`'s `2^-53`, are
    /// 0.01496 / 0.2539 / 0.9504, plus degrees 9 and 13), rounded down. Deviations from upstream,
    /// all cheaper (steps criterion) and within the oracle tolerance:
    /// - the degree is chosen on `|a|₁` alone, without upstream's exact norms of `a⁴` ..
    /// `a¹⁰` and
    ///   its `ell` backward-error refinement (matrix-vector products and a base-2 logarithm);
    /// - no degree 9 or 13: at the Q32.32 thresholds (θ₉ = 4.65 < 2 θ₇, θ₁₃ = 9.22 < 4
    /// θ₇) they
    ///   cost as many rounded products as degree 7 with one / two more squarings, and their
    ///   coefficients (up to 6.5e16) do not fit Q32.32 as integers;
    /// - the coefficients are upstream's integers (`R::from_int`), so `V`, `W` are exact
    ///   combinations of the powers and `P`, `Q` have the magnitude `b_0` (1.7e7 for degree 7).
    ///
    /// Accuracy (model, then the oracle suite `matrix_functions` in `tests_linalg_exp`): within a
    /// few ulp per unit of `max |exp(a)|` at the thresholds; each squaring roughly doubles the
    /// relative error already committed (14 ulp per unit at `|a|₁ = 15` in 6x6, 3 squarings).
    /// `a / 2^s` is the exact floor `a_ij >> s`. The scaling loop is data-dependent (`s` grows
    /// with `log2 |a|₁`, like upstream's), everything else is unrolled.
    ///
    /// Panics with the scalar's overflow error when a column sum of `|a_ij|`, a Padé term or a
    /// squaring does not fit (in particular whenever `exp(a)` itself does not), and with
    /// `nalgebra: singular Pade denom` if the LU solve meets an exactly zero pivot (upstream's
    /// `unwrap`). Sierra gas charges the degree branches at their costliest path; Cairo steps
    /// follow the executed branch.
    fn exp(self: Matrix2<T>) -> Matrix2<T> {
        let norm = self.one_norm();
        if norm <= R::from_ratio(16917, 100000) {
            let (p, q) = Exp2InternalTrait::pade3(self);
            return Exp2InternalTrait::solve_pq(p, q);
        }
        if norm <= R::from_ratio(10858, 10000) {
            let (p, q) = Exp2InternalTrait::pade5(self);
            return Exp2InternalTrait::solve_pq(p, q);
        }
        let theta7 = R::from_ratio(26681, 10000);
        let mut norm = norm;
        let mut factor = R::one();
        let mut s: u32 = 0;
        while norm > theta7 {
            norm = norm * R::HALF;
            factor = factor * R::HALF;
            s += 1;
        }
        let b = if s == 0 {
            self
        } else {
            self.scale(factor)
        };
        let (p, q) = Exp2InternalTrait::pade7(b);
        let mut x = Exp2InternalTrait::solve_pq(p, q);
        while s != 0 {
            x = x.mul_mat(x);
            s -= 1;
        }
        x
    }
}

/// Crate-internal kernels of `Matrix2ExpTrait::exp`: the Padé approximants and the LU solve.
#[generate_trait]
pub(crate) impl Exp2InternalImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Exp2InternalTrait<T> {
    /// The Padé [3/3] approximant of `exp(a)` as `(P, Q) = (V + U, V - U)`, upstream's
    /// `pade3`: A² (1 rounded product), `V = Σ b_2k A^2k`, `W = Σ b_(2k+1) A^2k`
    /// (integer coefficients: every term exact, one fused kernel per entry), `U = a W` (one more
    /// rounded product). The magnitude of `P` and `Q` is `b_0 = 120`, so the absolute
    /// rounding of the products is `1 / b_0` relative.
    fn pade3(a: Matrix2<T>) -> (Matrix2<T>, Matrix2<T>) {
        let a2 = a.mul_mat(a);
        let c0 = R::from_int(120);
        let c1 = R::from_int(60);
        let c2 = R::from_int(12);
        let w = Matrix2 { m11: a2.m11 + c1, m21: a2.m21, m12: a2.m12, m22: a2.m22 + c1 };
        let v = Matrix2 {
            m11: c2 * a2.m11 + c0, m21: c2 * a2.m21, m12: c2 * a2.m12, m22: c2 * a2.m22 + c0,
        };
        let u = a.mul_mat(w);
        (v + u, v - u)
    }

    /// The Padé [5/5] approximant of `exp(a)` as `(P, Q) = (V + U, V - U)`, upstream's
    /// `pade5`: A², A⁴ (2 rounded products), `V = Σ b_2k A^2k`, `W = Σ b_(2k+1) A^2k`
    /// (integer coefficients: every term exact, one fused kernel per entry), `U = a W` (one more
    /// rounded product). The magnitude of `P` and `Q` is `b_0 = 30240`, so the absolute
    /// rounding of the products is `1 / b_0` relative.
    fn pade5(a: Matrix2<T>) -> (Matrix2<T>, Matrix2<T>) {
        let a2 = a.mul_mat(a);
        let a4 = a2.mul_mat(a2);
        let c0 = R::from_int(30240);
        let c1 = R::from_int(15120);
        let c2 = R::from_int(3360);
        let c3 = R::from_int(420);
        let c4 = R::from_int(30);
        let w = Matrix2 {
            m11: a4.m11 + c3 * a2.m11 + c1,
            m21: a4.m21 + c3 * a2.m21,
            m12: a4.m12 + c3 * a2.m12,
            m22: a4.m22 + c3 * a2.m22 + c1,
        };
        let v = Matrix2 {
            m11: R::sum_prod2(c4, a4.m11, c2, a2.m11) + c0,
            m21: R::sum_prod2(c4, a4.m21, c2, a2.m21),
            m12: R::sum_prod2(c4, a4.m12, c2, a2.m12),
            m22: R::sum_prod2(c4, a4.m22, c2, a2.m22) + c0,
        };
        let u = a.mul_mat(w);
        (v + u, v - u)
    }

    /// The Padé [7/7] approximant of `exp(a)` as `(P, Q) = (V + U, V - U)`, upstream's
    /// `pade7`: A², A⁴, A⁶ (3 rounded products), `V = Σ b_2k A^2k`, `W = Σ b_(2k+1) A^2k`
    /// (integer coefficients: every term exact, one fused kernel per entry), `U = a W` (one more
    /// rounded product). The magnitude of `P` and `Q` is `b_0 = 17297280`, so the absolute
    /// rounding of the products is `1 / b_0` relative.
    fn pade7(a: Matrix2<T>) -> (Matrix2<T>, Matrix2<T>) {
        let a2 = a.mul_mat(a);
        let a4 = a2.mul_mat(a2);
        let a6 = a4.mul_mat(a2);
        let c0 = R::from_int(17297280);
        let c1 = R::from_int(8648640);
        let c2 = R::from_int(1995840);
        let c3 = R::from_int(277200);
        let c4 = R::from_int(25200);
        let c5 = R::from_int(1512);
        let c6 = R::from_int(56);
        let w = Matrix2 {
            m11: a6.m11 + R::sum_prod2(c5, a4.m11, c3, a2.m11) + c1,
            m21: a6.m21 + R::sum_prod2(c5, a4.m21, c3, a2.m21),
            m12: a6.m12 + R::sum_prod2(c5, a4.m12, c3, a2.m12),
            m22: a6.m22 + R::sum_prod2(c5, a4.m22, c3, a2.m22) + c1,
        };
        let v = Matrix2 {
            m11: R::sum_prod3(c6, a6.m11, c4, a4.m11, c2, a2.m11) + c0,
            m21: R::sum_prod3(c6, a6.m21, c4, a4.m21, c2, a2.m21),
            m12: R::sum_prod3(c6, a6.m12, c4, a4.m12, c2, a2.m12),
            m22: R::sum_prod3(c6, a6.m22, c4, a4.m22, c2, a2.m22) + c0,
        };
        let u = a.mul_mat(w);
        (v + u, v - u)
    }

    /// `Q⁻¹ P`, upstream's `solve_p_q` (`q.lu().solve(&p).unwrap()`): the LU factorisation of
    /// `Q` with partial pivoting and the solve of the 2 columns of `P`. `Q` is the Padé
    /// denominator of a matrix within the threshold of its degree, well conditioned; panics with
    /// `nalgebra: singular Pade denom` (upstream's `unwrap` panic) if a pivot is exactly zero.
    fn solve_pq(p: Matrix2<T>, q: Matrix2<T>) -> Matrix2<T> {
        let mut x = p;
        assert!(Lu2Trait::new(q).solve_mut(ref x), "{}", SINGULAR_PADE);
        x
    }
}

/// `Matrix3::exp`. Import `Matrix3ExpTrait` to use it.
#[generate_trait]
pub impl Matrix3ExpImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix3ExpTrait<T> {
    /// The matrix exponential `exp(a) = Σ a^k / k!`. Upstream: `OMatrix::exp`.
    ///
    /// Padé approximant with scaling and squaring, upstream's family (Higham 2005 / Al-Mohy and
    /// Higham 2009, scipy's `expm`), with the degree chosen by the 1-norm thresholds:
    ///
    /// ```text
    /// |a|₁ <= θ₃ = 0.16917        Padé [3/3]    2 rounded products + LU solve
    /// |a|₁ <= θ₅ = 1.0858         Padé [5/5]    3 rounded products + LU solve
    /// otherwise, s = the smallest integer with |a|₁ / 2^s <= θ₇ = 2.6681:
    ///                             Padé [7/7] of a / 2^s, then s squarings
    ///                             4 + s rounded products + LU solve
    /// ```
    ///
    /// The thresholds `θ_m` are Higham's backward-error bounds (`exp(a + Δa)` with `|Δa| <= u
    /// |a|`)
    /// recomputed for the Q32.32 unit roundoff `u = 2^-32` (upstream's, for `f64`'s `2^-53`, are
    /// 0.01496 / 0.2539 / 0.9504, plus degrees 9 and 13), rounded down. Deviations from upstream,
    /// all cheaper (steps criterion) and within the oracle tolerance:
    /// - the degree is chosen on `|a|₁` alone, without upstream's exact norms of `a⁴` ..
    /// `a¹⁰` and
    ///   its `ell` backward-error refinement (matrix-vector products and a base-2 logarithm);
    /// - no degree 9 or 13: at the Q32.32 thresholds (θ₉ = 4.65 < 2 θ₇, θ₁₃ = 9.22 < 4
    /// θ₇) they
    ///   cost as many rounded products as degree 7 with one / two more squarings, and their
    ///   coefficients (up to 6.5e16) do not fit Q32.32 as integers;
    /// - the coefficients are upstream's integers (`R::from_int`), so `V`, `W` are exact
    ///   combinations of the powers and `P`, `Q` have the magnitude `b_0` (1.7e7 for degree 7).
    ///
    /// Accuracy (model, then the oracle suite `matrix_functions` in `tests_linalg_exp`): within a
    /// few ulp per unit of `max |exp(a)|` at the thresholds; each squaring roughly doubles the
    /// relative error already committed (14 ulp per unit at `|a|₁ = 15` in 6x6, 3 squarings).
    /// `a / 2^s` is the exact floor `a_ij >> s`. The scaling loop is data-dependent (`s` grows
    /// with `log2 |a|₁`, like upstream's), everything else is unrolled.
    ///
    /// Panics with the scalar's overflow error when a column sum of `|a_ij|`, a Padé term or a
    /// squaring does not fit (in particular whenever `exp(a)` itself does not), and with
    /// `nalgebra: singular Pade denom` if the LU solve meets an exactly zero pivot (upstream's
    /// `unwrap`). Sierra gas charges the degree branches at their costliest path; Cairo steps
    /// follow the executed branch.
    fn exp(self: Matrix3<T>) -> Matrix3<T> {
        let norm = self.one_norm();
        if norm <= R::from_ratio(16917, 100000) {
            let (p, q) = Exp3InternalTrait::pade3(self);
            return Exp3InternalTrait::solve_pq(p, q);
        }
        if norm <= R::from_ratio(10858, 10000) {
            let (p, q) = Exp3InternalTrait::pade5(self);
            return Exp3InternalTrait::solve_pq(p, q);
        }
        let theta7 = R::from_ratio(26681, 10000);
        let mut norm = norm;
        let mut factor = R::one();
        let mut s: u32 = 0;
        while norm > theta7 {
            norm = norm * R::HALF;
            factor = factor * R::HALF;
            s += 1;
        }
        let b = if s == 0 {
            self
        } else {
            self.scale(factor)
        };
        let (p, q) = Exp3InternalTrait::pade7(b);
        let mut x = Exp3InternalTrait::solve_pq(p, q);
        while s != 0 {
            x = x.mul_mat(x);
            s -= 1;
        }
        x
    }
}

/// Crate-internal kernels of `Matrix3ExpTrait::exp`: the Padé approximants and the LU solve.
#[generate_trait]
pub(crate) impl Exp3InternalImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Exp3InternalTrait<T> {
    /// The Padé [3/3] approximant of `exp(a)` as `(P, Q) = (V + U, V - U)`, upstream's
    /// `pade3`: A² (1 rounded product), `V = Σ b_2k A^2k`, `W = Σ b_(2k+1) A^2k`
    /// (integer coefficients: every term exact, one fused kernel per entry), `U = a W` (one more
    /// rounded product). The magnitude of `P` and `Q` is `b_0 = 120`, so the absolute
    /// rounding of the products is `1 / b_0` relative.
    fn pade3(a: Matrix3<T>) -> (Matrix3<T>, Matrix3<T>) {
        let a2 = a.mul_mat(a);
        let c0 = R::from_int(120);
        let c1 = R::from_int(60);
        let c2 = R::from_int(12);
        let w = Matrix3 {
            m11: a2.m11 + c1,
            m21: a2.m21,
            m31: a2.m31,
            m12: a2.m12,
            m22: a2.m22 + c1,
            m32: a2.m32,
            m13: a2.m13,
            m23: a2.m23,
            m33: a2.m33 + c1,
        };
        let v = Matrix3 {
            m11: c2 * a2.m11 + c0,
            m21: c2 * a2.m21,
            m31: c2 * a2.m31,
            m12: c2 * a2.m12,
            m22: c2 * a2.m22 + c0,
            m32: c2 * a2.m32,
            m13: c2 * a2.m13,
            m23: c2 * a2.m23,
            m33: c2 * a2.m33 + c0,
        };
        let u = a.mul_mat(w);
        (v + u, v - u)
    }

    /// The Padé [5/5] approximant of `exp(a)` as `(P, Q) = (V + U, V - U)`, upstream's
    /// `pade5`: A², A⁴ (2 rounded products), `V = Σ b_2k A^2k`, `W = Σ b_(2k+1) A^2k`
    /// (integer coefficients: every term exact, one fused kernel per entry), `U = a W` (one more
    /// rounded product). The magnitude of `P` and `Q` is `b_0 = 30240`, so the absolute
    /// rounding of the products is `1 / b_0` relative.
    fn pade5(a: Matrix3<T>) -> (Matrix3<T>, Matrix3<T>) {
        let a2 = a.mul_mat(a);
        let a4 = a2.mul_mat(a2);
        let c0 = R::from_int(30240);
        let c1 = R::from_int(15120);
        let c2 = R::from_int(3360);
        let c3 = R::from_int(420);
        let c4 = R::from_int(30);
        let w = Matrix3 {
            m11: a4.m11 + c3 * a2.m11 + c1,
            m21: a4.m21 + c3 * a2.m21,
            m31: a4.m31 + c3 * a2.m31,
            m12: a4.m12 + c3 * a2.m12,
            m22: a4.m22 + c3 * a2.m22 + c1,
            m32: a4.m32 + c3 * a2.m32,
            m13: a4.m13 + c3 * a2.m13,
            m23: a4.m23 + c3 * a2.m23,
            m33: a4.m33 + c3 * a2.m33 + c1,
        };
        let v = Matrix3 {
            m11: R::sum_prod2(c4, a4.m11, c2, a2.m11) + c0,
            m21: R::sum_prod2(c4, a4.m21, c2, a2.m21),
            m31: R::sum_prod2(c4, a4.m31, c2, a2.m31),
            m12: R::sum_prod2(c4, a4.m12, c2, a2.m12),
            m22: R::sum_prod2(c4, a4.m22, c2, a2.m22) + c0,
            m32: R::sum_prod2(c4, a4.m32, c2, a2.m32),
            m13: R::sum_prod2(c4, a4.m13, c2, a2.m13),
            m23: R::sum_prod2(c4, a4.m23, c2, a2.m23),
            m33: R::sum_prod2(c4, a4.m33, c2, a2.m33) + c0,
        };
        let u = a.mul_mat(w);
        (v + u, v - u)
    }

    /// The Padé [7/7] approximant of `exp(a)` as `(P, Q) = (V + U, V - U)`, upstream's
    /// `pade7`: A², A⁴, A⁶ (3 rounded products), `V = Σ b_2k A^2k`, `W = Σ b_(2k+1) A^2k`
    /// (integer coefficients: every term exact, one fused kernel per entry), `U = a W` (one more
    /// rounded product). The magnitude of `P` and `Q` is `b_0 = 17297280`, so the absolute
    /// rounding of the products is `1 / b_0` relative.
    fn pade7(a: Matrix3<T>) -> (Matrix3<T>, Matrix3<T>) {
        let a2 = a.mul_mat(a);
        let a4 = a2.mul_mat(a2);
        let a6 = a4.mul_mat(a2);
        let c0 = R::from_int(17297280);
        let c1 = R::from_int(8648640);
        let c2 = R::from_int(1995840);
        let c3 = R::from_int(277200);
        let c4 = R::from_int(25200);
        let c5 = R::from_int(1512);
        let c6 = R::from_int(56);
        let w = Matrix3 {
            m11: a6.m11 + R::sum_prod2(c5, a4.m11, c3, a2.m11) + c1,
            m21: a6.m21 + R::sum_prod2(c5, a4.m21, c3, a2.m21),
            m31: a6.m31 + R::sum_prod2(c5, a4.m31, c3, a2.m31),
            m12: a6.m12 + R::sum_prod2(c5, a4.m12, c3, a2.m12),
            m22: a6.m22 + R::sum_prod2(c5, a4.m22, c3, a2.m22) + c1,
            m32: a6.m32 + R::sum_prod2(c5, a4.m32, c3, a2.m32),
            m13: a6.m13 + R::sum_prod2(c5, a4.m13, c3, a2.m13),
            m23: a6.m23 + R::sum_prod2(c5, a4.m23, c3, a2.m23),
            m33: a6.m33 + R::sum_prod2(c5, a4.m33, c3, a2.m33) + c1,
        };
        let v = Matrix3 {
            m11: R::sum_prod3(c6, a6.m11, c4, a4.m11, c2, a2.m11) + c0,
            m21: R::sum_prod3(c6, a6.m21, c4, a4.m21, c2, a2.m21),
            m31: R::sum_prod3(c6, a6.m31, c4, a4.m31, c2, a2.m31),
            m12: R::sum_prod3(c6, a6.m12, c4, a4.m12, c2, a2.m12),
            m22: R::sum_prod3(c6, a6.m22, c4, a4.m22, c2, a2.m22) + c0,
            m32: R::sum_prod3(c6, a6.m32, c4, a4.m32, c2, a2.m32),
            m13: R::sum_prod3(c6, a6.m13, c4, a4.m13, c2, a2.m13),
            m23: R::sum_prod3(c6, a6.m23, c4, a4.m23, c2, a2.m23),
            m33: R::sum_prod3(c6, a6.m33, c4, a4.m33, c2, a2.m33) + c0,
        };
        let u = a.mul_mat(w);
        (v + u, v - u)
    }

    /// `Q⁻¹ P`, upstream's `solve_p_q` (`q.lu().solve(&p).unwrap()`): the LU factorisation of
    /// `Q` with partial pivoting and the solve of the 3 columns of `P`. `Q` is the Padé
    /// denominator of a matrix within the threshold of its degree, well conditioned; panics with
    /// `nalgebra: singular Pade denom` (upstream's `unwrap` panic) if a pivot is exactly zero.
    fn solve_pq(p: Matrix3<T>, q: Matrix3<T>) -> Matrix3<T> {
        let mut x = p;
        assert!(Lu3Trait::new(q).solve_mut(ref x), "{}", SINGULAR_PADE);
        x
    }
}

/// `Matrix4::exp`. Import `Matrix4ExpTrait` to use it.
#[generate_trait]
pub impl Matrix4ExpImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Matrix4ExpTrait<T> {
    /// The matrix exponential `exp(a) = Σ a^k / k!`. Upstream: `OMatrix::exp`.
    ///
    /// Padé approximant with scaling and squaring, upstream's family (Higham 2005 / Al-Mohy and
    /// Higham 2009, scipy's `expm`), with the degree chosen by the 1-norm thresholds:
    ///
    /// ```text
    /// |a|₁ <= θ₃ = 0.16917        Padé [3/3]    2 rounded products + LU solve
    /// |a|₁ <= θ₅ = 1.0858         Padé [5/5]    3 rounded products + LU solve
    /// otherwise, s = the smallest integer with |a|₁ / 2^s <= θ₇ = 2.6681:
    ///                             Padé [7/7] of a / 2^s, then s squarings
    ///                             4 + s rounded products + LU solve
    /// ```
    ///
    /// The thresholds `θ_m` are Higham's backward-error bounds (`exp(a + Δa)` with `|Δa| <= u
    /// |a|`)
    /// recomputed for the Q32.32 unit roundoff `u = 2^-32` (upstream's, for `f64`'s `2^-53`, are
    /// 0.01496 / 0.2539 / 0.9504, plus degrees 9 and 13), rounded down. Deviations from upstream,
    /// all cheaper (steps criterion) and within the oracle tolerance:
    /// - the degree is chosen on `|a|₁` alone, without upstream's exact norms of `a⁴` ..
    /// `a¹⁰` and
    ///   its `ell` backward-error refinement (matrix-vector products and a base-2 logarithm);
    /// - no degree 9 or 13: at the Q32.32 thresholds (θ₉ = 4.65 < 2 θ₇, θ₁₃ = 9.22 < 4
    /// θ₇) they
    ///   cost as many rounded products as degree 7 with one / two more squarings, and their
    ///   coefficients (up to 6.5e16) do not fit Q32.32 as integers;
    /// - the coefficients are upstream's integers (`R::from_int`), so `V`, `W` are exact
    ///   combinations of the powers and `P`, `Q` have the magnitude `b_0` (1.7e7 for degree 7).
    ///
    /// Accuracy (model, then the oracle suite `matrix_functions` in `tests_linalg_exp`): within a
    /// few ulp per unit of `max |exp(a)|` at the thresholds; each squaring roughly doubles the
    /// relative error already committed (14 ulp per unit at `|a|₁ = 15` in 6x6, 3 squarings).
    /// `a / 2^s` is the exact floor `a_ij >> s`. The scaling loop is data-dependent (`s` grows
    /// with `log2 |a|₁`, like upstream's), everything else is unrolled.
    ///
    /// Panics with the scalar's overflow error when a column sum of `|a_ij|`, a Padé term or a
    /// squaring does not fit (in particular whenever `exp(a)` itself does not), and with
    /// `nalgebra: singular Pade denom` if the LU solve meets an exactly zero pivot (upstream's
    /// `unwrap`). Sierra gas charges the degree branches at their costliest path; Cairo steps
    /// follow the executed branch.
    fn exp(self: Matrix4<T>) -> Matrix4<T> {
        let norm = self.one_norm();
        if norm <= R::from_ratio(16917, 100000) {
            let (p, q) = Exp4InternalTrait::pade3(self);
            return Exp4InternalTrait::solve_pq(p, q);
        }
        if norm <= R::from_ratio(10858, 10000) {
            let (p, q) = Exp4InternalTrait::pade5(self);
            return Exp4InternalTrait::solve_pq(p, q);
        }
        let theta7 = R::from_ratio(26681, 10000);
        let mut norm = norm;
        let mut factor = R::one();
        let mut s: u32 = 0;
        while norm > theta7 {
            norm = norm * R::HALF;
            factor = factor * R::HALF;
            s += 1;
        }
        let b = if s == 0 {
            self
        } else {
            self.scale(factor)
        };
        let (p, q) = Exp4InternalTrait::pade7(b);
        let mut x = Exp4InternalTrait::solve_pq(p, q);
        while s != 0 {
            x = x.mul_mat(x);
            s -= 1;
        }
        x
    }
}

/// Crate-internal kernels of `Matrix4ExpTrait::exp`: the Padé approximants and the LU solve.
#[generate_trait]
pub(crate) impl Exp4InternalImpl<
    T,
    impl R: Real<T>,
    +Copy<T>,
    +Drop<T>,
    +Drop<R::Wide>,
    +Add<T>,
    +Sub<T>,
    +Mul<T>,
    +Neg<T>,
    +PartialEq<T>,
    +PartialOrd<T>,
> of Exp4InternalTrait<T> {
    /// The Padé [3/3] approximant of `exp(a)` as `(P, Q) = (V + U, V - U)`, upstream's
    /// `pade3`: A² (1 rounded product), `V = Σ b_2k A^2k`, `W = Σ b_(2k+1) A^2k`
    /// (integer coefficients: every term exact, one fused kernel per entry), `U = a W` (one more
    /// rounded product). The magnitude of `P` and `Q` is `b_0 = 120`, so the absolute
    /// rounding of the products is `1 / b_0` relative.
    fn pade3(a: Matrix4<T>) -> (Matrix4<T>, Matrix4<T>) {
        let a2 = a.mul_mat(a);
        let c0 = R::from_int(120);
        let c1 = R::from_int(60);
        let c2 = R::from_int(12);
        let w = Matrix4 {
            m11: a2.m11 + c1,
            m21: a2.m21,
            m31: a2.m31,
            m41: a2.m41,
            m12: a2.m12,
            m22: a2.m22 + c1,
            m32: a2.m32,
            m42: a2.m42,
            m13: a2.m13,
            m23: a2.m23,
            m33: a2.m33 + c1,
            m43: a2.m43,
            m14: a2.m14,
            m24: a2.m24,
            m34: a2.m34,
            m44: a2.m44 + c1,
        };
        let v = Matrix4 {
            m11: c2 * a2.m11 + c0,
            m21: c2 * a2.m21,
            m31: c2 * a2.m31,
            m41: c2 * a2.m41,
            m12: c2 * a2.m12,
            m22: c2 * a2.m22 + c0,
            m32: c2 * a2.m32,
            m42: c2 * a2.m42,
            m13: c2 * a2.m13,
            m23: c2 * a2.m23,
            m33: c2 * a2.m33 + c0,
            m43: c2 * a2.m43,
            m14: c2 * a2.m14,
            m24: c2 * a2.m24,
            m34: c2 * a2.m34,
            m44: c2 * a2.m44 + c0,
        };
        let u = a.mul_mat(w);
        (v + u, v - u)
    }

    /// The Padé [5/5] approximant of `exp(a)` as `(P, Q) = (V + U, V - U)`, upstream's
    /// `pade5`: A², A⁴ (2 rounded products), `V = Σ b_2k A^2k`, `W = Σ b_(2k+1) A^2k`
    /// (integer coefficients: every term exact, one fused kernel per entry), `U = a W` (one more
    /// rounded product). The magnitude of `P` and `Q` is `b_0 = 30240`, so the absolute
    /// rounding of the products is `1 / b_0` relative.
    fn pade5(a: Matrix4<T>) -> (Matrix4<T>, Matrix4<T>) {
        let a2 = a.mul_mat(a);
        let a4 = a2.mul_mat(a2);
        let c0 = R::from_int(30240);
        let c1 = R::from_int(15120);
        let c2 = R::from_int(3360);
        let c3 = R::from_int(420);
        let c4 = R::from_int(30);
        let w = Matrix4 {
            m11: a4.m11 + c3 * a2.m11 + c1,
            m21: a4.m21 + c3 * a2.m21,
            m31: a4.m31 + c3 * a2.m31,
            m41: a4.m41 + c3 * a2.m41,
            m12: a4.m12 + c3 * a2.m12,
            m22: a4.m22 + c3 * a2.m22 + c1,
            m32: a4.m32 + c3 * a2.m32,
            m42: a4.m42 + c3 * a2.m42,
            m13: a4.m13 + c3 * a2.m13,
            m23: a4.m23 + c3 * a2.m23,
            m33: a4.m33 + c3 * a2.m33 + c1,
            m43: a4.m43 + c3 * a2.m43,
            m14: a4.m14 + c3 * a2.m14,
            m24: a4.m24 + c3 * a2.m24,
            m34: a4.m34 + c3 * a2.m34,
            m44: a4.m44 + c3 * a2.m44 + c1,
        };
        let v = Matrix4 {
            m11: R::sum_prod2(c4, a4.m11, c2, a2.m11) + c0,
            m21: R::sum_prod2(c4, a4.m21, c2, a2.m21),
            m31: R::sum_prod2(c4, a4.m31, c2, a2.m31),
            m41: R::sum_prod2(c4, a4.m41, c2, a2.m41),
            m12: R::sum_prod2(c4, a4.m12, c2, a2.m12),
            m22: R::sum_prod2(c4, a4.m22, c2, a2.m22) + c0,
            m32: R::sum_prod2(c4, a4.m32, c2, a2.m32),
            m42: R::sum_prod2(c4, a4.m42, c2, a2.m42),
            m13: R::sum_prod2(c4, a4.m13, c2, a2.m13),
            m23: R::sum_prod2(c4, a4.m23, c2, a2.m23),
            m33: R::sum_prod2(c4, a4.m33, c2, a2.m33) + c0,
            m43: R::sum_prod2(c4, a4.m43, c2, a2.m43),
            m14: R::sum_prod2(c4, a4.m14, c2, a2.m14),
            m24: R::sum_prod2(c4, a4.m24, c2, a2.m24),
            m34: R::sum_prod2(c4, a4.m34, c2, a2.m34),
            m44: R::sum_prod2(c4, a4.m44, c2, a2.m44) + c0,
        };
        let u = a.mul_mat(w);
        (v + u, v - u)
    }

    /// The Padé [7/7] approximant of `exp(a)` as `(P, Q) = (V + U, V - U)`, upstream's
    /// `pade7`: A², A⁴, A⁶ (3 rounded products), `V = Σ b_2k A^2k`, `W = Σ b_(2k+1) A^2k`
    /// (integer coefficients: every term exact, one fused kernel per entry), `U = a W` (one more
    /// rounded product). The magnitude of `P` and `Q` is `b_0 = 17297280`, so the absolute
    /// rounding of the products is `1 / b_0` relative.
    fn pade7(a: Matrix4<T>) -> (Matrix4<T>, Matrix4<T>) {
        let a2 = a.mul_mat(a);
        let a4 = a2.mul_mat(a2);
        let a6 = a4.mul_mat(a2);
        let c0 = R::from_int(17297280);
        let c1 = R::from_int(8648640);
        let c2 = R::from_int(1995840);
        let c3 = R::from_int(277200);
        let c4 = R::from_int(25200);
        let c5 = R::from_int(1512);
        let c6 = R::from_int(56);
        let w = Matrix4 {
            m11: a6.m11 + R::sum_prod2(c5, a4.m11, c3, a2.m11) + c1,
            m21: a6.m21 + R::sum_prod2(c5, a4.m21, c3, a2.m21),
            m31: a6.m31 + R::sum_prod2(c5, a4.m31, c3, a2.m31),
            m41: a6.m41 + R::sum_prod2(c5, a4.m41, c3, a2.m41),
            m12: a6.m12 + R::sum_prod2(c5, a4.m12, c3, a2.m12),
            m22: a6.m22 + R::sum_prod2(c5, a4.m22, c3, a2.m22) + c1,
            m32: a6.m32 + R::sum_prod2(c5, a4.m32, c3, a2.m32),
            m42: a6.m42 + R::sum_prod2(c5, a4.m42, c3, a2.m42),
            m13: a6.m13 + R::sum_prod2(c5, a4.m13, c3, a2.m13),
            m23: a6.m23 + R::sum_prod2(c5, a4.m23, c3, a2.m23),
            m33: a6.m33 + R::sum_prod2(c5, a4.m33, c3, a2.m33) + c1,
            m43: a6.m43 + R::sum_prod2(c5, a4.m43, c3, a2.m43),
            m14: a6.m14 + R::sum_prod2(c5, a4.m14, c3, a2.m14),
            m24: a6.m24 + R::sum_prod2(c5, a4.m24, c3, a2.m24),
            m34: a6.m34 + R::sum_prod2(c5, a4.m34, c3, a2.m34),
            m44: a6.m44 + R::sum_prod2(c5, a4.m44, c3, a2.m44) + c1,
        };
        let v = Matrix4 {
            m11: R::sum_prod3(c6, a6.m11, c4, a4.m11, c2, a2.m11) + c0,
            m21: R::sum_prod3(c6, a6.m21, c4, a4.m21, c2, a2.m21),
            m31: R::sum_prod3(c6, a6.m31, c4, a4.m31, c2, a2.m31),
            m41: R::sum_prod3(c6, a6.m41, c4, a4.m41, c2, a2.m41),
            m12: R::sum_prod3(c6, a6.m12, c4, a4.m12, c2, a2.m12),
            m22: R::sum_prod3(c6, a6.m22, c4, a4.m22, c2, a2.m22) + c0,
            m32: R::sum_prod3(c6, a6.m32, c4, a4.m32, c2, a2.m32),
            m42: R::sum_prod3(c6, a6.m42, c4, a4.m42, c2, a2.m42),
            m13: R::sum_prod3(c6, a6.m13, c4, a4.m13, c2, a2.m13),
            m23: R::sum_prod3(c6, a6.m23, c4, a4.m23, c2, a2.m23),
            m33: R::sum_prod3(c6, a6.m33, c4, a4.m33, c2, a2.m33) + c0,
            m43: R::sum_prod3(c6, a6.m43, c4, a4.m43, c2, a2.m43),
            m14: R::sum_prod3(c6, a6.m14, c4, a4.m14, c2, a2.m14),
            m24: R::sum_prod3(c6, a6.m24, c4, a4.m24, c2, a2.m24),
            m34: R::sum_prod3(c6, a6.m34, c4, a4.m34, c2, a2.m34),
            m44: R::sum_prod3(c6, a6.m44, c4, a4.m44, c2, a2.m44) + c0,
        };
        let u = a.mul_mat(w);
        (v + u, v - u)
    }

    /// `Q⁻¹ P`, upstream's `solve_p_q` (`q.lu().solve(&p).unwrap()`): the LU factorisation of
    /// `Q` with partial pivoting and the solve of the 4 columns of `P`. `Q` is the Padé
    /// denominator of a matrix within the threshold of its degree, well conditioned; panics with
    /// `nalgebra: singular Pade denom` (upstream's `unwrap` panic) if a pivot is exactly zero.
    fn solve_pq(p: Matrix4<T>, q: Matrix4<T>) -> Matrix4<T> {
        let mut x = p;
        assert!(Lu4Trait::new(q).solve_mut(ref x), "{}", SINGULAR_PADE);
        x
    }
}
