// Generated by tools/linalggen/generate.py: do not edit by hand.
//! `Lblt2`: the Bunch-Kaufman `LBLᵀ` factorisation of a symmetric `Matrix2` (upstream
//! `nalgebra::linalg::LBLT<T, U2>`), fully unrolled (WP 8.5-P15).

pub use nalgebra_linalg_pivot4::linalg::lblt::lblt2::*;
