[package]
name = "pe"
version.workspace = true
edition.workspace = true
experimental-features = ["user_defined_inline_macros", "associated_item_constraints"]
[dependencies]
pf = { path = "../pf" }
[dev-dependencies]
assert_macros.workspace = true
