//! Dynamically sized matrices (upstream `DMatrix`, `DVector`, `RowDVector` and the partially
//! dynamic aliases `Matrix1xX..Matrix6xX`, `MatrixXx1..MatrixXx6`), DESIGN D5. Behind the Scarb
//! feature `dynamic` (in `default`, DESIGN D9): nothing ungated in the crate uses them; the
//! `mod` line and the re-exports in `base.cairo` / `lib.cairo` are written by
//! `tools/shapegen/shapegen.py` (`shapes.FEATURES`).
//!
//! - `dmatrix`, `dvector`, `row_dvector`: the three types, their methods and operators, and (in
//!   a block generated by `tools/shapegen/dynamic.py`) their conversions from the static shapes
//!   (Cairo finds an impl in the module of its trait or of one of its types);
//! - `shapes` (generated by `tools/shapegen/dynamic.py`): the edition forms of the static shapes
//! whose result is dynamic or another static
//!   shape (`insert_columns`, `remove_fixed_rows`...);
//! - `convolution`: `convolve_full` / `convolve_same` / `convolve_valid` of the column vectors
//!   (WP 8.6-P18);
//! - `kernels`: the loops on column-major spans.

pub mod convolution;
pub mod dmatrix;
pub mod dvector;
mod kernels;
pub mod row_dvector;
pub mod shapes;

pub use convolution::Convolution;
pub use dmatrix::{
    DMatrix, DMatrixTrait, Matrix2xX, Matrix3xX, Matrix4xX, Matrix5xX, Matrix6xX, MatrixXx2,
    MatrixXx3, MatrixXx4, MatrixXx5, MatrixXx6,
};
pub use dvector::{DVector, DVectorTrait, MatrixXx1};
pub use row_dvector::{Matrix1xX, RowDVector, RowDVectorTrait};
pub use shapes::{
    InsertFixedColumns, InsertFixedRows, Matrix1DynamicTrait, Matrix2DynamicTrait,
    Matrix2x3DynamicTrait, Matrix2x4DynamicTrait, Matrix2x5DynamicTrait, Matrix2x6DynamicTrait,
    Matrix3DynamicTrait, Matrix3x2DynamicTrait, Matrix3x4DynamicTrait, Matrix3x5DynamicTrait,
    Matrix3x6DynamicTrait, Matrix4DynamicTrait, Matrix4x2DynamicTrait, Matrix4x3DynamicTrait,
    Matrix4x5DynamicTrait, Matrix4x6DynamicTrait, Matrix5DynamicTrait, Matrix5x2DynamicTrait,
    Matrix5x3DynamicTrait, Matrix5x4DynamicTrait, Matrix5x6DynamicTrait, Matrix6DynamicTrait,
    Matrix6x2DynamicTrait, Matrix6x3DynamicTrait, Matrix6x4DynamicTrait, Matrix6x5DynamicTrait,
    RemoveFixedColumns, RemoveFixedRows, RowVector2DynamicTrait, RowVector3DynamicTrait,
    RowVector4DynamicTrait, RowVector5DynamicTrait, RowVector6DynamicTrait, Vector2DynamicTrait,
    Vector3DynamicTrait, Vector4DynamicTrait, Vector5DynamicTrait, Vector6DynamicTrait,
};
