pub mod bidiagonal1x5;
pub mod bidiagonal2x5;
pub mod bidiagonal3x5;
pub mod bidiagonal4x5;
pub mod bidiagonal5;
pub mod bidiagonal5x1;
pub mod bidiagonal5x2;
pub mod bidiagonal5x3;
pub mod bidiagonal5x4;
