[package]
name = "nalgebra_geometry4"
description = "Projective / affine / general transforms, perspective and orthographic projections, scales and reflections of dimension 1 to 4, Point1 / Translation1 methods, cg (homogeneous coordinates)."
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["linear-algebra", "fixed-point", "geometry", "base", "cg"]
readme = "README.md"

[dependencies]
nalgebra_core = { path = "../core", version = "0.1.0" }
nalgebra_shapes5 = { path = "../shapes5", version = "0.1.0" }
nalgebra_static3 = { path = "../static3", version = "0.1.0", default-features = false }
nalgebra_static4 = { path = "../static4", version = "0.1.0", default-features = false }
simba.workspace = true

[dev-dependencies]
fixed.workspace = true
snforge_std.workspace = true
assert_macros.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true
