//! Internal, no stability promise: the crate-private items of `base::matrix3x5` that the packages
//! above this one use (docs/SPLIT.md §12.3). Never re-exported by the facade `nalgebra`.

use nalgebra_core::base::errors;
use nalgebra_types3::base::vector3::Vector3;
use crate::base::matrix3x5::Matrix3x5;
use crate::base::row_vector5::RowVector5;

/// Private helpers of the `swap*` methods (runtime positions: one `match` each).
#[generate_trait]
pub impl Matrix3x5EditImpl<T, +Copy<T>, +Drop<T>> of Matrix3x5EditTrait<T> {
    /// `self` with the component at `index` (`(row, column)`) replaced by `v`; panics out of
    /// bounds.
    #[inline(always)]
    fn replace(self: Matrix3x5<T>, index: (usize, usize), v: T) -> Matrix3x5<T> {
        let (i, j) = index;
        match j {
            0 => match i {
                0 => Matrix3x5 {
                    m11: v,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                1 => Matrix3x5 {
                    m11: self.m11,
                    m21: v,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                2 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: v,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            1 => match i {
                0 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: v,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                1 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: v,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                2 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: v,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            2 => match i {
                0 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: v,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                1 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: v,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                2 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: v,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            3 => match i {
                0 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: v,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                1 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: v,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                2 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: v,
                    m15: self.m15,
                    m25: self.m25,
                    m35: self.m35,
                },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            4 => match i {
                0 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: v,
                    m25: self.m25,
                    m35: self.m35,
                },
                1 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: v,
                    m35: self.m35,
                },
                2 => Matrix3x5 {
                    m11: self.m11,
                    m21: self.m21,
                    m31: self.m31,
                    m12: self.m12,
                    m22: self.m22,
                    m32: self.m32,
                    m13: self.m13,
                    m23: self.m23,
                    m33: self.m33,
                    m14: self.m14,
                    m24: self.m24,
                    m34: self.m34,
                    m15: self.m15,
                    m25: self.m25,
                    m35: v,
                },
                _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
            },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    /// Row `i`, a `RowVector5`; panics out of bounds.
    #[inline(always)]
    fn row_at(self: Matrix3x5<T>, i: usize) -> RowVector5<T> {
        match i {
            0 => RowVector5 { x: self.m11, y: self.m12, z: self.m13, w: self.m14, a: self.m15 },
            1 => RowVector5 { x: self.m21, y: self.m22, z: self.m23, w: self.m24, a: self.m25 },
            2 => RowVector5 { x: self.m31, y: self.m32, z: self.m33, w: self.m34, a: self.m35 },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }

    /// Column `j`, a `Vector3`; panics out of bounds.
    #[inline(always)]
    fn column_at(self: Matrix3x5<T>, j: usize) -> Vector3<T> {
        match j {
            0 => Vector3 { x: self.m11, y: self.m21, z: self.m31 },
            1 => Vector3 { x: self.m12, y: self.m22, z: self.m32 },
            2 => Vector3 { x: self.m13, y: self.m23, z: self.m33 },
            3 => Vector3 { x: self.m14, y: self.m24, z: self.m34 },
            4 => Vector3 { x: self.m15, y: self.m25, z: self.m35 },
            _ => core::panic_with_felt252(errors::INDEX_OUT_OF_BOUNDS),
        }
    }
}
