// Generated by crates/nalgebra/src/linalg/generate.py: do not edit by hand.
//! Package `nalgebra_tests_linalg_hessenberg` (WP 8.5-P16): tests and gas benchmarks of the
//! Hessenberg decomposition, the symmetric tridiagonalisation, the balancing, through the public
//! API. Oracle vectors: `tools/oracle` suite `schur` (`oracle emit-cairo schur --from vectors
//! --max-per-dist 2 --ops <the ops below> --out src/oracle_schur.cairo`):
//!
//! - `hessenberg1`
//! - `hessenberg2`
//! - `hessenberg3`
//! - `hessenberg4`
//! - `hessenberg5`
//! - `hessenberg6`
//! - `symmetric_tridiagonal1`
//! - `symmetric_tridiagonal2`
//! - `symmetric_tridiagonal3`
//! - `symmetric_tridiagonal4`
//! - `symmetric_tridiagonal5`
//! - `symmetric_tridiagonal6`
//! - `balance1`
//! - `balance2`
//! - `balance3`
//! - `balance4`
//! - `balance5`
//! - `balance6`

#[cfg(test)]
mod balancing;
#[cfg(test)]
mod builders;
#[cfg(test)]
mod hessenberg1;
#[cfg(test)]
mod hessenberg2;
#[cfg(test)]
mod hessenberg3;
#[cfg(test)]
mod hessenberg4;
#[cfg(test)]
mod hessenberg5;
#[cfg(test)]
mod hessenberg6;
#[cfg(test)]
mod oracle_schur;
#[cfg(test)]
mod symmetric_tridiagonal1;
#[cfg(test)]
mod symmetric_tridiagonal2;
#[cfg(test)]
mod symmetric_tridiagonal3;
#[cfg(test)]
mod symmetric_tridiagonal4;
#[cfg(test)]
mod symmetric_tridiagonal5;
#[cfg(test)]
mod symmetric_tridiagonal6;
