"""Generated tests of the base completion (WP 8.2a, `completion.py`): the
four packages `crates/shapes_tests_{norms,componentwise,construction,structure}` (`PACKAGES`).

Tier A of `DESIGN.md` §3.3 on the 36 shapes: one exact case per (shape, family), the expected
values coming from a bit-exact integer model of the kernels, so the tests need no oracle run:

* the floor of the exact sum for every fused sum of products (`dot`, `norm_squared`,
  `component_mul`, `cmpy`, `symmetric_part`...);
* `isqrt` of the exact sum of squares for the norms (`norm`, `metric_distance`, the norm inside
  `normalize` / `cap_magnitude`...): `Real::normK` / `wide_sqrt` floor the square root of the
  UNSCALED exact sum, so the raw result is `isqrt(Σ raw²)`;
* the exact quotient rounded half to even (`Fraction`, Python's `round`) for every division
  (`unscale`, `normalize`, `component_div`, `cdpy`, the ratios of `cap_magnitude`), `fixed`'s
  nearest division.

The operations that need `Transcendental` (`angle`, `lp_norm` for `p >= 3`, `slerp`) have no
integer model: they are compared with Python's float evaluation within a tolerance in raw units
(Tier B), on a sample of shapes that covers every kernel size (`TRANSCENDENTAL_SAMPLE`) and on the
six column vectors for `slerp`.

Families and files (`src/<file>.cairo`): `norms`, `componentwise`, `extrema`, `construction`,
`structure` (comparisons, conversions, indexing, homogeneous forms, `Unit<VectorN>`),
`transcendental`, and `benches` (`gas/nalgebra_shapes_tests_norms`). Same test-file rules as
`tests_core.py`: shape values through `load` / `assert_raws` (one monomorphisation per shape), loops
for per-component checks, at most one `#[should_panic]` test per (shape, family).
"""

import math
import random
import re
import subprocess
from fractions import Fraction
from pathlib import Path

import completion as C
from model import ALL_SHAPES, COORDS, Shape
from tests_core import (FMT_MANIFEST, HELPERS, I64_MAX, ONE, col, floor_scale, load, new_call,
                        raws, rand_raw, span)

ROOT = Path(__file__).resolve().parents[2]
HEADER = "// Generated by tools/shapegen/shapegen.py (tests_ops.py): do not edit by hand.\n"

# One shape per kind and per kernel size (DESIGN §3.3 Tier B sample).
TRANSCENDENTAL_SAMPLE = [Shape(1, 1), Shape(2, 1), Shape(5, 1), Shape(1, 3), Shape(2, 3),
                         Shape(3, 2), Shape(5, 5), Shape(6, 4)]


def div_round(a: int, b: int) -> int:
    """`fixed`'s division of raws: the exact quotient `a / b` (Q32.32) rounded half to even."""
    return round(Fraction(a * ONE, b))


def mul(a: int, b: int) -> int:
    return floor_scale(a * b)


def to_f(raw: int) -> float:
    return raw / ONE


def nonzero_raw(rng: random.Random, lo: int = 30, hi: int = 34) -> int:
    """A raw whose magnitude is in `[2^lo, 2^hi)`, random sign."""
    v = rng.randrange(1 << lo, 1 << hi)
    return v if rng.random() < 0.5 else -v


class File:
    """A generated test file: its tests, the shapes whose trait it calls, extra `use` lines."""

    def __init__(self, name: str, what: str):
        self.name, self.what = name, what
        self.tests: list[str] = []
        self.traits: set[str] = set()
        self.uses: set[str] = set()

    def add(self, name: str, lines: list[str], traits=(), attr: str = ""):
        self.tests.append(f"{attr}#[test]\nfn {name}() {{\n" + "\n".join(lines) + "\n}")
        self.traits.update(traits)

    def render(self) -> str:
        body = "\n\n".join(self.tests)
        names = set(self.traits)
        for s in ALL_SHAPES:
            for n in (s.name, *s.aliases, s.unit_alias or ""):
                if n and re.search(rf"\b{n}\b", body):
                    names.add(n)
            for suffix in ("Trait", "AngleTrait"):
                if re.search(rf"\b{s.name}{suffix}\b", body):
                    names.add(f"{s.name}{suffix}")
            if s.unit_alias:
                for suffix in ("Trait", "AngleTrait"):
                    if re.search(rf"\b{s.unit_alias}{suffix}\b", body):
                        names.add(f"{s.unit_alias}{suffix}")
        for n in ("MatrixMul", "MatrixTrMul", "MatrixIndex", "Unit", "UnitTrait", "Point2",
                  "Point3"):
            if re.search(rf"\b{n}\b", body):
                names.add(n)
        for method, trait in (("mul_mat", "MatrixMul"), ("ad_mul", "MatrixTrMul"),
                              ("get", "MatrixIndex")):
            if re.search(rf"\.{method}\(", body):
                names.add(trait)
        helpers = [h for h in ("fx", "load", "assert_raws", "assert_near", "assert_raws_near")
                   if re.search(rf"\b{h}\(", body)]
        if "UnitTrait" in names:
            names.discard("UnitTrait")
            self.uses.add("use nalgebra::base::unit::UnitTrait;")
        uses = ["use fixed::Fixed;"] + sorted(self.uses)
        uses += [f"use nalgebra::{{{', '.join(sorted(names))}}};" if len(names) > 1 else
                 f"use nalgebra::{next(iter(names))};"] if names else []
        uses.append(f"use crate::helpers::{{{', '.join(helpers)}}};" if len(helpers) > 1 else
                    f"use crate::helpers::{helpers[0]};")
        return f"{HEADER}//! {self.what}\n\n" + "\n".join(uses) + "\n\n" + body + "\n"


def fxs(values) -> str:
    values = list(values)
    if not values:
        return "ArrayTrait::<Fixed>::new().span()"
    return f"array![{', '.join(f'fx({v})' for v in values)}].span()"


# --------------------------------------------------------------------------------------------
# Families
# --------------------------------------------------------------------------------------------


def norms(f: File, s: Shape):
    rng = random.Random(f"tests_ops/norms/{s.name}")
    a, b, k = raws(rng, s), raws(rng, s), nonzero_raw(rng)
    F = s.fields
    sq = sum(a[x] ** 2 for x in F)
    n = math.isqrt(sq)
    lines = [load(s, "a", a), load(s, "b", b),
             f"assert!(a.dot(b) == fx({floor_scale(sum(a[x] * b[x] for x in F))}));",
             f"assert!(a.norm_squared() == fx({floor_scale(sq)}));",
             f"assert!(a.magnitude_squared() == fx({floor_scale(sq)}));",
             f"assert!(a.norm() == fx({n}));", f"assert!(a.magnitude() == fx({n}));",
             f"assert!(a.metric_distance(b) == fx({math.isqrt(sum((a[x] - b[x]) ** 2 for x in F))}));",
             f"assert_raws(a.unscale(fx({k})), {col(s, {x: div_round(a[x], k) for x in F})});",
             f"assert_raws(a.normalize(), {col(s, {x: div_round(a[x], n) for x in F})});",
             f"assert_raws(a.try_normalize(fx({n - 1})).unwrap(), "
             f"{col(s, {x: div_round(a[x], n) for x in F})});",
             f"assert!(a.try_normalize(fx({n})).is_none());"]
    cap = n // 2 + 1
    ratio = div_round(cap, n)
    lines += [f"assert_raws(a.cap_magnitude(fx({cap})), {col(s, {x: mul(a[x], ratio) for x in F})});",
              f"assert_raws(a.cap_magnitude(fx({n})), {col(s, a)});"]
    mag = 3 * ONE + 12345
    ratio = div_round(mag, n)
    lines += ["let mut c = a;", f"c.try_set_magnitude(fx({mag}), fx({n - 1}));",
              f"assert_raws(c, {col(s, {x: mul(a[x], ratio) for x in F})});",
              f"c.try_set_magnitude(fx({mag}), fx({64 * ONE}));",
              f"assert_raws(c, {col(s, {x: mul(a[x], ratio) for x in F})});"]
    one = max(sum(abs(a[s.f(i, j)]) for i in range(s.r)) for j in range(s.c))
    lines.append(f"assert!(a.one_norm() == fx({one}));")
    if s.is_column:
        lines += orthonormalize_lines(s, a, b)
    f.add(f"test_{s.module}_norms", lines, [f"{s.name}Trait"])
    f.add(f"test_{s.module}_normalize_zero_panics",
          [f"let z: {s.name}<Fixed> = {s.name}Trait::zeros();", "let _ = z.normalize();"],
          [f"{s.name}Trait"], attr="#[should_panic(expected: 'Fixed: division by zero')]\n")


def gram_schmidt(vs: list[list[float]], dim: int) -> tuple[list[list[float]], int]:
    """Upstream's `orthonormalize` in floats (the expected values, within a tolerance)."""
    vs = [list(v) for v in vs]
    nb = 0
    for i in range(len(vs)):
        elt = vs[i]
        for b in vs[:nb]:
            d = sum(x * y for x, y in zip(elt, b))
            elt = [x - y * d for x, y in zip(elt, b)]
        vs[i] = elt
        n = math.sqrt(sum(x * x for x in elt))
        if n > 0:
            vs[i] = [x / n for x in elt]
            vs[nb], vs[i] = vs[i], vs[nb]
            nb += 1
            if nb == dim:
                break
    return vs, nb


def orthonormalize_lines(s: Shape, a: dict, b: dict) -> list[str]:
    """`orthonormalize([a, 0, b])` (the zero vector is dependent), then, on `Vector3`,
    `orthonormal_subspace_basis` of 0, 1 and 2 vectors."""
    F, S = s.fields, s.name
    va, vb = [to_f(a[x]) for x in F], [to_f(b[x]) for x in F]
    out, nb = gram_schmidt([va, [0.0] * s.r, vb], s.r)
    lines = [f"let mut vs: Array<{S}<Fixed>> = array![a, {S}Trait::zeros(), b];",
             f"assert!({S}Trait::orthonormalize(ref vs) == {nb});", "assert!(vs.len() == 3);"]
    for i, v in enumerate(out):
        lines.append(f"assert_raws_near(*vs[{i}], {span(round(x * ONE) for x in v)}, 4096);")
    if (s.r, s.c) == (3, 1):
        def cross(u, v):
            return [u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2], u[0] * v[1] - u[1] * v[0]]

        def unit(u):
            n = math.sqrt(sum(x * x for x in u))
            return [x / n for x in u]
        av = unit([va[2], 0.0, -va[0]] if abs(va[0]) > abs(va[1]) else [0.0, -va[2], va[1]])
        cases = [("ArrayTrait::<Vector3<Fixed>>::new()", [[1.0, 0, 0], [0, 1.0, 0], [0, 0, 1.0]]),
                 ("array![a]", [cross(av, va), av]), ("array![a, b]", [unit(cross(va, vb))])]
        for arr, basis in cases:
            lines += [f"let basis = Vector3Trait::orthonormal_subspace_basis({arr}.span());",
                      f"assert!(basis.len() == {len(basis)});"]
            for i, v in enumerate(basis):
                lines.append(f"assert_raws_near(*basis[{i}], {span(round(x * ONE) for x in v)}, "
                             f"{16384 if len(arr) > 9 else 4096});")
    return lines


def componentwise(f: File, s: Shape):
    rng = random.Random(f"tests_ops/componentwise/{s.name}")
    a = raws(rng, s)
    b = {x: nonzero_raw(rng) for x in s.fields}
    c = raws(rng, s)
    alpha, beta, k = rand_raw(rng, 34), rand_raw(rng, 34), rand_raw(rng)
    F = s.fields
    prod = {x: mul(a[x], b[x]) for x in F}
    quot = {x: div_round(a[x], b[x]) for x in F}
    cm = {x: floor_scale(mul(alpha, a[x]) * b[x] + beta * c[x]) for x in F}
    cd = {x: mul(beta, c[x]) + div_round(mul(alpha, a[x]), b[x]) for x in F}
    lines = [load(s, "a", a), load(s, "b", b), load(s, "c", c),
             f"assert_raws(a.component_mul(b), {col(s, prod)});",
             f"assert_raws(a.component_div(b), {col(s, quot)});",
             "let mut m = a;", "m.component_mul_assign(b);", f"assert_raws(m, {col(s, prod)});",
             "let mut d = a;", "d.component_div_assign(b);", f"assert_raws(d, {col(s, quot)});",
             f"assert_raws(a.inf(c), {col(s, {x: min(a[x], c[x]) for x in F})});",
             f"assert_raws(a.sup(c), {col(s, {x: max(a[x], c[x]) for x in F})});",
             "let (lo, hi) = a.inf_sup(c);",
             f"assert_raws(lo, {col(s, {x: min(a[x], c[x]) for x in F})});",
             f"assert_raws(hi, {col(s, {x: max(a[x], c[x]) for x in F})});",
             f"assert_raws(a.add_scalar(fx({k})), {col(s, {x: a[x] + k for x in F})});",
             "let mut p = c;", f"p.cmpy(fx({alpha}), a, b, fx({beta}));",
             f"assert_raws(p, {col(s, cm)});",
             "let mut q = c;", f"q.cdpy(fx({alpha}), a, b, fx({beta}));",
             f"assert_raws(q, {col(s, cd)});"]
    kd = nonzero_raw(rng)
    lines += ["let mut e = a;", f"e *= fx({k});", f"assert_raws(e, {col(s, {x: mul(a[x], k) for x in F})});",
              "let mut g = a;", f"g /= fx({kd});",
              f"assert_raws(g, {col(s, {x: div_round(a[x], kd) for x in F})});"]
    f.add(f"test_{s.module}_componentwise", lines, [f"{s.name}Trait"])
    zero = dict(b)
    zero[F[-1]] = 0
    f.add(f"test_{s.module}_component_div_by_zero_panics",
          [load(s, "a", a), load(s, "b", zero), "let _ = a.component_div(b);"],
          [f"{s.name}Trait"], attr="#[should_panic(expected: 'Fixed: division by zero')]\n")


def extrema(f: File, s: Shape):
    rng = random.Random(f"tests_ops/extrema/{s.name}")
    a = raws(rng, s)
    F = s.fields
    if s.n >= 3:  # ties: the first one (storage order) wins
        top = max(F, key=lambda x: abs(a[x]))
        later = [x for x in F if F.index(x) > F.index(top)]
        if later:
            a[later[-1]] = -a[top]
        lo = min(F, key=lambda x: a[x])
        later = [x for x in F if F.index(x) > F.index(lo)]
        if later:
            a[later[0]] = a[lo]
    vals = [a[x] for x in F]
    first = lambda pred: next(i for i, v in enumerate(vals) if pred(v))  # noqa: E731
    imin, imax = first(lambda v: v == min(vals)), first(lambda v: v == max(vals))
    iamin = first(lambda v: abs(v) == min(map(abs, vals)))
    iamax = first(lambda v: abs(v) == max(map(abs, vals)))
    lines = [load(s, "a", a),
             f"assert!(a.min() == fx({min(vals)}));", f"assert!(a.max() == fx({max(vals)}));",
             f"assert!(a.amin() == fx({min(map(abs, vals))}));",
             f"assert!(a.amax() == fx({max(map(abs, vals))}));",
             f"assert!(a.camin() == fx({min(map(abs, vals))}));",
             f"assert!(a.camax() == fx({max(map(abs, vals))}));",
             f"assert!(a.iamax_full() == ({iamax % s.r}, {iamax // s.r}));",
             f"assert!(a.icamax_full() == ({iamax % s.r}, {iamax // s.r}));"]
    if s.is_column:
        lines += [f"assert!(a.argmin() == ({imin}, fx({vals[imin]})));",
                  f"assert!(a.argmax() == ({imax}, fx({vals[imax]})));",
                  f"assert!(a.imin() == {imin});", f"assert!(a.imax() == {imax});",
                  f"assert!(a.iamin() == {iamin});", f"assert!(a.iamax() == {iamax});",
                  f"assert!(a.icamax() == {iamax});"]
    f.add(f"test_{s.module}_extrema", lines, [f"{s.name}Trait"])


def construction(f: File, s: Shape):
    rng = random.Random(f"tests_ops/construction/{s.name}")
    a, e = raws(rng, s), rand_raw(rng)
    S, F = s.name, s.fields
    m = min(s.r, s.c)
    d = [rand_raw(rng) for _ in range(m)]
    diag = lambda vs: {s.f(i, j): (vs[i] if i == j and i < len(vs) else 0)  # noqa: E731
                       for i in range(s.r) for j in range(s.c)}
    fn_raw = {s.f(i, j): i * 7 + j * 3 + 1 for i in range(s.r) for j in range(s.c)}
    lines = [f"assert_raws({S}Trait::repeat(fx({e})), {span([e] * s.n)});",
             f"assert_raws({S}Trait::from_element(fx({e})), {span([e] * s.n)});",
             f"let g: {S}<Fixed> = {S}Trait::from_fn(|i: usize, j: usize| fx((i * 7 + j * 3 + 1)"
             f".into()));", f"assert_raws(g, {col(s, fn_raw)});",
             f"assert_raws({S}Trait::from_row_slice({fxs(a[x] for x in s.row_major)}), {col(s, a)});",
             f"assert_raws({S}Trait::from_column_slice({fxs(a[x] for x in F)}), {col(s, a)});",
             f"assert_raws({S}Trait::from_partial_diagonal({fxs(d)}), {col(s, diag(d))});",
             f"assert_raws({S}Trait::from_partial_diagonal({fxs(d[:-1])}), {col(s, diag(d[:-1]))});",
             f"let z: {S}<Fixed> = {S}Trait::zeros();", "assert!(z.is_zero());",
             load(s, "a", a), "assert!(!a.is_zero());"]
    if s.is_column:
        for i, ax in enumerate(COORDS[:s.r]):
            unit = [ONE if k == i else 0 for k in range(s.r)]
            lines += [f"let ax: {S}<Fixed> = {S}Trait::{ax}();", f"assert_raws(ax, {span(unit)});"]
        i = rng.randrange(s.r)
        lines += [f"assert_raws({S}Trait::ith({i}, fx({e})), "
                  f"{span([e if k == i else 0 for k in range(s.r)])});",
                  f"let axis: Unit<{S}<Fixed>> = {S}Trait::ith_axis({i});",
                  f"assert_raws(axis.value, {span([ONE if k == i else 0 for k in range(s.r)])});"]
    lines += conversion_lines(f, s, a, rng)
    f.add(f"test_{s.module}_construction", lines, [f"{S}Trait"])
    f.add(f"test_{s.module}_from_row_slice_wrong_length_panics",
          [f"let _: {S}<Fixed> = {S}Trait::from_row_slice({fxs([1] * (s.n + 1))});"],
          [f"{S}Trait"], attr="#[should_panic(expected: 'nalgebra: wrong slice length')]\n")


# Serde images of the geometry sources (raw generators) and the method the conversion wraps.
GEOMETRY_SOURCES = {
    "Rotation2": (4, None), "Rotation3": (9, None), "UnitComplex": (2, None),
    "UnitQuaternion": (4, None), "Isometry2": (4, None), "Isometry3": (7, None),
    "Similarity2": (5, None), "Similarity3": (8, None), "Translation2": (2, None),
    "Translation3": (3, None),
}


def conversion_lines(f: File, s: Shape, a: dict, rng: random.Random) -> list[str]:
    lines = []
    for src, how, _ in C.GEOMETRY_INTO.get((s.r, s.c), []):
        n, _ = GEOMETRY_SOURCES[src]
        raw = [rand_raw(rng, 32) for _ in range(n)]
        var = src.lower()
        expected = how.replace("self", var)
        lines += [f"let {var}: {src}<Fixed> = load({span(raw)});",
                  f"let m: {s.name}<Fixed> = {var}.into();", f"assert!(m == {expected});"]
        f.uses.add(f"use nalgebra::{src};")
        m = re.match(r"(\w+Trait)::", how)
        if m:
            f.uses.add(f"use nalgebra::{m.group(1)};")
    if s.c in (2, 3):
        q = Shape(s.c, s.c)
        vq = raws(rng, q, 32)
        o = {s.f(i, j): floor_scale(sum(a[s.f(i, k)] * vq[q.f(k, j)] for k in range(s.c)))
             for i in range(s.r) for j in range(s.c)}
        od = {s.f(i, j): floor_scale(sum(a[s.f(i, k)] * vq[q.f(j, k)] for k in range(s.c)))
              for i in range(s.r) for j in range(s.c)}
        lines += [f"let rot: Rotation{s.c}<Fixed> = load({col(q, vq)});",
                  f"assert_raws(a.mul_mat(rot), {col(s, o)});",
                  f"assert_raws(a.div_rotation(rot), {col(s, od)});"]
        f.uses.add(f"use nalgebra::Rotation{s.c};")
    return lines


def structure(f: File, s: Shape):
    rng = random.Random(f"tests_ops/structure/{s.name}")
    a = raws(rng, s)
    S, F = s.name, s.fields
    t = s.transposed()
    tv = {t.f(j, i): a[s.f(i, j)] for i in range(s.r) for j in range(s.c)}
    lines = [load(s, "a", a), f"assert_raws(a.adjoint(), {col(t, tv)});",
             f"assert_raws(a.conjugate_transpose(), {col(t, tv)});",
             f"assert_raws(a.conjugate(), {col(s, a)});"]
    traits = {f"{S}Trait"}
    if s.is_square:
        sym = {s.f(i, j): (a[s.f(i, j)] if i == j else (a[s.f(i, j)] + a[s.f(j, i)]) >> 1)
               for i in range(s.r) for j in range(s.c)}
        lines += [f"assert_raws(a.symmetric_part(), {col(s, sym)});",
                  f"assert_raws(a.hermitian_part(), {col(s, sym)});"]
        if 2 <= s.r <= 5:
            u = Shape(s.r + 1, s.r + 1)
            h = {u.f(i, j): (a[s.f(i, j)] if i < s.r and j < s.r else ONE if i == j else 0)
                 for i in range(u.r) for j in range(u.c)}
            lines.append(f"assert_raws(a.to_homogeneous(), {col(u, h)});")
        idv = {s.f(i, j): ONE if i == j else 0 for i in range(s.r) for j in range(s.c)}
        lines += [f"let o: {S}<Fixed> = One::one();", f"assert_raws(o, {col(s, idv)});",
                  "assert!(o.is_one());", "assert!(!o.is_non_one());", "assert!(!a.is_one());",
                  "assert!(a.is_non_one());"]
        f.uses.add("use core::num::traits::{Bounded, One};")
    if s.is_column and s.r <= 5:
        u = Shape(s.r + 1, 1)
        v = rand_raw(rng)
        lines.append(f"assert_raws(a.push(fx({v})), {span([a[x] for x in F] + [v])});")
        if s.r >= 2:
            lines.append(f"assert_raws(a.to_homogeneous(), {span([a[x] for x in F] + [0])});")
        lines += [load(u, "hv", {**{x: a[x] for x in F}, u.fields[-1]: 0}),
                  load(u, "hp", {**{x: a[x] for x in F}, u.fields[-1]: ONE}),
                  f"assert_raws({S}Trait::from_homogeneous(hv).unwrap(), {col(s, a)});",
                  f"assert!({S}Trait::from_homogeneous(hp).is_none());"]
    # comparisons
    near = {x: a[x] + rng.choice((-3, -1, 0, 2, 3)) for x in F}
    near[F[0]] = a[F[0]] - 3  # the largest deviation is 3 ulp
    last = F[-1]
    a2 = dict(a)
    a2[last] = 5 * ONE + rng.randrange(ONE)
    far = dict(a2)
    far[last] = a2[last] + 1000
    lines += [load(s, "near", near), load(s, "a2", a2), load(s, "far", far),
              "assert!(a.relative_eq(near, 3, fx(0)));", "assert!(!a.relative_eq(near, 2, fx(0)));",
              "assert!(!a2.relative_eq(far, 3, fx(0)));", "assert!(a2.relative_eq(far, 3, fx(4096)));",
              "assert!(a.ulps_eq(near, 3, 0));", "assert!(!a2.ulps_eq(far, 3, 999));",
              "assert!(a2.ulps_eq(far, 3, 1000));", "assert!(a == a);"]
    lo = {x: a[x] - 1 for x in F}
    mixed = dict(lo)
    mixed[last] = a[last] + 1
    lines += [load(s, "lo", lo), "assert!(a != lo);",
              "assert!(lo < a);", "assert!(lo <= a);", "assert!(a > lo);", "assert!(a >= lo);",
              "assert!(a <= a);", "assert!(!(a < a));"]
    if s.n > 1:
        lines += [load(s, "mixed", mixed), "assert!(!(mixed < a) && !(mixed >= a));",
                  "assert!(!(mixed > a) && !(mixed <= a));"]
    # casts and conversions
    arr = "[" + ", ".join("[" + ", ".join(f"fx({a[s.f(i, j)]})" for i in range(s.r)) + "]"
                          for j in range(s.c)) + "]"
    lines += [f"let c: {S}<Fixed> = a.cast();", f"assert_raws(c, {col(s, a)});",
              f"let tc: {S}<Fixed> = a.try_cast().unwrap();", f"assert_raws(tc, {col(s, a)});",
              f"let m: {S}<Fixed> = {arr}.into();", f"assert_raws(m, {col(s, a)});",
              f"let nested: [[Fixed; {s.r}]; {s.c}] = a.into();",
              f"let back: {S}<Fixed> = nested.into();", f"assert_raws(back, {col(s, a)});",
              f"let mx: {S}<i64> = Bounded::MAX;", f"assert_raws(mx, {span([I64_MAX] * s.n)});",
              f"let mn: {S}<i64> = Bounded::MIN;", f"assert_raws(mn, {span([-I64_MAX - 1] * s.n)});"]
    f.uses.add("use core::num::traits::Bounded;" if not s.is_square else
               "use core::num::traits::{Bounded, One};")
    # indexing: every component through the four accessors, in loops
    lines += [f"let e = {col(s, a)};", "let mut k: usize = 0;",
              f"while k < {s.n} {{", "let v = fx(*e[k]);",
              "assert!(a[k] == v);", "assert!(MatrixIndex::index(a, k) == v);",
              "assert!(a.get(k) == Option::Some(v));",
              f"let (i, j) = (k % {s.r}, k / {s.r});",
              "assert!(a[(i, j)] == v);", "assert!(MatrixIndex::index(a, (i, j)) == v);",
              "assert!(a.get((i, j)) == Option::Some(v));", "k += 1;", "}",
              f"assert!(a.get({s.n}).is_none());", f"assert!(a.get(({s.r}, 0)).is_none());",
              f"assert!(a.get((0, {s.c})).is_none());"]
    # ad_mul (MatrixTrMul) and m * p
    col_v = Shape(s.r, 1)
    w = raws(rng, col_v)
    tm = {Shape(s.c, 1).f(i, 0): floor_scale(sum(a[s.f(q, i)] * w[col_v.f(q, 0)] for q in range(s.r)))
          for i in range(s.c)}
    lines += [load(col_v, "w", w), f"assert_raws(a.ad_mul(w), {col(Shape(s.c, 1), tm)});"]
    if s.r in (2, 3) and s.c in (2, 3):
        p = {COORDS[q]: rand_raw(rng) for q in range(s.c)}
        mp = [floor_scale(sum(a[s.f(i, q)] * p[COORDS[q]] for q in range(s.c))) for i in range(s.r)]
        lines += [f"let p: Point{s.c}<Fixed> = load({span(p[c] for c in COORDS[:s.c])});",
                  f"assert_raws(a.mul_mat(p), {span(mp)});"]
    # Unit<VectorN>
    if s.is_column:
        U = s.unit_alias
        lines += [f"let u: {U}<Fixed> = Unit {{ value: a }};",
                  f"let uc: {U}<Fixed> = u.cast();", f"assert_raws(uc.value, {col(s, a)});",
                  f"let un: {U}<Fixed> = Unit {{ value: near }};",
                  "assert!(u.relative_eq(un, 3, fx(0)));", "assert!(!u.relative_eq(un, 2, fx(0)));",
                  "assert!(u.ulps_eq(un, 3, 0));"]
        if s.r in (1, 5, 6):
            for i, ax in enumerate(F):
                lines += [f"let ua: {U}<Fixed> = {U}Trait::{ax}_axis();",
                          f"assert_raws(ua.value, {span([ONE if k == i else 0 for k in range(s.r)])});"]
            n = math.isqrt(sum(a[x] ** 2 for x in F))
            lines += [f"let nu: {U}<Fixed> = UnitTrait::new_normalize(a);",
                      f"assert_raws(nu.value, {col(s, {x: div_round(a[x], n) for x in F})});",
                      ]
        traits.add(f"{U}Trait")
    f.add(f"test_{s.module}_structure", lines, traits)
    f.add(f"test_{s.module}_index_out_of_bounds_panics",
          [load(s, "a", a), f"let _ = a[({s.r}, 0)];"],
          attr="#[should_panic(expected: 'nalgebra: index out of bounds')]\n")


def transcendental(f: File, s: Shape):
    rng = random.Random(f"tests_ops/transcendental/{s.name}")
    a, b = raws(rng, s), raws(rng, s)
    S, F = s.name, s.fields
    na = math.sqrt(sum(to_f(a[x]) ** 2 for x in F))
    nb = math.sqrt(sum(to_f(b[x]) ** 2 for x in F))
    cos = sum(to_f(a[x]) * to_f(b[x]) for x in F) / (na * nb)
    ang = math.acos(max(-1.0, min(1.0, cos)))
    l3 = sum(abs(to_f(a[x])) ** 3 for x in F) ** (1 / 3)
    lines = [load(s, "a", a), load(s, "b", b),
             f"assert_near(a.angle(b), {round(ang * ONE)}, 4096);",
             f"assert!(a.angle(a) == fx(0));",
             f"assert!(a.lp_norm(1) == fx({sum(abs(a[x]) for x in F)}));",
             f"assert!(a.lp_norm(2) == fx({math.isqrt(sum(a[x] ** 2 for x in F))}));",
             f"assert_near(a.lp_norm(3), {round(l3 * ONE)}, {max(4096, round(l3 * ONE * 1e-6))});"]
    f.add(f"test_{s.module}_transcendental", lines, [f"{S}AngleTrait"])


def slerp_case(f: File, s: Shape):
    rng = random.Random(f"tests_ops/slerp/{s.name}")
    S, F, U = s.name, s.fields, s.unit_alias
    if s.r == 1:  # Vector1: the only directions are +x and -x (opposite: `self` is kept)
        a = {"x": 3 * ONE}
        f.add(f"test_{s.module}_slerp", [
            load(s, "a", a), load(s, "b", {"x": -2 * ONE}),
            f"assert_raws(a.slerp(b, fx({ONE // 3})), {span([ONE])});",
            f"let u: {U}<Fixed> = Unit {{ value: a.normalize() }};",
            f"assert_raws(u.slerp(u, fx({ONE // 2})).value, {span([ONE])});"],
            [f"{S}AngleTrait", f"{S}Trait", f"{U}AngleTrait"])
        return
    a, b = raws(rng, s), raws(rng, s)
    t = rng.randrange(ONE)
    ua = [to_f(a[x]) for x in F]
    ub = [to_f(b[x]) for x in F]
    na, nb = math.sqrt(sum(v * v for v in ua)), math.sqrt(sum(v * v for v in ub))
    ua, ub = [v / na for v in ua], [v / nb for v in ub]
    th = math.acos(sum(x * y for x, y in zip(ua, ub)))
    tf = t / ONE
    wa, wb = math.sin((1 - tf) * th) / math.sin(th), math.sin(tf * th) / math.sin(th)
    exp = [round((wa * x + wb * y) * ONE) for x, y in zip(ua, ub)]
    n = math.isqrt(sum(a[x] ** 2 for x in F))
    self_raws = [div_round(a[x], n) for x in F]
    f.add(f"test_{s.module}_slerp", [
        load(s, "a", a), load(s, "b", b),
        f"assert_raws_near(a.slerp(b, fx({t})), {span(exp)}, 8192);",
        f"let ua: {U}<Fixed> = UnitTrait::new_normalize(a);",
        f"let ub: {U}<Fixed> = UnitTrait::new_normalize(b);",
        f"assert_raws_near(ua.slerp(ub, fx({t})).value, {span(exp)}, 8192);",
        f"assert_raws_near(ua.try_slerp(ub, fx({t}), fx(0)).unwrap().value, {span(exp)}, 8192);",
        f"assert!(ua.try_slerp(ub, fx({t}), fx({ONE})).is_none());",
        f"assert_raws_near(ua.slerp(ua, fx({t})).value, {span(self_raws)}, 8192);",
        f"let ex: {U}<Fixed> = Unit {{ value: {S}Trait::x() }};",
        f"assert!(ex.slerp(-ex, fx({t})) == ex);", f"assert!(ex.try_slerp(-ex, fx({t}), fx(0)).is_none());"],
        [f"{S}AngleTrait", f"{S}Trait", f"{U}AngleTrait"])


# --------------------------------------------------------------------------------------------
# Benchmarks
# --------------------------------------------------------------------------------------------


def bench(group: str, variant: str, lines: list[str]) -> str:
    return f"#[test]\n#[inline(never)]\nfn bench_{group}__{variant}() {{\n" + "\n".join(lines) + "\n}"


BENCH_HELPERS = """
/// `from_row_slice` with a length check then a bounds-checked `*data[k]` per component, against
/// the library's ONE fixed-size-array read (`Span -> @Box<[T; 9]>`).
fn alt_span_index_from_row_slice(data: Span<Fixed>) -> Matrix3<Fixed> {
    assert!(data.len() == 9, "nalgebra: wrong slice length");
    Matrix3 {
        m11: *data[0],
        m21: *data[3],
        m31: *data[6],
        m12: *data[1],
        m22: *data[4],
        m32: *data[7],
        m13: *data[2],
        m23: *data[5],
        m33: *data[8],
    }
}

/// `Matrix6::unscale` as four `div9` (the library chunks 36 quotients as `div16 + div16 + div4`).
fn alt_div9_unscale(m: Matrix6<Fixed>, k: Fixed) -> Matrix6<Fixed> {
    let (m11, m21, m31, m41, m51, m61, m12, m22, m32) = Real::div9(
        m.m11, m.m21, m.m31, m.m41, m.m51, m.m61, m.m12, m.m22, m.m32, k,
    );
    let (m42, m52, m62, m13, m23, m33, m43, m53, m63) = Real::div9(
        m.m42, m.m52, m.m62, m.m13, m.m23, m.m33, m.m43, m.m53, m.m63, k,
    );
    let (m14, m24, m34, m44, m54, m64, m15, m25, m35) = Real::div9(
        m.m14, m.m24, m.m34, m.m44, m.m54, m.m64, m.m15, m.m25, m.m35, k,
    );
    let (m45, m55, m65, m16, m26, m36, m46, m56, m66) = Real::div9(
        m.m45, m.m55, m.m65, m.m16, m.m26, m.m36, m.m46, m.m56, m.m66, k,
    );
    Matrix6 {
        m11, m21, m31, m41, m51, m61, m12, m22, m32, m42, m52, m62, m13, m23, m33, m43, m53, m63,
        m14, m24, m34, m44, m54, m64, m15, m25, m35, m45, m55, m65, m16, m26, m36, m46, m56, m66,
    }
}

/// `Vector4::slerp` with upstream's angle, `acos(u · v)` and `sqrt(1 - (u · v)²)`, against the
/// library's Kahan half-angle form (`2 atan2(|u - v|, |u + v|)`).
fn alt_acos_slerp(a: Vector4<Fixed>, b: Vector4<Fixed>, t: Fixed) -> Vector4<Fixed> {
    let u = a.normalize();
    let v = b.normalize();
    let c = Real::sum_prod4(u.x, v.x, u.y, v.y, u.z, v.z, u.w, v.w);
    if c >= Real::one() {
        return u;
    }
    let hang = Transcendental::acos(c);
    let shang = Real::sqrt(Real::diff_prod(Real::one(), Real::one(), c, c));
    let ta = Real::div(Transcendental::sin((Real::one() - t) * hang), shang);
    let tb = Real::div(Transcendental::sin(t * hang), shang);
    Vector4 {
        x: Real::sum_prod2(u.x, ta, v.x, tb),
        y: Real::sum_prod2(u.y, ta, v.y, tb),
        z: Real::sum_prod2(u.z, ta, v.z, tb),
        w: Real::sum_prod2(u.w, ta, v.w, tb),
    }
}

/// `Matrix2x3::unscale` with one `Real::div` per component (the library: one `div6`).
fn alt_per_component_unscale(m: Matrix2x3<Fixed>, k: Fixed) -> Matrix2x3<Fixed> {
    Matrix2x3 {
        m11: Real::div(m.m11, k),
        m21: Real::div(m.m21, k),
        m12: Real::div(m.m12, k),
        m22: Real::div(m.m22, k),
        m13: Real::div(m.m13, k),
        m23: Real::div(m.m23, k),
    }
}
"""


def render_benches() -> str:
    """Gas of the new operations, per family, on representative shapes (`bench_<group>__<v>`).

    Every variant of a group loads the same black-boxed inputs and compares its result with the
    same black-boxed expected value (`assert!(r == e)`, the baseline `assert!(e == e)`), so the
    net gas is the operation's. The transcendental results have no integer model: they are
    compared with a black-boxed value they differ from (`!=`, same cost as `==`)."""
    fns = []
    need = {"Matrix3", "Matrix3Trait", "Matrix6", "Matrix2x3", "Vector4Trait"}
    bb = lambda s, var, v: f"let {var}: {s.name}<Fixed> = black_box(load({col(s, v)}));"  # noqa: E731

    def group(name: str, s: Shape, expr, expected, variants=(), k: int | None = None,
              trait: str = "Trait", exact: bool = True):
        """`expr(a, b, k)` / `expected(a, b, k)` -> (Cairo type, Cairo value) on the raws."""
        need.update({s.name, f"{s.name}{trait}"})
        rng = random.Random(f"tests_ops/bench/{name}")
        a, b = raws(rng, s), {x: nonzero_raw(rng) for x in s.fields}
        code = expr("a", "b", "k")
        pre = [bb(s, "a", a)]
        if re.search(r"\bb\b", code):
            pre.append(bb(s, "b", b))
        if k is not None:
            pre.append(f"let k: Fixed = black_box(fx({k}));")
        ty, val = expected(a, b, k)
        pre.append(f"let e: {ty} = black_box({val});")
        op = "==" if exact else "!="
        base = [re.sub(r"let (a|b|k):", r"let _\1:", line) for line in pre]
        fns.append(bench(name, "baseline", base + ["assert!(e == e);"]))
        fns.append(bench(name, "library", pre + [f"assert!({code} {op} e);"]))
        for v, alt in variants:
            fns.append(bench(name, v, pre + [f"assert!({alt('a', 'b', 'k')} {op} e);"]))

    def shape_of(s: Shape, vals: dict) -> tuple[str, str]:
        return f"{s.name}<Fixed>", f"load({col(s, vals)})"

    def scalar(raw: int) -> tuple[str, str]:
        return "Fixed", f"fx({raw})"

    kk = 3 * ONE + 5
    for s, alt in ((Shape(2, 3), ("alt_per_component_div", "alt_per_component_unscale")),
                   (Shape(6, 6), ("alt_div9", "alt_div9_unscale"))):
        group(f"{s.module}_unscale", s, lambda a, b, k: f"{a}.unscale({k})",
              lambda a, b, k, s=s: shape_of(s, {x: div_round(a[x], k) for x in s.fields}),
              [(alt[0], lambda a, b, k, f=alt[1]: f"{f}({a}, {k})")], k=kk)
    v5 = Shape(5, 1)
    group("vector5_normalize", v5, lambda a, b, k: f"{a}.normalize()",
          lambda a, b, k: shape_of(v5, {x: div_round(a[x], math.isqrt(sum(a[y] ** 2 for y in v5.fields)))
                                        for x in v5.fields}))
    group("matrix5_norm", Shape(5, 5), lambda a, b, k: f"{a}.norm()",
          lambda a, b, k: scalar(math.isqrt(sum(v * v for v in a.values()))))
    group("matrix3x4_dot", Shape(3, 4), lambda a, b, k: f"{a}.dot({b})",
          lambda a, b, k: scalar(floor_scale(sum(a[x] * b[x] for x in a))))
    group("row_vector3_metric_distance", Shape(1, 3), lambda a, b, k: f"{a}.metric_distance({b})",
          lambda a, b, k: scalar(math.isqrt(sum((a[x] - b[x]) ** 2 for x in a))))
    m4 = Shape(4, 4)
    group("matrix4_component_div", m4, lambda a, b, k: f"{a}.component_div({b})",
          lambda a, b, k: shape_of(m4, {x: div_round(a[x], b[x]) for x in a}))
    m42 = Shape(4, 2)
    group("matrix4x2_cmpy", m42,
          lambda a, b, k: f"{{\nlet mut c = {a};\nc.cmpy(fx({ONE * 3}), {a}, {b}, fx({ONE * 5}));\nc\n}}",
          lambda a, b, k: shape_of(m42, {x: floor_scale(mul(3 * ONE, a[x]) * b[x] + 5 * ONE * a[x])
                                         for x in a}))
    m6 = Shape(6, 6)
    group("matrix6_amax", m6, lambda a, b, k: f"{a}.amax()",
          lambda a, b, k: scalar(max(abs(v) for v in a.values())))

    def iamax(a, s):
        vals = [abs(a[x]) for x in s.fields]
        i = vals.index(max(vals))
        return "(usize, usize)", f"({i % s.r}, {i // s.r})"
    group("matrix6_iamax_full", m6, lambda a, b, k: f"{a}.iamax_full()", lambda a, b, k: iamax(a, m6))
    v6 = Shape(6, 1)

    def argmax(a):
        vals = [a[x] for x in v6.fields]
        i = vals.index(max(vals))
        return "(usize, Fixed)", f"({i}, fx({vals[i]}))"
    group("vector6_argmax", v6, lambda a, b, k: f"{a}.argmax()", lambda a, b, k: argmax(a))
    group("matrix4_symmetric_part", m4, lambda a, b, k: f"{a}.symmetric_part()",
          lambda a, b, k: shape_of(m4, {m4.f(i, j): a[m4.f(i, j)] if i == j else
                                        (a[m4.f(i, j)] + a[m4.f(j, i)]) >> 1
                                        for i in range(4) for j in range(4)}))
    m3 = Shape(3, 3)

    def rel(a, b):
        def one(x, y):
            if abs(x - y) <= 4:
                return True
            if (x < 0) != (y < 0):
                return False
            return abs(x - y) <= floor_scale(max(abs(x), abs(y)) * 4096)
        return "bool", "true" if all(one(a[x], b[x]) for x in a) else "false"
    group("matrix3_relative_eq", m3, lambda a, b, k: f"{a}.relative_eq({b}, 4, fx(4096))",
          lambda a, b, k: rel(a, b))
    group("matrix3_partial_cmp", m3, lambda a, b, k: f"({a} < {b})",
          lambda a, b, k: ("bool", "true" if all(a[x] < b[x] for x in a) else "false"))
    group("matrix3_index_linear", m3, lambda a, b, k: f"{a}[black_box(7_usize)]",
          lambda a, b, k: scalar(a[m3.fields[7]]))
    group("matrix3_index_pair", m3, lambda a, b, k: f"{a}[(black_box(1_usize), black_box(2_usize))]",
          lambda a, b, k: scalar(a[m3.f(1, 2)]))
    m23 = Shape(2, 3)
    group("matrix2x3_one_norm", m23, lambda a, b, k: f"{a}.one_norm()",
          lambda a, b, k: scalar(max(abs(a[m23.f(0, j)]) + abs(a[m23.f(1, j)]) for j in range(3))))
    group("matrix3_lp_norm3", m3, lambda a, b, k: f"{a}.lp_norm(3)", lambda a, b, k: scalar(0),
          trait="AngleTrait", exact=False)
    group("matrix3x2_angle", Shape(3, 2), lambda a, b, k: f"{a}.angle({b})",
          lambda a, b, k: scalar(0), trait="AngleTrait", exact=False)
    group("vector4_slerp", Shape(4, 1), lambda a, b, k: f"{a}.slerp({b}, fx(1288490188))",
          lambda a, b, k: shape_of(Shape(4, 1), {x: 0 for x in a}),
          [("alt_acos", lambda a, b, k: f"alt_acos_slerp({a}, {b}, fx(1288490188))")],
          trait="AngleTrait", exact=False)
    rng = random.Random("tests_ops/bench/from_row_slice")
    m = raws(rng, Shape(3, 3))
    data = f"let data = black_box({fxs(m[x] for x in Shape(3, 3).row_major)});"
    e = f"let e: Matrix3<Fixed> = black_box(load({col(Shape(3, 3), m)}));"
    fns.append(bench("matrix3_from_row_slice", "baseline", [data.replace("let data", "let _data"),
                                                            e, "assert!(e == e);"]))
    fns.append(bench("matrix3_from_row_slice", "library",
                     [data, e, "assert!(Matrix3Trait::from_row_slice(data) == e);"]))
    fns.append(bench("matrix3_from_row_slice", "alt_span_index",
                     [data, e, "assert!(alt_span_index_from_row_slice(data) == e);"]))
    body = "\n\n".join(fns)
    names = sorted(need)
    uses = ["use fixed::Fixed;", "use nalgebra_testing::black_box;",
            "use simba::scalar::{Real, Transcendental};",
            f"use nalgebra::{{{', '.join(names)}}};", "use crate::helpers::{fx, load};"]
    return (f"{HEADER}//! Gas of the base completion (`bench_<group>__<variant>`, net of the "
            f"`baseline`): one\n//! representative shape per family, and the measured "
            f"alternatives of the kernel choices\n//! (`alt_*`).\n\n" + "\n".join(uses) + "\n"
            + BENCH_HELPERS + "\n" + body + "\n")


EXTRA_HELPERS = """
/// Asserts that `value` is within `tol` raw units of the raw `expected`.
#[inline(never)]
pub fn assert_near(value: Fixed, expected: i64, tol: u64) {
    let d = value.raw - expected;
    let d: u64 = if d < 0 {
        (-d).try_into().unwrap()
    } else {
        d.try_into().unwrap()
    };
    assert!(d <= tol, "off by {} raw units", d);
}

/// Asserts that every component of `value` (its `Serde` image) is within `tol` raw units of
/// `expected`.
#[inline(never)]
pub fn assert_raws_near<S, +Serde<S>, +Drop<S>>(value: S, expected: Span<i64>, tol: u64) {
    let mut out: Array<felt252> = array![];
    value.serialize(ref out);
    assert!(out.len() == expected.len());
    let mut i = 0;
    while i < expected.len() {
        let raw: i64 = (*out[i]).try_into().unwrap();
        assert_near(Fixed { raw }, *expected[i], tol);
        i += 1;
    }
}
"""


# The test-only packages (compile budget, `DESIGN.md` §3.1: each under ~7 GB of peak `scarb
# build --test`; two packages of these families measured about 9 GB each), their families, and
# the rows of the shapes of each file of a family (`<family>_r1_3`...: files under ~2,700 lines).
PACKAGES = {
    "shapes_tests_norms": [("norms", [(1, 3), (4, 6)]), ("transcendental", None)],
    "shapes_tests_componentwise": [("componentwise", [(1, 3), (4, 6)]), ("extrema", [(1, 6)])],
    "shapes_tests_construction": [("construction", [(1, 3), (4, 6)]), ("structure", [(1, 2)])],
    "shapes_tests_structure": [("structure", [(3, 4), (5, 6)])],
}
BENCHES_IN = "shapes_tests_norms"
FAMILIES = {
    "norms": ("Generated tests, `norms` family: `dot`, norms, `unscale`, `normalize` and its "
              "variants, `one_norm`.", norms),
    "componentwise": ("Generated tests, `componentwise` family: `component_mul/div(_assign)`, "
                      "`inf`, `sup`, `add_scalar`, `cmpy`, `cdpy`.", componentwise),
    "extrema": ("Generated tests, `extrema` family: `min`, `max`, `amin`, `amax`, `camin`, "
                "`camax`, the index searches.", extrema),
    "construction": ("Generated tests, `construction` family: `repeat`, `from_fn`, slices, "
                     "partial diagonals, axes, conversions from the geometry types, `m * r`.",
                     construction),
    "structure": ("Generated tests, `structure` family: adjoints, symmetric parts, homogeneous "
                  "forms, comparisons, casts, conversions, indexing, `Unit<VectorN>`.", structure),
}


def render_family(name: str, groups: list[tuple[int, int]] | None) -> dict[str, File]:
    if name == "transcendental":
        f = File("transcendental", "Generated tests, `transcendental` family (Tier B sample): "
                                   "`angle`, `lp_norm`, `slerp` against Python floats.")
        for s in TRANSCENDENTAL_SAMPLE:
            transcendental(f, s)
        for s in ALL_SHAPES:
            if s.is_column:
                slerp_case(f, s)
        return {"transcendental": f}
    what, gen = FAMILIES[name]
    out = {}
    for lo, hi in groups:
        key = name if (lo, hi) == (1, 6) else f"{name}_r{lo}_{hi}"
        rows = f" Shapes of {lo} to {hi} rows." if (lo, hi) != (1, 6) else ""
        f = File(key, what + rows)
        for s in ALL_SHAPES:
            if lo <= s.r <= hi:
                gen(f, s)
        out[key] = f
    return out


def render(package: str) -> dict[str, str]:
    """{file name under `src/`: text} of one of the `PACKAGES`."""
    files: dict[str, File] = {}
    for name, groups in PACKAGES[package]:
        files.update(render_family(name, groups))
    out = {f"{name}.cairo": f.render() for name, f in files.items()}
    out["helpers.cairo"] = HEADER + HELPERS + EXTRA_HELPERS
    mods = ["helpers", *files]
    if package == BENCHES_IN:
        out["benches.cairo"] = render_benches()
        mods.append("benches")
    families = ", ".join(f"`{n}`" + (f" (rows {', '.join(f'{lo}-{hi}' for lo, hi in g)})"
                                      if g and g != [(1, 6)] else "")
                         for n, g in PACKAGES[package])
    out["lib.cairo"] = (HEADER + "//! Generated tests of the base completion of the static shapes "
                        "(`tools/shapegen/tests_ops.py`,\n//! WP 8.2a): Tier A of "
                        "`tools/shapegen/DESIGN.md` §3.3, one exact case per (shape, family) on "
                        f"the\n//! 36 shapes; families {families}.\n//! Test-only package, not "
                        "published.\n\n"
                        + "".join(f"#[cfg(test)]\nmod {m};\n" for m in sorted(mods)))
    return out


def outputs(tmp: Path) -> dict[Path, Path]:
    """Writes the packages' sources under `tmp/<package>/src`, formatted, and returns
    {committed: generated}."""
    out = {}
    for package in PACKAGES:
        pkg = tmp / package
        src = pkg / "src"
        src.mkdir(parents=True)
        (pkg / "Scarb.toml").write_text(FMT_MANIFEST)
        for name, text in render(package).items():
            (src / name).write_text(text)
            out[ROOT / "crates" / package / "src" / name] = src / name
        subprocess.run(["scarb", "fmt"], cwd=pkg, check=True)
    return out
