pub mod col_piv_qr1x5;
pub mod col_piv_qr2x5;
pub mod col_piv_qr3x5;
pub mod col_piv_qr4x5;
pub mod col_piv_qr5;
pub mod col_piv_qr5x1;
pub mod col_piv_qr5x2;
pub mod col_piv_qr5x3;
pub mod col_piv_qr5x4;
