[package]
name = "nalgebra"
description = "Linear algebra for provable game physics: a Cairo port of the Rust nalgebra crate."
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
simba = { path = "../simba", version = "0.1.0" }

[dev-dependencies]
fixed = "0.3.0"
snforge_std.workspace = true
assert_macros.workspace = true
nalgebra_testing = { path = "../testing" }

[tool]
fmt.workspace = true
scarb.workspace = true
