[package]
name = "nalgebra_geometry5"
description = "The 5D geometry: points, translations, scales, reflections of dimension 5 (Reflection5 whole), Matrix6 homogeneous (cg)."
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["linear-algebra", "fixed-point", "geometry", "cg"]
readme = "README.md"

[dependencies]
nalgebra_core = { path = "../core", version = "0.1.0" }
nalgebra_types2 = { path = "../types2", version = "0.1.0" }
nalgebra_types3 = { path = "../types3", version = "0.1.0" }
nalgebra_types4 = { path = "../types4", version = "0.1.0" }
nalgebra_types5 = { path = "../types5", version = "0.1.0" }
nalgebra_types6 = { path = "../types6", version = "0.1.0" }
simba.workspace = true

[dev-dependencies]
fixed.workspace = true
snforge_std.workspace = true
assert_macros.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true
