//! Linear algebra for provable game physics: a Cairo port of the Rust `nalgebra` crate.
//!
//! Modules mirror upstream: `base` (vectors, matrices), `geometry` (rotations, isometries),
//! `linalg` (decompositions). See `docs/DESIGN.md` and `docs/ROADMAP.md`.

pub mod base;
pub mod geometry;
pub mod linalg;

// shapegen: begin
pub use base::{
    ColumnPart, EuclideanNorm, FixedColumns, FixedResize, FixedRows, FixedView, LpNorm, Matrix1,
    Matrix1AngleTrait, Matrix1BlasTrait, Matrix1CgTrait, Matrix1StatisticsTrait, Matrix1Trait,
    Matrix1x2, Matrix1x3, Matrix1x4, Matrix1x5, Matrix1x6, Matrix2, Matrix2AngleTrait,
    Matrix2BlasTrait, Matrix2CgTrait, Matrix2StatisticsTrait, Matrix2Trait, Matrix2x1, Matrix2x3,
    Matrix2x3AngleTrait, Matrix2x3BlasTrait, Matrix2x3StatisticsTrait, Matrix2x3Trait, Matrix2x4,
    Matrix2x4AngleTrait, Matrix2x4BlasTrait, Matrix2x4StatisticsTrait, Matrix2x4Trait, Matrix2x5,
    Matrix2x5AngleTrait, Matrix2x5BlasTrait, Matrix2x5StatisticsTrait, Matrix2x5Trait, Matrix2x6,
    Matrix2x6AngleTrait, Matrix2x6BlasTrait, Matrix2x6StatisticsTrait, Matrix2x6Trait, Matrix3,
    Matrix3AngleTrait, Matrix3BlasTrait, Matrix3CgAngleTrait, Matrix3CgTrait,
    Matrix3StatisticsTrait, Matrix3Trait, Matrix3x1, Matrix3x2, Matrix3x2AngleTrait,
    Matrix3x2BlasTrait, Matrix3x2StatisticsTrait, Matrix3x2Trait, Matrix3x4, Matrix3x4AngleTrait,
    Matrix3x4BlasTrait, Matrix3x4StatisticsTrait, Matrix3x4Trait, Matrix3x5, Matrix3x5AngleTrait,
    Matrix3x5BlasTrait, Matrix3x5StatisticsTrait, Matrix3x5Trait, Matrix3x6, Matrix3x6AngleTrait,
    Matrix3x6BlasTrait, Matrix3x6StatisticsTrait, Matrix3x6Trait, Matrix4, Matrix4AngleTrait,
    Matrix4BlasTrait, Matrix4CgAngleTrait, Matrix4CgTrait, Matrix4StatisticsTrait, Matrix4Trait,
    Matrix4x1, Matrix4x2, Matrix4x2AngleTrait, Matrix4x2BlasTrait, Matrix4x2StatisticsTrait,
    Matrix4x2Trait, Matrix4x3, Matrix4x3AngleTrait, Matrix4x3BlasTrait, Matrix4x3StatisticsTrait,
    Matrix4x3Trait, Matrix4x5, Matrix4x5AngleTrait, Matrix4x5BlasTrait, Matrix4x5StatisticsTrait,
    Matrix4x5Trait, Matrix4x6, Matrix4x6AngleTrait, Matrix4x6BlasTrait, Matrix4x6StatisticsTrait,
    Matrix4x6Trait, Matrix5, Matrix5AngleTrait, Matrix5BlasTrait, Matrix5CgTrait,
    Matrix5StatisticsTrait, Matrix5Trait, Matrix5x1, Matrix5x2, Matrix5x2AngleTrait,
    Matrix5x2BlasTrait, Matrix5x2StatisticsTrait, Matrix5x2Trait, Matrix5x3, Matrix5x3AngleTrait,
    Matrix5x3BlasTrait, Matrix5x3StatisticsTrait, Matrix5x3Trait, Matrix5x4, Matrix5x4AngleTrait,
    Matrix5x4BlasTrait, Matrix5x4StatisticsTrait, Matrix5x4Trait, Matrix5x6, Matrix5x6AngleTrait,
    Matrix5x6BlasTrait, Matrix5x6StatisticsTrait, Matrix5x6Trait, Matrix6, Matrix6AngleTrait,
    Matrix6BlasTrait, Matrix6CgTrait, Matrix6StatisticsTrait, Matrix6Trait, Matrix6x1, Matrix6x2,
    Matrix6x2AngleTrait, Matrix6x2BlasTrait, Matrix6x2StatisticsTrait, Matrix6x2Trait, Matrix6x3,
    Matrix6x3AngleTrait, Matrix6x3BlasTrait, Matrix6x3StatisticsTrait, Matrix6x3Trait, Matrix6x4,
    Matrix6x4AngleTrait, Matrix6x4BlasTrait, Matrix6x4StatisticsTrait, Matrix6x4Trait, Matrix6x5,
    Matrix6x5AngleTrait, Matrix6x5BlasTrait, Matrix6x5StatisticsTrait, Matrix6x5Trait, MatrixGemm,
    MatrixGemmTr, MatrixGemv, MatrixGemvTr, MatrixIndex, MatrixKronecker, MatrixMul, MatrixQuadform,
    MatrixQuadformTr, MatrixSolve, MatrixTrMul, Norm, OneNorm, Point1SwizzleTrait,
    Point2SwizzleTrait, Point3SwizzleTrait, Point4SwizzleTrait, Point5SwizzleTrait,
    Point6SwizzleTrait, RowPart, RowVector1, RowVector2, RowVector2AngleTrait, RowVector2BlasTrait,
    RowVector2StatisticsTrait, RowVector2Trait, RowVector3, RowVector3AngleTrait,
    RowVector3BlasTrait, RowVector3StatisticsTrait, RowVector3Trait, RowVector4,
    RowVector4AngleTrait, RowVector4BlasTrait, RowVector4StatisticsTrait, RowVector4Trait,
    RowVector5, RowVector5AngleTrait, RowVector5BlasTrait, RowVector5StatisticsTrait,
    RowVector5Trait, RowVector6, RowVector6AngleTrait, RowVector6BlasTrait,
    RowVector6StatisticsTrait, RowVector6Trait, UniformNorm, UnitVector1, UnitVector1AngleTrait,
    UnitVector1Trait, UnitVector2, UnitVector2AngleTrait, UnitVector2Trait, UnitVector3,
    UnitVector3AngleTrait, UnitVector3Trait, UnitVector4, UnitVector4AngleTrait, UnitVector4Trait,
    UnitVector5, UnitVector5AngleTrait, UnitVector5Trait, UnitVector6, UnitVector6AngleTrait,
    UnitVector6Trait, Vector1, Vector2, Vector2AngleTrait, Vector2BlasTrait, Vector2StatisticsTrait,
    Vector2Trait, Vector3, Vector3AngleTrait, Vector3BlasTrait, Vector3StatisticsTrait,
    Vector3Trait, Vector4, Vector4AngleTrait, Vector4BlasTrait, Vector4StatisticsTrait,
    Vector4Trait, Vector5, Vector5AngleTrait, Vector5BlasTrait, Vector5StatisticsTrait,
    Vector5Trait, Vector6, Vector6AngleTrait, Vector6BlasTrait, Vector6StatisticsTrait,
    Vector6Trait,
};
// shapegen: end
pub use base::{Normed, Point2, Point3, Unit, UnitTrait};
pub use geometry::{
    AbstractRotation, Affine2, Affine2Trait, Affine3, Affine3Trait, DualQuaternion,
    DualQuaternionTrait, Isometry2, Isometry2AngleTrait, Isometry2Trait, Isometry3,
    Isometry3AngleTrait, Isometry3DualQuaternionTrait, Isometry3Trait, IsometryMatrix2,
    IsometryMatrix2AngleTrait, IsometryMatrix2Trait, IsometryMatrix3, IsometryMatrix3AngleTrait,
    IsometryMatrix3Trait, Matrix4OrthographicTrait, Matrix4PerspectiveTrait, Orthographic3,
    Orthographic3AngleTrait, Orthographic3Trait, Perspective3, Perspective3AngleTrait,
    Perspective3Trait, Point1, Point1Trait, Point2ExtTrait, Point2Index, Point2PartialOrd,
    Point3ExtTrait, Point3Index, Point3PartialOrd, Point4, Point4Trait, Point5, Point5Trait, Point6,
    Point6Trait, Projective2, Projective2Trait, Projective3, Projective3Trait, Quaternion,
    QuaternionTrait, QuaternionTranscendentalTrait, Reflection1, Reflection1Columns,
    Reflection1Rows, Reflection1Trait, Reflection2, Reflection2Columns, Reflection2Rows,
    Reflection2Trait, Reflection3, Reflection3Columns, Reflection3Rows, Reflection3Trait,
    Reflection4, Reflection4Columns, Reflection4Rows, Reflection4Trait, Reflection5,
    Reflection5Columns, Reflection5Rows, Reflection5Trait, Reflection6, Reflection6Columns,
    Reflection6Rows, Reflection6Trait, Rotation2, Rotation2AngleTrait, Rotation2Trait, Rotation3,
    Rotation3AngleTrait, Rotation3Trait, Scale1, Scale1Trait, Scale2, Scale2Trait, Scale3,
    Scale3Trait, Scale4, Scale4Trait, Scale5, Scale5Trait, Scale6, Scale6Trait, Similarity2,
    Similarity2AngleTrait, Similarity2Trait, Similarity3, Similarity3AngleTrait, Similarity3Trait,
    SimilarityMatrix2, SimilarityMatrix2AngleTrait, SimilarityMatrix2Trait, SimilarityMatrix3,
    SimilarityMatrix3AngleTrait, SimilarityMatrix3Trait, Transform2, Transform2Trait, Transform3,
    Transform3Trait, TransformDiv, TransformMul, TransformSetCategory, Translation1,
    Translation1Trait, Translation2, Translation2Trait, Translation3,
    Translation3DualQuaternionTrait, Translation3Trait, Translation4, Translation4Trait,
    Translation5, Translation5Trait, Translation6, Translation6Trait, UnitComplex,
    UnitComplexAngleTrait, UnitComplexTrait, UnitDualQuaternion, UnitDualQuaternionAngleTrait,
    UnitDualQuaternionTrait, UnitQuaternion, UnitQuaternionAngleTrait,
    UnitQuaternionDualQuaternionTrait, UnitQuaternionTrait,
};
pub use linalg::{
    Cholesky2, Cholesky2Trait, Cholesky2UpdateTrait, Cholesky3, Cholesky3Trait,
    Cholesky3UpdateTrait, Cholesky4, Cholesky4Trait, Cholesky4UpdateTrait, Cholesky6,
    Cholesky6Trait, Cholesky6UpdateTrait, GivensRotate, GivensRotateRows, GivensRotation,
    GivensRotationTrait, Lu2, Lu2Trait, Lu3, Lu3Trait, Lu4, Lu4Trait, Lu6, Lu6Trait, Matrix1QrTrait,
    Matrix1SvdTrait, Matrix2CholeskyTrait, Matrix2InverseTrait, Matrix2LuTrait, Matrix2QrTrait,
    Matrix2SvdTrait, Matrix2UduTrait, Matrix2x3QrTrait, Matrix2x3SvdTrait, Matrix2x4QrTrait,
    Matrix2x4SvdTrait, Matrix2x5QrTrait, Matrix2x5SvdTrait, Matrix2x6QrTrait, Matrix2x6SvdTrait,
    Matrix3CholeskyTrait, Matrix3InverseTrait, Matrix3LuTrait, Matrix3QrTrait, Matrix3SvdTrait,
    Matrix3UduTrait, Matrix3x2QrTrait, Matrix3x2SvdTrait, Matrix3x4QrTrait, Matrix3x4SvdTrait,
    Matrix3x5QrTrait, Matrix3x5SvdTrait, Matrix3x6QrTrait, Matrix3x6SvdTrait, Matrix4CholeskyTrait,
    Matrix4InverseTrait, Matrix4LuTrait, Matrix4QrTrait, Matrix4SvdTrait, Matrix4UduTrait,
    Matrix4x2QrTrait, Matrix4x2SvdTrait, Matrix4x3QrTrait, Matrix4x3SvdTrait, Matrix4x5QrTrait,
    Matrix4x5SvdTrait, Matrix4x6QrTrait, Matrix4x6SvdTrait, Matrix5QrTrait, Matrix5SvdTrait,
    Matrix5x2QrTrait, Matrix5x2SvdTrait, Matrix5x3QrTrait, Matrix5x3SvdTrait, Matrix5x4QrTrait,
    Matrix5x4SvdTrait, Matrix5x6QrTrait, Matrix5x6SvdTrait, Matrix6CholeskyTrait,
    Matrix6InverseTrait, Matrix6LuTrait, Matrix6QrTrait, Matrix6SvdTrait, Matrix6UduTrait,
    Matrix6x2QrTrait, Matrix6x2SvdTrait, Matrix6x3QrTrait, Matrix6x3SvdTrait, Matrix6x4QrTrait,
    Matrix6x4SvdTrait, Matrix6x5QrTrait, Matrix6x5SvdTrait, Perm2, Perm2Trait, Perm3, Perm3Trait,
    Perm4, Perm4Trait, Perm6, Perm6Trait, PermuteColumns, PermuteRows, Qr1, Qr1Trait, Qr1x2,
    Qr1x2Trait, Qr1x3, Qr1x3Trait, Qr1x4, Qr1x4Trait, Qr1x5, Qr1x5Trait, Qr1x6, Qr1x6Trait, Qr2,
    Qr2Trait, Qr2x1, Qr2x1Trait, Qr2x3, Qr2x3Trait, Qr2x4, Qr2x4Trait, Qr2x5, Qr2x5Trait, Qr2x6,
    Qr2x6Trait, Qr3, Qr3Trait, Qr3x1, Qr3x1Trait, Qr3x2, Qr3x2Trait, Qr3x4, Qr3x4Trait, Qr3x5,
    Qr3x5Trait, Qr3x6, Qr3x6Trait, Qr4, Qr4Trait, Qr4x1, Qr4x1Trait, Qr4x2, Qr4x2Trait, Qr4x3,
    Qr4x3Trait, Qr4x5, Qr4x5Trait, Qr4x6, Qr4x6Trait, Qr5, Qr5Trait, Qr5x1, Qr5x1Trait, Qr5x2,
    Qr5x2Trait, Qr5x3, Qr5x3Trait, Qr5x4, Qr5x4Trait, Qr5x6, Qr5x6Trait, Qr6, Qr6Trait, Qr6x1,
    Qr6x1Trait, Qr6x2, Qr6x2Trait, Qr6x3, Qr6x3Trait, Qr6x4, Qr6x4Trait, Qr6x5, Qr6x5Trait,
    RowVector2QrTrait, RowVector2SvdTrait, RowVector3QrTrait, RowVector3SvdTrait, RowVector4QrTrait,
    RowVector4SvdTrait, RowVector5QrTrait, RowVector5SvdTrait, RowVector6QrTrait,
    RowVector6SvdTrait, Svd1, Svd1Trait, Svd1x2, Svd1x2Trait, Svd1x3, Svd1x3Trait, Svd1x4,
    Svd1x4Trait, Svd1x5, Svd1x5Trait, Svd1x6, Svd1x6Trait, Svd2, Svd2Trait, Svd2x1, Svd2x1Trait,
    Svd2x3, Svd2x3Trait, Svd2x4, Svd2x4Trait, Svd2x5, Svd2x5Trait, Svd2x6, Svd2x6Trait, Svd3,
    Svd3Trait, Svd3x1, Svd3x1Trait, Svd3x2, Svd3x2Trait, Svd3x4, Svd3x4Trait, Svd3x5, Svd3x5Trait,
    Svd3x6, Svd3x6Trait, Svd4, Svd4Trait, Svd4x1, Svd4x1Trait, Svd4x2, Svd4x2Trait, Svd4x3,
    Svd4x3Trait, Svd4x5, Svd4x5Trait, Svd4x6, Svd4x6Trait, Svd5, Svd5Trait, Svd5x1, Svd5x1Trait,
    Svd5x2, Svd5x2Trait, Svd5x3, Svd5x3Trait, Svd5x4, Svd5x4Trait, Svd5x6, Svd5x6Trait, Svd6,
    Svd6Trait, Svd6x1, Svd6x1Trait, Svd6x2, Svd6x2Trait, Svd6x3, Svd6x3Trait, Svd6x4, Svd6x4Trait,
    Svd6x5, Svd6x5Trait, SymmetricEigen1, SymmetricEigen1Trait, SymmetricEigen2,
    SymmetricEigen2Trait, SymmetricEigen3, SymmetricEigen3Trait, SymmetricEigen4,
    SymmetricEigen4Trait, SymmetricEigen5, SymmetricEigen5Trait, SymmetricEigen6,
    SymmetricEigen6Trait, Vector2QrTrait, Vector2SvdTrait, Vector3QrTrait, Vector3SvdTrait,
    Vector4QrTrait, Vector4SvdTrait, Vector5QrTrait, Vector5SvdTrait, Vector6QrTrait,
    Vector6SvdTrait,
};
